### ISSUE TITLE
SocketTimeOut when I use spring-cloud-netflix-core1.4.5.RELEASE zuul SimpleHostRoutingFilter with tomcat7（7.0.50，7.0.73）

### ISSUE THREAD

**Issue by xiaominger** [spring-cloud/spring-cloud-netflix#3534] opened 2019-05-17 02:54 UTC
Hello,a question,when I  use spring-cloud-netflix-core1.4.5.RELEASE zuul SimpleHostRoutingFilter with tomcat7（7.0.50，7.0.73）,it always reports SocketTimeOut:
```
Caused by: org.springframework.cloud.netflix.zuul.util.ZuulRuntimeException: com.netflix.zuul.exception.ZuulException: Read timed out
        at org.springframework.cloud.netflix.zuul.filters.route.SimpleHostRoutingFilter.run(SimpleHostRoutingFilter.java:212)
        at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:117)
        at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:193)
        ... 81 common frames omitted
Caused by: com.netflix.zuul.exception.ZuulException: Read timed out
        at org.springframework.cloud.netflix.zuul.util.ZuulRuntimeException.<init>(ZuulRuntimeException.java:33)
        ... 84 common frames omitted
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:170)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.read(InputRecord.java:503)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:118)
        at org.springframework.cloud.netflix.zuul.filters.route.SimpleHostRoutingFilter.forwardRequest(SimpleHostRoutingFilter.java:352)
        at org.springframework.cloud.netflix.zuul.filters.route.SimpleHostRoutingFilter.forward(SimpleHostRoutingFilter.java:271)
        at org.springframework.cloud.netflix.zuul.filters.route.SimpleHostRoutingFilter.run(SimpleHostRoutingFilter.java:207)
        ... 83 common frames omitted
~                                                                               
```

The pre filter before routeFilter is:
```
if (ApiMethodTypeEnum.POST.getName().equals(request.getMethod()) &&request.getContentType()!=null&&request.getContentType().contains(ContentType.APPLICATION_FORM_URLENCODED.getMimeType()) ) {
            String newReqBodyStr = "";
            for (Map.Entry<String, List<String>> entry : newParameterMap.entrySet()) {
                String key = entry.getKey();
                if (entry.getValue().size() > 0) {
                    newReqBodyStr += key + "=" + entry.getValue().get(0) + "&";
                }
            }
            if (newReqBodyStr.contains("&")) {
                newReqBodyStr = newReqBodyStr.substring(0, newReqBodyStr.length() - 1);
            }

            byte[] bytes = newReqBodyStr.getBytes("UTF-8");
            context.setRequest(new HttpServletRequestWrapper(getCurrentContext().getRequest()) {
                @Override
                public ServletInputStream getInputStream() throws IOException {
                    return new ServletInputStreamWrapper(bytes);
                }

                @Override
                public int getContentLength() {
                    return bytes.length;
                }

                @Override
                public long getContentLengthLong() {
                    return bytes.length;
                }
            });

        } else {
            context.setRequestQueryParams(newParameterMap);
        }

        HttpHost httpHost = getHttpHost(url);
        context.setRouteHost(UriComponentsBuilder.fromHttpUrl(httpHost.toString()).build().toUri().toURL());
        context.put(REQUEST_URI_KEY, url.getPath());
```
The Get  request is ok.

But when I use tomcat8(8.0.39),both Get and Post request is ok.but the version of tomcat is hardly to be changed in production enviroment,I have to use spring-cloud-netflix-core1.4.0.RELEASE,it is ok too

Why can't I use spring-cloud-netflix-core1.4.5.RELEASE with tomcat7

**Comment by ryanjbaxter** [comment] 2019-05-20 14:27
I dont see anything here that points to a problem with Spring Cloud Netflix.  There is no limitation with using Tomcat 7.  If you can provide a sample that reproduces the problem we can take a look.

**Comment by spring-issuemaster** [comment] 2019-05-27 14:30
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-06-03 14:29
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-06-03 14:29 UTC
Labels: feedback-reminder, waiting for feedback
