### ISSUE TITLE
Restcontroller not invoking among clients

### ISSUE THREAD

**Issue by kchaitan27490** [spring-cloud/spring-cloud-netflix#3542] opened 2019-05-24 19:27 UTC
Hi All, I am working on a microservice appn using spring data and eureka. Below are my controller classes of the client and service provider. 
Client:
```
package com.tibco.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cloud.client.loadbalancer.LoadBalanced;
import org.springframework.context.annotation.Bean;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.client.RestTemplate;

@RestController
public class RibbonController {

	@Autowired
	RestTemplate restTemplate;

	@Bean
	@LoadBalanced
	public RestTemplate restTemplate() {
		return new RestTemplate();
	}
	

	@GetMapping("/apitest")
	public String testMethod() {
		return restTemplate.getForObject("http://providerservice/cabprovider", String.class);
	}

}
```
Service Provider:
```
package com.tibco.providerservice.controller;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.env.Environment;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

import com.tibco.model.ProviderService;
import com.tibco.repository.ProviderServiceRepo;

@RestController
public class ProviderController {
	
	ProviderServiceRepo psrepo;
	
	@GetMapping("/cabprovider")
	public String backend() {
		return "The cab details are provider id: 1, provider name: ola, fare=1234";
	}
}
```
The main applications are default: 
```
package com.tibco.providerservice;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.client.discovery.EnableDiscoveryClient;

@SpringBootApplication
@EnableDiscoveryClient
public class ProviderServiceApplication {

	public static void main(String[] args) {
		SpringApplication.run(ProviderServiceApplication.class, args);
	}

}
```

```
package com.tibco.rideservice;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.client.discovery.EnableDiscoveryClient;
import org.springframework.cloud.netflix.ribbon.RibbonClient;

import com.tibco.rideservice.RibbonConfiguration;

@EnableDiscoveryClient
@SpringBootApplication
@RibbonClient(name = "RideService", configuration = RibbonConfiguration.class)
public class RideServiceApplication {

	public static void main(String[] args) {
		SpringApplication.run(RideServiceApplication.class, args);
	}

}
```
properties files:
rideservice:
```
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.datasource.url=jdbc:mysql://localhost:3306/test
spring.datasource.username=springuser
spring.datasource.password=Spr!ngUser!23

spring.application.name=rideservice
server.port=9102
 
eureka.client.serviceUrl.defaultZone= http://${registry.host:localhost}:${registry.port:9101}/eureka/
eureka.instance.leaseRenewalIntervalInSeconds= 1
eureka.instance.leaseExpirationDurationInSeconds= 2
 
server.ribbon.eureka.enabled=true
server.ribbon.ServerListRefreshInterval=1000
management.security.enabled=false
management.health.consul.enabled=false
```
providerservice:
```
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/test
spring.datasource.username=springuser
spring.datasource.password=Spr!ngUser!23

spring.application.name=providerservice
server.port = 9103
 
eureka.client.serviceUrl.defaultZone= http://${registry.host:localhost}:${registry.port:9101}/eureka/
eureka.instance.leaseRenewalIntervalInSeconds= 1
eureka.instance.leaseExpirationDurationInSeconds= 2
```
Whenever I hit localhost:9102/apitest, I am getting below message:
```
{
    "timestamp": "2019-05-24T19:16:54.572+0000",
    "status": 404,
    "error": "Not Found",
    "message": "No message available",
    "path": "/apitest"
}
```
Cant seem to narrow down the mistake, can someone help please?

**Comment by spencergibb** [comment] 2019-05-24 19:58
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

The 404 suggests there is something unrelated to netflix.

Putting a bunch of code in comments doesn't lend itself to debugging.

Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

Emphasis on minimal (ie no db's or embeded, etc..)

**Comment by kchaitan27490** [comment] 2019-05-24 20:14
Hi Spencer, Sorry i am new to github and whats expected. Please find below my git repo and the applications code which is causing this.

I know 404 suggests something thats not available, but the links seem correct from client to service provider, thats why i am unable to narrow down the place thats missing the link.

https://github.com/kchaitan27490/spring-boot/tree/microservices/ProviderService
https://github.com/kchaitan27490/spring-boot/tree/microservices/RibbonEurekaServer
https://github.com/kchaitan27490/spring-boot/tree/microservices/RideService

**Comment by spencergibb** [comment] 2019-05-24 20:31
> Emphasis on minimal (ie no db's or embeded, etc..)

I don't have mysql available like you do. I can't run your sample.

**Comment by spring-issuemaster** [comment] 2019-05-31 20:34
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-06-07 20:34
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-06-07 20:34 UTC
Labels: feedback-reminder, waiting for feedback
