### ISSUE TITLE
@FeignClient is now a primary bean and cannot be mocked out anymore

### ISSUE THREAD

**Issue by LutzStrobel** [spring-cloud/spring-cloud-netflix#1085] opened 2016-06-08 09:10 UTC
Since [issue #899](https://github.com/spring-cloud/spring-cloud-netflix/issues/899) a @FeignClient annotated interface will be exposed as a primary bean in spring.
So it cannot be mocked out in tests because then there will be more than one primary bean.
Is it possible to refine the solution of #899 a little bit, so that the primary flag is only set if there is a fallback configured?

**Comment by Koizumi85** [comment] 2016-06-08 09:21
Hello @LutzStrobel ,

i had the same problem and solved it with the following workaround:

1. Annotate your configuration where `@EnableFeignClients` is put on with `@Profile("!test")` (If you have this annotation on a class where other configuration is applied, move it to its own configuration class)
2. Create a Annotation in your Test which is annotated with `@Profile("test")` and create your mocks in there.

It isn't beautiful, but it works. Hope it helps

**Comment by spencergibb** [comment] 2016-06-08 18:17
Duplicate of #1016

**Closed by spencergibb** 2016-06-08 18:17 UTC
