### ISSUE TITLE
Add support for reactive feign clients

### ISSUE THREAD

**Issue by vasilievip** [spring-cloud/spring-cloud-netflix#1554] opened 2016-12-15 22:16 UTC
Since reactive web added to spring, it will be great to see some feign client support as well.
https://spring.io/blog/2016/11/28/going-reactive-with-spring-data
https://github.com/OpenFeign/feign/issues/361
https://github.com/OpenFeign/feign-vertx
https://github.com/OpenFeign/feign/pull/307

**Comment by spencergibb** [comment] 2016-12-20 18:10
Part of the problem is feign itself. It can do asynchronous, but non-blocking is another story. @adriancole correct me if I'm wrong.

**Comment by adriancole** [comment] 2016-12-21 00:43
@hosuaby lazy code search... does feign-vertx rewire itself in such a way that non-blocking I/O is possible?

**Comment by hosuaby** [comment] 2016-12-21 10:27
Feign-vertx is totally non blocking.

**Comment by hosuaby** [comment] 2016-12-21 10:36
All synchronous parts of feign was rewrited to support asynchronous HTTP client

**Comment by adriancole** [comment] 2016-12-22 01:34
@hosuaby sweet

**Comment by mohanrao** [comment] 2017-09-28 23:22
So is this still open or closed? If it is closed an example how to use this will be helpful because spring 5.0 is already released. Spring boot 2.0 will be released in a couple of months.

**Comment by spencergibb** [comment] 2017-09-28 23:26
Status is open, right? I doubt anything will be done by us for 2.0.0

**Comment by vasilievip** [comment] 2018-03-01 19:49
@spencergibb what is the best way to get this https://github.com/kptfh/feign-reactive integrated into spring cloud? 
PS: There is ribbon integration required and spring retry for retry policies.

**Comment by spencergibb** [comment] 2018-03-01 19:51
It's a good start, but it still uses blocking serialization and logging.

**Comment by vasilievip** [comment] 2018-03-01 20:03
ok, so non blocking serialization and logging. Should ribbon/spring-retry be in place as well?

**Comment by ryanjbaxter** [comment] 2018-03-02 01:05
If we want parity, which I think we do, then yes

**Comment by kptfh** [comment] 2018-03-05 17:54
@vasilievip Just added support of Ribbon load balancing for this reactive feign client
https://github.com/kptfh/feign-reactive

Plan to add hystrix support in nearest future.

**Comment by spencergibb** [comment] 2018-03-05 18:06
@kptfh 
> It's a good start, but it still uses blocking serialization and logging.

It will block in a webflux application.

**Comment by spencergibb** [comment] 2018-03-05 18:08
And blocking I/O

**Comment by kptfh** [comment] 2018-03-05 18:43
@spencergibb You comment is not clear to me. Can you give more details?

**Comment by spencergibb** [comment] 2018-03-05 18:53
Sorry, I'm probably in error.

**Comment by ryanjbaxter** [comment] 2018-03-05 21:27
Closing this issue in favor or https://github.com/spring-cloud/spring-cloud-openfeign/issues/4 where we should be tracking all feign issues going forward.

**Closed by ryanjbaxter** 2018-03-05 21:27 UTC
Labels: enhancement
