### ISSUE TITLE
i have set the @FeignClient config, but it does not work

### ISSUE THREAD

**Issue by ppsang** [spring-cloud/spring-cloud-netflix#2875] opened 2018-04-24 14:47 UTC
Hi:
    I want to config the special FeignClient to be intercepted, but it seems not work.
```
@FeignClient(value = ApiConstants.UC_MANAGE_SERVER_NAME, configuration = OperationService.TestConfig.class)
public interface OperationService {

    // @Configuration
    class TestConfig {

        @Bean
        public RequestInterceptor getRequestIntercptor() {

            return new BasicAuthRequestInterceptor("name", "pwd");
        }
    }
}

@EnableEurekaClient
@SpringBootApplication
@ComponentScan(basePackageClasses = {OperationService.TestConfig.class})
@EnableFeignClients(basePackages = {"cn.demo.manage", "cn.demo.api.service"})
public class DemoApplication  {
    ...
}

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Edgware.SR3</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.8.RELEASE</version>
    </parent>
```
I want to let the OperationService itself be intercepted, but when I add the annotation (@Configuration)   the TestConfig was be global, or it does not works if I didn't use the annotation. 
I have seen the document of spring cloud, but I cannot find the solution. Can you help me?

**Comment by ryanjbaxter** [comment] 2018-04-25 00:11
Can you provide a sample that reproduces this?

**Comment by ppsang** [comment] 2018-04-25 05:39
@ryanjbaxter https://github.com/ppsang/client this is client https://github.com/ppsang/server this is server, what wrong with the prject? thank you!

**Comment by ryanjbaxter** [comment] 2018-05-01 19:28
I am missing the point in your sample projects.  If you add spring security to you web app and set the user to be `name` and the password to `password` then your client app works perfectly fine.

**Comment by spencergibb** [comment] 2018-10-01 23:01
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2018-10-01 23:01 UTC
Labels: waiting for feedback
