### ISSUE TITLE
feign client page object error

### ISSUE THREAD

**Issue by Dreampie** [spring-cloud/spring-cloud-netflix#782] opened 2016-01-21 04:11 UTC
```java
@FeignClient("notice-service-provider")
public interface NoticeService {

  @RequestMapping(value = NoticeConstants.NOTICES_PATH, method = RequestMethod.GET)
  ResponseEntity<Page<NoticeEntity>> findAll();

}

```

if service return Page,get error:
```java
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of org.springframework.data.domain.Page, problem: abstract types either need to be mapped to concrete types, have custom deserializer, or be instantiated with additional type information
 at [Source: java.io.PushbackInputStream@67635da8; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148) ~[jackson-databind-2.6.4.jar:2.6.4]
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:892) ~[jackson-databind-2.6.4.jar:2.6.4]
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:139) ~[jackson-databind-2.6.4.jar:2.6.4]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736) ~[jackson-databind-2.6.4.jar:2.6.4]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2810) ~[jackson-databind-2.6.4.jar:2.6.4]
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:221) ~[spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	... 30 common frames omitted
```

**Comment by spencergibb** [comment] 2016-01-21 04:26
Duplicate of #556

**Closed by spencergibb** 2016-01-21 04:26 UTC

**Comment by Koizumi85** [comment] 2016-01-21 11:05
@spencergibb really a duplicate? If i am right, the issue in #556 is sending the Pageable as get parameters.
This issue here is receiving a Page object as ResponseBody.
Nevertheless i am not sure, if this is an issue in SpringCloud or Feign, but is simply a deserialization issue, because SpringData's PageImpl doesn't have a default constructor, so Jackson can't deserialize it.

@Dreampie A simple workaround would be to create an own implementation of the PageImpl class, with a default constructor and map the SpringData page-result to your own implementation. If you send this as result you can deserialize it in the FeignClient i think.
Real solution would be to ask in SpringData-repository if they could add everything needed to serialize and deserialize a Page result with Jackson.

**Comment by Dreampie** [comment] 2016-01-21 12:52
yes,but  I do not want  to create an own implementation of the PageImpl class，so...

**Comment by dwelch2344** [comment] 2016-01-21 22:44
@Dreampie @Koizumi85 it's definitely annoying, but we have been using our own impl for a while (both independently and with `Feign`) so we just published it at 

If you want to use it, should be straight forward: 

```
      <repositories>
        <repository>
            <id>lemniscate-repo</id>
            <url>https://github.com/lemniscate/maven-repo/raw/master/releases</url>
        </repository>
        <repository>
            <id>lemniscate-snapshot-repo</id>
            <url>https://github.com/lemniscate/maven-repo/raw/master/snapshots</url>
            <snapshots>
            </snapshots>
        </repository>
      </repositories>
     <!-- ... -->
     <dependency> 
        <groupId>com.lemniscate.struct</groupId>
        <artifactId>spring-paging-module</artifactId>
        <version>1.0.0.RELEASE</version>
    </dependency>
```

And then just define a bean of `PagingModule`.

**Comment by spencergibb** [comment] 2016-01-21 22:49
@dwelch2344 Interesting. Makes me question if this is even a spring-cloud responsibility? Wouldn't that module go in spring-data somewhere?

**Comment by dwelch2344** [comment] 2016-01-21 22:55
Yeah, I'd prefer to see Spring Data make the actual PageImpl serializer-friendly. Or include a custom serializer (though I guess that creates a hard dependency on Jackson)

**Comment by jamesbassett** [comment] 2016-06-22 01:22
Hi all, thanks for the feign integration - it's really neat!

We worked around this issue by:

- overriding the default `SpringMvcContract` in the client config to deserialize `Page` as Spring's `PageImpl`
- writing a custom Jackson module to deserialize `PageImpl`

It would be a bit simpler to use your own `Page` implementation, but we wanted to use Spring's dammit!

Code is in kotlin, but you get the idea :)  

**Customized contract**

Make `Page` -> `PageImpl`

```kotlin
import feign.MethodMetadata
import org.apache.commons.lang3.reflect.TypeUtils
import org.springframework.cloud.netflix.feign.support.SpringMvcContract
import org.springframework.data.domain.Page
import org.springframework.data.domain.PageImpl
import java.lang.reflect.Method
import java.lang.reflect.ParameterizedType
class APIContract : SpringMvcContract() {

    override fun parseAndValidateMetadata(targetType: Class<*>?, method: Method?): MethodMetadata? {
        return super.parseAndValidateMetadata(targetType, method).apply {
            updatePageReturnType(this)
        }
    }

    private fun updatePageReturnType(metadata: MethodMetadata) {
        val returnType = metadata.returnType()

        if (returnType is ParameterizedType && returnType.rawType == Page::class.java) {
            metadata.returnType(TypeUtils.parameterizeWithOwner(returnType.ownerType, PageImpl::class.java,
                    *returnType.actualTypeArguments))
        }
    }
}
```

**Jackson module**

Could probably have also achieved this via a Deserializer...

```kotlin
import com.fasterxml.jackson.core.JsonParser
import com.fasterxml.jackson.databind.*
import com.fasterxml.jackson.databind.deser.CreatorProperty
import com.fasterxml.jackson.databind.deser.SettableBeanProperty
import com.fasterxml.jackson.databind.deser.ValueInstantiator
import com.fasterxml.jackson.databind.deser.ValueInstantiators
import com.fasterxml.jackson.databind.deser.std.StdValueInstantiator
import com.fasterxml.jackson.databind.module.SimpleDeserializers
import com.fasterxml.jackson.databind.module.SimpleModule
import com.fasterxml.jackson.databind.node.ArrayNode
import org.springframework.data.domain.PageImpl
import org.springframework.data.domain.PageRequest
import org.springframework.data.domain.Sort
import java.io.IOException
import java.util.*

/**
 * Jackson module to configure paging related serialization/deserialization.
 */
class PagingModule : SimpleModule("PagingModule") {
    override fun setupModule(context: SetupContext) {
        super.setupModule(context)
        context.addDeserializers(SimpleDeserializers().apply {
            addDeserializer(Sort::class.java, SortDeserializer())
        })
        context.addValueInstantiators(PageImplValueInstantiators())
    }
}

/**
 * Registers PageImplValueInstantiator for instantiating PageImpl instances.
 */
internal class PageImplValueInstantiators : ValueInstantiators {

    override fun findValueInstantiator(config: DeserializationConfig, beanDesc: BeanDescription, defaultInstantiator: ValueInstantiator): ValueInstantiator {
        if (!beanDesc.beanClass.isAssignableFrom(PageImpl::class.java)) {
            return defaultInstantiator
        }
        return beanDesc.toPageImplValueInstantiator(defaultInstantiator)
    }

    fun BeanDescription.toPageImplValueInstantiator(defaultInstantiator: ValueInstantiator): ValueInstantiator {
        if (type.containedTypeCount() == 1) {
            val contentType = type.containedType(0).rawClass
            return PageImplValueInstantiator(defaultInstantiator as StdValueInstantiator, contentType)
        } else {
            throw IllegalStateException("No generic type specified for PageImpl!")
        }

    }
}

/**
 * Jackson value instantiator for PageImpl instances.
 */
internal class PageImplValueInstantiator(
        private val valueInstantiator: StdValueInstantiator,
        private val contentType: Class<*>)
: StdValueInstantiator(valueInstantiator) {

    override fun canCreateFromObjectWith(): Boolean = true

    override fun getFromObjectArguments(config: DeserializationConfig): Array<out SettableBeanProperty> {
        val intType = config.constructType(Int::class.java)
        val longType = config.constructType(Long::class.java)
        // MutableList is used as the PageImpl's content is mutable from Kotlin's perspective
        val contentElementType = config.typeFactory.constructCollectionType(MutableList::class.java, contentType)
        val sortType = config.constructType(Sort::class.java)
        return arrayOf(
                creatorProperty("content", contentElementType, 0, PropertyMetadata.STD_REQUIRED),
                creatorProperty("number", intType, 1, PropertyMetadata.STD_REQUIRED),
                creatorProperty("size", intType, 2, PropertyMetadata.STD_REQUIRED),
                creatorProperty("sort", sortType, 3, PropertyMetadata.STD_OPTIONAL),
                creatorProperty("totalElements", longType, 4, PropertyMetadata.STD_REQUIRED)
        )
    }

    override fun createFromObjectWith(ctxt: DeserializationContext, args: Array<out Any>): Any {
        val content = args[0] as MutableList<*>?
        val number = args[1] as Int
        val size = args[2] as Int
        val sort = args[3] as? Sort
        val totalElements = args[4] as Long
        return PageImpl(content, PageRequest(number, size, sort), totalElements)
    }

    private fun creatorProperty(name: String, type: JavaType, index: Int, metadata: PropertyMetadata): CreatorProperty {
        return CreatorProperty(PropertyName.construct(name), type, null,
                null, null, null, index, null, metadata)
    }
}

class SortDeserializer : JsonDeserializer<Sort>() {

    @Throws(IOException::class)
    override fun deserialize(jp: JsonParser, ctxt: DeserializationContext): Sort {
        val orders = ArrayList<Sort.Order>()

        val oc = jp.codec
        val arrayNode = oc.readTree<ArrayNode>(jp)

        for (i in 0..arrayNode.size() - 1) {
            val node = arrayNode.get(i)

            val property = node.get("property").textValue()
            val directionValue = node.get("direction").textValue()
            val direction = Sort.Direction.fromString(directionValue)

            val order = Sort.Order(direction, property)
            orders.add(order)
        }

        return Sort(orders)
    }
}
```

**Comment by YooLin** [comment] 2019-07-19 06:13
@jamesbassett 

It works, thanks!
