### ISSUE TITLE
Spring Boot Actuator strange behavior

### ISSUE THREAD

**Issue by tschechniker** [spring-cloud/spring-cloud-netflix#3520] opened 2019-04-26 09:13 UTC
Hi,

we discovered a strange behavior with the spring boot actuator and the eureka check.

Whenever a Services gets deleted in the Eureka server the eureka status in the actuator turns from up to down.

Up output of actuator:
```json
"discoveryComposite": {
      "status": "UP",
      "details": {
        "discoveryClient": {
          "status": "UP",
          "details": {
            "services": [
              "SERVICE-1",
              "SERVICE-2",
            ]
          }
        },
        "eureka": {
          "description": "Remote status from Eureka server",
          "status": "UP",
          "details": {
            "applications": {
              "SERVICE-1": 1,
              "SERVICCE-2": 1,
            }
          }
        }
      }
    }
```

Down output:

```json
   "discoveryComposite": {
      "description": "Remote status from Eureka server",
      "status": "DOWN",
      "details": {
        "discoveryClient": {
          "status": "UP",
          "details": {
            "services": [
              "SERVICE-1",
            ]
          }
        },
        "eureka": {
          "description": "Remote status from Eureka server",
          "status": "DOWN",
          "details": {
            "applications": {
              "SERVICE-1": 1,
            }
          }
        }
      }
    }
```

I did not find any documentation about the actuator indicators of eureka. Why does one shows up and the other down?

**Comment by spencergibb** [comment] 2019-04-26 09:15
I've not seen that behavior before.

Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment] 2019-05-03 09:18
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-06-24 15:03
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-07-01 15:03
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-07-01 15:03 UTC
Labels: feedback-reminder, waiting for feedback
