### ISSUE TITLE
Unable to mark non-Java service as DOWN in Eureka via sidecar pause call

### ISSUE THREAD

**Issue by radubutnaru** [spring-cloud/spring-cloud-netflix#1443] opened 2016-11-03 14:27 UTC
In our deployment, we call the /pause management endpoint for Spring-Cloud-based Java services during rolling updates, prior to taking them down. This updates the Eureka service status to DOWN, hence no new requests are coming after the status is propagated to Eureka clients (approx. 1 minute). When all pending requests are completed, the service instance can be shut down. This is our "graceful shutdown" procedure.

We tried the same with .NET services integrated into Eureka via the Spring-Cloud sidecar. Unfortunately, calling the /pause sidecar endpoint does not mark the service DOWN in Eureka, as long as the .NET service is running and its health-uri returns health status UP.

Is this intended behavior? Any way of gracefully taking down services with sidecar?

**Comment by spencergibb** [comment] 2016-11-09 16:26
I don't think `/pause` was intended to mark anything as down, so it doesn't surprise me that it is inconsisten. There is ongoing work to add an actuator endpoint that will help with this. https://github.com/spring-cloud/spring-cloud-netflix/compare/service-registry

**Comment by radubutnaru** [comment] 2016-11-10 12:42
If the actuator endpoint would allow setting the Eureka service status, and that would work properly in the sidecar + .NET service scenario, we should be fine.

**Comment by brenuart** [comment] 2016-12-22 10:35
> I don't think /pause was intended to mark anything as down

Invoking `/pause` stops the application context.
In Brixton.SR7, `EurekaDiscoveryClientConfiguration` is a `SmartLifecycle` and its `stop()` method is therefore invoked when the `/pause` endpoint is called. That method clearly sets the InstanceStatus to *DOWN* as per the code below:
```
	public void stop() {
		if (this.applicationInfoManager.getInfo() != null) {

			if (log.isInfoEnabled()) {
				log.info("Unregistering application " + this.instanceConfig.getAppname()
						+ " with eureka with status DOWN");
			}
			this.applicationInfoManager.setInstanceStatus(InstanceStatus.DOWN);
		}
		this.running.set(false);
	}
```

That new status triggers an _onDemandeUpdate_ on the InstanceInfoReplicator and the information is propagated back to the Eureka Registry.

So I would say, _yes, /pause was intended to mark the app DOWN_ (at least until Brixton.SR7).

**Comment by brenuart** [comment] 2016-12-22 13:37
@radubutnaru check https://github.com/spring-cloud/spring-cloud-netflix/issues/1571 if you are  running on <= Brixton.SR7

**Comment by spencergibb** [comment] 2017-01-09 16:05
> If the actuator endpoint would allow setting the Eureka service status, and that would work properly in the sidecar + .NET service scenario, we should be fine

It will do just that, closing.

**Closed by spencergibb** 2017-01-09 16:05 UTC
