### ISSUE TITLE
MaxAutoRetriesNextServer AvailabilityFilteringRule Not working properly

### ISSUE THREAD

**Issue by huangpang** [spring-cloud/spring-cloud-netflix#3603] opened 2019-07-23 03:55 UTC
Bug report

When 'Max AutoRetriesNext Server' was configured,'Availability Filtering Rule' did not perform as expected.

I have two services, 192.168.0.205, 192.168.0.70.

I set the 205 service to Thread. sleep (30000) which has been timed out and failed all the time.

Expectation: As expected, 205 should not be called after several failures

Actual: 205 was called all the time, resulting in a very time-consuming request (because it was retried many times).

After code tracking, 70 services are actually invoked, but when stats is updated, 205 is passed in.

Code location:
![QQ图片20190723113211](https://user-images.githubusercontent.com/31001984/61680835-98391980-ad3d-11e9-9329-94a4a5aedd2e.png)

Load Balancer Command retains 205 information

![QQ图片20190723112733](https://user-images.githubusercontent.com/31001984/61680778-6aec6b80-ad3d-11e9-86c0-ecef27920e4c.png)

Causing LoadBalancerContext. noteRequestCompletion to always call clearance (stats. clearSuccessiveConnection Failure Count ()) I don't think that's correct.

I see a similar question to mine #3131 
I don't know if there is a solution to this problem. 
Thank you

--------------------------
  <spring-cloud-dependencies.version>Greenwich.RELEASE</spring-cloud-dependencies.version>
  <spring-boot-dependencies.version>2.1.3.RELEASE</spring-boot-dependencies.version>

**Comment by spencergibb** [comment] 2019-07-23 19:29
Code in screenshots isn't very helpful. Where is that code located?

Please try with Greenwich.SR2 and boot 2.1.6

**Comment by huangpang** [comment] 2019-07-24 02:20
> Code in screenshots isn't very helpful. Where is that code located?
> 
> Please try with Greenwich.SR2 and boot 2.1.6

I've used the latest version, but it's the same as before.
```
        <spring-cloud-dependencies.version>Greenwich.SR2</spring-cloud-dependencies.version>
        <spring-boot-dependencies.version>2.1.6.RELEASE</spring-boot-dependencies.version>
```

The above code is located at: 
com.netflix.loadbalancer.reactive.LoadBalancerCommand
com.netflix.loadbalancer.LoadBalancerContext
org.springframework.cloud.openfeign.ribbon.RetryableFeignLoadBalancer

I guess the process is as follows:

com.netflix.loadbalancer.AvailabilityFilteringRule.choose

Judgment 205 is available, but it's actually overtime, so it's retried.

Retry Selection 70

Finally, when you update stats, you do update 205 information, because Load Balancer Command retains the stats that started 205.

The debugging screenshots are as follows:
![1](https://user-images.githubusercontent.com/31001984/61759894-56bb7380-adfc-11e9-809d-e7c525991201.png)
![2](https://user-images.githubusercontent.com/31001984/61759899-5a4efa80-adfc-11e9-8bae-c14a83d73033.png)
![3](https://user-images.githubusercontent.com/31001984/61759903-5c18be00-adfc-11e9-89d5-914cd8cf5ba2.png)
![4](https://user-images.githubusercontent.com/31001984/61759904-5d49eb00-adfc-11e9-83ff-42ed8cd2852c.png)
![5](https://user-images.githubusercontent.com/31001984/61759906-5e7b1800-adfc-11e9-9bae-26df3f1b22fa.png)
![6](https://user-images.githubusercontent.com/31001984/61759907-5fac4500-adfc-11e9-97c5-10c39116dcbb.png)

**Comment by ryanjbaxter** [comment] 2019-07-24 18:52
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment] 2019-07-31 18:53
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-08-07 18:54
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-08-07 18:54 UTC
Labels: feedback-reminder, waiting for feedback
