### ISSUE TITLE
may be found a bug for httpclient connection leak

### ISSUE THREAD

**Issue by zhangxsh** [spring-cloud/spring-cloud-netflix#2831] opened 2018-04-10 12:14 UTC
refer #2814 

I use a subclass of DefaultErrorAttributes  to deal with exceptions

```
 @Component("unifyErrorAttributes")
public class UnifyErrorAttributes extends DefaultErrorAttributes {
```

But I found that when exception generated,the http client connection can not be released.

here is normal routed request log,there are leased and released both exist,it's normal:

![image](https://user-images.githubusercontent.com/37093837/38555755-f252f072-3cf9-11e8-9c53-29d42729a0c0.png)

But when route failed,only the http connection leased action exists but no released action,bcz the coming exception disturbed the release action in future:

![qq 20180410200139](https://user-images.githubusercontent.com/37093837/38555948-93a0b400-3cfa-11e8-8551-5abfdaff6619.jpg)

the PostErrorHandlerFilter.java is a post filter,it throw an exception when route failed.

```
    @Override
        public Object filter() {
        HttpServletResponse response = RequestContext.getCurrentContext().getResponse();
        int cde = response.getStatus();
        String uri=getOriginalRequest().getRequestURI();
        HttpStatus status=HttpStatus.valueOf(cde);
        String req_detail= (String) 
        ThreadLocalCache.get(GatewayFilterConstants.CacheKey.HTTP_REQ_DETAIL);
        String body= (String) 
        ThreadLocalCache.get(GatewayFilterConstants.CacheKey.HTTP_REQ_BODY_DETAIL);


        if(status.isError()){//||status.is3xxRedirection()){
            runtimeURLCollection.errorUrls(uri,";"+cde+"[route response error]");
            throw new GateWayException(BasicErrorEnum.ERROR_1001,"status:"+cde);
        }
        return null;
    }
```

so, at last,all of the connections are not released,my app is down.'netstat' shows all TCP  in CLOSE_WAIT
my question:
1、is this a problem?
2、how to deal with that?

**Comment by ryanjbaxter** [comment] 2018-04-10 14:49
Is `PostErrorHandlerFilter` something you wrote?

**Comment by zhangxsh** [comment] 2018-04-10 16:35
BTW，PostErrorHandlerFilter is a very very simple post filter，after request routed，it check the response code，if not 2xx then throw an exception，if an exception throws during the time，the http connection will not be released

**Comment by ryanjbaxter** [comment] 2018-04-10 18:10
Why throw an exception?

**Comment by brenuart** [comment] 2018-04-12 15:59
My feeling is the issue is larger than what originally described.
In short: _there is no guarantee the upstream response is *always* closed._

For instance, although `SendResponseFilter#writeResponse()` does it's best to guarantee that the response stream from origin is properly closed in all cases (cfr. release pooled connection). However, it does not cover exceptions thrown outside of thath method, like during `addResponseHeader()` for instance. A first solution could be to wrap the entire run() method with a try/finally and move the close logic there.

But still, this would only guarantee that the response is closed *IF* it goes through the SendResponseFilter. What would happen if an exception is raised somewhere between, say, the RibbonRoutingFilter and SendResponseFilter filters? Zuul should normally direct the request to the "error" filters - but none of them seems to care about closing the response like what the SendResponseFilter does.

A more robust approach would be:
- filters should explicitly register their resources needing to be disposed when the request is fully completed
- the RequestContext is unset() by the ZuulServletFilter at request completion. We could use a custom version that would dispose registered resources when `unset()` is invoked.

What you think ?

**Comment by ryanjbaxter** [comment] 2018-04-12 20:59
> filters should explicitly register their resources needing to be disposed when the request is fully completed

So in this case there would be some code in Spring Cloud Netflix that would then dispose all those resources?

**Comment by brenuart** [comment] 2018-04-12 21:09
I'm here thinking about "our" RibbonRoutingFilter and SimpleHostRoutingFilter. 
They sets the `zuulResponse` (a `ClientHttpResponse` or `HttpResponse`) and the _responseDataStream_ in the context. Both need to be explicitly closed/disposed when done. This is currently done by the SendResponseFilter (only).

**Comment by brenuart** [comment] 2018-04-12 22:01
Thinking out loud here...

But why not simply register the destruction callbacks under a new custom key in the RequestContext and let the ZuulController invoke them in its finally block ?

**Comment by zhangxsh** [comment] 2018-04-13 23:57
@brenuart good，you are right，you get the point

**Comment by hooverhe** [comment] 2018-04-17 09:06
@zhangxsh 我遇到同样的问题，向您请教，能加一下QQ或微信（同号）：64427037

**Comment by hooverhe** [comment] 2018-04-17 09:26
@brenuart @ryanjbaxter I am also curious that why the following timer didn't take effect while throwing exceptions? The timer should close the expired connections per 5 seconds.
    private void initialize() {
        this.httpClient = newClient();
        SOCKET_TIMEOUT.addCallback(this.clientloader);
        CONNECTION_TIMEOUT.addCallback(this.clientloader);
        this.connectionManagerTimer.schedule(new TimerTask() {
            @Override
            public void run() {
                if (SimpleHostRoutingFilter.this.connectionManager == null) {
                    return;
                }
                SimpleHostRoutingFilter.this.connectionManager.closeExpiredConnections();
            }
        }, 30000, 5000);
    }

**Comment by zhangxsh** [comment] 2018-04-19 08:53
@hooverhe bcz the expire close timer only close the connections which are expired but leak,leak means the connection can not to close or reuse.

1、if  exception throws，then the SendResponseFilter can not be invoked,and the connection are not to close:
```
finally {
			/**
			* Closing the wrapping InputStream itself has no effect on closing the underlying tcp connection since it's a wrapped stream. I guess for http
			* keep-alive. When closing the wrapping stream it tries to reach the end of the current request, which is impossible for infinite http streams. So
			* instead of closing the InputStream we close the HTTP response.
			*
			* @author Johannes Edmeier
			*/
			try {
				Object zuulResponse = RequestContext.getCurrentContext()
						.get("zuulResponse");
				if (zuulResponse instanceof Closeable) {
					((Closeable) zuulResponse).close();
				}
				outStream.flush();
				// The container will close the stream for us
			}
			catch (IOException ex) {
			log.warn("Error while sending response to client: " + ex.getMessage());
			}
		}
```

to see the stack trace,the close activity is doing by the method of "releaseConnection" in  ConnectionHolder.java ，close means:

1、really close;
2、not really close ,only mark the connection can reuse next time
```

private void releaseConnection(final boolean reusable) {
        if (this.released.compareAndSet(false, true)) {
            synchronized (this.managedConn) {
                if (reusable) {
                    this.manager.releaseConnection(this.managedConn,
                            this.state, this.validDuration, this.tunit);
                } else {
                    try {
                        this.managedConn.close();
                        log.debug("Connection discarded");
                    } catch (final IOException ex) {
                        if (this.log.isDebugEnabled()) {
                            this.log.debug(ex.getMessage(), ex);
                        }
                    } finally {
                        this.manager.releaseConnection(
                                this.managedConn, null, 0, TimeUnit.MILLISECONDS);
                    }
                }
            }
        }
    }

```
if ConnectionHolder not close the connection,the the connection can not reuse and can not cleared by the timer(bcz the timer will find the connection is active although it is idle in fact).

at last,the connection is terminated by the nginx(bcz of  keepAlive_timeout config) unilaterally.

when nginx send a FIN package to zuul,then the tcp protocol return ACK and changes the status of this tcp to CLOSE_WAIT locally and notify the http client  to close the socket,but the application do not response(no thread to use the socket,the connection is idle in fact),then the connection leaves in the status of  CLOSE_WAIT。
as the pic shows:
![image](https://user-images.githubusercontent.com/37093837/38980341-2decad20-43ef-11e8-917a-2e14e789c7a3.png)

then the connection in CLOSE_WAIT . As we mentioned over that,more and more connections are in close_wait.the number of close_wait if equal to the value of "max-per-route-connections"

**Comment by hooverhe** [comment] 2018-04-20 06:08
@brenuart The codes you provided works fine. Fixed my issue. Thanks. 
@zhangxsh Thanks for your explanation and guide. It helps me a lot.

**Comment by ancin** [comment] 2018-04-24 03:42
got many helps.thanks all.

**Closed** 2018-04-25 02:42 UTC
Labels: waiting for feedback

**Comment by brenuart** [comment] 2018-05-04 08:47
Your are getting an exception while closing the ResponseEntity - don't know why.
I think the sample RequestContext proposed above should not rethrow such exception but simply log it - just like what the Ribbon and SimpleHost routing filter do.

**Comment by jadetang** [comment] 2018-05-04 08:50
yes, I just want to know why there is an exception when closing the response entity.

**Comment by brenuart** [comment] 2018-05-04 08:52
No idea… trace it and post what you found ;-)

Or remove the custom RequestContext and see what happens with plain vanilla SpringCloud…

**Comment by jadetang** [comment] 2018-05-07 12:48
@brenuart I check the code of `SendResponseFilter`, it only closes the `zuulResponse` while in the `GH2831RequestContext ` it actually closes both `zuulResponse` and `responseDataStream`.  Why do we need to close the `ResponseDataStream` explicitly since the `ResponseDataStream` is actually a part of the `zuulResponse`?

**Comment by bramalingam81** [comment] 2019-08-19 07:26
@ryanjbaxter, @zhangxsh , @brenuart  Is the fix made available in latest release of Spring Cloud Netflix ? If so, could someone please let know version of release ?

**Comment by ryanjbaxter** [comment] 2019-08-19 23:54
@bramalingam81 the author closed the issue, there was never any changes made

**Comment by grchis** [comment] 2022-03-14 08:20
I think this issue was not fully fixed, since we encounter the same issue on the 1.4.6.RELEASE version. Apart from the issue that's mentioned here, which we do bump in from time to time, I also don't see why there is no connection kept alive so that it can be reused. 
Wouldn't be a better solution to modify the SimpleHostRoutingFilter to release the connection after the response has been received from the downstream services? 
I extended the  SimpleHostRoutingFilter, and modified the forward method, which is doing the actual http call, to close the stream:

`private HttpResponseWrapper forwardRequest(CloseableHttpClient httpclient,
                                                 HttpHost httpHost, HttpRequest httpRequest) throws IOException {
    ResponseHandler<HttpResponseWrapper> responseHandler = response -> {
      InputStream inputStream = response.getEntity() != null ? response.getEntity().getContent() : null;
      return new HttpResponseWrapper(response.getStatusLine().getStatusCode(), response.getAllHeaders(), inputStream);
    };
    return execute(httpHost, httpRequest, responseHandler, null);
  }

  private <T> T execute(final HttpHost target, final HttpRequest request,
                        final ResponseHandler<? extends T> responseHandler, final HttpContext context)
      throws IOException, ClientProtocolException {
    Args.notNull(responseHandler, "Response handler");
    final CloseableHttpResponse response = httpClient.execute(target, request, context);
    RequestContext.getCurrentContext().set("zuulResponse", response);
    try {
      final T result = responseHandler.handleResponse(response);
      final HttpEntity entity = response.getEntity();
      EntityUtils.consume(entity);
      return result;
    } catch (final ClientProtocolException t) {
      // Try to salvage the underlying connection in case of a protocol exception
      final HttpEntity entity = response.getEntity();
      try {
        EntityUtils.consume(entity);
      } catch (final Exception t2) {
        // Log this exception. The original exception is more
        // important and will be thrown to the caller.
        this.log.warn("Error consuming content after an exception.", t2);
      }
      throw t;
    } finally {
      response.close();
    }
  }`

Would you think this approach can cause issues moving forward? Also, is there a 'hard' reason why the stream is not closed just after executing the http request?
