### ISSUE TITLE
I have a question.

### ISSUE THREAD

**Issue by SoberChina** [spring-cloud/spring-cloud-netflix#1971] opened 2017-05-22 11:30 UTC
Hello everyone 

- 

1. `<dependencies>
2.       <dependency>
3.         <groupId>org.springframework.cloud</groupId>
4.         <artifactId>spring-cloud-dependencies</artifactId>
5.         <version>Dalston.RELEASE</version>
6.         <type>pom</type>
7.         <scope>import</scope>
8.       </dependency>
9.     </dependencies>`

What is this configuration for? I configured my `hystrix` ,This version of the `Camden.SR2` not work (http status 503)，the `Dalston.RELEASE` is ok. What is the difference between the two versions?  thanks very much !

**Comment by spencergibb** [comment] 2017-05-22 14:15
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

**Comment by spencergibb** [comment] 2017-05-22 14:16
I'm afraid you haven't explained the problem at all. I have no idea how to help you without you providing more details.

**Comment by SoberChina** [comment] 2017-05-23 01:59
Thanks @spencergibb 
```
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>Dalston.RELEASE</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
```
This is my maven config ，Access to `http://localhost:8084/hystrix.stream` Camden.SR2 version will be reported 503, Switch to Dalston.RELEASE version is ok,What is the difference between the two versions?

**Comment by ryanjbaxter** [comment] 2017-05-24 17:49
Can you provide a stack trace and a sample project that reproduces the problem?

**Comment by SoberChina** [comment] 2017-05-25 03:25
Hi @ryanjbaxter  [this](https://github.com/SoberChina/admin_server) this project  is not worke.
Remember to change the dependent version of the pom。Camden.SR2 is not work.Thanks.

**Comment by ryanjbaxter** [comment] 2017-05-25 19:14
The sample does not start when using `Camden.*` releases.

**Comment by spencergibb** [comment] 2018-01-18 00:25
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2018-01-18 00:25 UTC
Labels: waiting for feedback
