### ISSUE TITLE
NullPointerException on FeignClientFactoryBean

### ISSUE THREAD

**Issue by ezraroi** [spring-cloud/spring-cloud-netflix#1542] opened 2016-12-08 13:49 UTC
I am trying to write integration test to my service.
My service is using Feign to communicate with another service.
When i am running the test i am getting the following NPE:
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.intel.swiss.microservices.nbocollectorservice.iface.IDataJobService': FactoryBean threw exception on object creation; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:175)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:103)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1606)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:254)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:207)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1289)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1258)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1094)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1059)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
	... 77 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.springframework.cloud.netflix.feign.FeignClientFactoryBean.loadBalance(FeignClientFactoryBean.java:147)
	at org.springframework.cloud.netflix.feign.FeignClientFactoryBean.getObject(FeignClientFactoryBean.java:168)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:168)
	... 88 common frames omitted
```

The problem is that the Targeter interface is null, although it is autowired to the factory. Also i made sure that the `FeignAutoConfiguration` class is loaded on the test and it is. I see in the `FeignAutoConfiguration` the following:
```java
@Configuration
	@ConditionalOnClass(name = "feign.hystrix.HystrixFeign")
	protected static class HystrixFeignTargeterConfiguration {
		@Bean
		@ConditionalOnMissingBean
		public Targeter feignTargeter() {
			return new HystrixTargeter();
		}
	}

	@Configuration
	@ConditionalOnMissingClass("feign.hystrix.HystrixFeign")
	protected static class DefaultFeignTargeterConfiguration {
		@Bean
		@ConditionalOnMissingBean
		public Targeter feignTargeter() {
			return new DefaultTargeter();
		}
	}
```

None of those methods are invoked during runtime of the test but other beans in the class are created.

Spring Cloud Camden release train
Spring Boot 1.4.2

**Comment by ezraroi** [comment] 2016-12-08 13:51
This is my test configuration:
```java
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT, classes = Application.class)
@TestPropertySource(properties = {
    "debug=true"
})
@DirtiesContext
```

```java
@SpringBootApplication
@EnableFeignClients
@EnableHystrixDashboard
@EnableDiscoveryClient
@EnableHystrix
public class Application  {
...
}
```

**Comment by spencergibb** [comment] 2016-12-08 16:38
@ezraroi what specific version are you using? Targeter hasn't been autowired since https://github.com/spring-cloud/spring-cloud-netflix/commit/f30e8b7b4630db74b1cccf436fb3f50f94618427 in Camden.SR1. SR3 is the latest.

**Comment by ezraroi** [comment] 2016-12-08 17:23
I am on Camden.Release

**Comment by spencergibb** [comment] 2016-12-08 17:26
Duplicate of #1366 which has been fixed for two releases.

**Closed by spencergibb** 2016-12-08 17:26 UTC
Labels: waiting for feedback

**Comment by ezraroi** [comment] 2016-12-08 18:13
So should i move from release to SR3 or just remove dev tools?

**Comment by spencergibb** [comment] 2016-12-08 18:19
The fix is in SR1, so update to at least that or the latest.

**Comment by ezraroi** [comment] 2016-12-08 18:21
Isnt Camden.Release is the latest SR3?

**Comment by spencergibb** [comment] 2016-12-08 18:24
>  SR3 is the latest.

**Comment by ezraroi** [comment] 2016-12-08 18:32
Cool thanks. I was sure release points to the latest

**Comment by spencergibb** [comment] 2016-12-08 18:46
no, it doesn't
