### ISSUE TITLE
EurekaRegistration not work when spring context refresh

### ISSUE THREAD

**Issue by loveai88** [spring-cloud/spring-cloud-netflix#2476] opened 2017-11-28 10:14 UTC
If I enable eureka.healthcheck,it will random error .

This is log
```
[2017-11-28 18:07:55.290]  INFO [microservice-config-server,,,,] 93921 --- [  XNIO-2 task-5] [com.netflix.discovery.DiscoveryClient:shutdown:852] com.netflix.discovery.DiscoveryClient    : Shutting down DiscoveryClient ...
[2017-11-28 18:07:55.294]  INFO [microservice-config-server,,,,] 93921 --- [  XNIO-2 task-5] [com.netflix.discovery.DiscoveryClient:unregister:884] com.netflix.discovery.DiscoveryClient    : Unregistering ...
[2017-11-28 18:07:55.301]  INFO [microservice-config-server,,,,] 93921 --- [  XNIO-2 task-5] [com.netflix.discovery.DiscoveryClient:unregister:886] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_MICROSERVICE-CONFIG-SERVER/192.168.11.248:microservice-config-server:7000 - deregister  status: 200
[2017-11-28 18:07:55.306]  INFO [microservice-config-server,,,,] 93921 --- [  XNIO-2 task-5] [com.netflix.discovery.DiscoveryClient:shutdown:873] com.netflix.discovery.DiscoveryClient    : Completed shut down of DiscoveryClient
[2017-11-28 18:07:55.309]  INFO [microservice-config-server,,,,] 93921 --- [  XNIO-2 task-5] [com.netflix.discovery.DiscoveryClient:<init>:344] com.netflix.discovery.DiscoveryClient    : Initializing Eureka in region us-east-1
[2017-11-28 18:07:55.312]  INFO [microservice-config-server,,,,] 93921 --- [  XNIO-2 task-5] [com.netflix.discovery.provider.DiscoveryJerseyProvider:<init>:70] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON encoding codec LegacyJacksonJson
[2017-11-28 18:07:55.313]  INFO [microservice-config-server,,,,] 93921 --- [  XNIO-2 task-5] [com.netflix.discovery.provider.DiscoveryJerseyProvider:<init>:71] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON decoding codec LegacyJacksonJson
[2017-11-28 18:07:55.316]  INFO [microservice-config-server,,,,] 93921 --- [  XNIO-2 task-5] [com.netflix.discovery.provider.DiscoveryJerseyProvider:<init>:80] c.n.d.provider.DiscoveryJerseyProvider   : Using XML encoding codec XStreamXml
[2017-11-28 18:07:55.317]  INFO [microservice-config-server,,,,] 93921 --- [  XNIO-2 task-5] [com.netflix.discovery.provider.DiscoveryJerseyProvider:<init>:81] c.n.d.provider.DiscoveryJerseyProvider   : Using XML decoding codec XStreamXml
[2017-11-28 18:07:55.450]  INFO [microservice-config-server,,,,] 93921 --- [  XNIO-2 task-5] [com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver:getClusterEndpoints:43] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
[2017-11-28 18:07:55.451]  INFO [microservice-config-server,,,,] 93921 --- [  XNIO-2 task-5] [com.netflix.discovery.DiscoveryClient:fetchRegistry:920] com.netflix.discovery.DiscoveryClient    : Disable delta property : false
[2017-11-28 18:07:55.452]  INFO [microservice-config-server,,,,] 93921 --- [  XNIO-2 task-5] [com.netflix.discovery.DiscoveryClient:fetchRegistry:921] com.netflix.discovery.DiscoveryClient    : Single vip registry refresh property : null
[2017-11-28 18:07:55.453]  INFO [microservice-config-server,,,,] 93921 --- [  XNIO-2 task-5] [com.netflix.discovery.DiscoveryClient:fetchRegistry:922] com.netflix.discovery.DiscoveryClient    : Force full registry fetch : false
[2017-11-28 18:07:55.453]  INFO [microservice-config-server,,,,] 93921 --- [  XNIO-2 task-5] [com.netflix.discovery.DiscoveryClient:fetchRegistry:923] com.netflix.discovery.DiscoveryClient    : Application is null : false
[2017-11-28 18:07:55.454]  INFO [microservice-config-server,,,,] 93921 --- [  XNIO-2 task-5] [com.netflix.discovery.DiscoveryClient:fetchRegistry:924] com.netflix.discovery.DiscoveryClient    : Registered Applications size is zero : true
[2017-11-28 18:07:55.454]  INFO [microservice-config-server,,,,] 93921 --- [  XNIO-2 task-5] [com.netflix.discovery.DiscoveryClient:fetchRegistry:926] com.netflix.discovery.DiscoveryClient    : Application version is -1: true
[2017-11-28 18:07:55.455]  INFO [microservice-config-server,,,,] 93921 --- [  XNIO-2 task-5] [com.netflix.discovery.DiscoveryClient:getAndStoreFullRegistry:1009] com.netflix.discovery.DiscoveryClient    : Getting all instance registry info from the eureka server
[2017-11-28 18:07:55.465]  INFO [microservice-config-server,,,,] 93921 --- [  XNIO-2 task-5] [com.netflix.discovery.DiscoveryClient:getAndStoreFullRegistry:1018] com.netflix.discovery.DiscoveryClient    : The response status is 200
[2017-11-28 18:07:55.466]  INFO [microservice-config-server,,,,] 93921 --- [  XNIO-2 task-5] [com.netflix.discovery.DiscoveryClient:initScheduledTasks:1244] com.netflix.discovery.DiscoveryClient    : Starting heartbeat executor: renew interval is: 30
[2017-11-28 18:07:55.467]  INFO [microservice-config-server,,,,] 93921 --- [  XNIO-2 task-5] [com.netflix.discovery.InstanceInfoReplicator:<init>:59] c.n.discovery.InstanceInfoReplicator     : InstanceInfoReplicator onDemand update allowed rate per min is 4
[2017-11-28 18:07:55.468]  INFO [microservice-config-server,,,,] 93921 --- [  XNIO-2 task-5] [com.netflix.discovery.DiscoveryClient:<init>:425] com.netflix.discovery.DiscoveryClient    : Discovery Client initialized at timestamp 1511863675468 with initial instances count: 18
[2017-11-28 18:07:55.476]  WARN [microservice-config-server,,,,] 93921 --- [  XNIO-2 task-5] [com.netflix.discovery.DiscoveryClient$3:notify:1277] com.netflix.discovery.DiscoveryClient    : Saw local status change event StatusChangeEvent [timestamp=1511863675476, current=UP, previous=DOWN]
[2017-11-28 18:07:55.477]  INFO [microservice-config-server,,,,] 93921 --- [nfoReplicator-0] [com.netflix.discovery.DiscoveryClient:register:795] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_MICROSERVICE-CONFIG-SERVER/192.168.11.248:microservice-config-server:7000: registering service...
[2017-11-28 18:07:55.486]  INFO [microservice-config-server,,,,] 93921 --- [nfoReplicator-0] [com.netflix.discovery.DiscoveryClient:register:804] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_MICROSERVICE-CONFIG-SERVER/192.168.11.248:microservice-config-server:7000 - registration status: 204
[2017-11-28 18:07:55.502] ERROR [microservice-config-server,,,,] 93921 --- [  XNIO-2 task-5] [io.undertow.servlet.api.LoggingExceptionHandler:handleThrowable:80] io.undertow.request                      : UT005023: Exception handling request to /bus/refresh

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@8f81942 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@22e3ca2d[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:326)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:812)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@8f81942 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@22e3ca2d[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:632)
	at com.netflix.discovery.InstanceInfoReplicator.onDemandUpdate(InstanceInfoReplicator.java:77)
	at com.netflix.discovery.DiscoveryClient.registerHealthCheck(DiscoveryClient.java:618)
	at com.netflix.discovery.DiscoveryClient$$FastClassBySpringCGLIB$$a84c8cb4.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.cloud.context.config.StandardBeanLifecycleDecorator$2.invoke(StandardBeanLifecycleDecorator.java:85)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at org.springframework.cloud.netflix.eureka.CloudEurekaClient$$EnhancerBySpringCGLIB$$24756cb2.registerHealthCheck(<generated>)
	at org.springframework.cloud.netflix.eureka.serviceregistry.EurekaServiceRegistry.register(EurekaServiceRegistry.java:49)
	at org.springframework.cloud.netflix.eureka.serviceregistry.EurekaAutoServiceRegistration.start(EurekaAutoServiceRegistration.java:73)
	at org.springframework.cloud.netflix.eureka.EurekaDiscoveryClientConfiguration$EurekaClientConfigurationRefresher.onApplicationEvent(EurekaDiscoveryClientConfiguration.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:256)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:177)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:140)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.cloud.context.scope.refresh.RefreshScope.refreshAll(RefreshScope.java:146)
	at org.springframework.cloud.context.refresh.ContextRefresher.refresh(ContextRefresher.java:58)
	at org.springframework.cloud.bus.event.RefreshListener.onApplicationEvent(RefreshListener.java:43)
	at org.springframework.cloud.bus.event.RefreshListener.onApplicationEvent(RefreshListener.java:30)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.cloud.bus.endpoint.AbstractBusEndpoint.publish(AbstractBusEndpoint.java:48)
	at org.springframework.cloud.bus.endpoint.RefreshBusEndpoint.refresh(RefreshBusEndpoint.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	... 61 common frames omitted
```

This is eureka config
```
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: 
    healthcheck:
      enabled: true
```

This is pom
```
<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
		<spring-cloud.version>Dalston.SR2</spring-cloud.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-config-server</artifactId>
		</dependency>
                <dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-bus-amqp</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-eureka</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
```

**Comment by loveai88** [comment] 2017-11-28 15:38
I found that `DiscoveryClient` is `@Singleton`,but when I debug,there is two,I think one is the new,and another should delete.And the exception is because of the delete one.

**Comment by loveai88** [comment] 2017-11-29 08:39
When refresh,`EurekaAutoServiceRegistration` will call start(),but the `EurekaRegistration` is the old which is destroy,so the thread pool is terminal.But it will call `			this.serviceRegistry.register(this.registration);
`,the `			reg.getEurekaClient().registerHealthCheck(reg.getHealthCheckHandler());
`will error.

**Comment by loveai88** [comment] 2017-11-30 01:48
is it not a bug?

**Comment by ryanjbaxter** [comment] 2017-12-03 14:46
Rather than pasting the code in the issue its better to provide a project that reproduces the issue.  If you have an idea of what the problem is would you mind submitting a PR?

**Comment by spencergibb** [comment] 2018-01-18 00:50
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2018-01-18 00:50 UTC
Labels: waiting for feedback
