### ISSUE TITLE
Zuul proxy overrides ContentType header to UTF-8

### ISSUE THREAD

**Issue by Lwiczyn** [spring-cloud/spring-cloud-netflix#914] opened 2016-03-17 19:06 UTC
Upon moving my service behind a Zuul proxy, a test verifying the ContentType header of attachments sent to the service began to fail. Previously, these test attachments were sent to the service with a ContentType of <text/plain;charset=us-ascii;name=file1.txt>, but after moving to Zuul, they were coming back as <text/plain;name=file1.txt;charset=UTF-8>. I removed the proxy and verified that without the proxy in the middle, the headers worked as expected.

After triage, I traced the issue to setCharacterEncoding("UTF-8") at SendResponseFilter ln 92, where the SendResponeFilter sets the response header's encoding to UTF-8. This overrides the ContentType header on the proxied message without accounting for other content types. Is there a reason that this overriding takes place without checking for non-UTF-8 content, and is there some way to disable it short of writing my own filter?

**Comment by spencergibb** [comment] 2016-03-22 22:00
Duplicate of #530 that has been fixed?

**Comment by Lwiczyn** [comment] 2016-03-25 18:59
@spencergibb 
Brixton.RC1 is proving non-passive for my test environment. Hoping to sort it all out and get validation of the fix by early next week.

**Comment by Lwiczyn** [comment] 2016-03-28 18:44
@spencergibb 
Confirmed: the commit from #530 fixes the problem. This issue can be closed. Thank you for your time.

**Closed** 2016-03-28 18:46 UTC
