### ISSUE TITLE
Zuul: server name based routing

### ISSUE THREAD

**Issue by mayaswrath** [spring-cloud/spring-cloud-netflix#378] opened 2015-06-05 18:25 UTC
I have been reviewing the Zuul stuff and it looks like there is no way to specify routes for a specific server name. I know some of this could be achieved by creating the pre filter and changing the context's serviceId or requestURI so that when it gets to the RibbonRoutingFilter or SimpleHostRoutingFilter it ends up going somewhere specific. This just seems like a really clunky work around. 

It would also be nice to 404 on a route if it did not exist for the current server name.

Are there plans for something like this or has it been considered?

**Comment by spencergibb** [comment] 2015-06-05 18:33
So you mean route based on the incoming server name rather than a path in the request?  If so, it has been requested before in #285

**Comment by mayaswrath** [comment] 2015-06-05 18:44
Yea that is what I was looking for. Didn't see that one when looking through the issues. Thanks

**Comment by spencergibb** [comment] 2015-06-05 18:48
Closed duplicate of #285

**Closed by spencergibb** 2015-06-05 18:48 UTC
Labels: duplicate
