### ISSUE TITLE
ERROR DiscoveryClient - ........ was unable to send heartbeat!

### ISSUE THREAD

**Issue by jinsenianhua-ai** [spring-cloud/spring-cloud-netflix#4119] opened 2022-09-15 00:13 UTC
Hi,

First, I upgraded spring cloud from Hoxton. SR12 to 2021.0.2, and spring cloud netflix from 2.2.10. RELEASE to 3.1.2. Now, The discovery client are occasionally unable to send heartbeat!, It will recover automatically after 5 seconds. This phenomenon happens about 10 times a day. Could you help on this:
![image](https://user-images.githubusercontent.com/43307372/190283760-7cc1d475-bae7-4139-9988-366094c9718a.png)

My code for Eureka Server yml file is below:

eureka:
    instance:
        hostname: ${HOSTNAME:localhost}
        lease-renewal-interval-in-seconds: 10
        lease-expiration-duration-in-seconds: 20
        secure-port-enabled: true
        secure-port: ${server.port}
        non-secure-port-enabled: false
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/
    server:
        waitTimeInMsWhenSyncEmpty: 0
        enableSelfPreservation: false
    dashboard:
        enabled: true

The discovery client application.yml file is as below:

eureka:
    client:
        register-with-eureka: true
        service-url:
            defaultZone: ${EUREKA_SERVER_URI:@spring.eureka.address@/eureka/}
    instance:
        hostname: ${HOSTNAME:localhost}

**Comment by spencergibb** [comment] 2023-03-04 05:33
If you'd like us to spend some time investigating, please take the time to provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) (something that we can unzip attached to this issue or git clone, build, and deploy) that reproduces the problem.

**Comment by spring-cloud-issues** [comment] 2023-03-11 05:37
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2023-03-18 05:36
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2023-03-18 05:36 UTC
Labels: waiting for feedback, feedback-reminder
