### ISSUE TITLE
Feign can never compress request/response.

### ISSUE THREAD

**Issue by eacdy** [spring-cloud/spring-cloud-netflix#1580] opened 2016-12-29 11:00 UTC
It seems that the feign's compression won't work. My version is Spring Cloud Camden SR3.

Here goes my configuration.

application.properties

```
feign.compression.response.enabled=true
feign.compression.request.enabled=true
feign.compression.request.mime-types=text/xml,application/xml,application/json
feign.compression.request.min-request-size=2048
```

I found the compression won't work. When I debuged the feign service, I  found that the code can never be loaded. like the pic below.
![1](https://cloud.githubusercontent.com/assets/9031050/21542481/0108043e-cdf9-11e6-95c6-2bb2f313081b.png)

Then I go into the code, in `spring-cloud-netflix-core`

```java
@Configuration
@EnableConfigurationProperties(FeignClientEncodingProperties.class)
@ConditionalOnClass(Feign.class)
@ConditionalOnBean(ApacheHttpClient.class)
@ConditionalOnProperty(value = "feign.compression.request.enabled", matchIfMissing = false)
@AutoConfigureBefore(FeignAutoConfiguration.class)
public class FeignContentGzipEncodingAutoConfiguration {

    @Bean
    public FeignContentGzipEncodingInterceptor feignContentGzipEncodingInterceptor(FeignClientEncodingProperties properties) {
        return new FeignContentGzipEncodingInterceptor(properties);
    }
}
```

In this line:

```
@ConditionalOnBean(ApacheHttpClient.class)
```

this class ApacheHttpClient, is in the jar `feign-httpclient` .

but the  dependency is even not in the classpath. Here goes my POM.XML

```xml
  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-eureka</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-feign</artifactId>
    </dependency>
  </dependencies>

  <!-- 引入spring cloud的依赖 -->
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>Camden.SR3</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
```

So, I added the denpency mannally.

```xml
    <dependency>
      <groupId>io.github.openfeign</groupId>
      <artifactId>feign-httpclient</artifactId>
    </dependency>
```

BUT even I did this, Feign's compression can never work.

## My Question

* What's wrong?
* Is it a bug?
* feign.compression.request.min-request-size=2048    Does it mean 2048 byte?

**Comment by eacdy** [comment] 2016-12-29 11:03
@jmnarloch @ryanjbaxter

**Comment by ryanjbaxter** [comment] 2017-01-03 21:12
The `feign-httpclient` dependency is included in [spring-cloud-netflix](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-dependencies/pom.xml#L295), so you do not need to include it in your POM.  Also notice that it is `@ConditionalOnBean` meaning the Spring Bean must be present.  The bean is created [here](https://github.com/spring-cloud/spring-cloud-netflix/blob/758ff920fc71d9a2aaf41d1250d3cc5ddd46b870/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/feign/FeignAutoConfiguration.java#L88).  However, `FeignContentGzipEncodingAutoConfiguration` is set to auto configure before `FeignAutoConfiguration` so the `ApacheHttpClient` bean will not have been created yet.

This might have worked before this change https://github.com/spring-cloud/spring-cloud-netflix/commit/959b0072696c321f524f9413f4399bdebdc0a670.  Maybe @spencergibb can verify?

**Comment by spencergibb** [comment] 2017-01-09 19:04
@ryanjbaxter the pom line you pointed to is `dependencyManagement` not `dependency` so it is indeed optional and including `feign-httpclient` is correct. The deletion in 959b0072696c321f524f9413f4399bdebdc0a670 was a duplicate that is still in [`FeignAutoConfiguration`](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/feign/FeignAutoConfiguration.java#L80-L101)

**Comment by ryanjbaxter** [comment] 2017-01-09 19:22
Right but I think the problem is that `FeignContentGzipEncodingAutoConfiguration` needs the `ApacheHttpClient` bean and is set to be configured before `FeignAutoConfiguration` which creates the `ApacheHttpClient` bean.  There fore the `ApacheHttpClient` bean will not be there when `FeignContentGzipEncodingAutoConfiguration`runs.

When the bean was being created twice before (which I agree is a bug) the problem probably didnt exist....at least that is my theory.

**Comment by spencergibb** [comment] 2017-01-09 19:42
So the fix is `FeignContentGzipEncodingAutoConfiguration` needs `@AutoConfigureAfter(FeignAutoConfiguration.class)` then?

**Comment by ryanjbaxter** [comment] 2017-01-10 15:55
Yes I think so.  But I am also wondering why the condition on the `ApacheHttpClient` bean is even there to begin with.  Maybe @jmnarloch could let us know why that condition is there, it is not obvious to me.

**Comment by eacdy** [comment] 2017-01-13 07:56
seems HAPPEN in Camden.SR4, too.

**Comment by ryanjbaxter** [comment] 2017-01-13 21:11
@jmnarloch bump, see my comment above, would love your insight.

**Comment by jpuigsegur** [comment] 2017-03-08 12:05
Hi, This is happening to us also. 
Any advance on the final solution?
Suggested workaround meanwhile?

Thanks.

**Comment by ryanjbaxter** [comment] 2017-03-08 20:01
@jpuigsegur I was hoping @jmnarloch would comment on the issue, but at this point I think we can just make the change.  I dont have a workaround at the moment, I think we can just make the fix I proposed

**Comment by ryanjbaxter** [comment] 2017-03-08 20:17
@jpuigsegur and @eacdy could you please try the fix in this branch and see if it works for you?  You can clone the branch, do `.mvnw install`, and then make sure you depend on `Camden.BUILD-SNAPSHOT`.

**Comment by pgonzalezgua** [comment] 2017-03-09 09:31
Hello @ryanjbaxter,
  I'm working with @jpuigsegur. This commit should solve the request compression.  The same problem occurs with the response compression and I think that the same change should be done in the class FeignAcceptGzipEncodingAutoConfiguration.

Thank you for your time.

**Comment by ryanjbaxter** [comment] 2017-03-09 16:06
Thanks, made a change there as well.  Let me know how it works.

**Comment by ryanjbaxter** [comment] 2017-05-01 18:06
@pgonzalezgua @jpuigsegur we are about to do a Camden SR release.  I would like to get this in.  Did you confirm that the changes are working as expected?

**Comment by jpuigsegur** [comment] 2017-05-02 21:32
Hi, Yes the request compression is working for us with these changes.
Thanks!

**Comment by ryanjbaxter** [comment] 2017-05-04 15:57
This has been fixed in both the 1.2.x and master branches.

**Closed by ryanjbaxter** 2017-05-04 15:57 UTC
Labels: in progress

**Comment by davidmelia** [comment] 2017-10-12 08:38
Hi,

@ryanjbaxter  I cannot get this to work.  If I create a Spring Boot 1.5.7.RELEASE (Dalston.SR4) Starter Project in eclipse with the following dependencies

```
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-feign</artifactId>
		</dependency>	
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>io.github.openfeign</groupId>
			<artifactId>feign-httpclient</artifactId>
		</dependency>		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
``` 
and add 

```
feign.compression.request.enabled=true
feign.compression.response.enabled=true
feign.httpclient.enabled=true
```
then GZIP is not enabled
```
FeignAcceptGzipEncodingAutoConfiguration: {
notMatched: [
{
condition: "OnBeanCondition",
message: "@ConditionalOnBean (types: feign.httpclient.ApacheHttpClient; SearchStrategy: all) did not find any beans"
}
],
matched: [
{
condition: "OnClassCondition",
message: "@ConditionalOnClass found required class 'feign.Feign'; @ConditionalOnMissingClass did not find unwanted class"
},
{
condition: "OnPropertyCondition",
message: "@ConditionalOnProperty (feign.compression.response.enabled) matched"
}
]
},
```

The only way to get this to work is to add 
```
	@Bean
	public ApacheHttpClient apacheHttpClient() {
		return new ApacheHttpClient();
	}
```

Thanks

**Comment by gbtec-ingogriebsch** [comment] 2017-11-18 13:54
@ryanjbaxter @spencergibb We have more or less the same situation as @davidmelia 
The auto configuration is not triggered at all because the ApacheHttpClient bean is not part of the application context at the moment the auto cfg's are triggering.
The way @davidmelia is also not working because if we are adding a ApacheHttpClient bean to the context the service is starting up, the auto cfg's are triggering and the header will be set but now the service discovery is not working anymore.
Therefore we are in limbo a little bit and don't really know how to configure/use the compression feature.
We are running Spring Boot 1.5.7 and Dalston.SR4. The resolved Spring Cloud Netflix Core version is 1.3.5.RELEASE.

**Comment by ryanjbaxter** [comment] 2017-11-18 18:38
@gbtec-ingogriebsch I dont see why service discovery isnt working.  I think you should open a new issue for this.

**Comment by gbtec-ingogriebsch** [comment] 2017-11-18 19:03
@ryanjbaxter In general I would still like to understand how one should configure his system to get compression used on Feign if using Spring Boot 1.5.x and Spring Cloud Dalston.SRX. If I understand it right it is not necessary to do what @davidmelia is trying to do. And I also would like to avoid configuring a ApacheHttpClient @Bean if it is not really necessary. Therefore it would be really helpful if you could give some hint about how to do it.

The thing with the service discovery is a problem I got after I added a new @Bean of type ApacheHttpClient to my context. Having this bean in the context is enabling the compression but if I try to execute the remote call to the other service which is registered at my local eureka I now get an exception the moment Feign is trying to reach the service. Without having a ApacheHttpClient @Bean in the context the remote call is working but then I have no compression.

Before creating a new issue I would like to understand if it is intended to configure a ApacheHttpClient @Bean to get the compression enabled.

I would really appreciate a little bit more detailed answer respectively explanation... :)

**Comment by ryanjbaxter** [comment] 2017-11-20 11:31
@gbtec-ingogriebsch no you should not have to configure a new `ApacheHttpClient` bean.  Open a new issue with a sample that reproduces the problem and we can look into it.

**Comment by gbtec-ingogriebsch** [comment] 2017-11-22 09:11
@ryanjbaxter I have created a new issue #2462 to clarify if there is a bug or if we are doing something wrong...
