### ISSUE TITLE
Eureka lient start failed : Ignoring onDemand update due to rate limiter

### ISSUE THREAD

**Issue by Tneciv** [spring-cloud/spring-cloud-netflix#3387] opened 2019-02-13 09:39 UTC
I use **spring boot 2.1.2.RELEASE** and **spring cloud Greenwich.RELEASE**

Other services use most of the same libs works fine except 2 services use **spring-boot-starter-amqp** cannot be registered to eureka .

Warn log is : **Ignoring onDemand update due to rate limiter**

**Comment by Tneciv** [comment] 2019-02-13 09:49
Seems like this : https://stackoverflow.com/questions/39168690/how-to-use-spring-amqp-with-spring-cloud-microservice

**Comment by OlgaMaciaszek** [comment] 2019-02-13 10:07
Hello @Tneciv does the solution from the referenced SO  issue not work? If this does not solve your issue, please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue, so we can verify it.

**Comment by spring-issuemaster** [comment] 2019-02-20 10:07
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-02-27 10:07
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-02-27 10:07 UTC
Labels: feedback-reminder, waiting for feedback
