### ISSUE TITLE
ClassNotFound exception when using Spring Cloud Starter Turbine AMQP

### ISSUE THREAD

**Issue by mpas** [spring-cloud/spring-cloud-netflix#562] opened 2015-09-29 05:57 UTC
When using the Spring Cloud Starter Turbine AMQP an exception is thrown:

Caused by: java.lang.ClassNotFoundException: com.netflix.turbine.aggregator.InstanceKey

**Comment by dsyer** [comment] 2015-09-29 09:12
Something got bust in the starters. You can work around it by adding an explicit dependency on turbine-core with the correct version:

```
		<dependency>
			<groupId>com.netflix.turbine</groupId>
			<artifactId>turbine-core</artifactId>
			<version>2.0.0-DP.2</version>
		</dependency>
```

**Comment by dsyer** [comment] 2015-09-29 09:38
Fixed in https://github.com/spring-cloud/spring-cloud-starters/commit/fd26f569c17a633c7cef9b79777537866e69b985

**Closed by dsyer** 2015-09-29 09:38 UTC
Labels: bug

**Comment by caingocduong** [comment] 2017-10-24 10:28
I added this dependency: 
`<dependency>`
`           ` `<groupId>com.netflix.turbine</groupId>`
`           ` `<artifactId>turbine-core</artifactId>`
`           ` `<version>2.0.0-DP.2</version>`
       ` </dependency>`
But still have exception:
 Caused by: java.lang.ClassNotFoundException: com.netflix.turbine.aggregator.InstanceKey

**Comment by dsyer** [comment] 2017-10-24 10:53
This issue was closed more than 2 years ago. I seriously doubt you experienced the same thing with any recent code. Please open a detailed issue with a sample project if you have issues with latest stable or snapshots.
