### ISSUE TITLE
Class cast exception during improper exception handling of Zuul Filter

### ISSUE THREAD

**Issue by jayguidos** [spring-cloud/spring-cloud-netflix#3052] opened 2018-07-02 23:42 UTC
Bug Report

spring-cloud-netflix-zuul-2.0.0-RELEASE 

org.springframework.cloud.netflix.zuul.filters.post.SendErrorFilter tests for the type of the throwable cause, but then casts a different object and fails.  This screen snapshot show the code in error:

![image](https://user-images.githubusercontent.com/4714987/42191218-f4d96b62-7e1e-11e8-8eb4-7629030acc65.png)

and a debugging snapshot showing a test where the cast is about to fail.
![image](https://user-images.githubusercontent.com/4714987/42191264-2962647e-7e1f-11e8-8758-303dcb6b731b.png)

**Comment by ryanjbaxter** [comment] 2018-07-03 00:11
Duplicate of #3033

**Closed by ryanjbaxter** 2018-07-03 00:11 UTC
