### ISSUE TITLE
Enable CORS for Zuul doesn't work.

### ISSUE THREAD

**Issue by coderdaudat** [spring-cloud/spring-cloud-netflix#2680] opened 2018-01-25 04:20 UTC
I used spring boot version 1.5.6.RELEASE. When I use a access_token for call some api from edge server. It's work when used postman but the front-end reactJs have a  issue:  No 'Access-Control-Allow-Origin' header is present on the requested.

I tried config cros follow on stackoverflow and tutorial spring.io but it still doesn't work. 
Please help me. Thank you.

This is my code:

@SpringBootApplication
@Controller
@EnableZuulProxy
@EnableResourceServer
public class ZuulApplication {

    private static final Logger LOG = LoggerFactory.getLogger(ZuulApplication.class);

    @Bean
    public Filter logFilter() {
        // TODO: Extract bean-def to Util-component!
        CommonsRequestLoggingFilter filter = new CommonsRequestLoggingFilter();
        filter.setIncludeQueryString(true);
        filter.setIncludePayload(true);
        filter.setMaxPayloadLength(5120);
        return filter;
    }

    public static void main(String[] args) {
        int buildNo = 15;
        LOG.info("Edge-server, starting build no. {}...", buildNo);

        new SpringApplicationBuilder(ZuulApplication.class).web(true).run(args);

        LOG.info("Edge-server, build no. {} started", buildNo);
    }

    @Configuration
    @EnableWebMvc
    public class WebConfig extends WebMvcConfigurerAdapter {
        @Override
        public void addCorsMappings(CorsRegistry registry) {
            registry.addMapping("/**");
        }
    }
}

application.yml

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  ignoredServices: "*"
  prefix: /api
  routes:
    customer-composite-service: /customer/**

**Comment by ryanjbaxter** [comment] 2018-01-25 12:42
Please learn how to [format code on GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

Instead of posting code in the issue itself could you please provide a sample app that reproduces the problem.

**Comment by spencergibb** [comment] 2018-04-25 19:30
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2018-04-25 19:30 UTC
Labels: waiting for feedback
