### ISSUE TITLE
dependencies has conflict

### ISSUE THREAD

**Issue by EightMonth** [spring-cloud/spring-cloud-netflix#3607] opened 2019-07-29 06:09 UTC
i have a company dependencies pom on spring cloud Greenwich.SR2.
it add spring cloud openfeing、spring cloud hystrix、spring cloud ribbon.
then
other company project make this pom as parent
will happend
com.netflix.hystrix.core:hystrix-core:1.4.26 (right version 1.5.18 on sping cloud netflix dependencies)
com.netflix.archaius:archauis-core:0.6.6 (right version : 0.7.6 on spring cloud netflix dependencies)

**Comment by marcingrzejszczak** [comment] 2019-07-29 14:10
Are you using any explicit versions manually? Can you please upload the whole pom of yours? It would be even better if you upload the whole sample

**Comment by EightMonth** [comment] 2019-07-30 02:44
[issue_pom.txt](https://github.com/spring-cloud/spring-cloud-netflix/files/3444965/issue_pom.txt)

**Comment by TYsewyn** [comment] 2019-07-30 08:55
Please remove the version of `spring-cloud-starter-openfeign` in your pom to rely on the dependency management from Spring Cloud.

I can't replicate this issue:
`mvn dependency:tree -Dverbose -Dincludes=com.netflix.archaius:archaius-core`:
```
com.demo.basic:com-demo-basic:jar:1.2.3-SNAPSHOT
\- org.springframework.cloud:spring-cloud-starter-openfeign:jar:2.1.2.RELEASE:compile
   \- io.github.openfeign:feign-hystrix:jar:10.2.3:compile
      \- com.netflix.archaius:archaius-core:jar:0.7.6:compile
```

`mvn dependency:tree -Dverbose -Dincludes=com.netflix.hystrix:hystrix-core`:
```
com.demo.basic:com-demo-basic:jar:1.2.3-SNAPSHOT
\- org.springframework.cloud:spring-cloud-starter-openfeign:jar:2.1.2.RELEASE:compile
   \- io.github.openfeign:feign-hystrix:jar:10.2.3:compile
      \- com.netflix.hystrix:hystrix-core:jar:1.5.18:compile
```

So what exactly are you doing here? The pom file you added to this issue acts as the parent?
If that's the case there is something wrong in the other pom file since this one resolves the correct dependencies AFAIC.

**Comment by EightMonth** [comment] 2019-07-30 09:58
I‘m so sorry for open this issue
this problem exists when i using spring cloud Greenwich SR 1
also at that time specify the version of spring cloud openfeign when I try to fix above problem
above problem has disappeared when I update spring cloud version is Greenwich SR2.
i dont have enough test , that's my fault.
but the problem still exists in the Greenwich SR1 version
Best Regards
Eightmonth

**Comment by TYsewyn** [comment] 2019-07-30 11:03
No reason to be sorry, every issue can be a valid one :)
`Greenwich.SR2` is the latest service release, so I'd encourage you to use this version.
I'm going to close this issue as you said it is not reproducible with that version.

**Closed by TYsewyn** 2019-07-30 11:03 UTC
Labels: feedback-provided
