### ISSUE TITLE
@EnableZuulProxy cause server.port=0 not working with Eureka registration

### ISSUE THREAD

**Issue by yoga1982** [spring-cloud/spring-cloud-netflix#1899] opened 2017-05-01 03:01 UTC
I'm using Spring-Cloud version "Dalston.RELEASE".
before i add annotation "@EnableZuulProxy" in my application, the random port can be registered into Eureka, here is the codes from my application.
```java
@EnableEurekaClient
@SpringBootApplication
@Controller
public class Application {
  ...
}
```

my application.yml
``` yml
  ...
server:
  port: 0
  ...
```

but if i add annotation "@EnableZuulProxy", the application register port '0' into Eureka.
Is it a bug? Is there any solution for it?

**Comment by ltjsjyyy** [comment] 2017-05-01 12:37
Seems the root cause is not because i add @EnableZuulProxy, i also can reproduce the issue if I set a break-point in 
line65 in EurekaAutoServiceRegistration.class
```
 >>>>      if (this.port.get() != 0 && this.registration.getNonSecurePort() == 0) {
			this.registration.setNonSecurePort(this.port.get());
		}
```

**Comment by ltjsjyyy** [comment] 2017-05-01 13:48
up vote
0
down vote
accept
also find something from logs:

when my application initializing without @EnableZuulProxy:

...
...
2017-05-01 21:34:57.409 INFO 23021 --- [ main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 59408 (http)
2017-05-01 21:34:57.410 INFO 23021 --- [ main] .s.c.n.e.s.EurekaAutoServiceRegistration : Updating port to 59408
2017-05-01 21:34:57.904 INFO 23021 --- [ main] o.s.c.n.eureka.InstanceInfoFactory : Setting initial instance status as: STARTING
...
...

when my application initializing with @EnableZuulProxy:

...
...
2017-05-01 21:39:41.409 INFO 23041 --- [ main] o.s.c.n.eureka.InstanceInfoFactory : Setting initial instance status as: STARTING
...
...
2017-05-01 21:39:42.137 INFO 23041 --- [ main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 59614 (http)
2017-05-01 21:39:42.138 INFO 23041 --- [ main] .s.c.n.e.s.EurekaAutoServiceRegistration : Updating port to 59614

the register information should be generated in InstanceInfoFactory. in the first case:
when generating register information, the real port has already updated by TomcatEmbeddedServletContainer and EurekaAutoServiceRegistration.

but in the second case:
the port updating is after register information generation.

still no idea how to resolve the problem.

**Comment by spencergibb** [comment] 2017-05-01 13:53
No need to cross post. http://stackoverflow.com/questions/43719690/random-port-not-registered-to-eureka-when-use-enablezuulproxy please close one.

Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

**Comment by ltjsjyyy** [comment] 2017-05-01 14:07
thanks for your reply, i will close question in stackoverflow.

**Comment by spencergibb** [comment] 2017-05-02 03:08
Obviously, the workaround is to not use `sever.port=0`. (I wish we never supported it, to begin with). There is an `@Import` in `@EnableZuulProxy` that is forcing some early initialization. Moving that `@Import` to auto-configuration ala `@EnableEurekaServer` would fix it, though not a super high priority.

**Comment by erezo** [comment] 2017-08-15 09:02
I also having the same issue, trying to run zuul and microservices with random ports.
@spencergibb what's the status of the change?
Is there a workaround we can implement other than not working with server.port=0?

**Comment by ryanjbaxter** [comment] 2017-08-15 11:36
There is no plan changed, that is why we have added the "help wanted" label.

**Comment by spencergibb** [comment] 2019-01-31 18:32
Moving to auto configuration was done here 31a3ff61e8297ee5d8b0cb8750cc43a52aaecff3

**Closed by spencergibb** 2019-01-31 18:32 UTC
Labels: enhancement, help wanted
