### ISSUE TITLE
Eureka Client register as OUT_OF_SERVICE after running for a while.

### ISSUE THREAD

**Issue by Incarnation-p-lee** [spring-cloud/spring-cloud-netflix#4080] opened 2022-03-17 00:33 UTC
**Describe the bug**
We have met one issue about eureka client talk to eureka server, which is difficult to reproduce but it happened from our customers' production environment monthly.

```
Spring cloud version = 2020.0.3
Eureka client version = 3.0.3
```

The typical behavior may look like below. One or more applications registered as UP and keep running, after a while, it registered as OUT_OF_SERVICE and sticking on it, or even worse sticking on DOWN.

During the time range, both the eureka server and client never restart, and it takes the default configuration of eureka client. It doesn't enable anything like eureka in K8S explicitly.

```
2022-03-07 11:11:50, Eureka server started.
2022-03-07 11:11:56, Application A registered as UP.
2022-03-07 11:53:36, Application A registered as OUT_OF_SERVICE.
2022-03-07 12:58:36, Application A registered as UP and then OUT_OF_SERVICE.
2022-03-07 12:59:15, Application B registered as DOWN.
```

This issue only happens in some of application(s) talk to eureka server, it is not easy to reproduce it with sample application(s). Could you please help to insight me into what we can do to resolve this issue?

Thank you!

**Sample**
I am sorry that it is not easy to reproduce this issue for happy path, we try to reproduce it by running more than 15 days but failed.

**Comment by OlgaMaciaszek** [comment] 2022-09-01 11:10
Hello, @Incarnation-p-lee , thanks for submitting the issue. We have done some changes around these areas recently: https://github.com/spring-cloud/spring-cloud-netflix/commit/a5e038cf13ee02845dfd5d5a8cf1aaa238b8fae5, https://github.com/spring-cloud/spring-cloud-netflix/commit/079ae668c08523399f105db51e3cab120ff512ff. Please verify against Spring Cloud `2021.0.3` and let us know if the problem persists, providing a reproducible sample (unfortunately, we'll not be able to triage the issue without a sample that reproduces it).

**Comment by spring-cloud-issues** [comment] 2022-09-08 11:12
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2022-09-15 11:12
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2022-09-15 11:12 UTC
Labels: waiting for feedback, feedback-reminder
