### ISSUE TITLE
EurekaHealthIndicator breaks @WebMvcTest because of @EnableDiscoveryClient on @SpringBootApplication

### ISSUE THREAD

**Issue by timtebeek** [spring-cloud/spring-cloud-netflix#1859] opened 2017-04-13 13:58 UTC
Hi all,

Sample app here: https://github.com/timtebeek/eureka-health-indicator
Build results here: https://travis-ci.org/timtebeek/eureka-health-indicator

What I've done:
- Created a starter app using `spring-cloud-starter-eureka`, `-web` & `-actuator` using `Dalston.RELEASE`.
- Created a `@SpringBootApplication` also using `@EnableDiscoveryClient` and `@RestController`.
- Created a `WebMvcTest` as follows:
```
@RunWith(SpringRunner.class)
@WebMvcTest(controllers = EurekaHealthIndicatorApplication.class)
public class EhiaWebMvcTest {
	@Autowired
	private MockMvc mockmvc;

	@Test
	public void test() throws Exception {
		mockmvc.perform(get("/hello")).andExpect(status().isOk());
	}
}
```

The problem:
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method eurekaHealthIndicator in org.springframework.cloud.netflix.eureka.EurekaDiscoveryClientConfiguration$EurekaHealthIndicatorConfiguration required a bean of type 'com.netflix.discovery.EurekaClient' that could not be found.


Action:

Consider defining a bean of type 'com.netflix.discovery.EurekaClient' in your configuration.
```

Analysis:
- `EurekaDiscoveryClientConfiguration` is triggered for the `WebMvcTest`, and it in turn sets up the `EurekaHealthIndicatorConfiguration` even though the required `EurekaClient`, `EurekaInstanceConfig` and `EurekaClientConfig` beans are missing.

**Comment by timtebeek** [comment] 2017-04-13 14:02
This breaks quite a few `@WebMvcTest` tests in various apps of mine after upgrading to `Dalston.RELEASE`. Adding `@MockBean` instances of the three beans works, but that's not feasible on a large codebase.

What can be done to resolve this issue? The conditionals that trigger the EurekaHealthIndicator seem to be internal to Spring. Setting `eureka.client.enabled=false` breaks some integration tests that do need eureka to run, and I see no option to only set that property in the WebMvcTests.. Did I miss something?

**Comment by spencergibb** [comment] 2017-04-13 17:56
From comments with the spring-boot guys, the problem is that `@WebMvcTest` only starts up part of your application, but your application has `@EnableDiscoveryClient`, but it's auto-config isn't executed. See https://github.com/spring-projects/spring-boot/issues/7999 for more information. Not sure this is a spring cloud issue.

**Comment by spencergibb** [comment] 2017-04-13 17:57
Specifically https://github.com/spring-projects/spring-boot/issues/8170 seems to be a duplicate of this.

**Comment by timtebeek** [comment] 2017-04-14 08:44
Ah great, thanks! That does appear to be the issue. My actual application was slightly different in that it uses a `@Import` of a class that has `@EnableDiscoveryClient`, triggering the same problem. I now think the test issue after the upgrade to Dalston coincided with an internal library upgrade that brought in the `@EnableDiscoveryClient`. Sorry for the duplicate! I'll update the title to make the issue easier to find / identify for others.

**Closed** 2017-04-14 08:45 UTC
Labels: waiting for feedback
