### ISSUE TITLE
Eureka: dangerous to change InstanceStatus during EurekaServiceregistry.unregister()

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#2542] opened 2017-12-12 17:54 UTC
About this line: https://github.com/spring-cloud/spring-cloud-netflix/blob/170739e662d1a57e6013b7f1599f1e58409bb87e/spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/serviceregistry/EurekaServiceRegistry.java#L67

Changing the InstanceStatus may trigger the async status replication. The replication request may hit the eureka server *after* the unregister request leading to the application being re-registered again.

This scenario is one of the primary causes of https://github.com/spring-cloud/spring-cloud-netflix/issues/1543.

On the other hand, this line is not required since Netflix's DiscoveryClient.shutdown() method already handles the status change: https://github.com/Netflix/eureka/blob/master/eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java#L896-L902

Finally, changing the status to `DOWN` prior unregistration causes an extra (useless) call to the Eureka server: a `register` call for the status updated followed by a `cancel` for the unregistration.

**Comment by ryanjbaxter** [comment] 2017-12-15 19:03
Seems to make sense to me, want to submit a PR?

**Comment by jebeaudet** [comment] 2018-01-18 01:28
It's actually a race condition in Eureka that has been fixed in https://github.com/Netflix/eureka/pull/1023, setting the instance status sets the dirty flag and the `InstanceInfoReplicator` catches that and might even re-register the instance.

IMO, setting the instance to DOWN and triggering an on demand refresh is wanted (let's say for long shutdown procedures), however, without that PR in Eureka, it _can_ create issues (server registering with DOWN status and eventually dying because of the lack of heartbeat instead of unregistering cleanly).

**Comment by ryanjbaxter** [comment] 2018-01-18 12:52
Thanks @jebeaudet.  We can pick up that fix in the next Netflix release.  Doesnt look like it has made it into a release yet.

**Comment by tdanylchuk** [comment] 2018-05-25 09:56
I'm facing with similar issue using `Edgware.SR3` cloud version, after /refresh endpoint called eureka instance is recreated and in logs i see
```
INFO serviceregistry.EurekaServiceRegistry: Unregistering application my-service with eureka with status DOWN 
INFO serviceregistry.EurekaServiceRegistry: Registering application my-service with eureka with status DOWN 
```
w/o any exceptions or warn messages, and service goes DOWN in eureka and never come back UP.
But if I create simple sample with same cloud version it goes ok.
this issue so far reproducing with 100% chance.

So question is this problem might related to original topic issue? Any chance to have fix for this?

**Comment by spencergibb** [comment] 2019-01-28 16:58
Closing as we have versions of eureka which include the fix.

**Closed by spencergibb** 2019-01-28 16:58 UTC
Labels: waiting-for-triage
