### ISSUE TITLE
Support spring-boot 1.3.0

### ISSUE THREAD

**Issue by xxlabaza** [spring-cloud/spring-cloud-netflix#326] opened 2015-04-30 14:33 UTC
Hi,

The issue is connected with this one: https://github.com/spring-cloud/spring-cloud-netflix/issues/212

My **pom.xml** dependencies block:

```
    ...
    <dependencies>
       ...
       <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-feign</artifactId>
            <version>1.0.2.BUILD-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-security</artifactId>
            <version>1.0.2.BUILD-SNAPSHOT</version>
        </dependency>
        ...
    </dependencies>
    ...
```

My **Main.class** app class:

```
@EnableHystrix
@EnableEurekaClient
@EnableFeignClients
@EnableOAuth2Resource
@SpringBootApplication
public class Main {

    public static void main (String[] args) {
        new SpringApplicationBuilder(Main.class)
                .web(true)
                .run(args);
    }
}
```

My **ClientApi.class**:

```
@FeignClient("clientsample")
interface ClientApi {

    @RequestMapping(
            value = "/who",
            method = RequestMethod.GET
    )
    String getWho ();
}
```

And my **bootstrap.yml** has the next configuration:

```
...
spring:
  oauth2:
    resource:
      userInfoUri: <http://my-domain.com/auth/user>
...
```

When I try to start my Spring Boot app it prints the following:

```
Caused by: java.lang.NullPointerException: encoder
	at feign.Util.checkNotNull(Util.java:93)
	at feign.ReflectiveFeign$ParseHandlersByName.<init>(ReflectiveFeign.java:138)
	at feign.ReflectiveFeign$ParseHandlersByName$$InjectAdapter.get(ReflectiveFeign$ParseHandlersByName$$InjectAdapter.java:67)
	at feign.ReflectiveFeign$ParseHandlersByName$$InjectAdapter.get(ReflectiveFeign$ParseHandlersByName$$InjectAdapter.java:19)
	at feign.ReflectiveFeign$$InjectAdapter.get(ReflectiveFeign$$InjectAdapter.java:62)
	at feign.ReflectiveFeign$$InjectAdapter.get(ReflectiveFeign$$InjectAdapter.java:23)
	at feign.ReflectiveFeign$Module$$ModuleAdapter$ProvideFeignProvidesAdapter.get(ReflectiveFeign$Module$$ModuleAdapter.java:114)
	at feign.ReflectiveFeign$Module$$ModuleAdapter$ProvideFeignProvidesAdapter.get(ReflectiveFeign$Module$$ModuleAdapter.java:78)
	at dagger.ObjectGraph$DaggerObjectGraph.get(ObjectGraph.java:272)
	at feign.Feign$Builder.target(Feign.java:265)
	at org.springframework.cloud.netflix.feign.FeignClientFactoryBean.loadBalance(FeignClientFactoryBean.java:126)
	at org.springframework.cloud.netflix.feign.FeignClientFactoryBean.getObject(FeignClientFactoryBean.java:136)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:168)
	... 44 more
```

If I turn off Spring Security:

* remove dependency from **pom.xml**;

* remove oauth2 configuration from **bootstrap.yml**.

it works perfectly, but how to run it with Spring Security?

**Comment by spencergibb** [comment] 2015-05-01 15:49
@xxlabaza I am unable to reproduce your problem with [this sample](https://github.com/spencergibb/communityanswers/tree/gh-326-feign-npe).  Do you have a sample project you can share?

**Comment by xxlabaza** [comment] 2015-05-01 16:14
@spencergibb yep, here we go:
https://github.com/xxlabaza/feignsample.git

**Comment by spencergibb** [comment] 2015-05-01 16:42
@xxlabaza we don't support spring-boot 1.3.0 yet.  Changing to 1.2.3.RELEASE and I didn't get your error.

**Comment by xxlabaza** [comment] 2015-05-01 16:51
Oh, this is very sad, I've lost 2 days =(

**Comment by spencergibb** [comment] 2015-05-01 16:54
@xxlabaza we will, we just haven't started it yet.  This will be an issue when we start

**Comment by joaoevangelista** [comment] 2015-05-04 19:36
If it can help, I had the same issue while trying to upgrade to boot 1.3.0.BUILD-SNAPSHOT. I debugged the source code while initializing the application, seems it's caused by `FeignClientsConfiguration` beans, which was not been created in time to `FeignClientFactoryBean` autowire dependencies, strange is it isn't creating any Spring autowire exception, but the `@Autowired private Encoder encoder;` has receiving `null`, and the debugger didn't pass through `FeignClientsConfiguration`,  class.
Maybe an configuration order issue came from the framework or race condition ?

**Comment by kristofferpeterhansel** [comment] 2015-05-28 14:12
I'm getting this exact issue with Spring Boot 1.2.3 and Spring Cloud 1.0.0 (or 1.0.1 for that matter).

In my case it may have been triggered by moving to Spring Data "Fowler" and MongoDB 3.0 drivers. At least that is the main major dependency chance since it started happening. And the issue happens when a MongoDB repository needs a client to a service that is implemented with the Feign support

The interesting part is that I don't see this running it locally in my IDE. But it does happen when I run it in on my server. So it does indeed appear it may be a race condition.

**Comment by spencergibb** [comment] 2015-06-17 16:36
See this initializr commit https://github.com/spring-io/initializr/commit/e6a1a17e519157b666d969b323f3f6a710d812a5

**Comment by jordanjennings** [comment] 2015-06-17 18:37
+1 for Spring Boot 1.3.0 support. Is there any general timeline in mind for this (even for a snapshot version)?

**Comment by spencergibb** [comment] 2015-06-17 18:46
Not a date, but in the pipeline it would not be a minor release.  There is a minor release that needs to come first.  We'll probably have at least one milestone and release candidate.

**Comment by spencergibb** [comment] 2015-07-27 21:34
Closed via https://github.com/spring-cloud/spring-cloud-build/commit/dd98d1e209a72ce8670c19ba65f163c9ad36e2d2

**Closed by spencergibb** 2015-07-27 21:34 UTC
