### ISSUE TITLE
Eureka Client doesn't change its status to UP

### ISSUE THREAD

**Issue by krasilnikovdmtr** [spring-cloud/spring-cloud-netflix#2490] opened 2017-11-30 22:54 UTC
Hi there. We came across a problem that Eureka Client doesn't change its status to _UP_ after registration in Eureka Server (even though `/health` endpoint indicates that it's _UP_).

**Given:**

Spring Boot based application with Spring Cloud support.

Spring Boot - 1.5.4.RELEASE
Spring Cloud - 1.3.1.RELEASE with eureka-client - 1.6.2

_although the same problem was for spring-boot 1.5.9.RELEASE and spring-cloud 1.3.5.RELEASE_

Application configurations:

```
eureka.instance.initialStatus=DOWN
eureka.client.healthcheck.enabled=true
```

**Scenario:**

We deploy a bunch of instances of the same spring boot application. Once all instances are up and running, they're all registered in Eureka Server with initial _DOWN_ status. One by one they should change their status to _UP_.

The problem is that some of them never change their status. 

Usually, there were 2-5 (this number varies randomly from restart to restart) out of 24 instances that never updated their status. The thing is that `/health` endpoint always showed that instance is _UP_ for all health checks registered, but in Eureka UI status was always _DOWN_.

**Investigation:**

It's really hard to reproduce this kind of bug (we could reproduce it only on one of our environments) and I can't provide a simple project to demonstrate this behavior, so I'll just try to describe the problem itself and my thoughts about it.

`DiscoveryClient` uses `HealthCheckHandler` in its `refreshInstanceInfo` method in order to get status for instance. By default, it happens every 30 seconds, and if status has changed, it will be propagated to the Eureka Server on the next heartbeat.

There are two implementations of `HealthCheckHandler` interface. The first one is provided by _Netflix_ which is `HealthCheckCallbackToHandlerBridge`, the other one is provided by _Spring Cloud_ itself which is `EurekaHealthCheckHandler`.

I was able to debug some of my instances at runtime, and it turned out that instances whose status was _DOWN_ were using `HealthCheckCallbackToHandlerBridge` to determine the status, the other ones, whose status was _UP_, were using `EurekaHealthCheckHandler`. 

It seemed really strange, so I went through the code in _eureka-client_ module and took a look at the implementation of `getStatus(InstanceInfo.InstanceStatus currentStatus)` from `HealthCheckCallbackToHandlerBridge`

That's how it looks like:

```
@Override
public InstanceInfo.InstanceStatus getStatus(InstanceInfo.InstanceStatus currentStatus) {
    if (null == callback || InstanceInfo.InstanceStatus.STARTING == currentStatus
            || InstanceInfo.InstanceStatus.OUT_OF_SERVICE == currentStatus) { // Do not go to healthcheck handler if the status is starting or OOS.
        return currentStatus;
    }

    return callback.isHealthy() ? InstanceInfo.InstanceStatus.UP : InstanceInfo.InstanceStatus.DOWN;
}
```

According to this implementation, it was pretty obvious why those instances never changed their status to _UP_. If the first condition is true (which is my case, since I don't have any callback provided),  then the `currentStatus` (which is _DOWN_) will be always returned.

The next question was how come that different implementations of `HealthCheckHandler` are used for different instances of the same application with the same configuration.

Taking look at the code in` spring-cloud-netflix-eureka-client` it can be seen, that `EurekaAutoServiceRegistration` uses `EurekaRegistration` to register it in `EurekaServiceRegistry`.

```
public class EurekaAutoServiceRegistration implements AutoServiceRegistration, SmartLifecycle, Ordered {

	@Override
	public void start() {

		// ... other code omitted

		this.serviceRegistry.register(this.registration);

		this.context.publishEvent(new InstanceRegisteredEvent<>(this, this.registration.getInstanceConfig()));
		this.running.set(true);
	}
	
}
```

During registration process in `EurekaServiceRegistry` the following check is performed:

```
@Override
public void register(EurekaRegistration reg) {

	// ... other code omitted

	if (reg.getHealthCheckHandler() != null) {
		reg.getEurekaClient().registerHealthCheck(reg.getHealthCheckHandler());
	}
}
```

If this condition returns false, then `DiscoveryClient` will use default health check handler which is `HealthCheckCallbackToHandlerBridge` from `netflix-eureka` module.

Now let's see how `EurekaRegistration` gets created (`EurekaClientAutoConfiguration` is responsible for this)

```
// ... other code

@Autowired(required = false)
private HealthCheckHandler healthCheckHandler;

// ... other code

@Bean
@ConditionalOnBean(AutoServiceRegistrationProperties.class)
@ConditionalOnProperty(value = "spring.cloud.service-registry.auto-registration.enabled", matchIfMissing = true)
public EurekaRegistration eurekaRegistration(EurekaClient eurekaClient, CloudEurekaInstanceConfig instanceConfig, ApplicationInfoManager applicationInfoManager) {
	return EurekaRegistration.builder(instanceConfig)
			.with(applicationInfoManager)
			.with(eurekaClient)
			.with(healthCheckHandler)
			.build();
}
```

We can see that `healthCheckHandler` is marked as not required. Actually, it's clear why, cause if `eureka.client.healthcheck.enabled` is false, then `EurekaHealthCheckHandlerConfiguration` never creates `EurekaHealthCheckHandler` bean and potentially it could be null, but not in my case.

**Conclusion:**

Based on the above, it looks like for some reasons `EurekaRegistration` bean gets created before `EurekaHealthCheckHandler` bean. It gets initialized with `healthCheckHandler` field equal to null. Since it's null, `EurekaHealthCheckHandler` won't be registered with `DiscoveryClient` and hence `HealthCheckCallbackToHandlerBridge` will be used as a default health check handler, and it will always return the current status (which is _DOWN_ in my case) for eureka instance.

The interesting thing is that eventually `EurekaHealthCheckHandler` gets created (I was able to see it from `/beans` actuator endpoint) but too late so it's never used. 

Finally, I managed to make it work using the following code:

```
@Configuration
public class EurekaContext {

    @Bean
    @ConditionalOnProperty({"eureka.client.enabled", "eureka.client.healthcheck.enabled"})
    public EurekaHealthCheckHandlerRegistrationListener eurekaHealthCheckHandlerRegistrationListener(EurekaHealthCheckHandler eurekaHealthCheckHandler,
                                                                                                     EurekaClient eurekaClient) {
        return new EurekaHealthCheckHandlerRegistrationListener(eurekaHealthCheckHandler, eurekaClient);
    }

    @Slf4j
    @AllArgsConstructor
    public static class EurekaHealthCheckHandlerRegistrationListener implements ApplicationListener<InstanceRegisteredEvent> {

        private final EurekaHealthCheckHandler eurekaHealthCheckHandler;
        private final EurekaClient eurekaClient;

        @Override
        public void onApplicationEvent(InstanceRegisteredEvent event) {
            if (!(eurekaClient.getHealthCheckHandler() instanceof EurekaHealthCheckHandler)) {
                eurekaClient.registerHealthCheck(eurekaHealthCheckHandler);
            }
        }
    }
}
```

It worked out for me, but it'd be really nice to see it fixed in the upcoming releases. 

I think the most obvious solution would be to add 

`@AutoConfigureAfter(EurekaHealthCheckHandlerConfiguration.class)` to `EurekaClientAutoConfiguration`. 

In this way, we could guarantee, that if `EurekaHealthCheckHandlerConfiguration` is enabled, then `EurekaHealthCheckHandler` will be created and injected into `EurekaClientAutoConfiguration` before `EurekaRegistration` is created.

If you're ok with this and the problem is really how I described it, then I could create a PR.

BTW, I've noticed that in Spring Boot 2.0.0 the process of `EurekaRegistration` creation was refactored and now `healthCheckHandler` is injected in the right way.

```
@Bean
@ConditionalOnBean(AutoServiceRegistrationProperties.class)
@ConditionalOnProperty(value = "spring.cloud.service-registry.auto-registration.enabled", matchIfMissing = true)
public EurekaRegistration eurekaRegistration(EurekaClient eurekaClient, CloudEurekaInstanceConfig instanceConfig, ApplicationInfoManager applicationInfoManager, ObjectProvider<HealthCheckHandler> healthCheckHandler) {
	return EurekaRegistration.builder(instanceConfig)
			.with(applicationInfoManager)
			.with(eurekaClient)
			.with(healthCheckHandler)
			.build();
}
```

So, in this case, `HealthCheckHandler` is coming from `ObjectProvider`, not from _field injection_ and it should work fine (I didn't test it with 2.0.0 version though)

@dsyer @spencergibb  could you please take a look into this? 

Thanks in advance!

**Comment by dsyer** [comment] 2017-12-01 09:28
If the `ObjectProvider` works we can backport it to 1.4.x I guess. The `@AutoConfigureAfter` trick only works with autoconfig classes (clue in the name), so it's not certain to work as you guessed (but feel free to try it).

What we really need though, is an explanation of why the instantiation was early. Did you see any of those tell tale "not eligible for autoproxying" logs, e.g.

```
2017-11-30 17:57:18.815  INFO 8218 --- [       Thread-0] trationDelegate$BeanPostProcessorChecker : Bean '...' of type [...] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
```

Debugging into that can give you clue about what is forcing the early instantiation.

**Comment by krasilnikovdmtr** [comment] 2017-12-01 10:51
@dsyer thanks for your prompt reply

> If the ObjectProvider works we can backport it to 1.4.x I guess.

At first glance, it should work but I can't be hundred percent sure since I haven't tested it yet. I could've checked it but in this case, I need to migrate to the _2.0.0_ version and it's not that trivial.

> Actually, from what I can tell there is already an order applied in EurekaClientAutoConfiguration and it looks like it would work.

Could you please clarify what you meant by _an order applied_?

For now, I see the following: 

**Version 1.3.1.RELEASE** 

```
@Configuration
@EnableConfigurationProperties
@ConditionalOnClass(EurekaClientConfig.class)
@ConditionalOnBean(EurekaDiscoveryClientConfiguration.Marker.class)
@ConditionalOnProperty(value = "eureka.client.enabled", matchIfMissing = true)
@AutoConfigureBefore({ NoopDiscoveryClientAutoConfiguration.class,
		CommonsClientAutoConfiguration.class, ServiceRegistryAutoConfiguration.class })
@AutoConfigureAfter(name = "org.springframework.cloud.autoconfigure.RefreshAutoConfiguration")
public class EurekaClientAutoConfiguration { ... }
```

As you can see it should be configured only after `RefreshAutoConfiguration`. The other thing, is that it depends on the bean `EurekaDiscoveryClientConfiguration.Marker.class` which is created by `EurekaDiscoveryClientConfiguration` which in its turn is a parent configuration for `EurekaHealthCheckHandlerConfiguration`.  So, I would say that there's an implicit relation between `EurekaClientAutoConfiguration` and `EurekaHealthCheckHandlerConfiguration` and ideally the latter one should be created first.

**Version 2.0.0.M4** 

```
@Configuration
@EnableConfigurationProperties
@ConditionalOnClass(EurekaClientConfig.class)
@Import(DiscoveryClientOptionalArgsConfiguration.class)
@ConditionalOnBean(EurekaDiscoveryClientConfiguration.Marker.class)
@ConditionalOnProperty(value = "eureka.client.enabled", matchIfMissing = true)
@AutoConfigureBefore({ NoopDiscoveryClientAutoConfiguration.class,
		CommonsClientAutoConfiguration.class, ServiceRegistryAutoConfiguration.class })
@AutoConfigureAfter(name = {"org.springframework.cloud.autoconfigure.RefreshAutoConfiguration",
		"org.springframework.cloud.netflix.eureka.EurekaDiscoveryClientConfiguration",
		"org.springframework.cloud.client.serviceregistry.AutoServiceRegistrationAutoConfiguration"})
public class EurekaClientAutoConfiguration { ... }
```

In this version we can see that `@AutoConfigureAfter` over `EurekaClientAutoConfiguration`  was expanded by @ryanjbaxter , and now this autoconfiguration should be created after `EurekaDiscoveryClientConfiguration` (btw it violates your statement that `@AutoConfigureAfter` works only with classes that have _autoconfig_  in their name) as well.

> The @AutoConfigureAfter trick only works with autoconfig classes (clue in the name), so it's not certain to work as you guessed (but feel free to try it)

In the code snippet above `EurekaDiscoveryClientConfiguration` is used in `@AutoConfigureAfter` so maybe it still works (or not) :)

> Did you see any of those tell tale "not eligible for autoproxying" logs, e.g.

Yes, there where some logs matching this pattern, but they are related to some other beans, such as 

```
Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$ffe10c37] is not eligible for getting processed by all BeanPostProcessors
```

OR 

```
Bean 'org.springframework.cloud.netflix.metrics.MetricsInterceptorConfiguration$MetricsRestTemplateConfiguration' of type [org.springframework.cloud.netflix.metrics.MetricsInterceptorConfiguration$MetricsRestTemplateConfiguration$$EnhancerBySpringCGLIB$$40e1497b] is not eligible for getting processed by all BeanPostProcessors
```

Actually, there were a lot of them, I've just provided a few examples.

But there was not a single mention of either `EurekaHealthCheckHandlerConfiguration` or `EurekaHealthCheckHandler` and other eureka-related classes.

**Comment by dsyer** [comment] 2017-12-01 11:09
> Could you please clarify what you meant by an order applied?

I mean what you think I mean. You didn't look at 1.4.x (I think that's what I was looking at and it was more like 2.0 than 1.3)?

> Actually, there were a lot of them, I've just provided a few examples.

That's not good. Might be unrelated, but maybe not. Any differences between the apps that register UP and those that don't?

**Comment by krasilnikovdmtr** [comment] 2017-12-01 11:21
> You didn't look at 1.4.x (I think that's what I was looking at and it was more like 2.0 than 1.3)

got it, I was checking 1.3.1.RELEASE version

> Any differences between the apps that register UP and those that don't

no, actually it's the same app, we just deploy a bunch of instances of this app, some instances failed to update their status from _DOWN_ to _UP_

**Comment by dsyer** [comment] 2017-12-01 11:32
OK, so if I were you I would upgrade to 1.4.x (Edgware release train). And if that doesn't work, try the `Optional` thing and send a PR if it works.

**Comment by krasilnikovdmtr** [comment] 2017-12-02 10:37
@dsyer ok, thank you, I'll check it out

**Comment by szagriichuk** [comment] 2018-01-22 17:31
The issue is in race condition investigated by @altomch :
to reproduce do sleeps as described in comments:
```
public HealthCheckHandler getHealthCheckHandler() {
// ... other code omitted
        if (null == healthCheckHandler) {
            //sleep for 100ms
            healthCheckHandler = new HealthCheckCallbackToHandlerBridge(null);                  // (1.6)
        }
// ... other code omitted
}
 
 
public void registerHealthCheck(HealthCheckHandler healthCheckHandler) {
// ... other code omitted
    if (healthCheckHandler != null) {
        //sleep for 50ms
        this.healthCheckHandler = healthCheckHandler;                                           // (2.1)
// ... other code omitted
}
```
code from DiscoveryClient class.

**Comment by tdanylchuk** [comment] 2018-06-21 09:35
So far, I see 2 issues
1. Sometimes ```HealthCheckHandler``` autowired as null even if eureka healthcheck is enabled. (@krasilnikovdmtr told me that he saw this in debug mode on some nodes)
2. Race condition on netflix ```DiscoveryClient``` which I guess most likely can't be fixed in scope of this project.

As for issue #1:
@dsyer @spencergibb can we backport to 1.4.x branch commit 
https://github.com/spring-cloud/spring-cloud-netflix/commit/f511c267ce7b2077e074f6862ab6fdcabbefd4cf ?
I guess it should fix late healthcheck initialization issue for old cloud version.

**Comment by tdanylchuk** [comment] 2018-06-21 13:07
As for issue 2: 
I've made PR for netflix eureka to avoid possible race conditions:
https://github.com/Netflix/eureka/pull/1088
please take a look

**Comment by tdanylchuk** [comment] 2018-06-26 08:35
UPD regarding issue 2:
PR has been merged to eureka project.
I've also created PR to include new version in spring cloud project:
https://github.com/spring-cloud/spring-cloud-netflix/pull/3027

**Closed** 2018-06-26 11:18 UTC

**Comment by tdanylchuk** [comment] 2018-06-26 11:20
still need to backport commit to 1.4.X
 https://github.com/spring-cloud/spring-cloud-netflix/commit/f511c267ce7b2077e074f6862ab6fdcabbefd4cf
to avoid issue 1.
