### ISSUE TITLE
healthCheckUrl and statusPageUrl are invalid when using sidecar.

### ISSUE THREAD

**Issue by wsvoorhees** [spring-cloud/spring-cloud-netflix#3175] opened 2018-09-04 16:09 UTC
Bug report

From a customer:

The trouble I'm having is with the <healthCheckUrl> reported in Eureka. It is being reported as the port of the pod in kubernetes. When I attempt to specify the correct IP and port that is accessible from outside of the kubernetes cluster using the spring property sidecar.health-uri the sidecar will report the status as DOWN and still reports the <healthCheckUrl> in Eureka using the pod port rather than the URL I provided in the spring property.

This feels like a bug since I'm providing the correct health check URL, but maybe there is some understanding into how it is intended to be used.

I'm requesting the version numbers being used, but I believe it's finchley.

**Comment by scottlindner** [comment] 2018-09-07 22:12
I am setting the following:
eureka.instance.prefer-ip-address: true
sidecar.port: 1234
sidecar.hostname: 123.4.5.6
sidecar.ip-address: 123.4.5.6
And this works and reports health UP

But when I add:
sidecar.health-uri: 1234.4.5.6:1234/actuator/health
It will report health as DOWN and the entire sidecar will crash if I try hitting any other actuator ports.

From looking at the code, it looks like the property is being used by the sidecar to check health rather than what is being sent to eureka.

We may be hitting a use case issue for the sidecar. I'm trying to use it in a kubernetes cluster combined with applications deployed in Pivotal Cloud Foundry. The internal kube network isn't accessible to the apps in PCF so I'm overriding them in the sidecar to be the nodePort and nodeIP that is accessible to PCF. This works for the hostname and port, but not for the health-uri.

**Comment by ryanjbaxter** [comment] 2018-09-10 15:22
So are you trying to set the health check url that will be registered with the Eureka server?

**Comment by ryanjbaxter** [comment] 2018-09-10 15:32
Did you try this http://cloud.spring.io/spring-cloud-static/Finchley.SR1/single/spring-cloud.html#_status_page_and_health_indicator?

**Comment by scottlindner** [comment] 2018-09-10 23:44
Thanks for that reference. I gave it a try in a couple of different ways. It doesn't seem to do anything to affect this.

Let me better try to depict what I'm doing and why so you can get a better visual for it. The sidecar is running in a container that is on a different network than the services that will be accessing it including eureka. This is because I'm accessing services deployed in kubernetes from a Cloud Foundry application server outside of the kubernetes network.

The sidecar is running in a kubernetes pod at http://10.200.43.41:5678

I have a Kubernetes NodePort service acting as a load balancer to this sidecar pod at IP address 10.100.200.153 with a NodePort of 32292 and target endpoint of 10.200.43.41:5678

The NodeIPs for this cluster are 192.168.24.12, 192.168.24,13 and 192.168.24.14.

By digging into the various layers I can curl the following successfully for a status UP:
http://localhost:5678/actuator/health
http://10.200.43.41:5678/actuator/health
http://192.168.24.13:32292/actuator/health

In eureka (both with and without the properties you referenced) the healthCheckUrl is
http://192.168.24.13:5678/actuator/health
Which is invalid since it is combining the NodeIP with the Pod Port.

I believe the problem is being caused by the SidecarConfiguration.java class on line 132 which is being used on line 137. However, this really boils down to a use case discussion. Is it even valid to attempt to use this sidecar in this fashion: registering services that are on one network but accessible from anther network where Eureka is?

**Comment by spencergibb** [comment] 2018-09-10 23:50
The most important thing is that the sidecar needs to communicate to both eureka and the service it is registering. It doesn't surprise me that you have issues, the sidecar was built, in general, to be on the same host as the service.

**Comment by scottlindner** [comment] 2018-09-10 23:53
The sidecar is on the same host as the service and it can communicate with eureka. What it isn't doing it allowing me to override the healthCheckUri to match the hostname and port registered in eureka.

But.. if this isn't the sidecar I'm looking for.. then @wsvoorhees may want to consider writing a PR for Pivotal to sort out how PAS and PKS can play nicely with each other.

**Comment by scottlindner** [comment] 2018-09-10 23:59
Maybe this will help. This is from Eureka. You'll see the hostname port and homePageUrl are correct, and the healthCheckUrl and statusPageUrl are invalid:

`<application>
<name>EUREKASIDECAR</name>
<instance>
<instanceId>eurekasidecar:eurekasidecar:5678</instanceId>
<hostName>192.168.24.13</hostName>
<app>EUREKASIDECAR</app>
<ipAddr>192.168.24.13</ipAddr>
<status>UP</status>
<overriddenstatus>UNKNOWN</overriddenstatus>
<port enabled="true">32292</port>
<securePort enabled="false">443</securePort>
<countryId>1</countryId>
<dataCenterInfo class="com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo">
<name>MyOwn</name>
</dataCenterInfo>
<leaseInfo>
<renewalIntervalInSecs>30</renewalIntervalInSecs>
<durationInSecs>90</durationInSecs>
<registrationTimestamp>1536620728329</registrationTimestamp>
<lastRenewalTimestamp>1536620728329</lastRenewalTimestamp>
<evictionTimestamp>0</evictionTimestamp>
<serviceUpTimestamp>1536620728329</serviceUpTimestamp>
</leaseInfo>
<metadata>
<management.port>5678</management.port>
<gateway.routePreference>subdomain</gateway.routePreference>
</metadata>
<homePageUrl>http://192.168.24.13:32292/</homePageUrl>
<statusPageUrl>http://192.168.24.13:5678/actuator/info</statusPageUrl>
<healthCheckUrl>http://192.168.24.13:5678/actuator/health</healthCheckUrl>
<vipAddress>eurekasidecar</vipAddress>
<secureVipAddress>eurekasidecar</secureVipAddress>
<isCoordinatingDiscoveryServer>false</isCoordinatingDiscoveryServer>
<lastUpdatedTimestamp>1536620728329</lastUpdatedTimestamp>
<lastDirtyTimestamp>1536620728233</lastDirtyTimestamp>
<actionType>ADDED</actionType>
</instance>
</application>`

**Comment by spencergibb** [comment] 2018-09-11 00:07
There's some misunderstanding. `sidecare.health-uri` has nothing to do with the `healthCheckUrl`. It's only purpose is so the sidecar can delegate its health to that of the actual service [LocalApplicationHealthIndicator](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-sidecar/src/main/java/org/springframework/cloud/netflix/sidecar/LocalApplicationHealthIndicator.java). `sidecare.health-uri` should be an actuator-compatible url on the non-jvm service.

A eureka `HealthCheckHandler` is created using the `LocalApplicationHealthIndicator`, and translates the status accordingly.

Have you tried setting `eureka.instance.health-check-url` (which is in fact only informational).

**Comment by spencergibb** [comment] 2018-09-11 13:34
So the workaround would be to extend `LocalApplicationHealthIndicator` (and create a bean) that does NOT try and contact the non-jvm service and just returns an OK status.

We've not considered the sidecar for PAS/PKS integration. Is the eureka standalone (if so where is it running) or spring cloud services tile?

**Comment by scottlindner** [comment] 2018-09-11 13:51
I think you are missing what isn't working and what is working. The only thing that doesn't work is the healthCheckUrl and statusPageUrl in Eureka are an invalid combination of IPs and Ports. We have tools that use the healthCheckUrl. That's what I'm after is setting that to be valid.

**Comment by spencergibb** [comment] 2018-09-11 13:58
I did change the title to reflect that. Also,

> Have you tried setting eureka.instance.health-check-url?

**Comment by scottlindner** [comment] 2018-09-11 14:16
Crud. I didn't notice that was different than the suggestion from @ryanjbaxter. The properties read so similar to didn't notice they were different. I apologize for not noticing you had suggested that earlier. I had mistook it as a repeat suggestion.

That does appear to have solved the problem. I'm going to do a bit of testing and then I'll post back with my working application.yml for this because there are a mountain of guides out there for doing exactly this with this sidecar that are just wrong.

**Comment by scottlindner** [comment] 2018-09-11 16:55
I have tested this a few times and it appears to be working for my needs. Thank you for the help. Although something about this doesn't seem to be documented very well. I have been working on this for weeks and all guides have at least one thing wrong or missing.

Here's the application.yml that is working for my needs with Finchley.SR1
server:
  port: ${EUREKA_SIDECAR_PORT} # this is the port for talking to the sidecar Spring Boot application
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_BASE_URL}/eureka
  instance:
    prefer-ip-address: true
    health-check-url: http://${KUBERNETES_NODE_IP}:${KUBERNETES_NODEPORT}/actuator/health
    status-page-url: http://${KUBERNETES_NODE_IP}:${KUBERNETES_NODEPORT}/actuator/info
    metadataMap:
      gateway.routePreference: subdomain
sidecar:
  port: ${KUBERNETES_NODEPORT}
  hostname: ${KUBERNETES_NODE_IP}
  ip-address: ${KUBERNETES_NODE_IP}

**Comment by ryanjbaxter** [comment] 2018-09-12 18:30
@scottlindner would you like to submit a PR to our docs to help improve things?

**Comment by ryanjbaxter** [comment] 2018-09-17 17:56
> I gathered from this discussion Kubernetes is a use case you don't want to formally support.

No that is not true.  From you previous comment it sounded like you thought our documentation needed to be improved, so I was just asking if you would like to take a crack at updating it.

**Comment by spencergibb** [comment] 2019-01-28 17:04
Closing as answered.

**Closed by spencergibb** 2019-01-28 17:04 UTC
Labels: question
