### ISSUE TITLE
com.netflix.zuul.exception.ZuulException: Forwarding error

### ISSUE THREAD

**Issue by bipin25** [spring-cloud/spring-cloud-netflix#3184] opened 2018-09-10 09:54 UTC
com.netflix.zuul.exception.ZuulException: Forwarding error

        at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.handleException(RibbonRoutingFilter.java:189) ~[spring-cloud-netflix-zuul-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]

        at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.forward(RibbonRoutingFilter.java:164) ~[spring-cloud-netflix-zuul-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]

        at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.run(RibbonRoutingFilter.java:112) ~[spring-cloud-netflix-zuul-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]

        at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:117) ~[zuul-core-1.3.1.jar!/:1.3.1]  

I got this execption in my zuul apigateway ....but sometime it work well but sometime it throw such exeption in api gateway 
plz suggest the solution 
thanks in advanced

**Comment by bipin25** [comment] 2018-09-10 14:13
@brenuart can u plz elobrolate

**Comment by bipin25** [comment] 2018-09-10 14:13
@brenuart how to overcome this problems

**Comment by brenuart** [comment] 2018-09-10 15:09
I mean the cause is written in your logs some lines before the Zuul stacktrace.

If not, this issue has been raised here so many often that you should find enough information in the closed cases.

If not, then you should provide us with your logs, a description of what happened and what was expected.

**Comment by bipin25** [comment] 2018-10-15 13:04
@brenuart 

com.netflix.zuul.exception.ZuulException: Forwarding error
        at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.handleException(RibbonRoutingFilter.java:189) ~[spring-cloud-netflix-zuul-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
        at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.forward(RibbonRoutingFilter.java:164) ~[spring-cloud-netflix-zuul-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
        at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.run(RibbonRoutingFilter.java:112) ~[spring-cloud-netflix-zuul-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
        at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:117) ~[zuul-core-1.3.1.jar!/:1.3.1]
        at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:193) ~[zuul-core-1.3.1.jar!/:1.3.1]
        at com.netflix.zuul.FilterProcessor.runFilters(FilterProcessor.java:157) ~[zuul-core-1.3.1.jar!/:1.3.1]
        at com.netflix.zuul.FilterProcessor

**Comment by bipin25** [comment] 2018-10-15 13:05
sometime i got these error in apigateway otherwise it work fine

**Comment by ryanjbaxter** [comment] 2018-10-15 14:55
This is only part of the stacktrace please provide the whole thing.

**Comment by spring-issuemaster** [comment] 2018-10-22 14:56
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2018-10-22 15:41
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2018-10-22 15:46
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2018-10-22 15:51
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2018-10-29 14:57
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2018-10-29 14:57 UTC
Labels: feedback-reminder, waiting for feedback
