### ISSUE TITLE
Header "Authorization" Spring Boot version 2.0.3

### ISSUE THREAD

**Issue by haasiniE** [spring-cloud/spring-cloud-netflix#3150] opened 2018-08-17 18:21 UTC
The request header "Authorization" is not being passed with Spring boot version 2.0.3 zuul to downstream services.I have disabled Authorization as sensitive header but Zuul will not send Authorization header to downstream service. 

Below is the present config that will work only with the following code.
```
zuul:
  sensitiveHeaders:   
  routes:
```

Versions:
```
springBootVersion = '2.0.3.RELEASE'
dependencyManagement {
	imports { 
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:Finchley.RELEASE"
		
	}
}
compile 'org.springframework.cloud:spring-cloud-starter-netflix-zuul'

```
Route filter as below:
```
    @SuppressWarnings("unchecked")
	@Override
    public Object run() {
    	
    	try {   
	        RequestContext ctx = RequestContext.getCurrentContext();
	        ctx.addZuulRequestHeader("Authorization","Bearer xxx");
    	} catch(Exception ex) {
    		log.error("Exception", ex);
    		
    	}
```

Spring boot version 1.5.7 Zuul is to able to send the header "Authorization" with the  to the downstream services without adding the Authorization header through RequestHeader by using route filter.
 
Below is the config:
```
zuul:
  sensitiveHeaders:   
  routes:
```
Versions:
```
 springBootVersion = "1.5.3.RELEASE"
dependencyManagement {
	imports { 
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:Dalston.SR1"
		
	}
}
 compile ‘org.springframework.cloud:spring-cloud-starter-zuul’
```

**Comment by spencergibb** [comment] 2018-08-27 13:38
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

**Comment by spencergibb** [comment] 2018-08-27 13:40
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by Junior-Sousa** [comment] 2018-09-19 02:29
@haasiniE I believe you can figure out this issue based on resolution of this ticket https://github.com/spring-cloud/spring-cloud-netflix/issues/3126 where the only change done was:

```
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
```

**Comment by spencergibb** [comment] 2018-09-19 02:31
Also please try with Edgware or Finchley

**Comment by Junior-Sousa** [comment] 2018-09-19 02:33
Edgware works without set sensitiveHeaders: Cookie,Set-Cookie

**Comment by spencergibb** [comment] 2019-01-31 19:40
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2019-01-31 19:40 UTC
Labels: feedback-provided
