### ISSUE TITLE
Feign Interceptor can't get the Authentication info when using SEMAPHORE as strategy

### ISSUE THREAD

**Issue by rmcruzv** [spring-cloud/spring-cloud-netflix#1380] opened 2016-10-05 21:50 UTC
Question

Hi, recently I have migrated from Spring boot 1.4.0 version (with Brixton.SR4) to 1.4.1 (with Camden.RELEASE versión of spring-cloud-dependencies). Everything looks Ok, but I have a little problem with my feign clients. When it is needed pass the security context, the interceptor obtains null as Authentication info.

Could you help me please?

This is the command definition:
`@HystrixCommand(fallbackMethod = "retrieveErrorFn", commandProperties = { @HystrixProperty(name = "execution.isolation.strategy", value = "SEMAPHORE") })`

An this is my Interceptor:

`
@Component
public class FeignClientInterceptor implements RequestInterceptor {

```
private static final String AUTHORIZATION_HEADER = "Authorization";
private static final String BEARER_TOKEN_TYPE = "Bearer";

@Override
public void apply(RequestTemplate template) {
    if (!template.headers().containsKey(AUTHORIZATION_HEADER)) {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        if (auth != null && auth.getDetails() instanceof OAuth2AuthenticationDetails) {
            OAuth2AuthenticationDetails details = (OAuth2AuthenticationDetails) auth.getDetails();
            template.header(AUTHORIZATION_HEADER, String.format("%s %s", BEARER_TOKEN_TYPE, details.getTokenValue()));
        }
    }
}
```

}
`

The previous version of spring-cloud-starter-feign was 1.1.5 and the new versión is 1.2.0

**Comment by ryanjbaxter** [comment] 2016-10-05 23:53
Is it `SecurityContextHolder.getContext().getAuthentication();` which is returning null?

**Comment by rmcruzv** [comment] 2016-10-05 23:56
Yes the interceptor worked fine until 1.4.0 version, but in 1.4.1, the method getAuthentication always return null

**Comment by ryanjbaxter** [comment] 2016-10-06 00:17
Spring Cloud Netflix does not have a version `1.4.x`  which dependency are you referring to?

**Comment by spencergibb** [comment] 2016-10-06 00:19
Boot?

**Comment by ryanjbaxter** [comment] 2016-10-06 00:21
Ah that makes sense...sounds like you should be opening an issue again Boot then since nothing changed on our end.

**Comment by rmcruzv** [comment] 2016-10-06 00:24
Sorry for that...

I'm using Spring boot 1.4.1 tha with spring-cloud-starter-feign 1.1.5

**Comment by ryanjbaxter** [comment] 2016-10-06 00:31
Do you mind updating the issue description with the correct versions?  Also if it is possible to provide a sample app that reproduces the issue that would be great.

**Comment by spencergibb** [comment] 2016-10-06 00:31
Was boot the only dependency change?

**Comment by rmcruzv** [comment] 2016-10-06 01:59
Mainly, yes, I only changed the Spring boot version from 1.4.0 to 1.4.1 and the Interceptor has damaged

**Comment by ryanjbaxter** [comment] 2016-10-06 10:23
> Hi, recently I have migrated from Spring boot 1.4.0 version (with Brixton.SR4) to 1.4.1 (with Camden.RELEASE versión of spring-cloud-dependencies).

Are you able to reproduce the problem with Boot 1.4.1 using Brixton.SR4?  What about using Boot 1.4.0 with Camden.RELEASE?

**Comment by rmcruzv** [comment] 2016-10-06 21:17
I'll try later and if it works I'll let you know

**Comment by spencergibb** [comment] 2018-01-17 23:57
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2018-01-17 23:57 UTC
Labels: waiting for feedback
