### ISSUE TITLE
Unable to rename the eureka server

### ISSUE THREAD

**Issue by vishakhakadam09** [spring-cloud/spring-cloud-netflix#4060] opened 2022-01-06 05:29 UTC
I have configured eureka-server as a client with configuration specified below. 
I am trying to rename the service to 'eureka-registry' (originally configured as 'eureka-server'). I have deleted the ecs service from AWS to avoid peer lookup. Have modified below configuration to reflect new name. However when the new service comes up it tries to find 'eureka-server' (old server) and fills logs completely with trying to locate the peer. Please suggest what I am missing or how to handle it. 
![image](https://user-images.githubusercontent.com/47795230/150046090-4855b9fc-ff68-452e-9fd6-a775bbb83c4f.png)

**Comment by OlgaMaciaszek** [comment] 2022-01-17 17:36
Hello, @vishakhakadam09. Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/). If I understand correctly what you are trying to do, setting `service-url` might be what you're looking for. You can do it like so:

```
eureka:
  client:
    service-url:
      defaultZone: https://dev.eureka-registry.rd.xxx.io/eureka/
```
Let me know if this is helpful.

**Comment by vishakhakadam09** [comment] 2022-01-19 01:26
Sorry for improper format. I have updated my post with correct format. It looks like workflow-registry is trying to poll for previous eureka server i.e. eureka-service.rd.xxx.io.
Could you please suggest what needs to be done in order to avoid it and not look for older instance.

![image](https://user-images.githubusercontent.com/47795230/150045999-ef420ac2-b559-474e-b640-f49d8ae693e2.png)

**Comment by OlgaMaciaszek** [comment] 2022-02-25 12:52
Yes, it does seem so. Setting the zone as shown [here](https://github.com/spring-cloud/spring-cloud-netflix/issues/4060#issuecomment-1014768904) should work. If it still persists, I will need a sample to verify why. 
Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-cloud-issues** [comment] 2022-03-04 12:55
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2022-03-11 12:55
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2022-03-11 12:55 UTC
Labels: waiting for feedback, feedback-reminder
