### ISSUE TITLE
Setting LOAD_BALANCER_KEY on RequestContext in Zuul pre filter is not passing data to IRule

### ISSUE THREAD

**Issue by illingtonFlex** [spring-cloud/spring-cloud-netflix#3551] opened 2019-06-06 14:17 UTC
When I try to pass a value in to my IRule.choose method by using RequestContext.getCurrentContext.set to store the data with the key FilterConstants.LOAD_BALANCER_KEY, the data is not passed into the IRule as I understand the documentation. Instead, the key parameter passed into the choose method is always the string value of the service-id for the route.

Using Finchley.SR2

Based on [this documentation]( https://cloud.spring.io/spring-cloud-netflix/multi/multi_spring-cloud-ribbon.html#how-to-provdie-a-key-to-ribbon)

I have this pre filter, which executes as expected in the debugger:

```
@Component
public class MyZuulPreFilter extends ZuulFilter {

    @Override
    public String filterType() {
        return "pre";
    }

    @Override
    public int filterOrder() {
        return 0;
    }

    @Override
    public boolean shouldFilter() {
        return true;
    }

    @Override
    public Object run() {

        RequestContext.getCurrentContext().set(FilterConstants.LOAD_BALANCER_KEY, "My Data");

        return null;
    }

}
```

I also have this IRule, which is also triggered as expected in the debugger:

```
public class MyRule implements IRule {

    private ILoadBalancer lb;

    @Override
    public Server choose(Object key) {
        
        // key = service-id

        return null;
    }

    @Override
    public void setLoadBalancer(ILoadBalancer lb){
        this.lb = lb;
    }

    @Override
    public ILoadBalancer getLoadBalancer(){
        return lb;
    }
}
```

**Comment by ryanjbaxter** [comment] 2019-06-10 14:37
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by illingtonFlex** [comment] 2019-06-10 14:42
I can try, though it will be tricky since this involves integrating with a registry and downstream services.

Is there an integration test or any sample code to look at in the meantime?

**Comment by ryanjbaxter** [comment] 2019-06-10 14:57
There is an integration test `RibbonRoutingFilterLoadBalancerKeyIntegrationTests`.

We don't necessarily need the downstream services or a registry (you can configure ribbon without a service discovery) we really need to see the code that set the key in the context and then the rule that doesnt have it.

**Comment by illingtonFlex** [comment] 2019-06-10 15:39
OK, this isn't the cleanest repo, but it does expose the issue for me.

https://github.com/illingtonFlex/ZuulDemo

Set a breakpoint in StickySessionZuulPreFilter and another in StickySessionRule and when you hit the configured endpoint, the debugger triggers on both, and the value from the pre filter is not passed to the IRule.

Thanks.

**Comment by spencergibb** [comment] 2019-06-10 15:45
I'm not aware of anything that sets a load balancer key in ribbon in zuul

**Comment by illingtonFlex** [comment] 2019-06-10 15:47
> I'm not aware of anything that sets a load balancer key in ribbon in zuul

Thanks, maybe I'm misreading [the documentation](https://cloud.spring.io/spring-cloud-netflix/multi/multi_spring-cloud-ribbon.html#how-to-provdie-a-key-to-ribbon):

> If you put any object into the RequestContext with a key of FilterConstants.LOAD_BALANCER_KEY, it is passed to the choose method of the IRule implementation. The code shown in the preceding example must be executed before RibbonRoutingFilter is executed. **Zuul’s pre filter is the best place to do that**.

**Comment by spencergibb** [comment] 2019-06-10 16:23
:-) looks like I forgot a feature

**Comment by illingtonFlex** [comment] 2019-07-08 19:27
I'm not sure how the waiting for triage thing works here. Is this something that will be addressed eventually, or is it my responsibility to keep this issue bumped?

**Comment by spencergibb** [comment] 2019-07-08 20:20
Once someone can triage the provided project, we'll update here.

**Comment by Haybu** [comment] 2019-07-29 23:47
Please find attached a triage that demonstrates passing a key value to a Ribbon IRule's Choose(...) method via a RequestContext (keyed with FilterConstants.LOAD_BALANCER_KEY) of a Zuul pre-filter. The same Spring Boot/Cloud versions listed in your sample code are used in this triage sample. 

After you unzip the triage sample, please follow the steps in the `README.md` file.

[trial-issue-3551.zip](https://github.com/spring-cloud/spring-cloud-netflix/files/3444583/trial-issue-3551.zip)

**Comment by spring-issuemaster** [comment] 2019-08-05 23:49
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-08-12 23:49
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-08-12 23:49 UTC
Labels: feedback-reminder, waiting for feedback
