### ISSUE TITLE
spring cloud zuul support Placeholder?

### ISSUE THREAD

**Issue by ypg521** [spring-cloud/spring-cloud-netflix#2766] opened 2018-03-08 03:46 UTC
Sorry for my bad Englist first.
spring cloud zuul support Placeholder???
Like this:
```yaml
zuul:
  routers:
    users:
      path:  /cities/{areaCode}/
      url: http://{areaCode}.google.com
```

**Comment by spencergibb** [comment] 2018-03-08 03:51
Where does `{areaCode}` come from?

**Comment by ypg521** [comment] 2018-03-08 03:54
A path Variable,{areaCode} can be any city code .
I find a same issues :     https://github.com/spring-cloud/spring-cloud-netflix/issues/2173

**Comment by spencergibb** [comment] 2018-03-08 05:04
Duplicate of #2173

**Closed by spencergibb** 2018-03-08 05:04 UTC
Labels: question

**Comment by zartc** [comment] 2018-03-16 12:59
You can achieve what you want to achieve with a slightly modified route definition and just a small redirector microservice of your own.

1. your route configuration:
```
zuul:
  routes:                        # <-- AFAIK it is 'routes' not 'routers'
    users:
      path: /cities/*/           # <-- note the '*' in the route definition
      url: http://<host>:<port>/redirector-service
      strip-prefix: false
```
2. In the redirector microservice the uri fragment represented by the '*' in the zuul route can be retrieved as a @PathVariable:
```
@RestController
public class RedirectorService {
    @GetMapping(value = "/cities/{areaCode}/")
    public String redirectTo(@PathVariable("areaCode") String areaCode) {
        // use a restTamplate to make the call to google.com with the areaCode
    }
}
```

**Comment by kishore-diyyana** [comment] 2018-11-15 15:36
Kishore Babu Diyyana: Recursive Path with ** - Add on points to pathParam (@PathVariable) and queryParam (@RequestParam) 
------------------------------------------------------------------------------------------------------------------
applicaiton.yml
---------------
zuul:
   routes:
       gatewayPathParamTest:
         path: /pathParamTest/**
         url: http://localhost:8081/pathParamTest/

-------------
RestService
-------------
@RequestMapping(value = {"/pathParamTest/{id}/test/getdata"}, 
  					produces = "application/json", method = {RequestMethod.GET})
	public String pathParamTest(@RequestParam(value="name", required = false) 
		String name, @PathVariable (value="id", required = false) String id) throws Exception
 { ....
  .... }


Valid endpoints access:
--------------------------
http://localhost:8085/pathParamTest/123/test/getdata
http://localhost:8085/pathParamTest/123/test/getdata?name=diyyana
