### ISSUE TITLE
SimpleHostRoutingFilter does not honor https.proxy

### ISSUE THREAD

**Issue by ktong** [spring-cloud/spring-cloud-netflix#510] opened 2015-09-01 17:30 UTC
config zuul as below:
```
zuul:
  routes:
    li:
      path: /li/**
      url: https://api.${li.api.domain}:443/${li.api.version}
```
and set system properties https.proxy, but zuul cannot connect to api via proxy.

**Comment by dsyer** [comment] 2015-09-04 09:27
Duplicate of #332?

What does the `\$` do?

**Comment by ktong** [comment] 2015-09-16 17:28
#332 is not supporting https, and this is not supporting proxy configuration

**Comment by kavinduraisamy91** [comment] 2016-09-20 04:58
@spencergibb  is Zuul RibbonRoutingFilter supports for proxy ? if not is there any workaround ?

**Comment by dsyer** [comment] 2016-09-20 10:35
Why would `RibbonRoutingFilter` need to go through a proxy?

**Closed** 2016-09-20 11:30 UTC
Labels: enhancement

**Comment by kavinduraisamy91** [comment] 2016-10-17 07:04
@spencergibb We are creating a simple Gateway application, which should implement the Hystrix circuit breaker, 
The SimpleRoutingFilter, circuit breaker implementation is not available.  To achieve the circuit breaker we are access the service with RibbonRoutingFilter, which takes the listofservers from application.properties file directly, without Eureka Service Registry and we don't have the direct access to the services, which can be access only via proxy.
So we are required the HTTP proxy for 'RibbonRoutingFilter'. 

As a workaround, we are creating the custom class by  extending the 'RibbonLoadBalancingHttpClient' and overriding the execute method to create our own HttpClient with proxy configuration.

The custom class has been injected by overriding the SpringClientFactor's getClient() method.


```
 public <C extends IClient<?, ?>> C getClient(String name, Class<C> clientClass) {
    final boolean isProxyEnabled =
        Boolean.valueOf(environment.getProperty(name + Constants.PROXY_CONFIG_PROPERTY_PROXY));
    if (isProxyEnabled && clientClass.getName().equalsIgnoreCase(RibbonLoadBalancingHttpClient)) {
      return (C) super.getClient(name, ProxyEnabledHttpClient.class);
    }
    return super.getClient(name, clientClass);
  }
```

Thank you!

**Comment by spencergibb** [comment] 2016-10-20 20:07
@kavinduraisamy91 having SimpleHostRoutingFilter use ribbon is not the scope of this **closed** issue.
