### ISSUE TITLE
zuul & consul always visit the 127.0.0.1:8300

### ISSUE THREAD

**Issue by ffch** [spring-cloud/spring-cloud-netflix#3557] opened 2019-06-10 11:13 UTC
spring-cloud-starter-netflix-zuul:2.1.0.RELEASE
spring-cloud-starter-consul-discovery:2.1.0.RELEASE

When I launch the zuul app, it always accesses the consul service (127.0.0.1:8300), and then the error "connection reset" while will appear.

only use
```
Zuul:
    ignoredServices: consul
```
This way can run normally.

What I am wondering is why the zuul visit the consul service  at this startup time?

**Comment by ryanjbaxter** [comment] 2019-06-10 14:19
Are you trying to use Consul for service discovery?  If so your app will try to reach out to consul on startup to register itself and retrieve the list of other services registered in Consul.  If it can't reach Consul then I can see why you would get the `Connection Reset` error.  

I am unsure why adding `zuul.ignoredServices=consul` solves this problem as it has nothing to do with service discovery.

**Comment by ffch** [comment] 2019-06-11 01:48
my application.yml is:
```
server:
   port: 8816
spring:
   application:
      name: consulZuul
   cloud:
      consul:
         host: 127.0.0.1
         port: 8500
         discovery:
            prefer-ip-address: true
            healthCheckPath: /consul/health
zuul:
   ignoredServices: consul
   routes:
      util:
         path: /util/**
         sensitiveHeaders: 
         serviceId: consulServer
```

`consul` service is the consul itself; 
`consulServer` is a server that I created to provides rest service, the 。

and if I remove the `consul ` in  `ignoredServices: consul` ,  will get the` Connection Reset` error。


The information before the error is:

```
2019-06-11 09:33:15.180  INFO 147324 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8816 (http) with context path ''
2019-06-11 09:33:15.191  INFO 147324 --- [           main] o.s.c.c.s.ConsulServiceRegistry          : Registering service with consul: NewService{id='consulZuul-8816', name='consulZuul', tags=[secure=false], address='10.247.62.91', meta=null, port=8816, enableTagOverride=null, check=Check{script='null', interval='10s', ttl='null', http='http://10.247.62.91:8816/consul/health', method='null', header={}, tcp='null', timeout='null', deregisterCriticalServiceAfter='null', tlsSkipVerify=null, status='null'}, checks=null}
2019-06-11 09:33:15.204  INFO 147324 --- [           main] c.p.s.consulzuul.ConsulZuulApplication   : Started ConsulZuulApplication in 6.482 seconds (JVM running for 7.185)
2019-06-11 09:33:22.895  INFO 147324 --- [nio-8816-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2019-06-11 09:33:22.896  INFO 147324 --- [nio-8816-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2019-06-11 09:33:22.903  INFO 147324 --- [nio-8816-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 7 ms
2019-06-11 09:33:23.114  INFO 147324 --- [nio-8816-exec-1] c.netflix.config.ChainedDynamicProperty  : Flipping property: consul.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647
2019-06-11 09:33:23.153  INFO 147324 --- [nio-8816-exec-1] c.n.u.concurrent.ShutdownEnabledTimer    : Shutdown hook installed for: NFLoadBalancer-PingTimer-consul
2019-06-11 09:33:23.154  INFO 147324 --- [nio-8816-exec-1] c.netflix.loadbalancer.BaseLoadBalancer  : Client: consul instantiated a LoadBalancer: DynamicServerListLoadBalancer:{NFLoadBalancer:name=consul,current list of Servers=[],Load balancer stats=Zone stats: {},Server stats: []}ServerList:null
2019-06-11 09:33:23.160  INFO 147324 --- [nio-8816-exec-1] c.n.l.DynamicServerListLoadBalancer      : Using serverListUpdater PollingServerListUpdater
2019-06-11 09:33:23.182  INFO 147324 --- [nio-8816-exec-1] c.netflix.config.ChainedDynamicProperty  : Flipping property: consul.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647
2019-06-11 09:33:23.184  INFO 147324 --- [nio-8816-exec-1] c.n.l.DynamicServerListLoadBalancer      : DynamicServerListLoadBalancer for client consul initialized: DynamicServerListLoadBalancer:{NFLoadBalancer:name=consul,current list of Servers=[127.0.0.1:8300],Load balancer stats=Zone stats: {unknown=[Zone:unknown;	Instance count:1;	Active connections count: 0;	Circuit breaker tripped count: 0;	Active connections per server: 0.0;]
},Server stats: [[Server:127.0.0.1:8300;	Zone:UNKNOWN;	Total Requests:0;	Successive connection failure:0;	Total blackout seconds:0;	Last connection made:Thu Jan 01 08:00:00 CST 1970;	First connection made: Thu Jan 01 08:00:00 CST 1970;	Active Connections:0;	total failure count in last (1000) msecs:0;	average resp time:0.0;	90 percentile resp time:0.0;	95 percentile resp time:0.0;	min resp time:0.0;	max resp time:0.0;	stddev resp time:0.0]
]}ServerList:ConsulServerList{serviceId='consul', tag=null}
2019-06-11 09:33:23.361  WARN 147324 --- [nio-8816-exec-1] o.s.c.n.z.filters.post.SendErrorFilter   : Error during filtering

com.netflix.zuul.exception.ZuulException: Forwarding error
```

**Comment by spencergibb** [comment] 2019-06-17 14:23
Nothing in zuul will automatically make a request to the `consul` service through ribbon. 
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by ffch** [comment] 2019-06-20 07:35
my code is :
https://github.com/ffch/zuulConsul.git

and the consul is running on port 8500.

**Comment by ryanjbaxter** [comment] 2019-06-20 10:13
I think it is probably your `healthCheckPath`, what is the entire exception?

**Comment by spencergibb** [comment] 2019-06-20 19:10
It is because you named a controller `/consul` which matches a service registered in consul, therefore there is a route created in zuul `/consul`. You configured the health check for `/consul/health` which actually matches against the zuul route first rather than your rest controller. Commenting out the health check path also removes the error.

Ignoring consul is the proper thing to do.

Closing in favor of https://github.com/spring-cloud/spring-cloud-consul/issues/569

**Closed by spencergibb** 2019-06-20 19:10 UTC
Labels: waiting for feedback
