### ISSUE TITLE
Performance problem with zuul

### ISSUE THREAD

**Issue by Imran-Mohamed** [spring-cloud/spring-cloud-netflix#2661] opened 2018-01-18 05:11 UTC
We are using api gateway pattern and making request to our microservices. our microservices are in private subnet hence we are using another service called api-gateway which has zuul in it for routing.when we are load testing our microservices, the time taken for request to hit the microservice and time taken for response to return to api-gateway is more.

1.  api-gateway service deployed in m4.10xlarge machine(40 core machine)
2.  recived data volume is 2.4 MB
3.  zipkin for distributed tracing
4. Jmeter for load testing with 3000 concurrent requests.

![image](https://user-images.githubusercontent.com/25953463/35081670-6f8a40e0-fc3b-11e7-8c2c-2c9fefe0db09.png)

**Comment by spencergibb** [comment] 2018-01-18 07:05
The trace you posted said, that a network call from your gateway to your service took 140 seconds.

**Comment by Imran-Mohamed** [comment] 2018-01-18 08:39
network call from api gateway to my service took 71.840 sec and response from my service to api gateway took close to 71sec(145.409s-73.569s). overall request time was 145.409 sec.

**Comment by ryanjbaxter** [comment] 2018-01-18 11:39
I dont see how this points to a problem with Zuul especially since it took 75 sec for the client to send the response back to Zuul.  Seems like something else might be going on.

**Comment by Imran-Mohamed** [comment] 2018-01-18 11:47
ok....then why is my server received time showing as 71.840s my api-gateway service is a plane zuul implementation.why is api-gateway taking so much time to send request to my back-end service.

**Comment by ryanjbaxter** [comment] 2018-01-18 12:38
I completely agree that there is something happening there as well.  Could you provide a project that reproduces the problem?

**Comment by spencergibb** [comment] 2018-04-25 19:28
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2018-04-25 19:28 UTC
Labels: waiting for feedback
