### ISSUE TITLE
Eureka server https Error: SSL configuration issue

### ISSUE THREAD

**Issue by dingwenxiang0** [spring-cloud/spring-cloud-netflix#3238] opened 2018-10-19 03:30 UTC
Hello everyone:
         I am try to config eureka https with multi region. But eureka cant setup. Because create JerseyReplicationClient cant get the SSLContext config. 
        see my config:
        
[eureka-server-west-zone1.txt](https://github.com/spring-cloud/spring-cloud-netflix/files/2494400/eureka-server-west-zone1.txt)

         see error logs:
 
[error.txt](https://github.com/spring-cloud/spring-cloud-netflix/files/2494405/error.txt)

        thanks all. (sorry i dont know how to set the code style)

**Comment by ryanjbaxter** [comment] 2018-10-19 14:03
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment] 2018-10-26 14:07
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2018-11-02 14:03
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2018-11-02 14:03 UTC
Labels: feedback-reminder, waiting for feedback
