### ISSUE TITLE
Not able to expose http and https endpoints for Eureka Client

### ISSUE THREAD

**Issue by Aakash-1990** [spring-cloud/spring-cloud-netflix#3527] opened 2019-05-07 13:17 UTC
Below are my configurations for Eureka Client

eureka.instance.instanceId=${spring.application.name}:${spring.application.instance_id:${random.int}}
eureka.instance.nonSecurePortEnabled=true
eureka.instance.securePortEnabled=true
eureka.instance.securePort=${server.port}
eureka.instance.nonSecurePort=${http.port}
spring.cloud.bus.enabled=true

same configuration is enable for Eureka Server, Zuul and COnfig Server.
When I try to call a service by using Zuul's non secure port, I am getting connection refused.

Below is the /eureka/apps/ output

<applications>
<versions__delta>1</versions__delta>
<apps__hashcode>UP_3_</apps__hashcode>
<application>
<name>DDO-CONFIG-SERVER</name>
<instance>
<instanceId>ddo-config-server:-1727522517</instanceId>
<hostName>GCOTVMMW7123731.nam.nsroot.net</hostName>
<app>DDO-CONFIG-SERVER</app>
<ipAddr>10.102.156.40</ipAddr>
<status>UP</status>
<overriddenstatus>UNKNOWN</overriddenstatus>
<port enabled="true">8887</port>
<securePort enabled="true">8888</securePort>
<countryId>1</countryId>
<dataCenterInfo class="com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo">
<name>MyOwn</name>
</dataCenterInfo>
<leaseInfo>
<renewalIntervalInSecs>30</renewalIntervalInSecs>
<durationInSecs>90</durationInSecs>
<registrationTimestamp>1557235502739</registrationTimestamp>
<lastRenewalTimestamp>1557235742706</lastRenewalTimestamp>
<evictionTimestamp>0</evictionTimestamp>
<serviceUpTimestamp>1557235502739</serviceUpTimestamp>
</leaseInfo>
<metadata>
<management.port>8888</management.port>
</metadata>
<homePageUrl>http://GCOTVMMW7123731.nam.nsroot.net:8887/</homePageUrl>
<statusPageUrl>
http://GCOTVMMW7123731.nam.nsroot.net:8888/actuator/info
</statusPageUrl>
<healthCheckUrl>
http://GCOTVMMW7123731.nam.nsroot.net:8888/actuator/health
</healthCheckUrl>
<secureHealthCheckUrl>
https://GCOTVMMW7123731.nam.nsroot.net:8888/actuator/health
</secureHealthCheckUrl>
<vipAddress>ddo-config-server</vipAddress>
<secureVipAddress>ddo-config-server</secureVipAddress>
<isCoordinatingDiscoveryServer>false</isCoordinatingDiscoveryServer>
<lastUpdatedTimestamp>1557235502739</lastUpdatedTimestamp>
<lastDirtyTimestamp>1557235502680</lastDirtyTimestamp>
<actionType>ADDED</actionType>
</instance>
</application>
<application>
<name>DDO-ZUUL</name>
<instance>
<instanceId>ddo-zuul:-933721402</instanceId>
<hostName>GCOTVMMW7123731.nam.nsroot.net</hostName>
<app>DDO-ZUUL</app>
<ipAddr>10.102.156.40</ipAddr>
<status>UP</status>
<overriddenstatus>UNKNOWN</overriddenstatus>
<port enabled="true">8078</port>
<securePort enabled="true">8079</securePort>
<countryId>1</countryId>
<dataCenterInfo class="com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo">
<name>MyOwn</name>
</dataCenterInfo>
<leaseInfo>
<renewalIntervalInSecs>30</renewalIntervalInSecs>
<durationInSecs>90</durationInSecs>
<registrationTimestamp>1557235419873</registrationTimestamp>
<lastRenewalTimestamp>1557235749588</lastRenewalTimestamp>
<evictionTimestamp>0</evictionTimestamp>
<serviceUpTimestamp>1557235419875</serviceUpTimestamp>
</leaseInfo>
<metadata>
<management.port>8079</management.port>
</metadata>
<homePageUrl>http://GCOTVMMW7123731.nam.nsroot.net:8078/</homePageUrl>
<statusPageUrl>
http://GCOTVMMW7123731.nam.nsroot.net:8079/actuator/info
</statusPageUrl>
<healthCheckUrl>
http://GCOTVMMW7123731.nam.nsroot.net:8079/actuator/health
</healthCheckUrl>
<secureHealthCheckUrl>
https://GCOTVMMW7123731.nam.nsroot.net:8079/actuator/health
</secureHealthCheckUrl>
<vipAddress>ddo-zuul</vipAddress>
<secureVipAddress>ddo-zuul</secureVipAddress>
<isCoordinatingDiscoveryServer>false</isCoordinatingDiscoveryServer>
<lastUpdatedTimestamp>1557235419875</lastUpdatedTimestamp>
<lastDirtyTimestamp>1557235419535</lastDirtyTimestamp>
<actionType>ADDED</actionType>
</instance>
</application>
<application>
<name>DDO-OS-DATAPROVIDER-SERVICE</name>
<instance>
<instanceId>ddo-os-dataprovider-service:-1777536612</instanceId>
<hostName>GCOTVMMW7123731.nam.nsroot.net</hostName>
<app>DDO-OS-DATAPROVIDER-SERVICE</app>
<ipAddr>10.102.156.40</ipAddr>
<status>UP</status>
<overriddenstatus>UNKNOWN</overriddenstatus>
<port enabled="true">8892</port>
<securePort enabled="true">8899</securePort>
<countryId>1</countryId>
<dataCenterInfo class="com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo">
<name>MyOwn</name>
</dataCenterInfo>
<leaseInfo>
<renewalIntervalInSecs>30</renewalIntervalInSecs>
<durationInSecs>90</durationInSecs>
<registrationTimestamp>1557235548752</registrationTimestamp>
<lastRenewalTimestamp>1557235758706</lastRenewalTimestamp>
<evictionTimestamp>0</evictionTimestamp>
<serviceUpTimestamp>1557235548752</serviceUpTimestamp>
</leaseInfo>
<metadata>
<management.port>8892</management.port>
</metadata>
<homePageUrl>http://GCOTVMMW7123731.nam.nsroot.net:8892/</homePageUrl>
<statusPageUrl>
http://GCOTVMMW7123731.nam.nsroot.net:8899/actuator/info
</statusPageUrl>
<healthCheckUrl>
http://GCOTVMMW7123731.nam.nsroot.net:8899/actuator/health
</healthCheckUrl>
<secureHealthCheckUrl>
https://GCOTVMMW7123731.nam.nsroot.net:8899/actuator/health
</secureHealthCheckUrl>
<vipAddress>ddo-os-dataprovider-service</vipAddress>
<secureVipAddress>ddo-os-dataprovider-service</secureVipAddress>
<isCoordinatingDiscoveryServer>false</isCoordinatingDiscoveryServer>
<lastUpdatedTimestamp>1557235548752</lastUpdatedTimestamp>
<lastDirtyTimestamp>1557235548690</lastDirtyTimestamp>
<actionType>ADDED</actionType>
</instance>
</application>
</applications>

spring Boot version : 2.1.3
Spring CLoud version Greenwish.SR1

**Comment by spencergibb** [comment] 2019-05-07 13:38
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spencergibb** [comment] 2019-05-07 13:58
Actually, it won't, since there is much more to projects than just properties.

**Comment by Aakash-1990** [comment] 2019-05-07 14:03
Hi Spencer,

My projects have not been evolved as of now. Whatever is needed to bring the Microservice framework up and running only those changes are there. Very minimal code is there.

**Comment by Aakash-1990** [comment] 2019-05-08 07:24
Hi Spencer,

Any update on this?

**Comment by ryanjbaxter** [comment] 2019-06-17 14:53
We need complete working projects to try and reproduce, whether there is minimal code or not.

**Comment by spring-issuemaster** [comment] 2019-06-24 14:58
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-07-01 14:58
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-07-01 14:58 UTC
Labels: feedback-reminder, waiting for feedback
