### ISSUE TITLE
Application fails to start due to `com.sun.jersey.api.client.filter.ClientFilter not present` when `endpoints.refresh.enabled` is set to `true`

### ISSUE THREAD

**Issue by hanishi** [spring-cloud/spring-cloud-netflix#2750] opened 2018-03-02 01:35 UTC
Under `1.8.1 EurekaClient without Jersey` of the spring-cloud-netflix documentation, it states that Jersey dependencies can be excluded, but when application's `endpoints.refresh.enabled` property is set to `true`, the application won't start due to `com.sun.jersey.api.client.filter.ClientFilter not present` that is presumably part of the dependencies explicitly excluded. 

Exception

`[org/springframework/cloud/netflix/eureka/EurekaClientAutoConfiguration.class]: Initialization of bean failed; nested exception is java.lang.TypeNotPresentException: Type com.sun.jersey.api.client.filter.ClientFilter not present
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151)
	at org.springframework.cloud.stream.app.euler.httpclient.processor.kafka.EulerHttpclientProcessorKafka10Application.main(EulerHttpclientProcessorKafka10Application.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'discoveryClientOptionalArgs' defined in class path resource [org/springframework/cloud/netflix/eureka/EurekaClientAutoConfiguration.class]: Initialization of bean failed; nested exception is java.lang.TypeNotPresentException: Type com.sun.jersey.api.client.filter.ClientFilter not present
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585)
	... 27 common frames omitted
Caused by: java.lang.TypeNotPresentException: Type com.sun.jersey.api.client.filter.ClientFilter not present
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(Unknown Source)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Unknown Source)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(Unknown Source)
	at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Unknown Source)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Unknown Source)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(Unknown Source)
	at sun.reflect.generics.repository.ClassRepository.getSuperclass(Unknown Source)
	at java.lang.Class.getGenericSuperclass(Unknown Source)
	at com.sun.beans.TypeResolver.prepare(Unknown Source)
	at com.sun.beans.TypeResolver.resolve(Unknown Source)
	at com.sun.beans.TypeResolver.resolve(Unknown Source)
	at com.sun.beans.TypeResolver.resolve(Unknown Source)
	at com.sun.beans.TypeResolver.resolve(Unknown Source)
	at com.sun.beans.TypeResolver.resolveInClass(Unknown Source)
	at java.beans.FeatureDescriptor.getParameterTypes(Unknown Source)
	at java.beans.PropertyDescriptor.findPropertyType(Unknown Source)
	at java.beans.PropertyDescriptor.updateGenericsFor(Unknown Source)
	at java.beans.Introspector.addPropertyDescriptor(Unknown Source)
	at java.beans.Introspector.addPropertyDescriptors(Unknown Source)
	at java.beans.Introspector.getTargetPropertyInfo(Unknown Source)
	at java.beans.Introspector.getBeanInfo(Unknown Source)
	at java.beans.Introspector.getBeanInfo(Unknown Source)
	at java.beans.Introspector.getBeanInfo(Unknown Source)
	at java.beans.Introspector.<init>(Unknown Source)
	at java.beans.Introspector.getBeanInfo(Unknown Source)
	at java.beans.Introspector.getBeanInfo(Unknown Source)
	at java.beans.Introspector.<init>(Unknown Source)
	at java.beans.Introspector.getBeanInfo(Unknown Source)
	at org.springframework.beans.CachedIntrospectionResults.<init>(CachedIntrospectionResults.java:279)
	at org.springframework.beans.CachedIntrospectionResults.forClass(CachedIntrospectionResults.java:189)
	at org.springframework.beans.BeanWrapperImpl.getCachedIntrospectionResults(BeanWrapperImpl.java:173)
	at org.springframework.beans.BeanWrapperImpl.getPropertyDescriptors(BeanWrapperImpl.java:248)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.filterPropertyDescriptorsForDependencyCheck(AbstractAutowireCapableBeanFactory.java:1418)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.filterPropertyDescriptorsForDependencyCheck(AbstractAutowireCapableBeanFactory.java:1397)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1259)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	... 36 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.sun.jersey.api.client.filter.ClientFilter
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	... 72 common frames omitted`

**Comment by ryanjbaxter** [comment] 2018-03-02 19:56
I was not able to reproduce this.  Can you provide a sample project that reproduces the issue?

**Comment by hanishi** [comment] 2018-03-03 01:31
Having investigated further, the property `endpoints.refresh.enabled` is irrelevant. It is most likely `true` by default. It could be dependency issue that is causing this error. Interestingly however, putting but what was `excluded` fixes the error. 

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>spring-cloud-starter-stream-processor-euler-httpclient</artifactId>
    <packaging>jar</packaging>
    <name>spring-cloud-starter-stream-processor-euler-httpclient</name>
    <description>Spring Cloud Stream processor-euler-httpclient core</description>
    <version>1.0.0.BUILD-SNAPSHOT</version>

    <parent>
        <groupId>jp.ad.iij.euler.adapter.stream.app</groupId>
        <artifactId>euler-httpclient-app-starters-build</artifactId>
        <version>1.0.0.BUILD-SNAPSHOT</version>
    </parent>

    <dependencies>
        <dependency>
            <groupId>org.springframework.integration</groupId>
            <artifactId>spring-integration-http</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.integration</groupId>
            <artifactId>spring-integration-event</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>joda-time</groupId>
            <artifactId>joda-time</artifactId>
            <version>2.9.9</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5.3</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.16.18</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mariadb.jdbc</groupId>
            <artifactId>mariadb-java-client</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-eureka</artifactId>
            <!--<exclusions>-->
                <!--<exclusion>-->
                    <!--<groupId>com.sun.jersey</groupId>-->
                    <!--<artifactId>jersey-client</artifactId>-->
                <!--</exclusion>-->
                <!--<exclusion>-->
                    <!--<groupId>com.sun.jersey</groupId>-->
                    <!--<artifactId>jersey-core</artifactId>-->
                <!--</exclusion>-->
                <!--<exclusion>-->
                    <!--<groupId>com.sun.jersey.contribs</groupId>-->
                    <!--<artifactId>jersey-apache-client4</artifactId>-->
                <!--</exclusion>-->
            <!--</exclusions>-->
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bus-kafka</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jayway.jsonpath</groupId>
            <artifactId>json-path-assert</artifactId>
            <version>2.2.0</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-zipkin</artifactId>
        </dependency>
        <dependency>
            <groupId>net.logstash.logback</groupId>
            <artifactId>logstash-logback-encoder</artifactId>
            <version>4.11</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-app-starter-doc-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>jp.ad.iij.euler.adapter.stream.app.plugin</groupId>
                <artifactId>spring-cloud-stream-app-maven-plugin</artifactId>
                <configuration>
                    <generatedProjectHome>${session.executionRootDirectory}/apps</generatedProjectHome>
                    <generatedProjectVersion>${project.version}</generatedProjectVersion>
                    <bom>
                        <name>scs-bom</name>
                        <groupId>jp.ad.iij.euler.adapter.stream.app</groupId>
                        <artifactId>euler-httpclient-app-dependencies</artifactId>
                        <version>${project.version}</version>
                    </bom>
                    <generatedApps>
                        <euler-httpclient-processor>
                            <extraTestConfigClass>
                                org.springframework.cloud.stream.app.test.euler.httpclient.HttpClientProcessorTestConfiguration.class
                            </extraTestConfigClass>
                        </euler-httpclient-processor>
                    </generatedApps>
                    <enableDiscoveryClient>true</enableDiscoveryClient>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <repositories>
        <repository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/milestone</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>
</project>
```

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>euler-httpclient-app-starters-build</artifactId>
    <version>1.0.0.BUILD-SNAPSHOT</version>
    <packaging>pom</packaging>

    <parent>
        <groupId>jp.ad.iij.euler.adapter.stream.app</groupId>
        <artifactId>stream-app-starters-build</artifactId>
        <version>1.0.0.BUILD-SNAPSHOT</version>
    </parent>

    <modules>
        <module>spring-cloud-starter-stream-processor-euler-httpclient</module>
        <module>euler-httpclient-app-dependencies</module>
        <module>euler-httpclient-app-starters-test-support</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>jp.ad.iij.euler.adapter.stream.app</groupId>
                <artifactId>euler-httpclient-app-dependencies</artifactId>
                <version>1.0.0.BUILD-SNAPSHOT</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>
```

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>jp.ad.iij.euler.adapter.stream.app</groupId>
    <artifactId>stream-app-starters-build</artifactId>
    <version>1.0.0.BUILD-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>stream-app-starters-build</name>
    <parent>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-build</artifactId>
        <version>1.3.7.RELEASE</version>
        <relativePath/>
    </parent>
    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <scs-app-maven-plugin.version>1.0.0.BUILD-SNAPSHOT</scs-app-maven-plugin.version>
        <app-starters-docs-plugin.version>1.1.3.RELEASE</app-starters-docs-plugin.version>
        <bomsWithHigherPrecedence/>
        <bootVersion>1.5.2.RELEASE</bootVersion>
        <stream-app-starters-dependencies.version>1.0.0.BUILD-SNAPSHOT</stream-app-starters-dependencies.version>
        <app-metadata-maven-plugin-version>1.0.0.RELEASE</app-metadata-maven-plugin-version>
    </properties>

    <modules>
        <module>euler-httpclient</module>
        <module>euler-sleuth</module>
        <module>spring-cloud-stream-app-starters-dependencies</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>jp.ad.iij.euler.adapter.stream.app</groupId>
                <artifactId>stream-app-starters-dependencies</artifactId>
                <version>1.0.0.BUILD-SNAPSHOT</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-metrics</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.jayway.jsonpath</groupId>
            <artifactId>json-path</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.integration</groupId>
            <artifactId>spring-integration-xml</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>commons-logging</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-test-support</artifactId>
            <optional>true</optional>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-test-support-internal</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.integration</groupId>
            <artifactId>spring-integration-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-logging</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>io.pivotal.spring.cloud</groupId>
            <artifactId>spring-cloud-services-starter-config-client</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-stream-kafka</artifactId>
        </dependency>
    </dependencies>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.springframework.cloud</groupId>
                    <artifactId>spring-cloud-app-starter-doc-maven-plugin</artifactId>
                    <version>${app-starters-docs-plugin.version}</version>
                    <executions>
                        <execution>
                            <id>generate-documentation</id>
                            <phase>verify</phase>
                            <goals>
                                <goal>generate-documentation</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>jp.ad.iij.euler.adapter.stream.app.plugin</groupId>
                    <artifactId>spring-cloud-stream-app-maven-plugin</artifactId>
                    <version>${scs-app-maven-plugin.version}</version>
                </plugin>
                <plugin>
                    <artifactId>maven-javadoc-plugin</artifactId>
                    <configuration>
                        <quiet>true</quiet>
                    </configuration>
                </plugin>
                <plugin>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                        <redirectTestOutputToFile>true</redirectTestOutputToFile>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <profiles>
        <profile>
            <id>generateApps</id>
            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <groupId>jp.ad.iij.euler.adapter.stream.app.plugin</groupId>
                            <artifactId>spring-cloud-stream-app-maven-plugin</artifactId>
                            <version>${scs-app-maven-plugin.version}</version>
                            <executions>
                                <execution>
                                    <id>app-gen</id>
                                    <phase>install</phase>
                                    <goals>
                                        <goal>generate-app</goal>
                                    </goals>
                                </execution>
                            </executions>
                            <configuration>
                                <javaVersion>${java.version}</javaVersion>
                                <bootVersion>${bootVersion}</bootVersion>
                                <applicationType>stream</applicationType>
                                <additionalBoms>
                                    <bom>
                                        <name>stream-app-starters-dependencies</name>
                                        <groupId>jp.ad.iij.euler.adapter.stream.app</groupId>
                                        <artifactId>stream-app-starters-dependencies</artifactId>
                                        <version>${stream-app-starters-dependencies.version}</version>
                                    </bom>
                                </additionalBoms>
                                <binders>
                                    <kafka-10/>
                                </binders>
                                <additionalGlobalDependencies>
                                    <dependency>
                                        <groupId>org.springframework.cloud</groupId>
                                        <artifactId>spring-cloud-starter-config</artifactId>
                                    </dependency>
                                </additionalGlobalDependencies>
                                <additionalPlugins>
                                    <plugin>
                                        <groupId>org.springframework.cloud</groupId>
                                        <artifactId>spring-cloud-app-starter-metadata-maven-plugin</artifactId>
                                        <version>${app-metadata-maven-plugin-version}</version>
                                        <executions>
                                            <execution>
                                                <id>aggregate-metadata</id>
                                                <phase>compile</phase>
                                                <goals>
                                                    <goal>aggregate-metadata</goal>
                                                </goals>
                                            </execution>
                                        </executions>
                                    </plugin>
                                </additionalPlugins>
                            </configuration>
                        </plugin>
                    </plugins>
                </pluginManagement>
            </build>
        </profile>
    </profiles>

</project>
```

**Comment by ryanjbaxter** [comment] 2018-03-19 18:55
@hanishi so is everything resolved now?

**Comment by hanishi** [comment] 2018-03-27 23:21
No we just left those explicitly excluded dependencies in the dependency tree. Although the document says that the dependencies can be excluded, the app won’t start if I take them out from the POM above.

**Comment by ryanjbaxter** [comment] 2018-03-27 23:47
> I was not able to reproduce this. Can you provide a sample project that reproduces the issue?

**Comment by spencergibb** [comment] 2019-02-11 15:40
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2019-02-11 15:40 UTC
Labels: feedback-provided
