### ISSUE TITLE
Zuul gateway fails to forward HTTP HEAD requests

### ISSUE THREAD

**Issue by LeonardLaszlo** [spring-cloud/spring-cloud-netflix#2296] opened 2017-09-26 08:12 UTC
Hi there!

I think I've found a bug in Zuul. My setup is the following:
- [eureka server](https://github.com/spring-cloud/spring-cloud-netflix/files/1329194/eureka-service.zip)
- [a RESTful Web Service](https://github.com/spring-cloud/spring-cloud-netflix/files/1329192/service.zip)
- [Zuul](https://github.com/spring-cloud/spring-cloud-netflix/files/1329193/zuul.zip)

When I send a HEAD request to the service through Zuul gateway at the following address: `localhost:8090/service/greeting` I get the following forwarding exception:
[gist](https://gist.github.com/LeonardLaszlo/1465ae881e14a5dccfb125fa13d626e3)

I tried to find the bug by debugging Zuul. Unluckily I could not identify what is causing the problem.

Can you confirm if this is a bug or I am doing something wrong?

The service works as expected if I don't send the request through Zuul.

**Comment by ryanjbaxter** [comment] 2017-09-26 13:55
It appears it is just Hystrix timing out.  You can try disabling Hystrix and everything should work
`hystrix.command.default.execution.timeout.enabled: false`

**Comment by LeonardLaszlo** [comment] 2017-09-26 15:01
I tried your solution, but I does not work. Here is the stack trace: [gist](https://gist.github.com/LeonardLaszlo/6402b408e26c26064fd397ab6495e0d6)

**Comment by LeonardLaszlo** [comment] 2017-09-29 08:46
Hi @ryanjbaxter !

I've figured out that HEAD methods were working with spring-cloud-netflix versions up to 1.2.0.RELEASE. The problem was introduced with the 1.2.1.RELEASE.

Can you add a bug label to this issue please?

**Comment by ryanjbaxter** [comment] 2017-10-02 00:46
I still don't see how this is a bug.  The exception is not just a socket timeout exception.  It has nothing to do with Zuul or the version of Spring Cloud.  The service is not responding quick enough to the request.

**Comment by LeonardLaszlo** [comment] 2017-10-02 12:10
Hi Ryan!

Please excuse me because I didn't provide you all the information why I think this problem might be a bug.

So first of all the REST service responds to both GET and HEAD requests in a matter of few milliseconds if I am not using Zuul. I tried it lots of times and I never had to wait for the response for long time. By default the value of ribbon.ReadTimeout is 5000 ms and I always get a timeout after 5 s.
Even when I set the ribbon.ReadTimeout property to 180000 ms the service is not responding. 

When I call the HEAD method on the service directly only the controller corresponding to HEAD method is invoked. However, when I call the same endpoint through Zuul I see in the logs that both GET and HEAD methods were invoked. This seems to be an anomaly. I tried to debug the Zuul gateway to understand why is it working that way, but I could not find the code which calls both GET and HEAD methods.

The 3rd reason why I think this is a problem of Zuul is that this scenario works with spring-cloud-dependencies versions prior and including Brixton.SR7. Of course this does not imply necessarily that the problem is in the spring-cloud-netflix project, but I am using only spring-boot-starter-web, spring-cloud-starter-zuul and spring-cloud-starter-eureka. My gut feeling is that this problem is not caused by spring-cloud-starter-eureka nor spring-boot-starter-web, because I see exceptions coming from Zuul.

Could you reproduce this behavior on your machine?

Thank you for your patience!

**Comment by ryanjbaxter** [comment] 2017-10-03 19:21
I just ran you samples and was unable to reproduce the problem.  The only thing I changed from the zips is that I changed the Eureka server to use the BOM, but that shouldnt have made a difference.
```
zuul curl --head "http://localhost:8090/service/greeting" \
     -H "Content-Type: application/x-www-form-urlencoded; charset=utf-8"
HTTP/1.1 200
X-Application-Context: zuul:8090
Date: Tue, 03 Oct 2017 19:21:08 GMT
Content-Type: application/json;charset=UTF-8
Content-Length: 0
```

**Comment by pradeepsingh1234** [comment] 2017-10-04 13:33
I am seeing the same behavior. when running service HEAD method independently I get the response, but if the request goes through ZUUL it fails with 502 bad gateway error. 502 response comes from service. if I invoke the same method for GET(method support GET/HEAD) through ZUUL it works.  Something ZUUL is adding up and causing 502 error.

**Comment by pradeepsingh1234** [comment] 2017-10-04 13:35
here is error 👍 
 [APP:null TRACKING_ID:null ACCOUNT_NUM:null] org.apache.http.wire - http-outgoing-1 << "Content-Type: text/plain; charset=utf-8[\r][\n]"
Tue Oct 03 10:39:21 MDT 2017 DEBUG [APP:null TRACKING_ID:null ACCOUNT_NUM:null] org.apache.http.wire - http-outgoing-1 << "X-Cf-Routererror: endpoint_failure[\r][\n]"
Tue Oct 03 10:39:21 MDT 2017 DEBUG [APP:null TRACKING_ID:null ACCOUNT_NUM:null] org.apache.http.wire - http-outgoing-1 << "X-Content-Type-Options: nosniff[\r][\n]"

**Comment by LeonardLaszlo** [comment] 2017-10-04 13:40
@pradeepsingh1234 do you use CloudFoundry?

**Comment by pradeepsingh1234** [comment] 2017-10-04 13:40
yes, we are using cloud foundry.

**Comment by LeonardLaszlo** [comment] 2017-10-04 13:51
You are getting 502 because the gorouter (load balancer) of cloud foundry kills the request on timeout. 
Check line 145 bellow:
https://github.com/cloudfoundry/gorouter/blob/2a81454fdc8170bd70a4977d3a0a255b08fcaa4e/proxy/handler/request_handler.go

If you try to run your services on a local machine you will see that Zuul responds after a while, but with 500 status code.

**Comment by pradeepsingh1234** [comment] 2017-10-04 13:55
Yes, I saw same.

Sent from my iPhone

On Oct 4, 2017, at 7:51 AM, Leonard L?szl? <notifications@github.com<mailto:notifications@github.com>> wrote:


You are getting 502 because the gorouter (load balancer) of cloud foundry kills the request on timeout.
Check line 145 bellow:
https://github.com/cloudfoundry/gorouter/blob/2a81454fdc8170bd70a4977d3a0a255b08fcaa4e/proxy/handler/request_handler.go

If you try to run your services on a local machine you will see that Zuul responds after a while, but with 500 status code.

-

**Comment by pradeepkusingh** [comment] 2017-10-04 14:36
Everything works fine if I use brixton SR7.

**Comment by ryanjbaxter** [comment] 2017-10-04 15:41
Like I said I ran the sample apps you provided above on my local machine and do not see any delay when making a HEAD request through Zuul.  Without a way to reproduce the problem its hard for me to help.

**Comment by LeonardLaszlo** [comment] 2017-10-04 15:51
What OS do you use guys?

**Comment by LeonardLaszlo** [comment] 2017-10-04 21:38
I tried this setup on OS X and it seems to work properly. I've got the errors on windows 7 and 10..

**Comment by pradeepsingh1234** [comment] 2017-10-04 21:39
I can rerpdoce this error in latest mac book pro2 with Sierra OS.

**Comment by ryanjbaxter** [comment] 2017-10-05 00:03
I am using OS X

**Comment by spring-issuemaster** [comment] 2018-10-02 17:01
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.

**Closed by spring-issuemaster** 2018-10-02 17:01 UTC
Labels: question
