### ISSUE TITLE
Netflix zuul "net::ERR_INCOMPLETE_CHUNKED_ENCODING" error for large javascript file

### ISSUE THREAD

**Issue by ashokdudhade** [spring-cloud/spring-cloud-netflix#1468] opened 2016-11-15 06:00 UTC
Chrome browser is throwing below error console when large js file is included in html.

net::ERR_INCOMPLETE_CHUNKED_ENCODING

**Comment by ryanjbaxter** [comment] 2016-11-15 12:24
I dont see how this is related to Spring Cloud.  Please reopen and provide more information.

**Comment by ashokdudhade** [comment] 2016-11-15 12:49
@ryanjbaxter When I'm accessing my website directly through nginx or apache it works fine. But when I use zuul to route requests it gives "ERR_INCOMPLETE_CHUNKED_ENCODING" error for javascript resource.

**Comment by ryanjbaxter** [comment] 2016-11-15 12:51
Can you please provide a sample which reproduces the issue?  It is probably related to the javascript resource you are serving.

**Comment by ashokdudhade** [comment] 2016-11-15 13:25
you can try loading any large javascript file, in my case js file is around 3MB. See below js file as sample it also throws same error in chrome when accessed through zuul, same works just fine with nginx or apache.

https://github.com/ashokdudhade/DartUnitTestDemo/blob/master/some.js

**Comment by ryanjbaxter** [comment] 2016-11-15 20:26
I am not able to reproduce the issue.  I can load the the file you linked to above through zuul without any issues.  A sample that reproduces the issue would be great.

**Comment by spencergibb** [comment] 2018-01-18 00:13
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2018-01-18 00:13 UTC
Labels: waiting for feedback
