### ISSUE TITLE
Provide ability to decorate AsyncRestTemplate using RestTemplateCustomizer

### ISSUE THREAD

**Issue by justinjohn83** [spring-cloud/spring-cloud-netflix#1128] opened 2016-06-23 22:31 UTC
Would like to be able to enable Ribbon functionality with AsyncRestTemplate either by adding new method to RestTemplateCustomizer interface accepting AsyncRestTemplate argument or adding new interface that takes this.

**Comment by spencergibb** [comment] 2016-06-23 22:36
Duplicate of https://github.com/spring-cloud/spring-cloud-commons/issues/36

**Closed by spencergibb** 2016-06-23 22:36 UTC
Labels: duplicate
