### ISSUE TITLE
Sidecar - POST not forwarding request body

### ISSUE THREAD

**Issue by reidadam** [spring-cloud/spring-cloud-netflix#1705] opened 2017-02-17 09:03 UTC
I have a remote Python service exposing two endpoints (one GET and one POST). Sidecar is installed on the host and registering itself with Eureka so this service is available to others.

I also have a Java Spring boot client running Feign which looks up services using serviceId.

    @FeignClient("PythonSidecar")
    public interface Client {

        @RequestMapping(value = "/test", method = RequestMethod.POST, produces =MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
        public String testPost(@RequestBody(required = true) String testString);
    }
When I invoke the python based service (via sidecar) **GET requests work as expected. However, POST requests do not**; they hit the endpoint but the request body is missing the data.

We are running Spring Cloud CAMDEN SR4.

We were running Spring Cloud ANGEL SR4 and this was working correctly. The upgrade broke it.

Thanks

**Comment by ryanjbaxter** [comment] 2017-02-17 16:35
Would it be possible to provide a sample that reproduces this?

**Comment by spencergibb** [comment] 2017-02-17 22:37
Please don't cross post http://stackoverflow.com/questions/42293478/spring-sidecar-post-not-forwarding-request-body

**Comment by ImranAdan** [comment] 2017-02-20 18:07
@spencergibb  Please, there is no reason to close this issue. Can we please have it re-opened. 

@ryanjbaxter  I have provided a sample that can reproduces this issue at: https://github.com/ImranAdan/PythonSidecar

**Comment by spencergibb** [comment] 2017-02-20 18:10
Pick one, SO or this issue.

**Comment by ImranAdan** [comment] 2017-02-20 18:17
This issue.

**Comment by spencergibb** [comment] 2017-02-20 18:21
You don't own the SO issue to close/delete it.

**Comment by reidadam** [comment] 2017-02-20 21:31
I've removed the SO issue. Please continue on this forum with this issue.

**Comment by ryanjbaxter** [comment] 2017-02-21 01:15
Quick question, did you happen to try `Brixton.SR7`?

**Comment by ryanjbaxter** [comment] 2017-02-21 16:45
@reidadam I am not a Python expert so excuse me if I am making a dumb mistake here...
I ran `pip install flask` and then ran `python app.py` but I get
```
Traceback (most recent call last):
  File "app.py", line 1, in <module>
    from flask import Flask, render_template, request, url_for
ImportError: No module named flask
```

**Comment by ImranAdan** [comment] 2017-02-21 17:35
@ryanjbaxter that looks like either Flask didn't get properly installed (did the `pip install flask` command succeed?) or you have more than one instance of the python interpreter (for instance if you are running stuff in a virtual machine) and it got installed in the wrong one.

If the `pip install` command ran properly, you should be able to fire up the python interpreter from the terminal (just type `python`) and then run `import flask` without getting any errors.

**Comment by ryanjbaxter** [comment] 2017-02-21 18:14
It installed correctly from what I can see.  Looks like it got installed to `/usr/local/lib/python2.7/site-packages/flask`, `python` is installed in `/usr/local/Cellar/python/2.7.13/bin/python`.

**Comment by jlopezpena** [comment] 2017-02-21 22:21
That is probably a python path issue. You seem to have installed python form homebrew, but OSX needs its own python for functioning normally. Sometimes system upgrades force default python interpreter to be the system one. If when you run from the terminal `which python` you get `/usr/bin/python` instead of `usr/local/bin/python` (or similar, something inside `/usr/local` then this is definitely your issue.

In any case, if Flask is installed properly you should have a `flask` command line tool which you can use to run your app like this (from the folder where `app.py` lives):
```export FLASK_APP=app.py; flask run```
This should use the same python interpreter that flask got installed with.

**Comment by jlopezpena** [comment] 2017-02-21 22:33
For the sake of completeness, it might also be a permission's issue with the python packages. This happens if you ever do `sudo pip install ...`, the installed modules get root ownership and cannot be loaded by regular users. If that is the case then try
```sudo pip uninstall flask
pip install flask
```

**Comment by ryanjbaxter** [comment] 2017-02-22 16:50
@jlopezpena thanks for the hints, I now have the app running!

**Comment by ryanjbaxter** [comment] 2017-02-22 22:05
Looks like setting the correct `Content-Type` header fixes the problem.

```
	@RequestMapping(value = "/testPost", method = RequestMethod.POST, consumes = "application/x-www-form-urlencoded")
	public String testPost(@RequestBody(required = true) String test);
```

**Comment by ImranAdan** [comment] 2017-02-23 09:52
@ryanjbaxter Thanks for this, I will add this to our services and see if that resolves that issue.

**Comment by reidadam** [comment] 2017-02-23 17:03
@ryanjbaxter I've tested this change in my own project. I can see the content-type header has changed from application/json to application/x-www-form-urlencoded but I still don't get any request body data

**Comment by ryanjbaxter** [comment] 2017-02-23 17:57
The only thing I changed in your git repo, is move from `Camden.SR2` to `Camden.SR5` and make the change above to the `@RequestMapping` annotation in `PythonFeignClient`.

**Comment by reidadam** [comment] 2017-02-24 14:48
This solution does work but unfortunately the sample app does not represent the problem exactly. 

This solution works only when Feign client uses a url to point the Python service directly (port 8000 in this case). Its is not using the Spring Side Car to proxy the requests.

```
//works!
@FeignClient(url = "http://localhost:8000", name = "PythonSidecar" )
public interface PythonFeignClient {
		
	@RequestMapping(value = "/testPost", method = RequestMethod.POST, consumes = "application/x-www-form-urlencoded")
	public String testPost(@RequestBody(required = true) String test);
	
}
```
However, if you incorporate a Eureka Server and lookup the service by  Id, then the problem occurs. 

```
//does not work!
@FeignClient(name = "PythonSidecar" )
public interface PythonFeignClient {
		
        @RequestMapping(value = "/testPost", method = RequestMethod.POST, consumes = "application/x-www-form-urlencoded")
	public String testPost(@RequestBody(required = true) String test);
	
}
```

Let me know if you'd like me to post a complete set of projects to demonstrate this.  Thx.

**Comment by ryanjbaxter** [comment] 2017-02-24 15:05
Yes a sample with all the projects that reproduce the problem would be welcome.

**Comment by ImranAdan** [comment] 2017-02-27 17:58
@ryanjbaxter Thanks, I have provided a sample with all the projects required to reproduce the issue. The sample can be found at: https://github.com/ImranAdan/SidecarIssue 

Please let me know if there is anything which is not clear and we can work on resolving it

**Comment by reidadam** [comment] 2017-03-06 11:06
@ryanjbaxter Did you see @ImranAdan's sample project and did you manage to reproduce the error? Thanks.

**Comment by ryanjbaxter** [comment] 2017-03-06 15:26
@reidadam yes I did, I was busy last week with some other work, I will try to look at the same soon

**Comment by ryanjbaxter** [comment] 2017-03-07 01:37
The difference is that the `content-length` header is not being sent when using the service id.  Apparently Flask does not like that.  I need to look into why we are removing the `content-length` header.

**Closed** 2017-03-07 03:11 UTC

**Comment by spencergibb** [comment] 2017-03-07 03:18
Applied to 1.2.x via bd3391ae55a3c63dbd19a1b7ef4f2bfd5765ea34

**Comment by ryanjbaxter** [comment] 2017-03-07 14:21
@reidadam if you move the TestHarness project in the sample to `Camden.BUILD-SNAPSHOT` or `Dalston.BUILD-SNAPSHOT` you should be able to pick up the fix @spencergibb made.  It is working for me.

**Comment by reidadam** [comment] 2017-03-07 14:23
@ryanjbaxter thanks. we'll check it out

**Comment by reidadam** [comment] 2017-03-07 15:17
That works. Thanks for your help! 

What are the timelines for 1.2.6.RELEASE release?

**Comment by ryanjbaxter** [comment] 2017-03-07 15:19
I am hoping this week.  Glad it worked!
