### ISSUE TITLE
Dynamic routing not working

### ISSUE THREAD

**Issue by shalmalim** [spring-cloud/spring-cloud-netflix#2227] opened 2017-08-24 23:25 UTC
My gateway is running on port 8080
Booksapp on 8090
Item Service on 9000

I'm trying to route the incoming request `http://localhost:8080/booksapp/available`
90% of the times to `http://localhost:8090/available`
10% to `http://localhost:9000/v2/items/1001` 

I know the URLs don't make sense right now, because one has an ID and the other does not but these values are there only for the purpose of the example.

application.properties
```
zuul.routes.booksapp.url=http://localhost:8090

ribbon.eureka.enabled=true

server.port=8080

```

I have a custom "pre" filter having order > that of PreDecorationFilter. The PreDecorationFilter has order 5.

The request always gets routed to the Booksapp, even though the `else` part is executed 10% of the times, the actual routing is always to the Booksapp. It seems like the dynamic routing cannot override the route defined in application.properties.

What am I missing?

I also tried doing `ctx.set("requestURI", url);` but that is not working either.
Thank you for your help!

Filter code below:

```
package hello.filters.pre;

import java.util.Random;

import javax.servlet.http.HttpServletRequestWrapper;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.web.util.UriComponentsBuilder;

import com.netflix.zuul.ZuulFilter;
import com.netflix.zuul.context.RequestContext;



public class RatioBasedFilter extends ZuulFilter {

  private static Logger log = LoggerFactory.getLogger(RatioBasedFilter.class);
  private Random random = new Random();

  @Override
  public String filterType() {
    return "pre";
  }

  @Override
  public int filterOrder() {
    return 100;
  }

  @Override
  public boolean shouldFilter() {
    return true;
  }

  @Override
  public Object run() {
      RequestContext ctx = RequestContext.getCurrentContext();

      log.info("Running ratio based filter");
      log.info("Request URL::::" + ctx.getRequest().getRequestURL());
      log.info("Request URI::::" + ctx.get("requestURI"));
      
      if (isLegacy()) {
          String urlLegacy = UriComponentsBuilder.fromHttpUrl("http://localhost:8090").path("/available").build()
                  .toUriString();
          log.info("Redirecting to " + urlLegacy);
          HttpServletRequestWrapper requestWrapper = new HttpServletRequestWrapper(ctx.getRequest()) {
        	  	@Override
        	  	public String getRequestURI() {
        	  		return urlLegacy;
        	  	}
        	  	
          	@Override
          	public StringBuffer getRequestURL() {
          		return new StringBuffer(urlLegacy);
          	}        	  	
          };
          ctx.setRequest(requestWrapper);
          
      } else {
          String urlNew = UriComponentsBuilder.fromHttpUrl("http://localhost:9000").path("/v2/items/1001").build()
                  .toUriString();
          log.info("Redirecting to " + urlNew);
          HttpServletRequestWrapper requestWrapper = new HttpServletRequestWrapper(ctx.getRequest()) {
      	  	@Override
      	  	public String getRequestURI() {
      	  		return urlNew;
      	  	}
      	  	
      	  	@Override
      	  	public StringBuffer getRequestURL() {
      	  		return new StringBuffer(urlNew);
      	  	}
        };
        ctx.setRequest(requestWrapper);
      }
      return null;
  }

  boolean isLegacy() {
      return random.nextInt(100) < 90;
  }
  
}

```

**Comment by ryanjbaxter** [comment] 2017-08-25 18:41
Have you tried using a route filter?  Those filters handle routing the request.

**Comment by shalmalim** [comment] 2017-08-25 19:27
I did try changing the above filter to a "route" type but did not work. I went along the lines of what is described here: https://github.com/spring-cloud/spring-cloud-netflix/issues/1754

Why is the modification of requestContext not taking any effect in my case?

**Comment by ryanjbaxter** [comment] 2017-08-25 19:31
Not sure, can you provide a sample that reproduces the problem so we can investigate?

**Comment by shalmalim** [comment] 2017-08-25 19:44
I only added the above filter to the gateway application described in the tutorial: https://spring.io/guides/gs/routing-and-filtering/

Attached source: 
[src.zip](https://github.com/spring-cloud/spring-cloud-netflix/files/1252839/src.zip)

**Comment by Aloren** [comment] 2017-09-01 18:48
We have done almost the same thing a little bit different, in `run` method:
```
        HttpServletRequest request = ctx.getRequest();
        URL previousRouteHost = ctx.getRouteHost();
        Object serviceId = ctx.get("serviceId");
        URL newHost = // get new host from your configuration here
        log.trace("Replaced route host: {} serviceId: {} with host: {} for request: {}",
                previousRouteHost, serviceId, newHost, request.getRequestURI());
        ctx.setRouteHost(newHost);
```
If you want to map to host manually you will need to set routeHost in `RequestContext`, but if you want to change the service name that will handle the request you will need to set serviceId in `RequestContext`. You need to update `RequestContext` because of how `RibbonRoutingFilter` and `SimpleHostRoutingFilter` route your requests.

**Comment by ryanjbaxter** [comment] 2017-09-02 11:02
Thanks @Aloren.  @shalmalim can you try @Aloren's suggestion above?

**Comment by spencergibb** [comment] 2018-01-18 00:32
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2018-01-18 00:32 UTC
Labels: waiting for feedback

**Comment by momentum123** [comment] 2018-04-06 09:01
hi @ryanjbaxter @spencergibb  im also facing kind of issue I have a VersionbasedFilter extending zuul filter 
but its not executing tried with debugging request is not even passing through :
`
import javax.servlet.http.HttpServletRequest;

import org.springframework.cloud.netflix.zuul.filters.support.FilterConstants;

import com.netflix.zuul.ZuulFilter;
import com.netflix.zuul.context.RequestContext;


public class VersionBasedFilter extends ZuulFilter {

	@Override
	public boolean shouldFilter() {
		return true;
	}

	@Override
	public Object run() {
		RequestContext ctx = RequestContext.getCurrentContext();
		HttpServletRequest request = ctx.getRequest();
	    String previousURI = request.getRequestURI();
	    Object serviceId = ctx.get("serviceId");
	    System.out.println("serviceId------------------------------------>------------------------>"+serviceId.toString());    
	    //URL newHost = new URL(arg0)

	    if (isFilterRequired(previousURI)) {
	    	    // ctx.setRouteHost(newHost);
	    	 ctx.set("serviceId", serviceId.toString()+"V2");
	    	 serviceId = ctx.get("serviceId");
	 	    System.out.println("serviceId------------------------------------>------------------------>"+serviceId.toString());
	      }
	      return null;
	}

	@Override
	public String filterType() {

		return "pre";
	}

	@Override
	public int filterOrder() {
		return FilterConstants.PRE_DECORATION_FILTER_ORDER -100;
	}
	
	private boolean isFilterRequired(String uri){
		if(uri.contains("api/v2.0"))
		return true;
		else
		return false;
	}

}`

I have tried with routing filter and changing order before /after pre decoration filter 
and given that have one more subdomain router  filter of order  FilterConstants.PRE_DECORATION_FILTER_ORDER -1

works fine

**Comment by momentum123** [comment] 2018-04-06 13:10
hi @Aloren @ryanjbaxter 
im trying to set request uri manually using
`requestContext.set("requestURI","someURI")
`
but is not getting appended and using older one

**Comment by ryanjbaxter** [comment] 2018-04-06 19:35
@momentum123 please open a separate issue with a working sample app that reproduces the problem
