### ISSUE TITLE
ZuulFallbackProvider not getting triggered

### ISSUE THREAD

**Issue by madheshr** [spring-cloud/spring-cloud-netflix#1461] opened 2016-11-13 03:13 UTC
Hi

  My custom class implementing ZuulFallbackProvider never gets triggered.  I am getting alternating responses like

{"timestamp":1479006378665,"status":500,"error":"Internal Server Error","exception":"com.netflix.zuul.exception.ZuulException","message":"SHORTCIRCUIT"}

and

{"timestamp":1479006364293,"status":500,"error":"Internal Server Error","exception":"com.netflix.zuul.exception.ZuulException","message":"NUMBEROF_RETRIES_NEXTSERVER_EXCEEDED"}

Here's my basic Fallback code at the Gateway application level

@Component
class SessionFallbackProvider implements ZuulFallbackProvider {

	@Override
	public String getRoute() {
		return "session";
	}

	@Override
	public ClientHttpResponse fallbackResponse() {
		return new ClientHttpResponse() {
			@Override
			public HttpStatus getStatusCode() throws IOException {
				return HttpStatus.OK;
			}

			@Override
			public int getRawStatusCode() throws IOException {
				return 200;
			}

			@Override
			public String getStatusText() throws IOException {
				return "OK";
			}

			@Override
			public void close() {

			}

			@Override
			public InputStream getBody() throws IOException {
				return new ByteArrayInputStream("fallback".getBytes());
			}

			@Override
			public HttpHeaders getHeaders() {
				HttpHeaders headers = new HttpHeaders();
				headers.setContentType(MediaType.APPLICATION_JSON);
				return headers;
			}
		};
	}
}

Here's the gateway application yml entries
zuul:
  routes:
    session:
      path: /SessionTracker/*
      serviceId: session
      sensitiveHeaders: Cookie,Set-Cookie,Authorization

ribbon:
  eureka:
    enabled: false

session:
  ribbon:
    listOfServers: localhost:8090

Here's the Microservice yml entry
spring.cloud.config.discovery.serviceId: session 

I don't see a detailed exception being thrown in the logs.

**Comment by ryanjbaxter** [comment] 2016-11-14 16:18
I am not able to reproduce this in my environment, could you perhaps provide the projects that reproduce the issue?

**Comment by madheshr** [comment] 2016-11-14 17:48
Hi
  I did some debugging using the sample application provided.  I see that in the working sample application, RibbonRoutingFilter gets initialized with the HttpClientRibbonCommandFactory, whereas in my application it gets the RestClientRibbonCommandFactory.  Is there a particular setting that drives this?  I think this might be the issue.

  I will try to see if i can pull out the code and share a working project?

**Comment by ryanjbaxter** [comment] 2016-11-14 18:56
Do you have `zuul.ribbon.restclient.enabled` or `ribbon.restclient.enabled` set to true?

**Comment by madheshr** [comment] 2016-11-14 19:23
No.. I don't.  Is this the default?

**Comment by ryanjbaxter** [comment] 2016-11-14 20:32
No by default we use `HttpClientRibbonCommandFactory`.  If you can provide a sample we can better look into the problem.

**Comment by madheshr** [comment] 2016-11-14 23:07
Finally.. managed to fix the project.  Looks like it could have been due to multiple versions of spring cloud in my project.  The ZuulFallbackProvider is only present in the latest snapshot which was somehow not in the classpath.  What is the cleanest way to forward the request to a default endpoint? 

		@Override
		public InputStream getBody() throws IOException {
                        // Need to forward the entire request to a default endpoint
			return new ByteArrayInputStream("fallback".getBytes());
		}

**Comment by ryanjbaxter** [comment] 2016-11-15 01:12
I wouldn't suggest taking any kind of action in the fallback that could result in another failure.  Calling an endpoint in the fallback could result in another failure.

**Comment by madheshr** [comment] 2016-11-15 03:13
I get your point.  However the fallback service is internally hosted.  For convenience sake, we just want to invoke the Rest endpoint rather than re-factor it as a method.

**Comment by ryanjbaxter** [comment] 2016-11-15 12:49
If you really want to take that approach than you can use a `RestTemplate` just like you normally would.  I am going to close this issue since the original problem has ben solved.

**Closed by ryanjbaxter** 2016-11-15 12:49 UTC
