### ISSUE TITLE
@FeignClient configuration works not properly if 2 clients have the same name

### ISSUE THREAD

**Issue by harthorst** [spring-cloud/spring-cloud-netflix#1184] opened 2016-07-13 13:39 UTC
I use version 8.16.2. This problem seems to occur when I have 2 different configuration classes, in my case I use SpringMvcContract in SpringMVCAnnotatedServiceClient and JAXRSContract in JaxRSAnnotatedServiceClient. If both clients have exact the same name I get the following error:

Method greetJaxRS not annotated with HTTP method type (ex. GET, POST)

SpringMvcContract seems to be used, but JAXRSContract is configured. If I change 

```
@FeignClient(name = "SERVICE-WITH-TWO-INTERFACES", configuration = SpringMVCAnnotatedServiceClientConfiguration.class)
public interface SpringMVCAnnotatedServiceClient extends SpringMVCAnnotatedService {...}
```

to 

```
@FeignClient(name = "http://SERVICE-WITH-TWO-INTERFACES", configuration = SpringMVCAnnotatedServiceClientConfiguration.class)
public interface SpringMVCAnnotatedServiceClient extends SpringMVCAnnotatedService {...}
```

everything works like expected.

You can find a sample project [here](https://www.dropbox.com/sh/9txrnlok817iqjh/AAAvwbTyJc5qfemWKOprrRUXa?dl=0) , just run the test.

Greetings,
Thomas

**Comment by spencergibb** [comment] 2016-10-05 21:19
Duplicate of #1211 (more conversation there)

**Closed by spencergibb** 2016-10-05 21:19 UTC
