### ISSUE TITLE
circuit breakers isssue

### ISSUE THREAD

**Issue by gangakrishh** [spring-cloud/spring-cloud-netflix#2266] opened 2017-09-11 10:04 UTC
@ryanjbaxter 

i've xyz service (spring boot/cloud), running on ecs (running 2 tasks) requests going through zuul (circuit breakers enabled, ribbon configuration seems ok). i've put some load on this service (jmeter load) in between i've stopped one of the task (kind of chaos testing). few requests were failing, we are using sumologic for logs (fluent-d driver). i see only [org.springframework.cloud.netflix.zuul.filters.post.SendErrorFilter:run] - [Error during filtering] ", error.

1. i want to see the full stacktrace?
2. how to confirm requests are redirected to other task (next server) (which is running)?

**Comment by ryanjbaxter** [comment] 2017-09-11 13:43
Could you provide more the of the logs?

**Comment by gangakrishh** [comment] 2017-09-11 13:54
hmm. i didn't have much logs

[TRANS_ID:5fcae811-5e48-440c-8882-bcb0fc4a8f16] [TRACE_ID:71879d59a310f31d] [SPAN_ID:71879d59a310f31d] [XXXX_HEADERS:] [http-nio-8001-exec-593] [org.springframework.cloud.netflix.zuul.filters.post.SendErrorFilter:run] - [Error during filtering] ",

that is why i've asked how to confirm,  let me know which package i've enable debug logging. 

problem is we are using docker / sumologic . seems docker logs doesn't support multiline logs

**Comment by ryanjbaxter** [comment] 2017-09-11 14:45
What is the issue?  Are you just trying to confirm that we are retrying on another service instance or have you confirmed that it is not occurring?

**Comment by gangakrishh** [comment] 2017-09-11 16:25
i just want to confirm zuul/circuit breakers trying nextServer.. how to do that?

**Comment by ryanjbaxter** [comment] 2017-09-11 17:53
You could probably enable logging around the Apache HTTP Client (used by default, or the OK HTTP Client if you are using that client) and it should show you the request being made.

**Comment by gangakrishh** [comment] 2017-09-12 09:14
i've enabled debug logging for org.apache.http.client: DEBUG

captured only below log
[TRACE_ID:2769b4f8ad25d32d] [SPAN_ID:61deb6af196355cf] [EBSCO_HEADERS:] [http-nio-8001-exec-103] [org.apache.http.client.protocol.RequestAuthCache:process] - [Auth cache not set in the context] ",

so not much help with http debug logging


i've written the post filter as below, for errors it is logging 0 (zero) status and null as error/exception

`import javax.servlet.http.HttpServletResponse;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.netflix.zuul.ZuulFilter;
import com.netflix.zuul.context.RequestContext;

public class CustomFilter extends ZuulFilter {

	private static final Logger LOGGER = LoggerFactory.getLogger(CustomFilter.class.getName());
	@Override
	public boolean shouldFilter() {
		return true;
	}

	@Override
	public Object run() {
		
		RequestContext ctx = RequestContext.getCurrentContext();
		HttpServletResponse resp = ctx.getResponse();
		
		int responseStatus = ctx.getResponse().getStatus();
		if(responseStatus!=200){
			ctx.getResponse().getStatus();
			ctx.getFilterExecutionSummary().toString();
			Throwable t = ctx.getThrowable();
			String errorMessage = null;
			if( t != null ){
				errorMessage = "THROWABLE\t"+errorMessage;
			}
			errorMessage += "\tERROR\t"+ctx.getResponseBody();
			LOGGER.info("ERROR_RESPONSE_"+errorMessage+"_ISRESPONSE_COMMITTED_"+resp.isCommitted());
		}
		LOGGER.info("RESPONSE_CODE_"+resp.getStatus());
		return null;
	}

	@Override
	public String filterType() {
		return "post";
	}

	@Override
	public int filterOrder() {
		return 999;
	}

}
`

**Comment by gangakrishh** [comment] 2017-09-12 09:16
1. which filter executed before sending response to client ? (just want to see the response at least through filters)
2. where exactly retry logic written (ribbon ?) want to see the code

**Comment by ryanjbaxter** [comment] 2017-09-12 14:01
I dont see how that is the only useful logging that your application is producing.  Maybe you could attach the entire log file so I can take a look.  

`RetryableRibbonLoadalancingHttpClient` is the class that is handing the retry logic.
https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/ribbon/apache/RetryableRibbonLoadBalancingHttpClient.java#L70

**Comment by gangakrishh** [comment] 2017-10-06 10:59
@ryanjbaxter  sample prototype to test ribbon here 
[https://github.com/gangakrishh/ribbon-testing]

**Comment by gangakrishh** [comment] 2017-10-06 11:05
@joshlong if you can help

**Comment by spring-issuemaster** [comment] 2018-10-02 17:01
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.

**Closed by spring-issuemaster** 2018-10-02 17:01 UTC
Labels: question
