### ISSUE TITLE
eureka can not find the second service if use server.port=0

### ISSUE THREAD

**Issue by ExtremeYu** [spring-cloud/spring-cloud-netflix#2968] opened 2018-05-24 09:03 UTC
**eureka  just show the first instance but wil never show the incoming service if use server.port=0**

**Comment by spencergibb** [comment] 2018-05-24 13:42
Duplicate of #843?

**Comment by spencergibb** [comment] 2018-10-01 23:05
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2018-10-01 23:05 UTC
Labels: waiting for feedback
