### ISSUE TITLE
Upgrade to Brixton.M5 from Angel breaks existing @FeignClient runtime behavior

### ISSUE THREAD

**Issue by eoliphan** [spring-cloud/spring-cloud-netflix#898] opened 2016-03-10 19:47 UTC
Hi, I have a some code that calls a backend spring HATEOAS service using a @FeignClient decorated interface.  This code works just fine under Angel. After upgrading to Brixton, it stops working in a peculiar fashion.  

Here's the signature from my backend service controller

```
public PagedResources<Resource<MyClass>> search(....
```

Here's my client
```
@Service
@FeignClient("myclass")
public interface GrantListServices {
    @RequestMapping(method = RequestMethod.GET,value="/api/myclass")
    PagedResources<Resource< MyClass >> getMyClass();
   ...
```

So again, under Angel, this works just as expected.  Under Brixton, I was getting no results in my application.  After digging into the code at runtime with the debugger the PagedResources metadata seems to be fine.  The size, totalElements, etc. values are as expected based on what the service sent over.  Yet the content and links arrays are empty.   I'm really perplexed by this as not only did it work fine under Angel, but whatever is going on, seems to be a 'silent failure', i'm getting no errors, etc.  It's just not working as expected.

**Comment by spencergibb** [comment] 2016-03-10 20:05
Duplicate of #856

**Closed by spencergibb** 2016-03-10 20:05 UTC
Labels: duplicate
