### ISSUE TITLE
Change groupBy logic for aggregatorServer in spring turbine amqp

### ISSUE THREAD

**Issue by JagmohanSharma** [spring-cloud/spring-cloud-netflix#1301] opened 2016-08-29 09:25 UTC
As per default implementation, we are getting aggreagted dashboard with all instances present in RabbitMq channels. How can we update this logic to aggregate the instances ? As we want to make one cluster per application so can we have one cluster per channel of rabbit mq?
I am referring this code -

                                 Observable<Map<String, Object>> publishedStreams = StreamAggregator
				.aggregateGroupedStreams(hystrixSubject().groupBy(
						data -> InstanceKey.create((String) data.get("instanceId"))))
				.doOnUnsubscribe(() -> log.info("Unsubscribing aggregation."))
				.doOnSubscribe(() -> log.info("Starting aggregation")).flatMap(o -> o)
				.publish().refCount();

**Comment by spencergibb** [comment] 2016-08-29 14:25
Duplicate of #166

**Closed by spencergibb** 2016-08-29 14:25 UTC
Labels: duplicate

**Comment by JagmohanSharma** [comment] 2016-08-31 09:01
I am not able find any concrete example for this purpose with issue #166 . As we need to filter the data in the turbine server anyway (not the messaging layer) so here we have to configure the metrics generation as well in - 

            @Scheduled(fixedRateString = "${hystrix.stream.queue.gatherRate:500}")
	                public void gatherMetrics() {
                            JsonGenerator json = this.jsonFactory.createGenerator(jsonString);
                        }
where we can add some parameter which can be used in our turbine server to filter this.

Do we have such concrete example as I am not getting that thing configured?/

**Comment by spencergibb** [comment] 2016-08-31 14:49
Turbine already has data, the cluster, to group by. I'm not keen on adding a new way to group by.

**Comment by JagmohanSharma** [comment] 2016-08-31 15:31
Can we have clusters while using spring cloud turbine amqp or stream as well? 
Like here we are getting all service instance all together on a single dashboard. How can we configure cluster in rabbit mq implementation ?

**Comment by spencergibb** [comment] 2016-08-31 15:43
Like I said, that feature doesn't exist yet and is the purpose for #166.
