### ISSUE TITLE
Spring cloud does not fully support HTTP

### ISSUE THREAD

**Issue by voronaam** [spring-cloud/spring-cloud-netflix#2343] opened 2017-10-04 16:05 UTC
This is a copy of https://github.com/Netflix/zuul/issues/365 , because we are thinking of migrating from plane Zuul installation onto Spring Cloud. Perhaps it can be fixed here. Feel free to close if you do not think it is fixable inside spring cloud.

Sample call:

```
curl http://your.host.com -H'Accept-Encoding: notgzip, nevergzip, pleasenogzip'
```

Expected result:
Content is not compressed

Actual result:
Response content is gzipp'ed

Note that there is at least one real world HTTP compression type for which it matters: `pack200-gzip`

More RFC-strict example to disallow gzip is
```
curl http://your.host.com -H'accept-encoding: gzip;q=0,deflate,sdch'
```

Accroding to RFC https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.3 the qvalue zero means "not acceptable".

And Zuul breaks RFC.

**Comment by spencergibb** [comment] 2017-10-04 16:08
Have you actually seen this using zuul provided by spring cloud? Please provide a sample that recreates the problem.

**Comment by voronaam** [comment] 2017-10-04 18:07
Sure. For reproducing I used this getting started guide: https://spring.io/guides/gs/routing-and-filtering/

```
git clone https://github.com/spring-guides/gs-routing-and-filtering.git
cd gs-routing-and-filtering/complete/book
./gradlew bootRun &
sleep 10
cd ../gateway
echo 'server.compression.enabled=true' >> src/main/resources/application.properties
./gradlew bootRun &
sleep 10
curl http://localhost:8080/books/available -i -H'accept-encoding: gzip;q=0,deflate,sdch'
HTTP/1.1 200 
X-Application-Context: application:8080
Date: Wed, 04 Oct 2017 18:04:29 GMT
Content-Type: text/plain;charset=UTF-8
Transfer-Encoding: chunked
Content-Encoding: gzip
Vary: Accept-Encoding

�
.(��KW��SpL.�������~u
```

**Comment by voronaam** [comment] 2017-10-26 20:41
Dear Spring team. Could you please find some time to look at the issue? I am not asking about much, just removing the "waiting for feedback" label would be enough.

It took me an hour to provide you with the full script that once executed reproduced the bug end-to-end. It has been 22 days since then and I am extremely sad to see that something that takes 5 seconds has not been done.

**Comment by ryanjbaxter** [comment] 2017-11-13 20:57
I spent some time digging into this only to conclude that Spring Boot doesnt appear to honor `accept-encoding: gzip;q=0,deflate,sdch`.  If you create a plain Boot app and enable 
```
server.compression.enabled=true
server.compression.min-response-size=1
```
Then send a request with the above `accept-encoding` header the content still comes back gziped.  Even if the problem is addressed in Boot there are some changes we will have to make in Spring Cloud Netflix as well.  Namely in `ProxyRequestHelper` where we just overwrite the `accept-encoding` header https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/ProxyRequestHelper.java#L148

Also in `SendResponseFilter` where we just check if the `accept-encoding` filter contains `gzip` and assume the content should be gzipped
https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/post/SendResponseFilter.java#L152

**Comment by nivemaham** [comment] 2017-11-23 17:54
I am having the same issue. It is quite weird to experience this. Also zuul filter is overriding the parameters.  We are having a blocker because of adding zuul filter. Is there any progress or quick fix that we cold available ? @spencergibb @ryanjbaxter

**Comment by voronaam** [comment] 2017-11-24 09:27
My take on it is that `SendResponseFilter` should be fixed.

Being a dynamic prroxy, it may front traffic to other backend applications - not only Spring Boot based. At least that fix would be a step in the right direction.

**Comment by ryanjbaxter** [comment] 2017-11-27 16:33
I dont agree.  Boot should be fixed first and then we can make the appropriate changes above to fix Zuul as well.  I suggest you open an issue with Boot and then link to that issue here.

**Comment by voronaam** [comment] 2017-11-28 00:51
I have created one: https://github.com/spring-projects/spring-boot/issues/11173

**Comment by spencergibb** [comment] 2018-01-18 00:49
Closing in favor of https://github.com/spring-projects/spring-boot/issues/11173

**Closed by spencergibb** 2018-01-18 00:49 UTC
Labels: waiting for feedback
