### ISSUE TITLE
Force FeignClient to requset microrService over https instead of HTTP?

### ISSUE THREAD

**Issue by nmahcene** [spring-cloud/spring-cloud-netflix#3107] opened 2018-07-26 14:06 UTC
My service is configured to https , registred on Eureuka server. 
when i use @FeignClient(value = "my-service") for example,it is always request serves over http,
how to slove it? 
and i have this server Error : No subject alternative DNS name matching

**Comment by ryanjbaxter** [comment] 2018-07-26 17:41
Can you try setting `ribbon.IsSecure`?  If that doesnt work please provide a sample that reproduces the problem

**Comment by tridipch** [comment] 2018-08-02 12:45
There is already some discussion here-
https://stackoverflow.com/questions/40853829/springboot-feignclient-with-ssl-p12
For me it was easier not to use the mentioned socket factory but instead something like this-

@Bean
    public Client feignClient()
    {
        Client trustSSLSockets = new Client.Default(getSSLSocketFactory1(), new NoopHostnameVerifier());
        log.info("feignClient called"); 
        return trustSSLSockets;
    }

   
    private SSLSocketFactory getSSLSocketFactory() {
        try {
        TrustStrategy acceptingTrustStrategy = new TrustStrategy() {
            @Override
            public boolean isTrusted(X509Certificate[] chain, String authType) throws CertificateException {

                return true;
            }
            };

            SSLContext sslContext = SSLContexts.custom().loadTrustMaterial(null, acceptingTrustStrategy).build();
            return sslContext.getSocketFactory();
        } catch (Exception exception) {
            //Do something
        }
    }

**Comment by sergeivisotsky** [comment] 2019-01-23 15:38
> Can you try setting `ribbon.IsSecure`? If that doesnt work please provide a sample that reproduces the problem

I cannot find ribbon.IsSecure property. It seems that it does not exist anymore. Is it right?

**Comment by ryanjbaxter** [comment] 2019-01-24 01:16
No it exists

**Comment by sergeivisotsky** [comment] 2019-01-24 05:45
If so, in which version of Spring Cloud? Due to in Greenwich.M1 it is not found. I have tried to add other dependencies as well "spring-cloud-starter-netflix-ribbon", "spring-cloud-netflix-ribbon", "spring-cloud-starter-ribbon" but it does not seems to be accessible.

**Comment by spencergibb** [comment] 2019-01-24 06:34
@sergeivisotsky just because the property isn't autocompleted by an ide doesn't mean it doesn't exist.

**Comment by sergeivisotsky** [comment] 2019-01-24 06:41
@spencergibb Ok thanks!

**Comment by spencergibb** [comment] 2019-01-24 06:45
Waiting for OP to provide sample.

**Comment by spring-issuemaster** [comment] 2019-01-31 06:50
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-02-07 06:49
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-02-07 06:49 UTC
Labels: feedback-reminder, waiting for feedback

**Comment by AnilChandrashekar** [comment] 2025-03-11 23:07
I'm facing same issue with Springboot 3.4.1. Feign calls are triggered as 'HTTP' though ribbon.IsSecure is set to true

Appreciate any help.

**Comment by spencergibb** [comment] 2025-03-12 00:19
ribbon is long not supported, so that property wouldn't have any effect

**Comment by spencergibb** [comment] 2025-03-12 01:40
Are you using service Discovery?

**Comment by AnilChandrashekar** [comment] 2025-03-12 14:18
Yes @spencergibb I do use Eureka Service Discovery with all my microservices registered in eureka with https.

**Comment by Bhavana2105** [comment] 2025-06-24 10:27
I am also facing the same issue, is it solved? or what is the final answer to solve this?
