### ISSUE TITLE
user feignClients, cause in fallbackFactory often is null

### ISSUE THREAD

**Issue by maoyunfei** [spring-cloud/spring-cloud-netflix#2047] opened 2017-06-15 08:06 UTC
I want to get failed reason with feign,so I use fallbackFactory to log "cause",but it is often null so that I can not get any useful message.

codes  are there.
```
@Component
public class OsApiClientFallbackFactory implements FallbackFactory<OsApiClient> {

    public static final Logger logger = LoggerFactory.getLogger(OsApiClientFallbackFactory.class);

    @Override
    public OsApiClient create(Throwable cause) {
        return new OsApiClient() {
            @Override
            public Map<String, List<OsNews>> getHomeTopNews() {
                logger.error("fail getHomeTopNews from OsApiClient,cause={}", cause);
                return Collections.emptyMap();
            }
        };
    }
}
```

**Comment by eacdy** [comment] 2017-06-15 08:33
Same problem.
This is a bug of feign. Feign 9.4.0 has fixed it.
Which version of spring-cloud-netflix are you using? 
I think you can upgrade your Spring Cloud Netflix to Dalston.RELEASE or higher.

**Comment by maoyunfei** [comment] 2017-06-15 08:53
@eacdy I hava changed version from Camden.SR6 to Dalston.RELEASE, but it still doesn't work.

**Comment by eacdy** [comment] 2017-06-15 09:47
@maoyunfei 
really? I think it's fixed. ref: <https://github.com/OpenFeign/feign/issues/464>

**Comment by maoyunfei** [comment] 2017-06-15 10:14
@eacdy 
It really doesn't work for me, hava you fix it by upgdate  version?

**Comment by maoyunfei** [comment] 2017-06-16 08:07
can anyone give me some help?

**Comment by ryanjbaxter** [comment] 2017-06-16 15:35
If you enable FINE logging do you see the cause being logged?
https://github.com/OpenFeign/feign/blob/e1ad7fc75d5abb8227e34db85d2f50034eb34c88/hystrix/README.md#considering-the-cause

**Comment by maoyunfei** [comment] 2017-06-18 07:06
@ryanjbaxter
 I mean the arg "cause" of method `public OsApiClient create(Throwable cause)`  is null ,   so your suggestion will not help me !  ╮(╯_╰)╭

**Comment by ryanjbaxter** [comment] 2017-06-19 14:50
I know enabling FINE logging wont fix the problem, but I am wondering if the cause is actually being logged or not.  If you can provide a sample that reproduces the issue we can better help you.

**Comment by spencergibb** [comment] 2017-06-19 14:55
@maoyunfei can you verify the version of feign your project is using?

**Comment by maoyunfei** [comment] 2017-06-20 02:00
@spencergibb  It's Camden.SR6.

**Comment by spencergibb** [comment] 2017-06-20 02:34
Version of open feign.

**Comment by maoyunfei** [comment] 2017-06-20 02:38
@spencergibb  version 9.3.1.

**Comment by spencergibb** [comment] 2017-06-20 02:41
Version 9.4.0 is where the fix is.

**Comment by maoyunfei** [comment] 2017-06-20 02:50
@spencergibb
 I'm sorry that I didn't describe it understandable.
I didn't specify the version of feign. The version of feign depends on the version of spring cloud.
When I use `Camden.SR6` spring cloud, the version of feign is `9.3.1 `; when I use `Dalston.RELEASE` spring cloud, the version of feign is `9.4.0`.
I tried both `Camden.SR6` and `Dalston.RELEASE`, so I can't conclude that it's problem of feign verison.

**Comment by spencergibb** [comment] 2017-06-30 23:05
If you have, we have tests that validate that the cause is not null. You'll need to provide a minimal sample that reproduces the problem.

**Comment by maoyunfei** [comment] 2017-07-31 01:51
@spencergibb 
When the hystrix command  circuitBreaker status is open , the "cause" will be  null , am I  right?

**Comment by spencergibb** [comment] 2017-08-04 19:59
That sounds about right. Did you add the property I asked about?

**Comment by spencergibb** [comment] 2018-01-18 00:29
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2018-01-18 00:29 UTC
Labels: waiting for feedback

**Comment by hemintang** [comment] 2019-01-30 01:19
Hello, I have encountered the same problem as you. Can you solve it?@maoyunfei
