### ISSUE TITLE
Request param with no value add '='

### ISSUE THREAD

**Issue by EstebanDugueperoux2** [spring-cloud/spring-cloud-netflix#3638] opened 2019-08-27 07:04 UTC
We have a cluster platform based on Spring Cloud Netflix stack.
This platform hosts some legacy soap webservices whose wsdl is accessible through ?wsdl queryparam without value.
But when requesting through Zuul gateway, this last append a '=' which make ?wsdl= but our legacy webservices doesn't recognize that.

Why Zuul does this query param change?

Best Regards.

**Comment by OlgaMaciaszek** [comment] 2019-08-27 11:53
Hello @EstebanDugueperoux2 
Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-issuemaster** [comment] 2019-09-03 11:58
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-09-10 11:58
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-09-10 11:58 UTC
Labels: feedback-reminder, waiting for feedback
