### ISSUE TITLE
BeanCreationNotAllowedException: Error creating bean with name 'eurekaClient'

### ISSUE THREAD

**Issue by aftersss** [spring-cloud/spring-cloud-netflix#3505] opened 2019-04-17 07:33 UTC
spring-cloud:Greenwich.RELEASE

Sometimes when we shutdown our spring-cloud application, the following error may occur:

```
c.n.l.PollingServerListUpdater[PollingServerListUpdater.java:119] -> Failed one update cycle
org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'eurekaClient': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:208)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:273)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1247)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory$DependencyObjectProvider.getValue(DefaultListableBeanFactory.java:1911)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory$Jsr330Factory$Jsr330Provider.get(DefaultListableBeanFactory.java:1954)
	at com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList.obtainServersViaDiscovery(DiscoveryEnabledNIWSServerList.java:158)
	at com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList.getUpdatedListOfServers(DiscoveryEnabledNIWSServerList.java:152)
	at org.springframework.cloud.netflix.ribbon.eureka.DomainExtractingServerList.getUpdatedListOfServers(DomainExtractingServerList.java:57)
	at com.netflix.loadbalancer.DynamicServerListLoadBalancer.updateListOfServers(DynamicServerListLoadBalancer.java:240)
	at com.netflix.loadbalancer.DynamicServerListLoadBalancer$1.doUpdate(DynamicServerListLoadBalancer.java:62)
	at com.netflix.loadbalancer.PollingServerListUpdater$1.run(PollingServerListUpdater.java:116)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I think it is because that the eurekaClient bean is destroyed too early.

**Comment by OlgaMaciaszek** [comment] 2019-04-17 10:44
This is a duplicate of #1064

**Closed** 2019-04-17 10:44 UTC
Labels: duplicate
