### ISSUE TITLE
Zuul ssl config with http routes 

### ISSUE THREAD

**Issue by jayhamilton** [spring-cloud/spring-cloud-netflix#2234] opened 2017-08-29 00:37 UTC
I have a Zuul configuration as below. The port 8001 is setup to be https. The appa-service and appb-service as well as Spring Boot/Zuul are running on the same server but without Eureka. I have added SimpleFilter which extends ZuulFilter. I also have an angular GUI being served from 8001 via the static folder of the Spring Boot/Zuul configuration. No Eureka and no Ribbon. The base urls established within the angular gui includes https://machine ip/8001/appa/ and https://machine ip/8001/appb/ 

Just wondering if this is a valid configuration?

spring:
  application:
    name: zuul
server:
  port: 8001
  ssl:
    enabled: true
    key-store: classpath:keystore.jks
    key-store-password: *****
    key-alias: selfsigned
    keyStoreType: JKS
zuul:
  routes:
    appa-service:
      url: http://localhost:8082
      path: /appa/**
    appb-service:
      url: http://localhost:8083
      path: /appb/**
  sensitiveHeaders: Cookie,Set-Cookie
  addProxyHeaders: false

**Comment by ryanjbaxter** [comment] 2017-08-31 00:24
I am unsure what the issue is, can you elaborate?

**Comment by jayhamilton** [comment] 2017-08-31 01:28
Hi Ryan,
After I created this question I solved one of the problems that prompted this. We had a bug in the GUI's request to the Zuul proxy. Zuul was setup for ssl but the request from the GUI was non ssl. So that issue is solved. 

I am now facing a problem with HATEOAS links coming from one of the services whith Zuul configured for ssl. The request coming into ZUUL is now HTTPS based but the service's HATEOAS links are returning HTTP and thus causes a Mixed Content error within the browser.  I found some reference to using a post filter to rewrite the HATEOAS links within the context.getResponseBody() or context.getResponseDataStream(). So far I have had no luck accessing the json response from either of these operations.

**Comment by jayhamilton** [comment] 2017-08-31 13:56
We have moved further in getting access to the response body within a post filter. It turned out that there was a pre filter impacting our ability to get access to the post filter information. With the pre-filter removed we are now able to access the post filter's response body after unzipping the content.

**Comment by ryanjbaxter** [comment] 2017-08-31 20:56
So can we close this?

**Comment by jayhamilton** [comment] 2017-08-31 22:53
Yes, please close this.

Sent from my iPhone

On Aug 31, 2017, at 4:56 PM, Ryan Baxter <notifications@github.com<mailto:notifications@github.com>> wrote:


So can we close this?

**Closed** 2017-08-31 22:55 UTC
Labels: question, waiting for feedback
