### ISSUE TITLE
Why does Zuul Proxy no longer forward to services Eureka shows as DOWN?

### ISSUE THREAD

**Issue by ewoest** [spring-cloud/spring-cloud-netflix#3548] opened 2019-06-03 20:25 UTC
My team is working to migrate from Spring Boot 1.5 to 2.1 because 1.5 will be end of life soon. We've been using a Zuul proxy with Eureka service discovery. When moving from 1.5 to 2.1 we noticed that the Zuul proxy no longer forwards requests on to services that are running but show as DOWN in Eureka. In our use case, the service reports DOWN because one of the databases it connects to is unavailable. We still want the request to go to the service, though, to process as much as it can and so that any errors are logged with that service.

I know that when you have multiple instances of a service running and one of them is down it would make sense for Zuul to ignore the DOWN service and instead forward to the UP service. In this case we may have only one service running and still want Zuul to proxy to that service.

From our observation this seems to be a behavior change from Spring Boot 1.5 to 2.1. Is there some way we can configure Zuul to still proxy to the DOWN service if it is the only instance registered with Eureka?

Also, is there any documentation you can recommend about changes in Zuul (or Eureka) from Spring Boot 1.5 to 2.1?

**Comment by spencergibb** [comment] 2019-06-03 20:32
That's not a situation we've encountered before. You'll have to describe your setup and configuration and how to reproduce it.

**Comment by spring-issuemaster** [comment] 2019-06-10 20:36
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-06-17 20:36
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-06-17 20:36 UTC
Labels: feedback-reminder, waiting for feedback

**Comment by ewoest** [comment] 2019-06-28 15:50
Thank you @spencergibb  for your quick response. 

We have a system of multiple microservices that communicate together using Eureka. We then have a Zuul proxy running as the entry point for external requests. The Zuul proxy will get the list of available services from Eureka for it's routes.

We've found that a service will most often report DOWN if it is not able to connect to a database or if the database driver does not have a valid health check. It seems some types of database connections will not allow the service to start up if the username is incorrect. Other types of database connections will allow the service to start and will simply show as DOWN in Eureka. You may know more about this support than I do.

To reproduce this you will need a Eureka server, an app with Eureka client that will show as DOWN, and a Zuul proxy. Start up each service and note that the app shows on the Eureka server but shows as DOWN. Then attempt to make a request to it through the Zuul proxy by using the service name. You should see Zuul report that no instances were found for that service name.

**Comment by spencergibb** [comment] 2019-06-28 21:29
Can you show your zuul configuration?

**Comment by ewoest** [comment] 2019-07-02 15:42
Here are the parts of our properties file that pertain to Eureka, Zuul, Histrix, or Ribbon:

```
eureka.client.serviceUrl.defaultZone=[URL]
eureka.instance.nonSecurePortEnabled=false
eureka.instance.securePort=[PORT]
eureka.instance.securePortEnabled=true

hystrix.command.default.execution.timeout.enabled=false

zuul.ribbon.okhttp.enabled=true
zuul.okhttp.enabled=true

ribbon.ConnectTimeout: 4000
ribbon.MaxAutoRetries: 1
ribbon.MaxAutoRetriesNextServer: 2
ribbon.OkToRetryOnAllOperations: true
ribbon.ReadTimeout: 60000
ribbon.isSecured: true

server.port=[PORT]

zuul.retryable: true
zuul.sensitiveHeaders: NoSenstiveHeaders
zuul.sslHostnameValidationEnabled: false
```
