### ISSUE TITLE
No such host is known (swagger-service)

### ISSUE THREAD

**Issue by otaku0304** [spring-cloud/spring-cloud-netflix#4276] opened 2024-04-06 04:35 UTC
Hello, 

I'm encountering an issue with  microservices architecture. Specifically, when I attempt to access the microservices using with the application names, I receive an error stating "No such host is known". This problem arises even though I have set up an Eureka Discovery Server along with three Eureka client servers. As I am new to microservices, this is my first project, and I would greatly appreciate any guidance or assistance you can provide. Thank you for your understanding.

SpringBoot versions and Spring cloud versions for all micro services
SpringBoot version = 3.2.4
Spring Cloud version = 2023.0.0
java Version = 21
Eureka localhost dashboard running at 8761

![image](https://github.com/spring-cloud/spring-cloud-commons/assets/107242846/324688e9-c652-40fa-8251-994c5dbf364f)

Application names and port numbers were defined separately in each yml files as swag-service, swagger-service, swaggest-service. 
so below is the swag yml file that show the application name

![image](https://github.com/spring-cloud/spring-cloud-commons/assets/107242846/f044ea50-7a68-4f3e-9656-2da8b5a437b1)

swagger yml file 

![image](https://github.com/spring-cloud/spring-cloud-commons/assets/107242846/946b72b5-d764-4263-9ef4-4625d0e068f1)

Port numbers for microservices  8081, 8082, 8083 below is the swag yml file and running in the port 8081

![image](https://github.com/spring-cloud/spring-cloud-commons/assets/107242846/41c04d38-7f84-49bc-8443-c43358fb68c1)

When I changed the hostname and port numbers to include the application name, I encountered an error. However, the application is working fine when I used localhost and port numbers.

![image](https://github.com/spring-cloud/spring-cloud-commons/assets/107242846/b8b4e7ae-4b17-4d30-b64b-979e1047682d)

swagApplication

![image](https://github.com/spring-cloud/spring-cloud-commons/assets/107242846/3b967042-f873-46a1-b552-5cd95dd24588)

SwaggerApplication

![image](https://github.com/spring-cloud/spring-cloud-commons/assets/107242846/360a5b0e-1461-4a5a-a72e-690ce8dbc984)

swag controller with swag endpoint (/swag) calling save-swagger endpoint 

![image](https://github.com/spring-cloud/spring-cloud-commons/assets/107242846/9b6a0f32-d717-4a15-b0fc-b74acb05fad2)

swagService 

![image](https://github.com/spring-cloud/spring-cloud-commons/assets/107242846/0437c052-8aa8-47d6-9a37-06844d71e185)

swaggerController with (/swagger) hitting save end point 

![image](https://github.com/spring-cloud/spring-cloud-commons/assets/107242846/4f3fc61f-b2c4-404c-8dd7-e649bcfeef70)

swaggerService 

![image](https://github.com/spring-cloud/spring-cloud-commons/assets/107242846/6f87e5dc-c5ba-4bde-ac25-af8c7c9183aa)

When i make an request from swag endpoint to save swagger I was getting the hostName error with 500 internal error

![image](https://github.com/spring-cloud/spring-cloud-commons/assets/107242846/de73299a-25a2-4eac-9098-b1d957543e80)

error 

![image](https://github.com/spring-cloud/spring-cloud-commons/assets/107242846/951d82fd-a237-4854-b6f4-4a90ec263647)

![image](https://github.com/spring-cloud/spring-cloud-commons/assets/107242846/41dfafe0-5319-4688-8f3f-9129721cae11)

**Comment by otaku0304** [comment] 2024-04-13 06:25
Hi @OlgaMaciaszek [https://github.com/otaku0304/Swag-Micro-Services](url) [https://github.com/otaku0304/config-repo](url) please clone the repos from this link and run the applications, 

Once after applications are running send the request to the below url by using the postman and pass the requestBody as a json body, you will get the error.

url: http://localhost:8081/swag/save-swaggest

{
    "swaggestContent": "Elon Musk1",
    "user": "sai"
}

error: {
    "responseCode": 400,
    "token": null,
    "responseMessage": "I/O error on POST request for \"http://swaggest-service/swaggest/save\": No such host is known (swaggest-service)",
    "responseBody": null
}

**Comment by OlgaMaciaszek** [comment] 2024-04-15 13:39
@otaku0304 thanks, but please provide a **minimal** sample, with only as many services doing only as mush as absolutely necessary to reproduce the issue (this provided sample runs a lot of stuff unrelated to Spring Cloud Netflix, including a MongoDB).

**Comment by spring-cloud-issues** [comment] 2024-04-22 13:39
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2024-04-29 13:39
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2024-04-29 13:39 UTC
Labels: feedback-reminder
