### ISSUE TITLE
Wrong IP for config Server shared by Erureka

### ISSUE THREAD

**Issue by RodrigoAditazz** [spring-cloud/spring-cloud-netflix#2410] opened 2017-10-31 17:02 UTC
Hello Guys,

We are facing a problem where at some point the config servers are being restarted (which is OK) with new IPs. Then, when any other service is restarted, for some reason they are trying to connect with the old IPs of the config server, throwing:

`Caused by: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://10.19.11.8:8888/my-service/default/development": No route to host (Host unreachable); nested exception is java.net.NoRouteToHostException: No route to host (Host unreachable)`

We follow a **Discovery first** strategy, where the location of the config server is shared by eureka. 
Maybe eureka is caching? ungraceful shutdown of config server?

If you have ever faced this issue, I would really appreciate any guidance you can provide to overcome this problem

Thanks

**Comment by spencergibb** [comment] 2017-10-31 17:20
Is this a duplicate of https://github.com/spring-cloud/spring-cloud-config/issues/514

**Comment by spencergibb** [comment] 2018-01-18 00:44
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2018-01-18 00:44 UTC
Labels: waiting for feedback
