### ISSUE TITLE
client get the congfig update message occur exception:java.util.concurrent.RejectedExecutionException:

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#2985] opened 2018-05-31 15:22 UTC
https://github.com/spring-cloud/spring-cloud-bus/issues/94

**Comment by ryanjbaxter** [comment] 2018-05-31 18:20
Duplicate of #2228

**Closed by ryanjbaxter** 2018-05-31 18:20 UTC

**Comment by tdanylchuk** [comment] 2018-05-31 18:22
i guess, same root cause as in https://github.com/spring-cloud/spring-cloud-netflix/issues/2972

**Comment by ryanjbaxter** [comment] 2018-05-31 19:53
Doesnt seem like it based on the description in the issue.

**Comment by tdanylchuk** [comment] 2018-05-31 19:56
it's not, but root cause same - it tries to `updateOnDemand()` on already shutdown client instead of new one, which were re-created  after bus context refresh event

**Comment by ryanjbaxter** [comment] 2018-05-31 20:03
If the root cause is the same than you shouldnt see it in Edgware.SR3
https://github.com/spring-cloud/spring-cloud-netflix/issues/2792

**Comment by tdanylchuk** [comment] 2018-05-31 20:07
That commit fixes only throw of the exception, since it tries to add event to already shut down scheduler.
If we get newly created eureka client, which has running scheduler, this exception should not happen.
