### ISSUE TITLE
SimpleHostRoutingFilter cannot handle multipart upload due to content type containing ";"

### ISSUE THREAD

**Issue by markodinic** [spring-cloud/spring-cloud-netflix#1671] opened 2017-02-06 15:08 UTC
Content type is not handled correctly in SimpleHostRoutingFilter. The issue has been resolved in #1649 for charset only, but content type may contain multiple entries delimited with `;`, for example, for multipart upload: `Content-Type:multipart/form-data; boundary=----WebKitFormBoundaryGO5S2JaD1gVbOxBb`.

**Comment by spencergibb** [comment] 2017-02-06 15:30
Closed, duplicate of #1663

**Closed by spencergibb** 2017-02-06 15:30 UTC
