### ISSUE TITLE
Zuul becomes non-responsive after moderate use

### ISSUE THREAD

**Issue by DaveBender** [spring-cloud/spring-cloud-netflix#1997] opened 2017-05-30 23:10 UTC
We're having trouble getting Zuul to run for any length of time before it becomes non-responsive.  Requests just hang, eventually timing out.   This behavior corresponds to a high number of sockets left in a CLOSE_WAIT state, but we're not clear on how to determine why the sockets are being created and not eventually cleaned up, even if traffic dies down overnight.  

We're running `org.springframework.cloud:spring-cloud-starter-parent:Camden.SR7`, which we understand has a fix for a socket leak. 

Do you have suggestions or ideas for how we can debug this?

**Comment by aivans** [comment] 2017-05-31 06:52
I think there a few issues open related to this.

**Comment by DaveBender** [comment] 2017-05-31 15:27
https://github.com/spring-cloud/spring-cloud-netflix/issues/1979

**Comment by ryanjbaxter** [comment] 2017-05-31 18:29
Im going to close this as a duplicate of the open issues above.  Please add any additional information you may have to those issues.

**Closed by ryanjbaxter** 2017-05-31 18:29 UTC
Labels: duplicate

**Comment by DaveBender** [comment] 2017-05-31 18:34
Do you have any suggestions on how we can debug this?

**Comment by ryanjbaxter** [comment] 2017-05-31 20:39
Not at the moment, it is on my list to look at though so follow the other issues for updates.

**Comment by ryanjbaxter** [comment] 2017-06-05 18:44
@DaveBender can you take a look at the PR in #1970?  Perhaps you can try it out and let us know if it works for you.

**Comment by DaveBender** [comment] 2017-06-06 16:54
I looked, but I'm not understanding what the change would be for us.  Or maybe I'm not looking at the right thing.  We're seeing the problem in Camden.SR7.  If I follow this fix correctly, it [reverts a change ](https://github.com/ryanjbaxter/spring-cloud-netflix/commit/bcb65b07bf076f0d5128caec83441ad929fd40ca)that was made a couple minutes [earlier](https://github.com/ryanjbaxter/spring-cloud-netflix/commit/7d06c140fa319f7bbdbc14ae77c4f7b9647a7bb3).    

What should I be looking at to evaluate this change?

**Comment by ryanjbaxter** [comment] 2017-06-06 18:20
@DaveBender this is the PR I am referring to.  I reverted some changes in the `1.3.x.` branch in my fork, the changes you want to try are in the branch named `response-code-retry-close-wait`.
