### ISSUE TITLE
nested exception is feign.RetryableException: Connection refused executing GET

### ISSUE THREAD

**Issue by Dreampie** [spring-cloud/spring-cloud-netflix#730] opened 2015-12-17 04:17 UTC
docker run -d -p xx:xx -v /var/log --name user-xx-provider 192.168.60.41:5000/user-xx-provider:1.0-SNAPSHOT.1

api use docker continer ip not host ip.
![image](https://cloud.githubusercontent.com/assets/3667080/11864563/a3464ce2-a4d8-11e5-9ef6-88811c67cc46.png)
![image](https://cloud.githubusercontent.com/assets/3667080/11865868/e953d6b0-a4e1-11e5-8813-51ab9e02b325.png)

192.168.60.41  service：  172.17.0.2:user-service-provider:9001， 172.17.0.3:user-api-provider:10001
192.168.60.43  service：  172.17.0.7:user-service-provider:9001， 172.17.0.8:user-api-provider:10001

in eureka，I think when  172.17.0.3:user-api-provider:10001 connection 172.17.0.7:user-service-provider:9001  refused, also when 172.17.0.8:user-api-provider:10001 connection 172.17.0.2:user-service-provider:9001 refused

every single api provider is ok,like:
192.168.60.41:9001/users is ok.
192.168.60.43:9001/users is ok.
...

```
2015-12-17 04:11:56.473 ERROR 1 --- [  XNIO-2 task-4] io.undertow.request                      : UT005023: Exception handling request to /users

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is feign.RetryableException: Connection refused executing GET http://user-service-provider/users
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:130)
	at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:291)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132)
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:102)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132)
	at org.springframework.boot.actuate.autoconfigure.MetricFilterAutoConfiguration$MetricsFilter.doFilterInternal(MetricFilterAutoConfiguration.java:90)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:85)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:61)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:56)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:45)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:63)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:70)
	at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:261)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:247)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:76)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:166)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:197)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:765)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: feign.RetryableException: Connection refused executing GET http://user-service-provider/users
	at feign.FeignException.errorExecuting(FeignException.java:56)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:97)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:71)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:94)
	at com.sun.proxy.$Proxy92.findAll(Unknown Source)
	at cn.dreampie.api.user.controller.UserController.findAll(UserController.java:23)
	at sun.reflect.GeneratedMethodAccessor88.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
	... 48 common frames omitted
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at feign.Client$Default.convertResponse(Client.java:143)
	at feign.Client$Default.execute(Client.java:70)
	at feign.ribbon.LBClient.execute(LBClient.java:69)
	at feign.ribbon.LBClient.execute(LBClient.java:38)
	at com.netflix.client.AbstractLoadBalancerAwareClient$1.call(AbstractLoadBalancerAwareClient.java:109)
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1.call(LoadBalancerCommand.java:303)
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1.call(LoadBalancerCommand.java:287)
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
	at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:41)
	at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:30)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable.unsafeSubscribe(Observable.java:7466)
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.subscribeNext(OperatorConcat.java:176)
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.onNext(OperatorConcat.java:141)
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.onNext(OperatorConcat.java:78)
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:185)
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:180)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable.subscribe(Observable.java:7556)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:442)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:341)
	at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:102)
	at feign.ribbon.RibbonClient.execute(RibbonClient.java:69)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:92)
	... 64 common frames omitted

```

**Comment by spencergibb** [comment] 2016-01-21 22:46
Closing as the error message in the stack trace is the same as #769

**Closed by spencergibb** 2016-01-21 22:46 UTC

**Comment by sharmarohit707** [comment] 2017-01-14 04:39
The issue is still happening. Please post the solution.

**Comment by spencergibb** [comment] 2017-01-14 04:45
@sharmarohit707 this was closed as a duplicate, which itself was closed due to lack of feedback. If you can provide a sample that reproduces the problem, please open a new issue.

**Comment by sharmarohit707** [comment] 2017-01-14 23:19
Thanks for the Quick Reply. I have mention my changes in a new thread:

https://github.com/spring-cloud/spring-cloud-netflix/issues/1620

#1620

**Comment by shenqianfan** [comment] 2017-12-02 10:01
how do you solve it, I hava this problem too

**Comment by mrh-jishan** [comment] 2019-03-07 08:18
I am using docker, and having the same issue. did anybody solve this problem?

**Comment by ryanjbaxter** [comment] 2019-03-07 21:37
@mrh-jishan please open a new issue with a sample that reproduces the problem

**Comment by xjx3316** [comment] 2019-03-13 05:43
I also encountered this problem, solved a week's time to find the reason,  I was too careless,.hope to get the call path is a URL with an IP address, such as http://172.12.0.12/customer/getCustomerByPhone, but it became a service name, IP partError as a result of such http://customer-servie/customer/getCustomerByPhone, as long as in the application. The properties of the configuration file with three lines of configuration can be started when the first configuration is registered eureka server IP registration, the second configuration is exposed to the IP, port, the final configuration is to host names into IP addresses：

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.cloud.client.ip-address}:${server.port}
eureka.instance.hostname=${spring.cloud.client.ip-address}

**Comment by xjx3316** [comment] 2019-03-13 05:45
> 
> 
> how do you solve it, I hava this problem too

I've printed the method below

**Comment by mrh-jishan** [comment] 2019-05-15 08:37
Sorry for the late response. I just had to use the IP address of the laptop instead of localhost or 172.0.0.1 as eureka ip.

**Comment by gunjanvishwakarma** [comment] 2019-06-05 06:22
try disabling network card of your laptop/computer if all the service running in same machine.

**Comment by MohanEruvaram** [comment] 2019-09-25 14:32
For me it got resolved by adding the image in docker container that is the time when i have faced this issue

**Comment by UbaidurRehman1** [comment] 2019-10-05 09:56
> I also encountered this problem, solved a week's time to find the reason, I was too careless,.hope to get the call path is a URL with an IP address, such as http://172.12.0.12/customer/getCustomerByPhone, but it became a service name, IP partError as a result of such http://customer-servie/customer/getCustomerByPhone, as long as in the application. The properties of the configuration file with three lines of configuration can be started when the first configuration is registered eureka server IP registration, the second configuration is exposed to the IP, port, the final configuration is to host names into IP addresses：
> 
> eureka.instance.prefer-ip-address=true
> eureka.instance.instance-id=${spring.cloud.client.ip-address}:${server.port}
> eureka.instance.hostname=${spring.cloud.client.ip-address}

Thank you so much, I have been spent 5 days to solve this issue :( and after I found this one, and I less than 1 minute I resolve this issue

**Comment by metayx** [comment] 2019-11-25 06:48
> I also encountered this problem, solved a week's time to find the reason, I was too careless,.hope to get the call path is a URL with an IP address, such as http://172.12.0.12/customer/getCustomerByPhone, but it became a service name, IP partError as a result of such http://customer-servie/customer/getCustomerByPhone, as long as in the application. The properties of the configuration file with three lines of configuration can be started when the first configuration is registered eureka server IP registration, the second configuration is exposed to the IP, port, the final configuration is to host names into IP addresses：
> 
> eureka.instance.prefer-ip-address=true
> eureka.instance.instance-id=${spring.cloud.client.ip-address}:${server.port}
> eureka.instance.hostname=${spring.cloud.client.ip-address}

sixsixsix
