### ISSUE TITLE
Eureka default zone setting is not picked up in properties not work

### ISSUE THREAD

**Issue by becerriljc** [spring-cloud/spring-cloud-netflix#3186] opened 2018-09-11 18:51 UTC
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8200/eureka/

defaultZone Not work!

**Comment by spencergibb** [comment] 2018-09-11 18:53
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

"Not work!" is not helpful. From our issue template
> Please provide details of the problem, including the version of Spring Cloud that you
are using. If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

**Comment by bhargodevarya** [comment] 2018-09-16 19:37
I this it is registerWithEureka, fetchRegistry and serviceUrl

**Comment by ryanjbaxter** [comment] 2018-09-17 17:52
Again please describe what is not working and include a sample to reproduce the problem.

**Comment by spencergibb** [comment] 2019-02-11 15:36
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2019-02-11 15:36 UTC
Labels: feedback-provided
