### ISSUE TITLE
RestTemplate postForEntity with JSON body causes Not implemented exception

### ISSUE THREAD

**Issue by nielssj** [spring-cloud/spring-cloud-netflix#410] opened 2015-06-23 13:11 UTC
I'm using `spring-web-4.1.6` and `spring-cloud-netflix-core-1.0.1`. When performing the following POST request:
```Java
return restTemplate.postForObject(BASE_URL + "/save", tenantUser, TenantUser.class, tenantId);
```
I get the following RuntimeException:
```
java.lang.RuntimeException: Not implemented
	at org.springframework.cloud.netflix.ribbon.RibbonClientHttpRequestFactory$RibbonHttpRequest.getBodyInternal(RibbonClientHttpRequestFactory.java:105)
	at org.springframework.http.client.AbstractClientHttpRequest.getBody(AbstractClientHttpRequest.java:47)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:217)
	at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:208)
	at org.springframework.web.client.RestTemplate$HttpEntityRequestCallback.doWithRequest(RestTemplate.java:774)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:567)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:530)
	at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:330)
```

**Comment by spencergibb** [comment] 2015-06-23 14:04
Closing as duplicate of #350.  Waiting for release.

**Closed by spencergibb** 2015-06-23 14:04 UTC
Labels: duplicate
