### ISSUE TITLE
Support for URI template regex in Feign client 

### ISSUE THREAD

**Issue by Infrag** [spring-cloud/spring-cloud-netflix#1006] opened 2016-05-05 18:05 UTC
When I try to use REST endpoint with uri template regex in my @FeignClient i.e:
```
	@RequestMapping(value = "/{login:[_'.@a-z0-9-]+}",
		method = RequestMethod.GET,
		produces = MediaType.APPLICATION_JSON_VALUE)
	public ResponseEntity<ManagedUserDTO> getUser(@PathVariable("login") String login);
```
Exception is thrown:
```
java.lang.IllegalArgumentException: Illegal character in path at index 25: http://gateway/api/users/{login:[_'.@a-z0-9-]%20}
	at java.net.URI.create(URI.java:852)
	at org.springframework.cloud.netflix.feign.ribbon.LoadBalancerFeignClient.execute(LoadBalancerFeignClient.java:56)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:95)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:74)
	at feign.hystrix.HystrixInvocationHandler$1.run(HystrixInvocationHandler.java:80)
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:293)
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:288)

```
http://docs.spring.io/autorepo/docs/spring/4.2.x/spring-framework-reference/html/mvc.html#mvc-ann-requestmapping-uri-templates-regex

**Comment by venilnoronha** [comment] 2016-05-05 22:41
Duplicate of #816? I'm planning a PR, any suggestions  where to begin?

**Comment by spencergibb** [comment] 2016-05-05 22:48
Duplicate of #816

**Closed by spencergibb** 2016-05-05 22:48 UTC
Labels: enhancement, help wanted
