### ISSUE TITLE
ribbon ensure liveness of servers

### ISSUE THREAD

**Issue by panqingcui** [spring-cloud/spring-cloud-netflix#1566] opened 2016-12-21 02:12 UTC
HI ,when ribbon is selected from multiple servers, it often chooses unavailable services. How can you ensure server availability?

**Comment by ryanjbaxter** [comment] 2016-12-21 17:02
If you are not using Eureka, you probably want to look into using the `IPing` functionality in [Ribbon](https://github.com/Netflix/ribbon/wiki/Working-with-load-balancers#components-of-load-balancer).  You can customize the ping interfaced using in Spring Cloud Netflix Ribbon in your [Ribbon configuration](http://cloud.spring.io/spring-cloud-netflix/spring-cloud-netflix.html#_customizing_the_ribbon_client_using_properties).

**Comment by panqingcui** [comment] 2016-12-22 02:18
I has been used Eureka , also uses the IPing, but now ,it often chooses unavailable server.

**Comment by ryanjbaxter** [comment] 2016-12-24 01:38
Can you provide an app that reproduces the problem?

**Comment by spring-issuemaster** [comment] 2018-10-02 17:01
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.

**Closed by spring-issuemaster** 2018-10-02 17:01 UTC
Labels: question
