### ISSUE TITLE
Zuul changing request when receiving a multipart form with single quotes values

### ISSUE THREAD

**Issue by rafaelfcsouza** [spring-cloud/spring-cloud-netflix#2214] opened 2017-08-19 00:18 UTC
When receiving a POST with data like:

```
Content-Disposition: form-data; name='image'; filename='picture.jpg'
Content-Type: image/jpeg
```

Zuul changes the Request to:

```
Content-Disposition: form-data; name="'image'"; filename="'picture.jpg'"
Content-Type: image/jpeg
```

**Comment by ryanjbaxter** [comment] 2017-08-21 15:45
From what I read about the `Content-Disposition` header, it is valid to use double quotes in the header.

https://tools.ietf.org/html/rfc6266

Shouldnt your header include the double quotes instead of single quotes?

**Comment by rafaelsouza-picpay** [comment] 2017-08-21 15:51
Yes, but it's not my app =(

**Comment by ryanjbaxter** [comment] 2017-08-21 16:12
If the problem is even in Spring Cloud Netflix (and not Zuul) itself, I personally am not in favor of changing the behavior because one app is not quoting the headers correctly.  If I am wrong, and single quotes are valid than we can look at it (or open an issue with Zuul).

**Comment by rafaelsouza-picpay** [comment] 2017-08-21 16:19
Actually my question is, should zuul change the request and add the double quotes? Even if it's wrong, should it change the request?

**Comment by spencergibb** [comment] 2017-08-21 16:23
We need to narrow down exactly where it's happening.

**Comment by ryanjbaxter** [comment] 2017-08-22 00:16
@rafaelsouza-picpay I am not able to reproduce this issue.  Can you perhaps provide a sample app?

**Comment by spencergibb** [comment] 2018-01-18 00:31
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2018-01-18 00:31 UTC
Labels: waiting for feedback
