### ISSUE TITLE
spring-cloud-netflix-turbine-stream can not work with spring-boot-starter-actuator

### ISSUE THREAD

**Issue by FlyRabit** [spring-cloud/spring-cloud-netflix#3546] opened 2019-05-31 01:23 UTC
Question
spring boot version:2.1.3.RELEASE
spring cloud version: Greenwich.SR1
when I add dependency spring-boot-starter-actuator , the turbine stream can't work but just output "{data: ping}" when open the stream in browser. if the dependency removed from pom file,it works fine.

below is my pom file
```xml
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-boot-starter-netflix-turbine-stream</artifactId>
            <exclusions>
            	<exclusion>
            		<groupId>org.springframework.cloud</groupId>
            		<artifactId>spring-boot-starter-netflix-eureka-client</artifactId>
            	</exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-boot-starter-stream-rabbit</artifactId>
        </dependency>
        <dependency>
        	<groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.7</version>
        </dependency>
    </dependencies>
```
my application.properties just config the spring.rabbitmq.*

**Comment by ryanjbaxter** [comment] 2019-06-03 20:14
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment] 2019-06-10 20:16
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-06-17 20:16
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-06-17 20:16 UTC
Labels: feedback-reminder, waiting for feedback
