### ISSUE TITLE
spring-cloud-starter-netflix-eureka-client 4.0.2 vs. 4.0.1 breaking change?

### ISSUE THREAD

**Issue by SledgeHammer01** [spring-cloud/spring-cloud-netflix#4178] opened 2023-06-04 03:52 UTC
I have a Spring Boot 3.1.x project that uses Hazelcast for distributed caching. Hazelcast is set up to use Eureka discovery. This is done using Hazelcast-eureka (https://github.com/hazelcast/hazelcast-eureka). Unfortunately, that project was seemingly abandoned :(. 

I was able to pull to pull down the code for Hazelcast-eureka and "semi upgrade" it to Java 17 and the necessary dependencies and got it working with spring-cloud-starter-netflix-eureka-client 4.0.1.

If I upgrade spring-cloud-starter-netflix-eureka-client to 4.0.2, it no longer works and I get:

**Field optionalArgs in org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration$RefreshableEurekaClientConfiguration required a bean of type 'com.netflix.discovery.AbstractDiscoveryClientOptionalArgs' that could not be found.**

When running 4.0.1, this is seemingly a RestTemplateDiscoveryClientOptionalArgs bean which doesn't seem to get created in 4.0.2.

Any theory on what might have changed?

**Comment by SledgeHammer01** [comment] 2023-06-04 05:25
After many hours of debugging, I think I found what the issue is... seems like in 4.0.2 you might have switched to a new transport? One that doesn't understand urls of the format:

https://username:password@eureka01.xxxsoftware.com:8761/eureka/

In 4.0.2, I end up getting a 401 when it tries to connect to the Eureka server.

If I create a bean of type RestTemplateTransportClientFactories(), then it gets a 200.

**Comment by rjunqueira** [comment] 2023-06-05 10:45
same here

**Comment by rjunqueira** [comment] 2023-06-05 10:46
Plus this one ...

https://spring.io/blog/2023/05/25/spring-cloud-2022-0-3-aka-kilburn-is-available

"There is a known defect in Spring Cloud Config related to locating the config server via service discovery. In order to activate this feature in this release you will need to set spring.cloud.config.discovery.enabled=true and spring.cloud.config.discovery.serviceId in an environment variable or as a system property. This bug will be addressed in the next release."

**Comment by OlgaMaciaszek** [comment] 2023-11-09 18:13
@SledgeHammer01 @rjunqueira 
Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-cloud-issues** [comment] 2023-11-16 18:14
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2023-11-23 18:14
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2023-11-23 18:14 UTC
Labels: waiting for feedback, feedback-reminder
