### ISSUE TITLE
Error creating bean with name 'eurekaApplicationInfoManager'

### ISSUE THREAD

**Issue by mayex-rony** [spring-cloud/spring-cloud-netflix#4112] opened 2022-08-03 20:22 UTC
Iam use grpc + spring cloud +eureka ,but eureka client has this error,how can i do?

status=Status{code=UNAVAILABLE, description=Failed to update server list for bh-server, cause=org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'scopedTarget.eurekaClient' defined in class path resource [org/springframework/cloud/netflix/eureka/EurekaClientAutoConfiguration$RefreshableEurekaClientConfiguration.class]: Unsatisfied dependency expressed through method 'eurekaClient' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'eurekaApplicationInfoManager': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
--
Thu, Aug 4 2022 4:07:57 am | at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
Thu, Aug 4 2022 4:07:57 am | at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541)
Thu, Aug 4 2022 4:07:57 am | at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
Thu, Aug 4 2022 4:07:57 am | at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
Thu, Aug 4 2022 4:07:57 am | at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
Thu, Aug 4 2022 4:07:57 am | at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
Thu, Aug 4 2022 4:07:57 am | at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$1(AbstractBeanFactory.java:374)
Thu, Aug 4 2022 4:07:57 am | at org.springframework.cloud.context.scope.GenericScope$BeanLifecycleWrapper.getBean(GenericScope.java:376)
Thu, Aug 4 2022 4:07:57 am | at org.springframework.cloud.context.scope.GenericScope.get(GenericScope.java:179)
Thu, Aug 4 2022 4:07:57 am | at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:371)
Thu, Aug 4 2022 4:07:57 am | at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
Thu, Aug 4 2022 4:07:57 am | at org.springframework.aop.target.SimpleBeanTargetSource.getTarget(SimpleBeanTargetSource.java:35)
Thu, Aug 4 2022 4:07:57 am | at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:195)
Thu, Aug 4 2022 4:07:57 am | at com.sun.proxy.$Proxy102.getInstancesByVipAddress(Unknown Source)
Thu, Aug 4 2022 4:07:57 am | at org.springframework.cloud.netflix.eureka.EurekaDiscoveryClient.getInstances(EurekaDiscoveryClient.java:62)
Thu, Aug 4 2022 4:07:57 am | at org.springframework.cloud.client.discovery.composite.CompositeDiscoveryClient.getInstances(CompositeDiscoveryClient.java:53)
Thu, Aug 4 2022 4:07:57 am | at ph.coins.framework.grpcclient.nameresolver.DiscoveryClientNameResolver$Resolve.resolveInternal(DiscoveryClientNameResolver.java:184)
Thu, Aug 4 2022 4:07:57 am | at ph.coins.framework.grpcclient.nameresolver.DiscoveryClientNameResolver$Resolve.run(DiscoveryClientNameResolver.java:159)
Thu, Aug 4 2022 4:07:57 am | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Thu, Aug 4 2022 4:07:57 am | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Thu, Aug 4 2022 4:07:57 am | at java.base/java.lang.Thread.run(Thread.java:829)
Thu, Aug 4 2022 4:07:57 am | Caused by: org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'eurekaApplicationInfoManager': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
Thu, Aug 4 2022 4:07:57 am | at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:220)
Thu, Aug 4 2022 4:07:57 am | at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
Thu, Aug 4 2022 4:07:57 am | at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
Thu, Aug 4 2022 4:07:57 am | at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
Thu, Aug 4 2022 4:07:57 am | at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
Thu, Aug 4 2022 4:07:57 am | at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
Thu, Aug 4 2022 4:07:57 am | at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
Thu, Aug 4 2022 4:07:57 am | at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
Thu, Aug 4 2022 4:07:57 am | ... 20 more
Thu, Aug 4 2022 4:07:57 am | }

**Comment by OlgaMaciaszek** [comment] 2022-09-01 11:43
@mayex-rony  Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by OlgaMaciaszek** [comment] 2022-09-01 11:43
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

**Comment by spring-cloud-issues** [comment] 2022-09-08 11:47
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2022-09-15 11:47
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2022-09-15 11:47 UTC
Labels: waiting for feedback, feedback-reminder
