### ISSUE TITLE
Ribbon error (e.g. downstream 404 or timeout) in Zuul proxy bypasses normal Spring Boot error handling

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-netflix#868] opened 2016-03-02 12:27 UTC
The response is probably being manipulated directly somewhere, so the tomcat error page shows up (HTML) instead of the normal Spring Boot one (JSON).

**Comment by dsyer** [comment] 2016-03-03 10:42
I can't reproduce this now. Leaving it open in case it pops back again.

**Comment by leofromgroza** [comment] 2016-03-30 15:30
I've reproduced bug using Spring Cloud Brixton.RC1 + Spring Boot 1.3.3.REALASE + Spring Security. Here is an example: 
STR: 
- Just clone project https://github.com/leofromgroza/zuul-server
- Start Spring Boot Application.  
- Open URL http://localhost:8765/dummy/ (credentials -> user:password) and you will see standard Tomcat error page. 

Turn Spring Security off:
- Comment Spring Security dependency in pom.xml file 
- Comment security configuration in application.yml. 

Restart app and open URL http://localhost:8765/dummy/  - you will see custom error page.

I debugged program and found that if Spring Security is turned on - app wraps `javax.servlet.AsyncContext` into `org.springframework.security.web.servletapi.HttpServlet3RequestFactory$SecurityContextAsyncContext` and Tomcat does not commit Response in method [org.apache.catalina.core.ApplicationDispatcher](https://svn.apache.org/repos/asf/tomcat/tc8.0.x/tags/TOMCAT_8_0_32/java/org/apache/catalina/core/ApplicationDispatcher.java)#doForward because of check in line 394.

**Comment by dsyer** [comment] 2016-04-01 10:18
Thanks for the sample app. I raised a ticket in Spring Security for that specific problem (which only seems to show up when you have a custom error handler as you do): https://github.com/spring-projects/spring-security/issues/3780.

I also noticed while investigating this that if there is an error rendering the custom error page you get the same effect.

**Comment by rwinch** [comment] 2016-04-01 15:08
@leofromgroza Thanks for the detailed walk through! This appears to be a bug in Tomcat. However, the workaround was simple so I pushed a fix to master. Please see https://github.com/spring-projects/spring-security/issues/3780#issuecomment-204427591 for additional details (including a link to the bug report I filed with Tomcat).

**Comment by leofromgroza** [comment] 2016-04-02 06:34
@dsyer @rwinch Thank you guys for so fast reaction. You are really cool! I felt the real power of open source;) Thank you!

**Comment by spencergibb** [comment] 2016-05-09 15:41
@dsyer are we still tracking this here or can we close it?

**Closed** 2016-05-09 17:20 UTC
Labels: bug, icebox
