### ISSUE TITLE
getURI() in EurekaServiceInstance misses custom contextPath.

### ISSUE THREAD

**Issue by thomasdarimont** [spring-cloud/spring-cloud-netflix#737] opened 2015-12-18 23:30 UTC
I have several Spring Boot Apps with REST endpoints with custom `server.contextPath`'s
which use `@EnableDiscoveryClient` to register themselves in the eureka service registry.

The applications are registered with eureka at startup and later queried
by a management application. I just found out that the `URI`s returned by

```
org.springframework.cloud.netflix.eureka.EurekaDiscoveryClient.EurekaServiceInstance.getUri()
```

only contain scheme,hostname and port but no custom context-path. 

The `URI`s were returned by `discoveryClient.getInstances(serviceId)` where 
`discoveryClient` is an `EurekaDiscoveryClient`.

The URI one gets via 

``` java
public URI getUri() {
  return DefaultServiceInstance.getUri(this);
}
```

 looks like:

```
http://localhost:8761
```

The proper URI would be:

```
http://localhost:8761/mycontextpath/
```

I fixed tested this by locally shadowing the `org.springframework.cloud.netflix.eureka.EurekaDiscoveryClient` and replacing the body of the `URI getUri()` method with:

``` java
@Override
public URI getUri() {

  //HACK to get proper URI with context-path back
  //return DefaultServiceInstance.getUri(this);
  return URI.create(this.instance.getHomePageUrl());
}
```

With that adjustment the `org.springframework.cloud.client.ServiceInstance` that I got back
returned the proper service `URI`s.

I think the op of the issue #500 has the same problem.

Another Problem was that I needed to explicitly declare a 

``` java
@Bean
public EurekaInstanceConfig eurekaConfigBean() {
  return new EurekaInstanceConfigBean();
}
```

in order to get custom eureka instance settings in an `applications.yml` file taken into account at
all but I guess that's for another issue ;-)

```
server:
  port: 9999
  context-path: /admin
...
eureka:
  instance:
    statusPageUrlPath: /admin/manage/info
    homePageUrlPath: /admin/
    healthCheckUrlPath: /admin/manage/health
    non-secure-port: ${server.port:9999}
    ...
```

**Comment by ofbizbrazil** [comment] 2016-03-14 21:31
Hi,

When will it be available to download?

**Comment by spencergibb** [comment] 2016-03-14 22:28
@ofbizbrazil it hasn't been done, until it has, it won't be available to download.

**Comment by ofbizbrazil** [comment] 2016-03-14 22:32
@spencergibb,

My applications have context-path at uri, is there any workaround until this is done?

**Comment by spencergibb** [comment] 2016-03-14 22:39
https://github.com/spring-cloud/spring-cloud-netflix/issues/737#issue-123043546

**Comment by ofbizbrazil** [comment] 2016-03-15 13:22
Hi @spencergibb, of course i saw that comment, but my doubt is how to apply this 'locally shadowing' mentioned in there.

I guess the spring package was patched to overwrite the class EurekaDiscoveryClient. Do you know how to do it?

**Comment by thomasdarimont** [comment] 2016-03-15 13:26
Hi @ofbizbrazil,

(as a quick hack) just copy the `org.springframework.cloud.netflix.eureka.EurekaDiscoveryClient` in your local source folder (e.g. src/main/java) with the same package structure and change the method in question as described.
Your classes take precedence over classes from additional libraries.

Cheers,
Thomas

**Comment by ofbizbrazil** [comment] 2016-03-15 13:42
That's I was afraid of, doing a patch into my project to handle the class EurekaDiscoveryClient.

**Comment by thomasdarimont** [comment] 2016-03-15 13:46
Yep - same here - I just used this to verify what a potential solution might be... ;-)

**Comment by spencergibb** [comment] 2016-03-15 13:46
What's the use case? Why do you need this?

**Comment by ofbizbrazil** [comment] 2016-03-15 13:57
Nowadays we are limiting an application to only use a root context, and if I want to change the context-path to a different name, EurekaDiscoveryClient simply does work and nobody will know about it.

So, in my opinion that's a critical issue, taking in mind Spring Netflix just works for a specific URI.

**Comment by spencergibb** [comment] 2016-03-15 14:06
I guess I think it's strange that you would change the context of a service and not expect clients to change. This has been marked as `Help Wanted `. Pull requests are welcome.

**Comment by ofbizbrazil** [comment] 2016-03-15 14:14
My micro-service uses a context-path and the clients which uses it really works fine.

The issue here is EurekaDiscoveryClient does support context-path when the method getUri() builds the URI. There should be the property contextPath in EurekaServiceInstance to allow this resource.

**Comment by sfat** [comment] 2016-04-20 10:49
@spencergibb I wanted to do a fix on this fella the other day
When I modified the EurekaDiscoveryClient.getUri to what @thomasdarimont suggested, DiscoveryClientConfigServiceAutoConfigurationTests fails on `onWhenRequested` because
 DiscoveryClientConfigServiceBootstrapConfiguration sets the `homePage` as follows
```
private String getHomePage(ServiceInstance server) {
        return server.getUri().toString() + "/";
 }
```
So, I think if it is decided to change the EurekaDiscoveryClient.getUri, to modify in spring-cloud-config the homePage

**Comment by kk-manh** [comment] 2016-04-20 18:59
Hi,
I ran into the same problem and looks like the current implementation assumes that no two eureka clients  will be deployed in a single web container . For example , you cant have 2 springboot eureka client apps deployed as WAR files in a single tomcat container.

**Comment by ofbizbrazil** [comment] 2016-06-15 02:03
is ther any news about this matter?

**Comment by ofbizbrazil** [comment] 2016-06-15 02:03
is ther any news about this matter?

**Comment by dilgerma** [comment] 2016-10-15 06:07
Is this still the case? I´m running in to this problem at the moment using the default ribbon configuration.

**Comment by cjemison** [comment] 2017-01-06 21:21
I am curious. Has there been any update to this issue? Thanks!

**Comment by spencergibb** [comment] 2017-01-09 20:05
No update. It's not high on our priorities since it can be done with properties. Pull requests welcome.

**Comment by cbos** [comment] 2017-01-20 12:16
Use case for this issue:
We have a java application deployed on Tomcat with a context root. The urls look like '/myapp/url_path_in_the_application.
Now we have also deploy the application in on Docker. Now the urls are the same, but without the context root '/myapp', so only '/url_path_in_the_application'.

We are looking for a way that we can register the old version with context root '/myapp' and the new version with '/' as context root.
For the client the invocation is easy base_url + '/url_path_in_the_application'.
Base_url is created based on the registration in Eureka.

**Comment by TateHuang** [comment] 2017-02-22 09:32
@cbos the exact same problem,any suggestions for now?

**Comment by cbos** [comment] 2017-02-22 12:54
We fixed the issue ourselves, as we did register the services ourselves to Eureka. So we added the context path as setting to the metadata.
In this specific situation we did not use the default eureka client, so we were able to read that context path setting and use that in the request as well. 
In the default setup it is hard to fix it yourself.

**Comment by cecchisandrone** [comment] 2017-03-17 11:36
@cbos How did you register your service manually with custom context-path?

**Comment by cbos** [comment] 2017-03-17 19:55
We have our own client which registers the service to Eureka. With that we add teh context-path in the metadata.

**Comment by rax215** [comment] 2017-05-19 13:54
@cbos could you please provide any code snippet you used in your client to register context path?

**Comment by silentFred** [comment] 2017-06-02 16:58
Hi @spencergibb,

Thank you for your insights! So i'n my case we are running multiple services in a single weblogic container and they all need different context paths. The port number is also fixed, so that's not an option.

You mentioned that this can be changed with properties? I have looked into the home page url properties and tried every combination I could think of with no luck.

**Comment by kasibkismath** [comment] 2017-07-19 05:55
Hi @spencergibb,

I too face the same issue as @slientFred. It would be great if you could provide us some insights on this issue. 

I have tried the following as of now and it has failed:
1. turbine.istance-url-suffix.<clusterName> together with turbine.cluster-config
2. Setting eureka.instance.metadataMap.management.context-path and eureka.instance.home-page-url-path the same values as the microservices properties.

The context path is not added to the hystrix stream url, it's still http://host:port/hystrix.stream, it isn't http://host:port/context-path/hystrix.stream

As @silentFred addressed, the host and the port are same for all the microservice while the context paths are different.

Note: The microservice, turbine-app are deployed in weblogic 12c and the eureka server is running in tomcat.

**Comment by spencergibb** [comment] 2017-07-19 17:01
@kasibkismath you are the first to mention turbine, so I'm not sure if it's the same issue.

**Comment by kasibkismath** [comment] 2017-07-19 17:38
@spencergibb, since I have the context path added to each microservice's weblogic.xml, the hystrix dashboard is accessible through http://host:port/context-path/hystrix.stream, whereas nextflix turbine listens for http://host:port/hystrix.stream - without the context path, by default. 

Therefore, I should make netflix turbine listen with the microservices context path or else the microservices should use the root context path, the latter wouldn't be possible with weblogic because all the microservices will be running on the same host and port but the context path is different.

Hope you get my question right.

**Comment by spencergibb** [comment] 2017-07-19 17:45
@kasibkismath I think I understand, it is just different than the current issue.

**Comment by silentFred** [comment] 2017-07-19 17:47
Agree. In general though, it has proven very difficult to use all the spring cloud components on services that have context roots. We also have yet to figure out how we will get turbine and co. to work

**Comment by kasibkismath** [comment] 2017-07-19 17:53
@spencergibb, yes, it's a different issue but the underlying issue is due to the context path not being added. @silentFred hope that the context path issue would be fixed soon, so that all comes together.

**Comment by rax215** [comment] 2017-07-19 17:56
looked at @thomasdarimont Hack!!! wondering if that can be included in source code and published as new jar files

**Comment by thomasdarimont** [comment] 2017-07-19 18:11
...btw. was asked about that a month ago on [twitter] (https://twitter.com/cmptrwizard/status/872443692962992130)
...turns out one also needs to take care about the context-path when using ribbon, a PoC for this can be found [here](https://github.com/thomasdarimont/service-discovery-example-eureka-hacks/tree/master/tdlabs-frontend/src/main/java).

**Comment by spencergibb** [comment] 2017-07-19 18:17
Part of the issue is this goes beyond just eureka and would have to be changed in other discovery clients as well.

**Comment by silentFred** [comment] 2017-07-19 18:52
@spencergibb yep! We ended up abusing the homePageUrl config to cater for contexts in Zuul and other clients that use ribbon. Not all that pretty =(

With some inspiration from @thomasdarimont I managed to put together something that worked for me:

http://webler.co.za/blog/spring-cloud-web-context-root-aware-zuul-eureka-service-calls-code-bit/
http://webler.co.za/blog/spring-cloud-web-context-aware-feign-clients-using-eureka-service-discovery-code-bit/

**Comment by spencergibb** [comment] 2017-07-19 20:37
It's all or nothing and doing "all" is a big effort.

**Comment by kasibkismath** [comment] 2017-07-20 00:31
@silentFred when I go to the link I get 403 error.

**Comment by rax215** [comment] 2017-07-20 13:12
@silentFred Can you please check for the Autowired block in http://webler.co.za/blog/spring-cloud-web-context-root-aware-zuul-eureka-service-calls-code-bit/ ? I am getting error in that

**Comment by silentFred** [comment] 2017-07-20 13:58
@rax215 @kasibkismath the pages load fine for me...

`@Bean
@Primary
public RibbonRoutingFilter ribbonRoutingFilter(ProxyRequestHelper helper,
                                               RibbonCommandFactory<?>; ribbonCommandFactory,
                                               LoadBalancerClient loadBalancerClient) {
 
    return new ContextAwareRibbonRoutingFilter(helper, ribbonCommandFactory, loadBalancerClient);
}`

**Comment by rax215** [comment] 2017-07-20 14:09
@silentFred Sorry for the confusion, I meant Autowired block of "ContextAwareRibbonRoutingFilter" class.
`public ContextAwareRibbonRoutingFilter(
            ProxyRequestHelper helper,
            RibbonCommandFactory<?>; ribbonCommandFactory,
            LoadBalancerClient loadBalancerClient) {

        super(helper, ribbonCommandFactory);`
The semicolon after RibbonCommandFactory<?>**;**, is it correct? and the attributes in **super()** are throwing error for me.

**Comment by silentFred** [comment] 2017-07-20 14:58
@rax215 It looks like a typo. Remove that semicolon. Not too sure why super() is throwing errors

**Comment by fahimfarookme** [comment] 2017-07-20 22:40
@kasibkismath for the context-path with **Turbine** issue you have raised, PFB my finding and the fix worked for me.

- The service discovery approach can be plugged-into Turbine with the following property. 
`InstanceDiscovery.impl=....`
[https://github.com/Netflix/Turbine/wiki/Plugging-in-your-own-InstanceDiscovery-(1.x)](https://github.com/Netflix/Turbine/wiki/Plugging-in-your-own-InstanceDiscovery-(1.x))

- Spring cloud's implementation for this is based on 'Eureka discovery' and implemented in `EurekaInstanceDiscovery` class.

- So that I have extended the spring `EurekaInstanceDiscovery` class to provide context-path as well.

- Had to use same package as Spring `org.springframework.cloud.netflix.turbine` for my subclass in order to override a package-private method (i.e. just to avoid overriding entire thing.)

[PoC here. ](https://github.com/fahimfarookme/turbine-context-path-issue)

**Comment by kasibkismath** [comment] 2017-07-21 05:47
@fahimfarookme it works perfectly as expected. 

There are few gotchas as you have mentioned, however, what is the overall impact since we are extending EurekaInstanceDiscovery, which is a class of spring-cloud-netflix-turbine, considering the fact that at a later point of time we will be upgrading netflix-turbine as well.

**Comment by fahimfarookme** [comment] 2017-07-21 06:03
@kasibkismath This solution is only for the Turbine issue you have raised. [This is the standard way of providing custom discovery mechanism for Turbine](https://github.com/Netflix/Turbine/wiki/Plugging-in-your-own-InstanceDiscovery-(1.x)). Will have upgradability concern only for  Turbine, however safer than extending Eureka server or client related classes - if everything else works fine for you.

**Comment by Pytry** [comment] 2017-10-05 22:01
Is anyone already working on this issue? I don't want to step on toes.

**Comment by s332401890** [comment] 2017-12-07 05:41
i have some idea to  avoid this problem 
this my code 

`@LoadBalanced
    @Bean
    public RestTemplate getRestTemplate()
    {
        RestTemplate restTemplate = new RestTemplate();
        List<ClientHttpRequestInterceptor> interceptors = new ArrayList<>();
        interceptors.add(new EurekaContextPathInterceptor());
        restTemplate.setInterceptors(interceptors);
        return restTemplate;
    }
    
    public static class EurekaContextPathInterceptor implements ClientHttpRequestInterceptor
    {
        
        @Override
        public ClientHttpResponse intercept(HttpRequest request, byte[] body, ClientHttpRequestExecution execution)
            throws IOException
        {
            return execution.execute(new EurekaContextPathHttpRequestWrapper(request), body);
        }
        
    }
    
    public static class EurekaContextPathHttpRequestWrapper extends HttpRequestWrapper
    {
        private URI original;
        
        public EurekaContextPathHttpRequestWrapper(HttpRequest request)
        {
            super(request);
            original = request.getURI();
        }
        
        @Override
        public URI getURI()
        {
            URI newURI = null;
            try
            {
                String scheme = original.getScheme();
                
                if(StringUtils.isEmpty(scheme)){
                    scheme = "";
                }
                
                StringBuilder sb = new StringBuilder();
                sb.append(scheme).append("://");
                if (StringUtils.isEmpty(original.getRawUserInfo()))
                {
                    sb.append(original.getRawUserInfo()).append("@");
                }
                sb.append(original.getHost()).append("/").append(original.getHost());
                sb.append(original.getRawPath());
                if (StringUtils.isEmpty(original.getRawQuery()))
                {
                    sb.append("?").append(original.getRawQuery());
                }
                if (StringUtils.isEmpty(original.getRawFragment()))
                {
                    sb.append("#").append(original.getRawFragment());
                }
                newURI = new URI(sb.toString());
            }
            catch (URISyntaxException e)
            {
            }
            return newURI;
        }
    }`

**Comment by s332401890** [comment] 2017-12-07 05:49
i have some other way to solve this problem but it is bad and  case another problem,this is contextPath must be same with applicationname. 

my code
`@LoadBalanced
    @Bean
    public RestTemplate getRestTemplate()
    {
        RestTemplate restTemplate = new RestTemplate();
        List<ClientHttpRequestInterceptor> interceptors = new ArrayList<>();
        interceptors.add(new EurekaContextPathInterceptor());
        restTemplate.setInterceptors(interceptors);
        return restTemplate;
    }
    
    public static class EurekaContextPathInterceptor implements ClientHttpRequestInterceptor
    {
        
        @Override
        public ClientHttpResponse intercept(HttpRequest request, byte[] body, ClientHttpRequestExecution execution)
            throws IOException
        {
            return execution.execute(new EurekaContextPathHttpRequestWrapper(request), body);
        }
        
    }
    
    public static class EurekaContextPathHttpRequestWrapper extends HttpRequestWrapper
    {
        private URI original;
        
        public EurekaContextPathHttpRequestWrapper(HttpRequest request)
        {
            super(request);
            original = request.getURI();
        }
        
        @Override
        public URI getURI()
        {
            URI newURI = null;
            try
            {
                String scheme = original.getScheme();
                
                if(StringUtils.isEmpty(scheme)){
                    scheme = "";
                }
                
                StringBuilder sb = new StringBuilder();
                sb.append(scheme).append("://");
                
                sb.append(original.getHost()).append("/").append(original.getHost());
                sb.append(original.getRawPath());
                if (!StringUtils.isEmpty(original.getRawQuery()))
                {
                    sb.append("?").append(original.getRawQuery());
                }
                if (!StringUtils.isEmpty(original.getRawFragment()))
                {
                    sb.append("#").append(original.getRawFragment());
                }
                newURI = new URI(sb.toString());
            }
            catch (URISyntaxException e)
            {
            }
            return newURI;
        }
    }`

**Comment by dsushil2000** [comment] 2017-12-29 23:37
I have requirement to publish Boot Microservices with context path. How we can solve the problem? Eureka does not register the App with Context Path

**Comment by silentFred** [comment] 2017-12-30 07:08
I don't know if this code will stioll work on later version but give this a
shot:
http://webler.co.za/blog/spring-cloud-web-context-root-aware-zuul-eureka-service-calls-code-bit/

**Comment by jrauschenbusch** [comment] 2018-05-02 08:32
I think that there is still a lot of interest in this feature and I also want to present a problem that we are currently facing.

Example: Dynamic microservice architecture using TLS/SSL secured endpoints only with no need for an wildcard certificate.

Solutions:
- Context-path based routing
- Creating an certificate containing all SANs of all microservices (not really dynamic)

Downside of context-path based routing with current EUREKA implementation:
Context paths must be added to all inter-service API calls if before sub-domain based routing was used.
=> Support for context paths would really help here

Downside SANs:
One has to add a new SAN to the certificate all the time a new microservice is added

**Comment by Pytry** [comment] 2018-05-02 14:44
@jrauschenbusch For me, this behavior seems like a huge design bug with Spring Cloud in general (not just Eureka). One of the founding design concepts of Java Servlets, and web development in general, was the ability to be deployed anywhere under any context, and have the application behave the same. It shouldn't matter if we "make war" instead of jar, deploy as root or with a custom context, nor even if the different instances have different contexts. This was the main appeal of Servlets, and the reason why so many companies (many on windows) decided to adopt it.

**Comment by haglerchristopher** [comment] 2018-10-10 04:35
Has there been any update on this issue? I am facing the same issues mentioned above.

**Comment by silentFred** [comment] 2018-10-10 04:47
I have a workaround for the edgeware release train if you are looking to
expose your services via zuul. For service to service calls we've had to
add the context to the service name in our load balanced clients ie.
http://some-service-name/some-context

There is a way you can override ribbon behaviour to take care of this for
you that i have lying around somewhere if anyone is interested.

**Comment by spencergibb** [comment] 2019-02-07 16:02
This is something we've avoided in the past and are not looking to implement this at this time.

**Comment by georglundesgaard** [comment] 2019-12-11 08:09
I just bumped into this bu^H^Hfeature today. Is there a reason why this couldn't be fixed by used the specified homePageUrl/homePageUrlPath in Eureka? Would this break some other functionality? Most of our services unfortunately have a context path and are not served on '/', so this makes it a little harder to use the default Eureka client (I would rather use the default instead of supporting my own).

**Comment by spencergibb** [comment] 2019-12-11 11:52
We've decided as a team not to support this.

**Closed by spencergibb** 2019-12-11 11:52 UTC
Labels: wontfix

**Comment by tarn2206** [comment] 2021-06-08 05:25
You can pass the custom context-path into the instance metadata-map
```
eureka:
   instance:
      metadata-map:
         contextPath: ${server.servlet.context-path}
```

and access the value by calling
```
String url = instance.getUri() + instance.getMetadata().get("contextPath");
```
