### ISSUE TITLE
Read Timeout not reflecting

### ISSUE THREAD

**Issue by kavinduraisamy91** [spring-cloud/spring-cloud-netflix#1655] opened 2017-01-30 12:10 UTC
We have done the below configurations to terminate the service after the 20 sec.

```
zuul.routes.book.path=/book/**
zuul.routes.book.serviceId=book
book.ribbon.listOfServers=localhost:9200
book.ribbon.ReadTimeout=20000
book.ribbon.ConnectTimeout=20000
hystrix.command.book.execution.isolation.thread.timeoutInMilliseconds=20000
zuul.eureka.book.semaphore.maxSemaphores=50
```

But the configuration did not send the timeout response after the 20 sec. It is waiting until retrieve the response from the service (around 120 secs).

We are using the spring-cloud-dependencies Camden.SR3 version.

Thank you!

**Comment by ryanjbaxter** [comment] 2017-02-01 12:46
This looks like it should be working can you maybe provide a sample app that reproduces the problem?

**Comment by spencergibb** [comment] 2018-01-18 00:19
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2018-01-18 00:19 UTC
Labels: waiting for feedback
