### ISSUE TITLE
Ribbon PoolKeepAliveTime is never read

### ISSUE THREAD

**Issue by arkin** [spring-cloud/spring-cloud-netflix#3038] opened 2018-06-28 22:24 UTC
Because the ribbon config entry PoolKeepAliveTime is read as a string instead of an integer/long, it never passes the check at https://github.com/spring-cloud/spring-cloud-netflix/blob/1.4.x/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/ribbon/apache/HttpClientRibbonConfiguration.java#L90
Due to this issue, one cannot override the default value of 900 seconds.

**Comment by arkin** [comment] 2018-06-28 22:47
Looks like the same issue exists on master, too, although the code was moved to another class.

**Comment by spencergibb** [comment] 2019-01-18 19:11
This was fixed in the 1.4.x line by #3039.

**Comment by spencergibb** [comment] 2019-01-18 19:11
Looks like there was a regression when property access was moved.

**Closed** 2019-01-18 20:57 UTC
Labels: bug, waiting-for-triage
