### ISSUE TITLE
Turbine Stream Refresh

### ISSUE THREAD

**Issue by brianchambers21** [spring-cloud/spring-cloud-netflix#342] opened 2015-05-07 19:26 UTC
We are using Spring Cloud Turbine to aggregate Hystrix streams from a number of servers.  For discovery we use a custom implementation of the InstanceDiscovery class.

What I have noticed is that, on the aggregated turbine stream, the turbine stream only publishes metrics for methods that have activity.

In the example below, you see data for the operation called searchLdapUser that is published at the time when the method was hit, but afterwards you just see reporting hosts and timestamps.

The impact of this is that the Hystrix Dashboard for monitoring a turbine stream looks very choppy for methods with lower volumes.  It seems that the Hystrix streams publish metrics continually whether there is activity or not, which enables a smooth dashboard experience (no activity means the volume line on the dashboard updates continually at 0).  Turbine seems to be dropping these "no activity" metrics.

Is this something that can be configured differently or is this a defect with spring-cloud-netflix-turbine?

Thanks for your help!

Here is an example from the raw turbine stream:

data: {"rollingCountFallbackSuccess":0,"rollingCountFallbackFailure":0,"propertyValue_circuitBreakerRequestVolumeThreshold":40,"propertyValue_circuitBreakerForceOpen":false,"propertyValue_metricsRollingStatisticalWindowInMilliseconds":20000,"latencyTotal_mean":22,"type":"HystrixCommand","rollingCountResponsesFromCache":0,"rollingCountTimeout":0,"propertyValue_executionIsolationStrategy":"THREAD","rollingCountFailure":0,"rollingCountExceptionsThrown":0,"latencyExecute_mean":22,"isCircuitBreakerOpen":false,"errorCount":0,"rollingCountSemaphoreRejected":0,"group":"UnboundLdapUserService","latencyTotal":{"0":18,"99":26,"100":26,"25":18,"90":26,"50":26,"95":26,"99.5":26,"75":26},"requestCount":0,"rollingCountCollapsedRequests":0,"rollingCountShortCircuited":0,"propertyValue_circuitBreakerSleepWindowInMilliseconds":10000,"latencyExecute":{"0":18,"99":26,"100":26,"25":18,"90":26,"50":26,"95":26,"99.5":26,"75":26},"currentConcurrentExecutionCount":0,"propertyValue_executionIsolationSemaphoreMaxConcurrentRequests":20,"errorPercentage":0,"rollingCountThreadPoolRejected":0,"propertyValue_circuitBreakerEnabled":true,"propertyValue_executionIsolationThreadInterruptOnTimeout":true,"propertyValue_requestCacheEnabled":true,"rollingCountFallbackRejection":0,"propertyValue_requestLogEnabled":true,"rollingCountSuccess":0,"propertyValue_fallbackIsolationSemaphoreMaxConcurrentRequests":20,"propertyValue_circuitBreakerErrorThresholdPercentage":100,"propertyValue_circuitBreakerForceClosed":false,"name":"searchLdapUser","reportingHosts":2,"propertyValue_executionIsolationThreadPoolKeyOverride":"null","propertyValue_executionIsolationThreadTimeoutInMilliseconds":120000}

data: {"currentCorePoolSize":20,"currentLargestPoolSize":20,"currentActiveCount":0,"propertyValue_metricsRollingStatisticalWindowInMilliseconds":20000,"currentMaximumPoolSize":20,"currentQueueSize":0,"type":"HystrixThreadPool","currentTaskCount":7305,"currentCompletedTaskCount":7305,"rollingMaxActiveThreads":0,"name":"LDAPQueryProcessor","reportingHosts":2,"currentPoolSize":20,"propertyValue_queueSizeRejectionThreshold":10,"rollingCountThreadsExecuted":0}

: ping
data: {"reportingHostsLast10Seconds":2,"name":"meta","type":"meta","timestamp":1431026257357}

: ping
data: {"reportingHostsLast10Seconds":2,"name":"meta","type":"meta","timestamp":1431026261357}

: ping
data: {"reportingHostsLast10Seconds":2,"name":"meta","type":"meta","timestamp":1431026264358}

: ping
data: {"reportingHostsLast10Seconds":2,"name":"meta","type":"meta","timestamp":1431026268359}

**Comment by karthik101** [comment] 2015-07-22 12:41
@brianchambers21 I have something similar problem but instead of reporting timestamps, i see only continuous ping messages after initial data. Have you overcome this issue yet?

**Comment by brianchambers21** [comment] 2015-07-22 14:30
Unfortunately no.  I have not seen any comments about the issue either.

**Comment by karthik101** [comment] 2015-07-23 13:13
@brianchambers21 i have opened an issue here https://github.com/Netflix/Turbine/issues/98

**Comment by brianchambers21** [comment] 2015-07-23 14:19
Thanks!  Source has not been refreshed in a while.  I moved on to some different projects so we just accepted this as a minor frustration for the time being.

**Comment by spencergibb** [comment] 2016-03-03 01:43
@brianchambers21 is this still an issue?

**Comment by brianchambers21** [comment] 2016-03-03 02:53
I am not working on the same project where this was used anymore so I am
not 100 percent sure as I don't know if any subsequent updates have
resolved the issue.

**Comment by spencergibb** [comment] 2016-03-03 04:04
I'm going to close this, if someone sees this again and can report how to reproduce, feel free to reopen.

**Closed by spencergibb** 2016-03-03 04:04 UTC

**Comment by mblasi** [comment] 2017-04-05 16:55
Hi!

I'm seeing this issue now, here is my turbine configuration:

turbine.instanceUrlSuffix = ':8080/hystrix.stream'
turbine.ConfigPropertyBasedDiscovery.defualt.instances=["server1.mydomain.com"]

the curl to /hystrix.stream shows all the stats, but the /turbine.stream just shows:

: ping
data: {"timestamp":1491410032203,"name":"meta","reportingHostsLast10Seconds":0,"type":"meta"}

: ping
data: {"timestamp":1491410036204,"name":"meta","reportingHostsLast10Seconds":0,"type":"meta"}

: ping
: ping

The stack:

Old grails application (1.3.7), I just added the servlets for hystrix-stream and turbine-stream, altogether on same port (8080) and a filter for Turbine initializing.
Java version: 1.6

dependencies added:

        runtime('com.netflix.hystrix:hystrix-core:1.5.9')
        runtime('com.netflix.hystrix:hystrix-metrics-event-stream:1.4.10')
        runtime("com.netflix.turbine:turbine-core:1.0.0")

I don't know if something else could be useful.

**Comment by mblasi** [comment] 2017-04-24 20:50
Hi everybody, any help on this? I'm still working on that. Best regards!

**Comment by spencergibb** [comment] 2017-04-24 20:52
Are you using spring cloud?

**Comment by mblasi** [comment] 2017-04-24 20:55
No, it is an old grails-1.3.7 web application.
Just that.
It has already hystrix working, for an external API consuming, and I added hystrix:hystrix-metrics-event-stream and turbine:turbine-core deps, just for being able to see hystrix metrix in the hystrix-dashboard (it runs in a different server).

Regards,
Matías.

**Comment by spencergibb** [comment] 2017-04-24 21:33
This tracker is specifically for folks using the netflix tools integrated into spring.

**Comment by mblasi** [comment] 2017-04-24 21:42
Thank you @spencergibb!

Regards,
Matías.

**Comment by anandmohan777** [comment] 2018-06-13 12:08
@spencergibb I have the same issue.

### Turbine console logs:
`2018-06-13 12:58:18.546  INFO 23916 --- [        Timer-0] o.s.c.n.t.CommonsInstanceDiscovery       : Fetching instance list for apps: [res]

2018-06-13 12:58:18.547  INFO 23916 --- [        Timer-0] o.s.c.n.turbine.EurekaInstanceDiscovery  : Fetching instances for app: res

2018-06-13 12:58:18.547  INFO 23916 --- [        Timer-0] o.s.c.n.turbine.EurekaInstanceDiscovery  : Received instance list for app: res, size=1

2018-06-13 12:58:18.548  INFO 23916 --- [        Timer-0] c.n.t.discovery.InstanceObservable       : Retrieved hosts from InstanceDiscovery: 1

2018-06-13 12:58:18.549  INFO 23916 --- [        Timer-0] c.n.t.discovery.InstanceObservable       : Found hosts that have been previously terminated: 0

2018-06-13 12:58:18.549  INFO 23916 --- [        Timer-0] c.n.t.discovery.InstanceObservable       : Hosts up:1, hosts down: 0`

### Turbine.stream is showing beow data (http://localhost:8088/turbine.stream?cluster=res)
`: ping
data: {"reportingHostsLast10Seconds":0,"name":"meta","type":"meta","timestamp":1528890982586}

: ping
data: {"reportingHostsLast10Seconds":0,"name":"meta","type":"meta","timestamp":1528890985587}

: ping
data: {"reportingHostsLast10Seconds":0,"name":"meta","type":"meta","timestamp":1528890988589}

: ping
data: {"reportingHostsLast10Seconds":0,"name":"meta","type":"meta","timestamp":1528890991591}`

And So the problem is dashboard is just showing 'Loading ...'
