### ISSUE TITLE
Header added using addZuulRequestHeader is not forwarded to micorservics

### ISSUE THREAD

**Issue by nagrm** [spring-cloud/spring-cloud-netflix#3437] opened 2019-03-19 07:39 UTC
We have built a Zuul gateway using spring-cloud-starter-netflix-zuul.

In Zuul gateway am adding header using addZuulRequestHeader() method in a ZuulFilter. But could not find the header in request routed to micorservic.

Am using the following versions
-------------------------------------
spring-cloud.version : Finchley.SR2 
spring-boot-starter-parent : 2.0.6.RELEASE 
spring-cloud-starter-netflix-zuul : 2.1.0.RELEASE 
 
```
/**** Zuul Filter ***/
@Component
public class TrackingFilter extends ZuulFilter{
	
    private static final int      FILTER_ORDER =  1;
    private static final boolean  SHOULD_FILTER=true;

    @Autowired
    private FilterUtils filterUtils;

    @Override
    public String filterType() {
        return FilterUtils.PRE_FILTER_TYPE;
    }

    @Override
    public int filterOrder() {
        return FILTER_ORDER;
    }

    public boolean shouldFilter() {
        return SHOULD_FILTER;
    }


    public Object run() {

        RequestContext ctx = RequestContext.getCurrentContext();
		ctx.addZuulRequestHeader("tmx-correlation-id", java.util.UUID.randomUUID().toString()); 
        return null;
    }
}

/**** Microservice Controller ***/
@RestController
public class MyController {

    private static final Logger LOGGER = LoggerFactory.getLogger(MyController.class);

    @RequestMapping("/")
    public String external(HttpServletRequest request ) throws InterruptedException {

        string correlationid = request.getHeader("tmx-correlation-id");
        LOGGER.info("correlationid = " + correlationid);
        
        return "Success";
    } 
 
}
```

**Comment by spencergibb** [comment] 2019-03-19 19:11
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

I don't know. That is the mechanism we use in `PreDecorationFilter` to add headers.

How come you are using Finchley.SR2 but spring-cloud-starter-netflix-zuul : 2.1.0.RELEASE, 2.1.0.x is not compatible with boot 2.0.x?

**Comment by nagrm** [comment] 2019-03-20 05:38
Hi Spencer,

I changed  spring-cloud-starter-netflix-zuul  version to **2.0.2.RELEASE**, still it did not work.

Should I try with different spring-cloud.version? if so please let me know what should I use.

**Comment by ryanjbaxter** [comment] 2019-03-20 16:09
You should let the Spring Cloud BOM manage the dependencies for you.  The latest Finchley release is SR3 please use that.  If you are still having he issue please provide a sample we can use to reproduce the problem.

**Comment by nagrm** [comment] 2019-03-26 13:58
Hi Ryan,

I tried "Finchley SR3". I also tried removing the "spring-cloud-dependencies" so that Spring manages it. Still its not working.

Within Zuul Gateway I have implemented Token Authentication using springs _WebSecurityConfigurerAdapter_'s method _configure(HttpSecurity httpSecurity)_ method.
Please let me know whether this might have any relation to this issue.

**Comment by ryanjbaxter** [comment] 2019-04-10 23:38
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment] 2019-04-17 23:43
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-04-24 23:40
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-04-24 23:40 UTC
Labels: feedback-reminder, waiting for feedback
