### ISSUE TITLE
Two instances of CloudEurekaClient (non- and RefreshScope) are initialized even though AutoConfiguration should be exclusive

### ISSUE THREAD

**Issue by filpano** [spring-cloud/spring-cloud-netflix#3335] opened 2019-01-04 11:41 UTC
Hello, 

I am currently using Spring Cloud Finchley.SR2 together with Spring Boot 2.0.6.RELEASE dependencies. I am seeing odd behaviour in `EurekaHealthIndicator`, namely:

![image](https://user-images.githubusercontent.com/5376771/50685916-9024c100-101b-11e9-8c3f-1d74aec81b42.png)

We can see that the specific instance of the `DiscoveryClient` that was used to initialize the health indicator is `CloudEurekaClient@4087` and not a proxy object. Unfortunately, the `lastFetch` value is never updated and stays at either `-1` or some specific timestamp.

Investigating further, I found that during `DicoveryClient#refreshRegistry`, a completely separate instance is updating its registry:

![image](https://user-images.githubusercontent.com/5376771/50686229-b565ff00-101c-11e9-9972-4b95e34d64f8.png)

Indeed, this is the same (and *only*) instance registered in the application context:

![image](https://user-images.githubusercontent.com/5376771/50686280-00801200-101d-11e9-9a58-e7a8b3c94c46.png)

Furthermore, it seems that the following occurs on startup:

1. `EurekaClientAutoConfiguration$EurekaClientConfiguration#eurekaClient()` is invoked, constructing a `CloudEurekaClient`. This inner configuration class has `@ConditionalOnMissingRefreshScope`.
2. `RefreshAutoConfiguration` is initialized.
3. `EurekaClientAutoConfiguration$RefreshableEurekaClientConfiguration#eurekaClient()` is invoked, constructing *another* `CloudEurekaClient`. This inner configuration class has `@ConditionalOnRefreshScope`.

It seems to me that these configuration classes should be mutually exclusive, yet they are not and are both triggered every time in the same order. Seemingly it also causes problems in the health indicator, since the instance that is registered there does not seem to be the one that is actually used by the application context, meaning the `lastFetch` value is never updated and the `HealthStatus` forever has a `failCount` associated with it.

I haven't been able to invest more time into this as of yet, but if anyone has any pointers as to how I might debug this further, I could give it a shot. I have not yet time to try and reproduce this error in a minimal application (though it might very well be the case there as well).

**Comment by ryanjbaxter** [comment] 2019-01-07 21:15
Interesting, if you can come up with a sample that reproduces the problem that would help a lot.

**Comment by spencergibb** [comment] 2019-01-07 21:17
In fact, we'll need it. I can't duplicate it.

**Comment by filpano** [comment] 2019-01-08 08:59
Thanks for the replies. I will try to isolate the issue and get back to you. It almost looks like two separate scans are picking up those configuration classes.

**Comment by spencergibb** [comment] 2019-02-11 16:26
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2019-02-11 16:26 UTC
Labels: feedback-provided
