### ISSUE TITLE
Spring boot devtools disrupts Feign initialisation

### ISSUE THREAD

**Issue by msoub** [spring-cloud/spring-cloud-netflix#1396] opened 2016-10-13 18:49 UTC
When I add spring boot devtools to my project, the Feign clients are initialised too early and don't have access to the Targeter which causes a NPE. Any idea why devtools disrupts the initialisation?

**Comment by spencergibb** [comment] 2016-10-13 19:19
Duplicate of #1366

**Closed by spencergibb** 2016-10-13 19:19 UTC
