### ISSUE TITLE
Canary Support in Zuul

### ISSUE THREAD

**Issue by stiyyagura** [spring-cloud/spring-cloud-netflix#2337] opened 2017-10-02 15:53 UTC
I would like to know if there is any one already identified and working on the need for Canary release feature in Zuul API Gateway?

If it is not already then can we discuss here to capture the thoughts and design, so that who ever is implementing/enhancing the canary support in the current Camden release can do things rightly so that it is easy for tomorrow.

**Comment by ryanjbaxter** [comment] 2017-10-03 00:06
Can you provide a use case?

**Comment by spencergibb** [comment] 2017-10-03 00:13
It won't be in Camden. If it's anywhere it would be Edgware or later.

**Comment by ykushch** [comment] 2017-10-24 15:01
Then the question is still relevant. Probably you could advise. What is the best approach to do canary releases for Eureka?

**Comment by ryanjbaxter** [comment] 2017-11-07 18:49
@ykushch as I asked for above, it would be nice to hear about your use case.

**Comment by ykushch** [comment] 2017-11-07 20:00
@ryanjbaxter thanks! Here is a related ticket to the use-case. Probably you could advise how to do that [Issue #372].

[Issue #372]: https://github.com/Netflix/zuul/issues/372

**Comment by ryanjbaxter** [comment] 2017-11-07 20:32
Thanks.  Your use case seems to have less to do with Zuul and more to do with Ribbon, which Zuul is using under the covers to choose which server to route the request to.  I would think you could write a custom `IRule` which looks at the header and decides which server to route the request to.

**Comment by felixoldenburg** [comment] 2017-11-15 21:05
Ribbon is only used to resolve the services from a service discovery. See the usage of the routeLocator in ZuulHandlerMapping. The decision on how to route incoming requests is still done by Zuul itself.
If you have, let's say, a ServiceA and another version ServiceA2 you want to roll out. They're probably already covered by your service discovery and thus available as Eureka/Ribbon clients.
I think this could be easily done by writing a pre ZuulFilter which rewrites the requestUri based on the request headers. If I remember correctly the Ribbon/-EurekaRoutingFilter then is responsible to pick the corresponding ribbon client and route the request depending on the requestUri (you just modified in the pre filter).

**Comment by lowzj** [comment] 2017-11-16 03:51
I think that ribbon can do this by using loadBalancerKey, there's a PR working on this feature: https://github.com/spring-cloud/spring-cloud-netflix/pull/2439

**Comment by ryanjbaxter** [comment] 2017-11-16 16:20
@felixoldenburg Zuul will decide which service to route to, but the Ribbon load balancer will decide which instance of that service to send the request to.  

@lowzj is right, that PR is trying to solve this.

**Comment by felixoldenburg** [comment] 2017-11-17 18:54
Thanks for the clarification. I automatically thought of separate Ribbon clients for each version of a service for the canary deployment.
Modeling them as different target instances behind the same Ribbon client makes perfect sense.

**Comment by ryanjbaxter** [comment] 2017-11-18 12:47
I am going to close this as a duplicate of #2439

**Closed by ryanjbaxter** 2017-11-18 12:47 UTC
Labels: waiting for feedback
