### ISSUE TITLE
Connect to Config Service from Config client via Eureka in a load balanced way.

### ISSUE THREAD

**Issue by jbaurchn** [spring-cloud/spring-cloud-netflix#2139] opened 2017-07-19 10:31 UTC
We are using Spring cloud config service along with eureka and zuul in our environment.

We have registered the config service as a eureka client in the registry along with Zuul.

We have multiple instances of config service , Eureka as well as Zuul. We also have a F5 load balancer in front of Zuul to route the external requests in a load balanced manner.

From the Config clients, we are connecting to Config Service as below.
We are using the F5 load balancer url because , we can load balance and choose Zuul instance from that and then Zuul can load balance and choose a config service instance via Eureka/Ribbon.

But, we feel it might have a performance impact because there are multiple hops from config client to F5 and then to Zuul and then to Config Service and then on the reverse sending while getting the response.

Is there a way to lookup a instance of Config Service from config client in a load balanced way without going via F5 or Zuul, but via Eureka.

I currently see there is only a config service url which can be provided as configuration. 

Is there a way to customize the lookup of Config Service instances to go via Eureka in a load balanced way.

**Comment by jbaurchn** [comment] 2017-07-19 14:38
I see there is an option with the below config,
`spring.cloud.config.discovery.enabled=true`
and  service clients can lookup with the registered serviceId of config service.

But, the concern is, when the services startup up they need the Eureka registration url which is common for all services so they are part of the application.yml in config repo maintained via config service.

So, when they startup up they need to first fetch eureka registration url from configuration from common application.yml in config repo via config service.

That is possible, only if they know the url of config service. If we supply that as part of the command line for each service at startup , then it  becomes difficult to support high availability of config service(add /remove config service instances) as well maintenance if the config service changes location . 

This has the downside, that we will end up with recycling every service whenever the config service changes location or we add/remove config service instances.

So, we came up with the option of accessing the config service via F5 and Zuul to provide high availability and better maintenance. Config server is still registered with eureka but access via F5 and the zuul proxy.

But, we see the performance issues with multiple hops to get the configuration. 

Is there a better way to address this.

**Comment by spencergibb** [comment] 2017-07-19 16:50
I believe this is a duplicate of https://github.com/spring-cloud/spring-cloud-config/issues/514

**Comment by spencergibb** [comment] 2017-10-31 17:20
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2017-10-31 17:20 UTC
Labels: waiting for feedback
