### ISSUE TITLE
Proxy settings for Zuul Simple Routing Filter

### ISSUE THREAD

**Issue by rbkumar88** [spring-cloud/spring-cloud-netflix#1219] opened 2016-08-01 15:03 UTC
Hi,

Is there any way where we can set proxy host and proxy port for specific simple Zuul routes?

Thanks
Bharath

**Comment by ryanjbaxter** [comment] 2016-08-03 18:47
Zuul is the proxy in this case....so it is proxying the request to another server.  I am not sure I understand your question.

**Comment by rbkumar88** [comment] 2016-08-04 02:56
Hi,

I am not talking about Zuul/reverse proxy, am talking about the corporate/enterprise proxy for some of the urls. Something like below ...

HttpClientBuilder clientBuilder = HttpClientBuilder.create();

			clientBuilder.useSystemProperties();
			
			clientBuilder.setProxy(new HttpHost(PROXY_HOST, PROXY_PORT));

**Comment by spencergibb** [comment] 2016-08-04 19:08
If you are talking about the http client in `SimpleHostRoutingFilter`, then not currently. `SimpleHostRoutingFilter` isn't as configurable as the `RibbonCommand` used in `RibbonRoutingFilter`. We should make it simpler to customize.

**Comment by spencergibb** [comment] 2016-09-09 17:16
Duplicate of #510?

**Comment by spencergibb** [comment] 2016-10-05 21:25
Closed via f094ecfd889be7c22d26e939fa0650b6b6b3642e

**Closed by spencergibb** 2016-10-05 21:25 UTC
Labels: question
