### ISSUE TITLE
Using Exceptions in FeignClient Fallback

### ISSUE THREAD

**Issue by harthorst** [spring-cloud/spring-cloud-netflix#1117] opened 2016-06-19 20:26 UTC
Hi.

I'd like to get access to the Exception causing a call of fallback method in FeignClient annotated clients.
Something like this:

```
public interface ServiceInterface {
// ... some mvc annotations
public void iFailSometimes(String s);
}
```

```
@FeignClient(name = "hello", fallback = HystrixClientFallback.class)
public interface HystrixClient extends ServiceInterface {
}
```

```
// will not work
public class HystrixClientFallback {
public void iFailSometimes(String paramOfServiceInterface, Exception paramNotPartOfServiceInterface) {

// do something with the Exception

return "fallback";
}
}
```

The problem is, that HystrixClientFallback has to implement the HystrixClient iterface which has no Exception parameter in the iFailsometimes method. The FeignClientFactoryBean.HystrixTargeter checks whether the fallback class is derivied from the client interface. Maybe it makes sense to change this behavior to accept also methods which have an additional exception parameter and pass the exception object to it in case of an error.

Would this be a useful extension?

**Comment by cforce** [comment] 2016-06-20 06:54
+1
Very useful, i need the same.

**Comment by tjuchniewicz** [comment] 2016-08-04 14:06
`FeignClientFactoryBean.HystrixTargeter` only checks for proper interface. Real work is done by [Feign ](https://github.com/OpenFeign/feign). See [HystrixInvocationHandler](https://github.com/OpenFeign/feign/blob/82a3aac8313eb3b29139b467ffa813de246dd72f/hystrix/src/main/java/feign/hystrix/HystrixInvocationHandler.java#L113). Maybe better solution would be to allow such code:

```java
public interface ServiceInterface {
   // ... some mvc annotations
   public void iFailSometimes(String s);
}

@FeignClient(name = "hello", fallback = HystrixClientFallback.class)
   public interface HystrixClient extends ServiceInterface {
}
   
public class HystrixClientFallback extends HystrixClient {
   // standard fallback
   @Override
   public void iFailSometimes(String s) {

   }
   // prefer this fallback if available. The same signature method as a standard fallback + Exception
   public void iFailSometimes(String paramOfServiceInterface, Exception paramNotPartOfServiceInterface)    {
      // do something with the Exception
      return "fallback";
   }
}
```

so no changes needed on Spring Cloud Netflix. 
We need to talk with Feign guys.

**Comment by tjuchniewicz** [comment] 2016-08-05 12:09
Please take a look at the changes in Feign Hystrix in my private branch: https://github.com/ebjwc/feign/tree/gh-431/hystrix

**Comment by cforce** [comment] 2016-08-05 14:48
From your above example i assume that now we are able to inspect the server side (or is it a feign exception) exception (which one is that?) in the fallback.
I would like to have that for functional exception (which is a regular server use case) Feign never will raise the fallback.  This said, all (checked) exceptions defined on the server interface spec should not lead our control flow into the fallback execution. This can be reached by scanning the interface for the defined exceptions (and its childs) and switch on that base to go or not to go into the fallback.

**Comment by tjuchniewicz** [comment] 2016-08-08 08:02
This is feign exception.

Please create separate ticket for your idea about checked exceptions.

**Comment by tjuchniewicz** [comment] 2016-08-09 06:16
@harthorst Any real life use-case for this change? Please see comments: https://github.com/OpenFeign/feign/issues/431

**Comment by adriancole** [comment] 2016-08-16 14:41
So, there's a fork in the road to solve this.

Either we just log the cause of the fallback (simple change)
Or, we make it programmatically accessible.

Here's a PR that I think will be a sustainable option for the latter, if there's a real use-case for programmatically accessing the fallback's cause. https://github.com/OpenFeign/feign/pull/443

**Comment by tjuchniewicz** [comment] 2016-08-16 17:28
Still no real life use-case so from my side we can close this issue but... your proposal can't be easily integrated into `@FeignClient` (from Spring Cloud Netflix).  At least `@FeignClient` implementation must be changed. My idea was not to change anything except Feign.

**Comment by spencergibb** [comment] 2016-08-16 17:33
@tjuchniewicz I think we'll keep this open.

**Comment by adriancole** [comment] 2016-08-17 00:53
ps it is correct that spring-cloud-netflix will need to be changed to support the lateest fallback-with-cause via factory design. There are a couple ways to do this..

* do a minor that bumps to a release of feign with the thing, and inspect the provided fallback to see if it self-implements fallbackfactory; dispatch accordingly to the HystrixFeign object.
* do something less minor which declares a bean for the fallbackfactory
* something else!

**Comment by seetharamani** [comment] 2016-09-07 21:24
Does this mean even when i use 9.3.1 version, i wont be able to make use of FallbackFactory and get to know the cause ?

**Comment by spencergibb** [comment] 2016-09-07 21:30
Not using `@FeignClient`. We would need to build that integration. Hence the `help-wanted` label. You could use Feign directly.

**Closed** 2016-10-05 00:46 UTC
Labels: enhancement, help wanted
