### ISSUE TITLE
Upgrading from Spring Cloud Angel.SR4 to Brixton.M3 Breaks RestTemplate Injection

### ISSUE THREAD

**Issue by tkvangorder** [spring-cloud/spring-cloud-netflix#726] opened 2015-12-16 17:31 UTC
I have an application where I am defining a RestTemplate in Java configuration and then injecting that into other beans.

```java
	@Bean(name="buildRestTemplate")
	@ConditionalOnProperty(prefix = "eureka.client", name = "enabled", matchIfMissing=true)
	public RestTemplate buildRestTemplateRibbon(SpringClientFactory springClientFactory, LoadBalancerClient loadBalancerClient) {

		RestTemplate restTemplate = new RestTemplate();
		restTemplate.setErrorHandler(new ServiceClientErrorHandler());

		//Decorate our rest template with a load balancing aware request factory.
		RibbonRetryHttpRequestFactory lFactory = new RibbonRetryHttpRequestFactory(springClientFactory, loadBalancerClient);
		restTemplate.setRequestFactory(lFactory);
		return restTemplate;
	}	

```

And I use Autowire: 

```java
public abstract class ServiceClient {
	
	@Autowired
	@Qualifier("buildRestTemplate")
	protected RestTemplate restTemplate;

.
.
.

```
I believe the issue is because there is now a metrics package in the spring netflix core: 

```
@Aspect
public class RestTemplateUrlTemplateCapturingAspect {
	@Around("execution(* org.springframework.web.client.RestOperations+.*(String, ..))")
.
.
```

Because this is applied to the RestOperations interface, I end up with a JDK proxy and I get an exception : 

```Can not set org.springframework.web.client.RestTemplate field com.build.client.ServiceClient.restTemplate to com.sun.proxy.$Proxy116```

Does this mean that where I autowire my RestClient I need to change all references to the RestOperations interface? Can I force Spring to use CGLib instead? 

Suggestions?

**Comment by spencergibb** [comment] 2015-12-16 18:10
Duplicate of https://github.com/spring-cloud/spring-cloud-commons/issues/66.  See [this comment specifically](https://github.com/spring-cloud/spring-cloud-commons/issues/66#issuecomment-165081043)

**Closed** 2015-12-16 18:11 UTC
Labels: duplicate

**Comment by tkvangorder** [comment] 2015-12-16 18:14
Thanks, I will change it to the interface.
