### ISSUE TITLE
@HystrixCommand not working on Java 8 default method in controller

### ISSUE THREAD

**Issue by ldirz80** [spring-cloud/spring-cloud-netflix#864] opened 2016-03-01 21:31 UTC
I have a problem using @HystrixCommand and am not sure if it is a bug or not.  The problem resides in using a default method in an interface that contains a @RequestMapping.

``` java
interface GreetingController
{
    static final String template    = "Hello, %s!";
    final AtomicLong    counter     = new AtomicLong();

    @RequestMapping("/greeting")
    @HystrixCommand
    default public String greeting(@RequestParam(value = "name", defaultValue = "World") String name)
    {
        return new String(counter.incrementAndGet() + " " + String.format(template, name));
    }
}
```

If I generate two classes, Greeting1 and Greeting2 as follows (mapped to /1 and /2 respectively)

``` java
@RequestMapping("/1")
@RestController
public class Greeting1 implements GreetingController
{}
```

If I leave out the @HystrixCommand then all is fine.[http://localhost:8080/1/greeting], I fail to generate any RESTful interfaces.  

Is this a problem or have I done something incorrect ?

``` gradle
buildscript {
    ext {
        springBootVersion = '1.3.3.RELEASE'
    }
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}") 
    }
}

apply plugin: 'java'
apply plugin: 'spring-boot' 

jar {
    baseName = 'demo'
    version = '0.0.1-SNAPSHOT'
}
sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    mavenCentral()
    maven { url "https://repo.spring.io/snapshot" }
    maven { url "https://repo.spring.io/milestone" }
}


dependencies {
    compile('org.springframework.cloud:spring-cloud-starter-hystrix')
    compile('org.springframework.boot:spring-boot-starter-web')
}

dependencyManagement {
    imports { 
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:Brixton.BUILD-SNAPSHOT" 
    }
}

task wrapper(type: Wrapper) {
    gradleVersion = '2.9'
}

```

**Comment by dsyer** [comment] 2016-03-03 13:01
I also noticed that `@HystrixCommand` doesn't work on a `@Configuration` class that is itself a `@RestController`. Not sure why, but maybe related. Default methods are a new thing to try with Spring AOP generally. Whether or not it works is unlikely to be in the control of this project.

**Comment by marcingrzejszczak** [comment] 2018-09-10 13:10
@ldirz80 can you please check if the problem is still there with the latest release?

**Comment by spencergibb** [comment] 2018-10-01 23:02
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2018-10-01 23:02 UTC
Labels: waiting for feedback
