### ISSUE TITLE
Circuit Breaker exception ignoring failed in HystrixCommands.from() for WebFlux 

### ISSUE THREAD

**Issue by BondarenkoIlya** [spring-cloud/spring-cloud-netflix#3642] opened 2019-09-03 12:25 UTC
Hello! 

I run into problem during Hystrix Circuit Breaker set-up for WebFlux application. I want to apply CB feature on reactive webClient and activate CB depend on type of exception occurs during call. Example: 500 server error should trigger CB but 400 should not. As soon as I didn't find any build in capability to add exception which should be ignored (like property "ignoreException" in HystrixCommand annotation), I decided to catch exception and wraps it into HystrixBadRequestException which should not trigger fallback and CB according the documentation. This approach works till the very first circuit breaker opening: exception is thrown in normal way every interaction until any other request with another exception trigger CB. Right after some request trigger it once there is no any chance to stop trigger CB and fallback by HystrixBadRequestException. 
Am I trying to ignore exception in wrong way using reactive approach or it is real problem?

Thank you in advanced!

**Comment by ryanjbaxter** [comment] 2019-09-16 15:10
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment] 2019-09-23 15:10
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-09-30 15:15
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-09-30 15:15 UTC
Labels: feedback-reminder, waiting for feedback
