### ISSUE TITLE
Loss of ZuulFilter request body

### ISSUE THREAD

**Issue by fzng** [spring-cloud/spring-cloud-netflix#3547] opened 2019-05-30 03:16 UTC
Excuse me, when I use **ZuulFilter**, I rewrote the **userAccessIdentification** method. When I **return true**, the forwarded service will not receive the request parameters.

  if(requestUri.startsWith("/tms")){
           //It's here to go back.
            return true;
   }

`
private boolean userAccessIdentification(RequestContext ctx, String serverToken) throws Exception {
        HttpServletRequest req = ctx.getRequest();
        MultiReadHttpServletRequest request = new MultiReadHttpServletRequest(req);

        final String requestUri = request.getRequestURI().substring(zuulPrefix.length());
        final String method = request.getMethod();

        if (isStartWith(requestUri)) {
            return true;
        }

        AppPermission appPermission;
        String userTokenByHeader = ComUtil.getTokenByHeader(request, CommonConstant.System.USER_TOKEN_HEADER, log);
        ApplicationJwt applicationJwt = new ApplicationJwt(getUserPubKey());
        JwtInfoInfc tokenInfo = applicationJwt.getInfoFromToken(userTokenByHeader);

        String userAppId = tokenInfo.getAid();

            ResponseModel<AppPermission> permissionModel = gatewayTokenUtil.getPermission(userAppId, new String(Base64.encodeBase64(serverToken.getBytes()), StandardCharsets.UTF_8));

        if (!ComUtil.responseSuccess(permissionModel)) {
            log.warn(String.format("Cannot find the list of permissions for appId [%s]", appId));
            ErrorCodeEnum errorEnum = ErrorCodeEnum.INVALID_SAFE_PERMISSION;
            BaseException baseException = new BaseException(errorEnum.getMsg(), errorEnum.getCode());
            ctx.set(CommonConstant.System.SPRING_EXCEPTION_SIGN, baseException);

            return false;
        } else {
            appPermission = permissionModel.getData();
        }

        boolean ableToAccess = false;

        List<AppOperating> operatingList = appPermission.getOperatingList();
        if (ComUtil.isEmpty(operatingList) || operatingList.isEmpty()) {
            log.warn(String.format("Cannot find the list of operating for appId [%s]", appId));
            ctx.set("error.status_code", HttpServletResponse.SC_INTERNAL_SERVER_ERROR);

            ErrorCodeEnum invalidSafeOperating = ErrorCodeEnum.INVALID_SAFE_OPERATING;
            BaseException baseException = new BaseException(invalidSafeOperating.getMsg(), invalidSafeOperating.getCode());
            ctx.set(CommonConstant.System.SPRING_EXCEPTION_SIGN, baseException);
            return false;
        }

        if(requestUri.startsWith("/tms")){
           //It's here to go back.
            return true;
        }

        int operatingListSize = operatingList.size();
        AntPathMatcher ant = new AntPathMatcher();
        for (int i = 0; i < operatingListSize; i++) {

            AppOperating operating = operatingList.get(i);
            if (ant.match(operating.getOperUri(), requestUri) && ant.match(operating.getMethod(), method.toLowerCase())) {
                ableToAccess = true;
                break;
            }
        }

        if (!ableToAccess) {
            log.warn(String.format("Current user [%s] cannot access to %s [%s]", userAppId, requestUri, method));
            ctx.set("error.status_code", HttpServletResponse.SC_INTERNAL_SERVER_ERROR);

            ErrorCodeEnum errorEnum = ErrorCodeEnum.FORBIDDEN;
            BaseException baseException = new BaseException(errorEnum.getMsg(), errorEnum.getCode());
            ctx.set(CommonConstant.System.SPRING_EXCEPTION_SIGN, baseException);
        }

        return true;
    }
`

**Comment by ryanjbaxter** [comment] 2019-06-03 16:08
Please provide a description of what the problem is and a sample that reproduces the problem.

**Comment by spring-issuemaster** [comment] 2019-06-10 16:11
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-06-17 16:11
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-06-17 16:11 UTC
Labels: feedback-reminder, waiting for feedback
