### ISSUE TITLE
Delay in getServices() method of EurekaDiscoveryClient

### ISSUE THREAD

**Issue by subhrm** [spring-cloud/spring-cloud-netflix#2292] opened 2017-09-22 13:56 UTC
Hi,

I am using the method `getServices()` of `DiscoveryClient` interface to to get a list of registered instances. 

I have noticed that, the method does not return the name of a registered service for about 30 secs after its registered and can be seen at Eureka home portal `http://localhost:8761/` .  

The same is true for unregistered services. The method returns the name of the service for about 30 secs after its unregistered from eureka server .  

Code:

    import java.util.List;
    import java.util.StringJoiner;
    import org.springframework.beans.factory.annotation.Autowired;
    import org.springframework.cloud.client.ServiceInstance;
    import org.springframework.cloud.client.discovery.DiscoveryClient;
    import org.springframework.stereotype.Component;

    @Component
    public class DiscoveryHelper {

        // Implemeted in :
        // spring-cloud-netflix/spring-cloud-netflix-eureka-client
        //  /src/main/java/org/springframework/cloud/netflix/eureka/EurekaDiscoveryClient.java 

        @Autowired
        private DiscoveryClient discoveryClient;

        public List<String> discoverServices() {
            return discoveryClient.getServices();
        }
     }

**Comment by ryanjbaxter** [comment] 2017-09-25 18:53
What version of Spring cloud are you using?  If you are not using `Camden.SR7` or `Dalston.SR3` could you please try again with either one of those versions?

**Comment by subhrm** [comment] 2017-10-04 08:00
I have tried both `Camden.SR7` and  `Dalston.SR3` . In both the releases, I am getting the same delay.

**Comment by ryanjbaxter** [comment] 2017-10-04 15:33
I cannot reproduce this.  Can you provide a sample that reproduces that problem?

**Comment by spencergibb** [comment] 2018-01-18 00:37
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2018-01-18 00:37 UTC
Labels: waiting for feedback
