### ISSUE TITLE
HealtCheck status during shutdown

### ISSUE THREAD

**Issue by lechen26** [spring-cloud/spring-cloud-netflix#3986] opened 2021-04-08 06:46 UTC
Hi

i have a spring boot app (2.2.7.RELEASE) with Spring cloud (Hoxton.SR6) and i have an issue with Cronjob on K8s and i wonder if its a bug or misconfiguration from our side.

sometimes when the spring application finishing the work and status changed to DOWN we get the additional error of healthcheck failure.

```
Saw local status change event StatusChangeEvent [timestamp=1617818479572, current=DOWN, previous=UP]
Saw local status change event StatusChangeEvent [timestamp=1617818479586, current=OUT_OF_SERVICE, previous=DOWN]
hutting down DiscoveryClient ...
DataSource health check failed org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: HikariDataSource HikariDataSource (Hikari) has been closed. at
DiscoveryClient_MYJOB/MyJob:73ddcf20013a9695468c8e436e5a0620: registering service...
DiscoveryClient_MYJOB/MyJob:73ddcf20013a9695468c8e436e5a0620 - registration status: 204
Completed shut down of DiscoveryClient
```

i understand the app is in the process of shutdown.
why when app changes the status to DOWN the org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler checks the status of all Health Indicator. its obvious some of them will fail no?

i'm trying to understand how to handle this as i'm not sure its a bug or misconfiguration on our side.

thanks!
CL

**Comment by spencergibb** [comment] 2021-04-19 14:52
Duplicates https://github.com/spring-cloud/spring-cloud-commons/issues/943

**Comment by spencergibb** [comment] 2021-04-19 15:37
What you described is working as designed. How could the `EurekaHealthCheckHandler` know the context?

**Comment by spring-cloud-issues** [comment] 2021-04-26 15:37
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2021-05-03 15:40
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2021-05-03 15:40 UTC
Labels: feedback-reminder, waiting for feedback
