### ISSUE TITLE
Refresh config make the application hold many threads

### ISSUE THREAD

**Issue by ralphgj** [spring-cloud/spring-cloud-netflix#2297] opened 2017-09-26 09:28 UTC
I requested to the url http://localhost:8080/bus/refresh in my application, the methods of EurekaClientConfiguration#eurekaClient(in spring-cloud-netflix-eureka-client-1.3.4.RELEASE.jar) and RefreshableEurekaClientConfiguration#eurekaClient would both be invoked, and the method of CloudEurekaClient#shutdown would just be invoked once.  Since I refresh the config multiple times, the application will hold a lot of threads(thread named "DiscoveryClient-%d"). How can I resolve the problem?

dependency:
 + spring-boot: 1.5.2
 + spring-cloud: Dalston.SR3

**Comment by ryanjbaxter** [comment] 2017-09-26 14:31
That all makes sense why those methods are invoked but I dont see how that relates to the threads being held onto.  Can you provide any more information on what the threads are doing?

**Comment by dpy1123** [comment] 2017-09-27 03:05
I came up with the same issue.
dev env with: config erueka zuul bus kafka
I use git webhook and bus to auto refresh zuul routing config. After a week, found out that over 3000 threads were created.
thread dump report here: [report from fastthread](http://fastthread.io/my-thread-report.jsp?p=c2hhcmVkLzIwMTcvMDkvMjcvLS1hcGktZ2F0ZXdheS50eHQtLTItNDctMw==)
And figure out that, everytime when call the `XXX/bus/refresh` endpoint, will cause threads number increase by 7. 
increased thread list:
```
DiscoveryClient-0       3
xxxx-cleaner            2
xxxx-intutls            1
asyncResolver-bootstrap 1
```
After some debugging and tracing, I find that when refresh , 
first will call `EurekaClientConfiguration#eurekaClient` and then call `RefreshableEurekaClientConfiguration#eurekaClient`.
science annotation of these are `@ConditionalOnMissingRefreshScope` and `@ConditionalOnRefreshScope`, I think only one of them will be invoke.

Anyway, just present some info.

**Comment by ralphgj** [comment] 2017-09-28 02:48
The problem I met just liked @dpy1123 described. 

And, by the way, I debugged and found the ApplicationContext in `EurekaClientConfiguration` is `org.springframework.context.annotation.AnnotationConfigApplicationContext`,  while in `RefreshableEurekaClientConfiguration` is `org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext`. I supposed, maybe the two contexts cause the problem.

Is this information enough to understand the problem?

**Comment by ryanjbaxter** [comment] 2017-10-04 15:16
@ralphgj @dpy1123 I cannot seem to reproduce this.  I am using the config server from https://github.com/spring-cloud-samples/configserver.  I created a config client with
```
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-bus-amqp</artifactId>
		</dependency>
```

Also using Eureka as a service discovery service.

When I hit `http://localhost:8888/admin/bus/refresh` I ONLY see `RefreshableEurekaClientConfiguration` being run.  I DO NOT see `EurekaClientConfiguration` being run.

Is there some kind of configuration I am missing?

**Comment by ralphgj** [comment] 2017-10-09 08:42
@ryanjbaxter I found this problem with my config client application, not  the config server. When I hit `/bus/refresh` in the config server, the config client was refreshing through the bus. And then,  `RefreshableEurekaClientConfiguration` and `EurekaClientConfiguration` both were running in the config client application.

Here is my dependency.
config server with
```xml
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-hystrix</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-eureka</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-config-server</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bus-kafka</artifactId>
        </dependency>
```
config client with:
```xml
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-config</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bus-kafka</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-eureka</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-hystrix</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-zuul</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-sleuth</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-sleuth-stream</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-binder-kafka</artifactId>
        </dependency>
```

**Comment by spencergibb** [comment] 2018-01-18 00:38
@ralphgj is this still an issue with Edgware.SR1?

**Comment by spencergibb** [comment] 2018-04-25 19:25
@DustyDuprel I don't think it's related, see #2228

**Comment by spencergibb** [comment] 2018-04-25 19:25
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2018-04-25 19:25 UTC
Labels: waiting for feedback
