### ISSUE TITLE
Rest endpoint /eureka/apps/delta is not returning delta correctly

### ISSUE THREAD

**Issue by piyushkumar13** [spring-cloud/spring-cloud-netflix#3347] opened 2019-01-15 13:55 UTC
I am updating the eureka metadata with key `weight` and `some value` using endpoint `/eureka/apps/${app-name}/${app-id}/metadata?weight=40`. I am calling this update metadata api **once** for each of my registered service instances(eureka client registered with eureka) in a **loop**(registered instances are two and it can be more). Simultaneously, I am hitting the endpoint `/eureka/apps/delta` but this endpoint sometimes returning the response with the updates I have done using update metadata api and sometimes its not.  <br/>
Just to re-verify my above result, I have deployed zuul application, registered it with eureka and customized the Ribbon configuration- getting the **servers from loadbalancers** and **from returned server fetching InstanceInfo** object and printing **InstanceInfo.getMetadata** . This also sometimes giving the correct updated metadata and sometimes not.

**Note** : I am using Spring cloud version `Edgware.SR4`. 

Have a look at this snapshot Response of /eureka/apps/delta after update metadata call

<img width="1332" alt="screen shot 2019-01-15 at 10 06 08 pm" src="https://user-images.githubusercontent.com/13505531/51197849-9e76b500-1918-11e9-896e-759d6b5b5e46.png">

**Comment by ryanjbaxter** [comment] 2019-01-15 16:09
There is nothing here pointing to an issue with Spring Cloud as you are just using the Netflix Eureka endpoints.  It would be worth trying Finchley.SR2 and seeing if you have the same issue.

**Comment by piyushkumar13** [comment] 2019-01-15 17:20
Ok. Looks like Finchley.SR2  uses spring boot 2(correct me if i am wrong)?
Currently, we are using Spring boot 1.5.x version.

**Comment by ryanjbaxter** [comment] 2019-01-15 19:10
Yes that is correct

**Comment by piyushkumar13** [comment] 2019-01-16 16:14
@ryanjbaxter Ok..we might not use that.It might break the existing code. 
I have raised the issue in `netflix/eureka` repo. Here is the issue https://github.com/Netflix/eureka/issues/1173 . I dont see any response on the issue yet. If its possible for you to intimate any of their contributor about this, would a great help for me.

**Comment by spencergibb** [comment] 2019-01-22 21:42
Closing in favor of the Netflix issue. If needed, we can reopen if it's determined the problem is here.

**Closed by spencergibb** 2019-01-22 21:42 UTC
Labels: feedback-provided

**Comment by piyushkumar13** [comment] 2019-01-24 05:15
Ok @spencergibb .
There is no activity happened on the ticket I had raised in netflix library. Is it possible, if you can ping anyone from netflix contributors to have a look at the ticket.
