### ISSUE TITLE
Although the produces attribute is set to "application/json", the returned result is still in XML format

### ISSUE THREAD

**Issue by Surrin1999** [spring-cloud/spring-cloud-netflix#4039] opened 2021-10-01 03:00 UTC
**Describe the bug**
My **spring-cloud-starter-netflix-eureka-server** version is **3.0.4**, though i set the produces attribute as "application/json" in controller, it still returns xml format

**Sample**
![image](https://user-images.githubusercontent.com/37960540/135559026-0edba783-eee0-4339-9e4f-9cdf1007f33b.png)
![1633057426(1)](https://user-images.githubusercontent.com/37960540/135559069-0396f5d0-aae0-448c-8d58-aa07e22017cc.jpg)

**Comment by OlgaMaciaszek** [comment] 2021-11-17 21:20
This looks like something that is handled by the application code, not by Eureka. We can take a closer look, but please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-cloud-issues** [comment] 2021-11-24 21:25
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2021-12-01 21:25
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2021-12-01 21:25 UTC
Labels: waiting for feedback, feedback-reminder
