### ISSUE TITLE
Client load-balancing not working when instances running on different datacenters

### ISSUE THREAD

**Issue by fiunchinho** [spring-cloud/spring-cloud-netflix#2964] opened 2018-05-23 15:40 UTC
We are running Spring Cloud applications on AWS, using Eureka as service discovery, and hystrix+feign+ribbon to service to service communication.

We are now migrating applications to another datacenter, so we want to start deploying a single instance of one of our applications to that datacenter, but still using the same Eureka cluster as service discovery, so that services can communicate with each other. Our Eureka cluster consist on three different instances running on the same AWS region, each instance running on a different availability zone.

As soon as we deploy one instance of APPLICATION-1 and it's running on the new cluster, all the requests coming to APPLICATION-1 (requests coming from APPLICATION-2 or APPLICATION-3) end up on this instance, and the AWS instances for APPLICATION-1 get no requests at all.

If we remove the instance running on the new datacenter, then all APPLICATION-1 instances running on AWS start receiving traffic normally.

This is our Eureka instance configuration for all our applications
```
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    useDnsForFetchingServiceUrls: true
    eurekaServerDNSName: ${CLOUD_EUREKA}
    eurekaServerPort: 8080
    eurekaServerURLContext: eureka-server/v2
    region: eu-west-1
  instance:
    hostname: ${HOSTNAME}
    nonSecurePort: 80
    preferIpAddress: false
    instanceId: ${INSTANCE_ID}
```

And the application that's trying to send requests to the app called "myapp"
```
feign:
  hystrix:
    enabled: true
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 2000
  MaxAutoRetries: 1
myapp:
  value: "myapp"
  ReadTimeout: 1000
  ConnectTimeout: 1000
```

We detected that the information being stored on Eureka about all the instances from APPLICATION-1 is different depending on where the instance is running. [Instances running on AWS have datacenter metadata information about AWS](https://cloud.spring.io/spring-cloud-netflix/multi/multi__service_discovery_eureka_clients.html#_using_eureka_on_aws), like the availability zone.
But instances running outside AWS, don't have that metadata, and it says the datacenter is "MyOwn".

Then this is the configuration I've tried (I randomly selected "eu-west-1a", but you could write "eu-west-1c")
```
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    useDnsForFetchingServiceUrls: true
    eurekaServerDNSName: ${CLOUD_EUREKA}
    eurekaServerPort: 8080
    eurekaServerURLContext: eureka-server/v2
    region: eu-west-1
  instance:
    hostname: ${HOSTNAME}
    nonSecurePort: 80
    preferIpAddress: false
    instanceId: ${INSTANCE_ID}
    metadataMap:
      zone: "eu-west-1a"
```

I tried hardcoding metadata information on the instance running outside AWS (the one that was receiving all the requests), then all the instances, both inside and outside AWS, start receiving traffic in a round robbin fashion.
This seems to work but I don't know why, or the potential implications of this change.

Any ideas?

**Comment by ryanjbaxter** [comment] 2018-05-23 19:22
Can you supply the output of `/eureka/apps` so we can see the difference between the instances deployed on AWS and the one that isnt?

**Comment by fiunchinho** [comment] 2018-05-24 08:05
These are both instances registered on Eureka, the first one is running outside AWS
```
{
  "application": {
    "name": "MYAPP",
    "instance": [
      {
        "instanceId": "myapp-2192356809-6nsf5",
        "hostName": "myapp.public-dns.com",
        "app": "MYAPP",
        "ipAddr": "myapp.public-dns.com,
        "status": "UP",
        "overriddenstatus": "UNKNOWN",
        "port": {
          "$": 80,
          "@enabled": "true"
        },
        "securePort": {
          "$": 443,
          "@enabled": "false"
        },
        "countryId": 1,
        "dataCenterInfo": {
          "@class": "com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
          "name": "MyOwn"
        },
        "leaseInfo": {
          "renewalIntervalInSecs": 30,
          "durationInSecs": 90,
          "registrationTimestamp": 1527090938308,
          "lastRenewalTimestamp": 1527148706344,
          "evictionTimestamp": 0,
          "serviceUpTimestamp": 1527090938308
        },
        "metadata": {
          "@class": "java.util.Collections$EmptyMap"
        },
        "homePageUrl": "http://myapp.public-dns.com:80/",
        "statusPageUrl": "http://myapp.public-dns.com:80/info",
        "healthCheckUrl": "http://myapp.public-dns.com:80/health",
        "vipAddress": "myapp",
        "secureVipAddress": "myapp",
        "isCoordinatingDiscoveryServer": "false",
        "lastUpdatedTimestamp": "1527090938308",
        "lastDirtyTimestamp": "1527090937752",
        "actionType": "ADDED"
      },
      {
        "instanceId": "i-0ca1682cc2f744b2d",
        "hostName": "ip-192-168-xxx-xxx.eu-west-1.compute.internal",
        "app": "MYAPP",
        "ipAddr": "192.168.xxx.xxx",
        "status": "UP",
        "overriddenstatus": "UNKNOWN",
        "port": {
          "$": 8000,
          "@enabled": "true"
        },
        "securePort": {
          "$": 443,
          "@enabled": "false"
        },
        "countryId": 1,
        "dataCenterInfo": {
          "@class": "com.netflix.appinfo.AmazonInfo",
          "name": "Amazon",
          "metadata": {
            "public-ipv4": "52.xxx.xxx.xx",
            "accountId": "231205868121",
            "local-hostname": "ip-192-168-xxx-xxx.eu-west-1.compute.internal",
            "public-hostname": "ec2-xx-xxx-xxx-xx.eu-west-1.compute.amazonaws.com",
            "instance-id": "i-0ca1682cc2f744b2d",
            "local-ipv4": "192.168.xxx.xxx",
            "instance-type": "t2.micro",
            "vpc-id": "vpc-abcdc1234",
            "ami-id": "ami-1234abcd",
            "mac": "01:23:45:ab:cd:da",
            "availability-zone": "eu-west-1b"
          }
        },
        "leaseInfo": {
          "renewalIntervalInSecs": 30,
          "durationInSecs": 90,
          "registrationTimestamp": 1527139935264,
          "lastRenewalTimestamp": 1527148698668,
          "evictionTimestamp": 0,
          "serviceUpTimestamp": 1527139935264
        },
        "metadata": {
          "@class": "java.util.Collections$EmptyMap"
        },
        "homePageUrl": "http://ip-192-168-xxx-xxx.eu-west-1.compute.internal:8000/",
        "statusPageUrl": "http://ip-192-168-xxx-xxx.eu-west-1.compute.internal:8000/info",
        "healthCheckUrl": "http://ip-192-168-xxx-xxx.eu-west-1.compute.internal:8000/health",
        "vipAddress": "myapp",
        "secureVipAddress": "myapp",
        "isCoordinatingDiscoveryServer": "false",
        "lastUpdatedTimestamp": "1527139935264",
        "lastDirtyTimestamp": "1527139934856",
        "actionType": "ADDED"
      }
    ]
  }
}
```
It seems to work if I hardcode the metadata containing a random (it doesn't matter which one) availability zone, resulting in this information for the instance running outside AWS

```
{
        "instanceId": "myapp-2192356809-6nsf5",
        "hostName": "myapp.public-dns.com",
        "app": "MYAPP",
        "ipAddr": "myapp.public-dns.com,
        "status": "UP",
        "overriddenstatus": "UNKNOWN",
        "port": {
          "$": 80,
          "@enabled": "true"
        },
        "securePort": {
          "$": 443,
          "@enabled": "false"
        },
        "countryId": 1,
        "dataCenterInfo": {
          "@class": "com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
          "name": "MyOwn"
        },
        "leaseInfo": {
          "renewalIntervalInSecs": 30,
          "durationInSecs": 90,
          "registrationTimestamp": 1527090938308,
          "lastRenewalTimestamp": 1527148706344,
          "evictionTimestamp": 0,
          "serviceUpTimestamp": 1527090938308
        },
        "metadata": {
          "zone": "eu-west-1a"
        },
        "homePageUrl": "http://myapp.public-dns.com:80/",
        "statusPageUrl": "http://myapp.public-dns.com:80/info",
        "healthCheckUrl": "http://myapp.public-dns.com:80/health",
        "vipAddress": "myapp",
        "secureVipAddress": "myapp",
        "isCoordinatingDiscoveryServer": "false",
        "lastUpdatedTimestamp": "1527090938308",
        "lastDirtyTimestamp": "1527090937752",
        "actionType": "ADDED"
      }
```

**Comment by ryanjbaxter** [comment] 2018-05-30 20:49
From out documentation...

> If there is no other source of zone data, then a guess is made, based on the client configuration (as opposed to the instance configuration). We take eureka.client.availabilityZones, which is a map from region name to a list of zones, and pull out the first zone for the instance’s own region (that is, the eureka.client.region, which defaults to "us-east-1", for compatibility with native Netflix).

But if I understand you correctly all the clients have `eureka.client.region=eu-west-1` right?  So I would expect that we would be default to preferring only the clients registered in that region (which would not include the one in the new datacenter).

**Comment by fiunchinho** [comment] 2018-05-31 07:11
We have this bean defined for all our clients that sets the eu-west-1 region.

```
  @Primary
  @Bean
  public EurekaClientConfigBean configureEurekaClient() {
    EurekaClientConfigBean eurekaClientConfigBean = new EurekaClientConfigBean();
    eurekaClientConfigBean.setUseDnsForFetchingServiceUrls(true);
    eurekaClientConfigBean.setEurekaServerDNSName(environment.getProperty("CLOUD_EUREKA"));
    eurekaClientConfigBean.setEurekaServerPort(environment.getProperty("CLOUD_EUREKA_PORT", "8080"));
    eurekaClientConfigBean.setEurekaServerURLContext(environment.getProperty("CLOUD_EUREKA_PATH", "eureka-server/v2"));
    eurekaClientConfigBean.setRegion(environment.getProperty("EC2_REGION", "eu-west-1"));

    return eurekaClientConfigBean;
  }
```

One would expect that without AZ information available, it'd choose a random instance.

**Comment by ryanjbaxter** [comment] 2018-06-01 13:36
Maybe it has something to do with the region in the config bean and what is registered in eureka no matching?  All clients have a region set to `eu-west-1` but in what was returned from `/eureka/apps` the region in the metadata is `eu-west-1a` (for the ones deployed on amazon).

**Comment by fiunchinho** [comment] 2018-06-14 19:15
I don't understand. They all have the same region eu-west-1

**Comment by fiunchinho** [comment] 2018-06-15 07:52
Because one is an availability zone and the other one is the region. They can't never be equal because they are different things.

**Comment by fiunchinho** [comment] 2018-06-15 20:01
If you read my first comment on this ticket, I had no AZ set when the misbehavior was happening. Then I added 
```
"availability-zone": "eu-west-1b"
```

and it seems to work. So the mismatch wasn't there when the load balancing was failing. What's the value that should be set?

**Comment by ryanjbaxter** [comment] 2018-06-25 19:49
To be honest I am at a lost as to why this is happening.  Without having a way of reproducing what you are experiencing I am not sure how to dig into this.  Do you think it would be possible to reproduce this without actually requiring AWS?

**Comment by fiunchinho** [comment] 2018-06-26 20:06
Having two instances with different DataCenter info maybe?

**Comment by spencergibb** [comment] 2019-02-11 15:42
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment] 2019-02-18 15:47
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-02-25 15:47
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-02-25 15:47 UTC
Labels: feedback-reminder, waiting for feedback
