### ISSUE TITLE
HystrixManagementContextConfiguration  doesn't work with Spring Webflux.fn and Actuator

### ISSUE THREAD

**Issue by juergenzimmermann** [spring-cloud/spring-cloud-netflix#2438] opened 2017-11-12 13:19 UTC
My build.gradle file for a microservice based on Spring Boot 2.0.0.M6 (same with M5), Spring WebFlux.fn 5.0.1, Kotlin, Java VM 9.0.1, Spring Security, Spring Data, and Spring Cloud Finchley M3 has these dependencies:

```
implementation(
    ...
    'org.springframework.cloud:spring-cloud-starter-config',
    'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client',
    'org.springframework.cloud:spring-cloud-starter-netflix-hystrix',
    'org.springframework.cloud:spring-cloud-starter-openfeign',
    ...)
```

When I add the dependency `runtime ('org.springframework.boot:spring-boot-starter-actuator')` I get this error message at startup time:

```
...
nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException:
Error creating bean with name 'org.springframework.cloud.netflix.hystrix.HystrixManagementContextConfiguration':
Unsatisfied dependency expressed through constructor parameter 0;
nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException:
No qualifying bean of type 'org.springframework.boot.actuate.autoconfigure.web.servlet.ManagementServletContext' available:
expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
```

**Comment by ryanjbaxter** [comment] 2017-11-13 16:48
We dont yet support Boot 2.0.0.M6 in the Finchley release train, but if it is also happening with M5 can you please provide the complete project source code the reproduces the problem?

**Comment by juergenzimmermann** [comment] 2017-11-19 13:35
@ryanjbaxter A testcase is attached. My environment: JDK 9.0.1, Gradle 4.3.1 (see Gradle wrapper) and Windows 10 Enterprise.
[tc2438.zip](https://github.com/spring-cloud/spring-cloud-netflix/files/1485568/tc2438.zip)

**Comment by juergenzimmermann** [comment] 2017-11-23 16:27
@ryanjbaxter @spencergibb Is the testcase ok, or do you need anything else?

**Comment by ryanjbaxter** [comment] 2017-11-27 16:53
I am completely unfamiliar with Kotlin, but when I run `gradle build` I get a compilation error
```
:compileKotline: /Users/ryanjbaxter/Downloads/tc2438/src/main/kotlin/testcase/Application.kt: (5, 33): Unresolved reference: runApplication
e: /Users/ryanjbaxter/Downloads/tc2438/src/main/kotlin/testcase/Application.kt: (25, 5): Unresolved reference: runApplication
e: /Users/ryanjbaxter/Downloads/tc2438/src/main/kotlin/testcase/Application.kt: (26, 9): Unresolved reference: webApplicationType
```

**Comment by juergenzimmermann** [comment] 2017-11-27 17:12
Hmm, `runApplication` is available since Spring Boot 2.0.0.M6. I just downloaded the testcase, unzipped it, and just invoked `gradle` (the default task is `bootRun`). There was no compilation error. I'm having Java/JVM 9.0.1, gradle 4.4-rc-2, and Windows 10 Enterprise.
I'll attach the output of `gradle dependencies`. Could you check whether you really have Spring Boot 2.0.0.M6, please?
[dependencies.txt](https://github.com/spring-cloud/spring-cloud-netflix/files/1506831/dependencies.txt)

**Comment by ryanjbaxter** [comment] 2017-12-03 15:03
Is Java 9 required?

**Comment by spencergibb** [comment] 2018-01-10 04:35
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2018-01-10 04:35 UTC
Labels: waiting for feedback
