### ISSUE TITLE
zuul retry is not working 

### ISSUE THREAD

**Issue by chelailee** [spring-cloud/spring-cloud-netflix#2938] opened 2018-05-17 02:49 UTC
maven:
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.12.RELEASE</version>
        <relativePath/> 
    </parent>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Edgware.SR1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

here is my Configuration：

        spring:
          application:
            name: gateway
          cloud:
            loadbalancer:
              retry:
                enabled: true
        server:
          port: 7003
        eureka:
          client:
            serviceUrl:
              defaultZone: http://peer1:7001/eureka/,http://peer2:7002/eureka/
        
        zuul:
          host:
              socket-timeout-millis: 60000
              connect-timeout-millis: 60000
          retryable: true
          routes:
            admin-cloud-client:
              path: /admin-cloud-client/**
              servicesId: admin-cloud-client
        
        hystrix:
          command:
            default:
              execution:
                isolation:
                  thread:
                    timeoutInMilliseconds: 60000
              metrics:
                rollingStates:
                  timeInMilliseconds: 10000
              circuitBreaker:
                sleepWindowInMilliseconds: 5000
                requestVolumeThreshold: 5
                errorThresholdPercentages:  50
        
        ribbon:
          ReadTimeout: 5000 
          ConnectTimeout: 200 
          MaxAutoRetries: 0 
          MaxAutoRetriesNextServer: 1
          OkToRetryOnAllOperations: true

I have done anything I can do ,but
when one is down，"MaxAutoRetriesNextServer" can't working,it can't call the normal one.
please tell me what should i do,thank you very much

**Comment by Lovnx** [comment] 2018-05-17 07:54
:blush: add dependency:
        <dependency>  
            <groupId>org.springframework.retry</groupId>  
            <artifactId>spring-retry</artifactId>  
        </dependency>

**Comment by chelailee** [comment] 2018-05-17 08:40
thanks for your reminder,but,Actually, I have already done that

         <dependency>
            <groupId>org.springframework.retry</groupId>
            <artifactId>spring-retry</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-zuul</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-eureka</artifactId>
        </dependency>

**Comment by ryanjbaxter** [comment] 2018-05-17 16:35
Just saying it is not working is not going to allow us to help you.  Please provide a sample app that reproduces the problem you are seeing.

**Comment by chelailee** [comment] 2018-05-20 16:47
yes,of course. https://github.com/chelailee/zuul-retry

**Comment by spencergibb** [comment] 2019-01-31 19:37
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2019-01-31 19:37 UTC
Labels: feedback-provided
