### ISSUE TITLE
DiscoveryEnabledNIWSServerList Load balancer does not have available server for client: XXX

### ISSUE THREAD

**Issue by xiezhaofeng** [spring-cloud/spring-cloud-netflix#2531] opened 2017-12-08 09:08 UTC
eureka-provider)application.xml

```
server:
  port: 8800/8801
spring:
  application:
    name: eureka-provider
eureka:
  instance:
    virtualHostName: eureka-provider-vip
    preferIpAddress: true
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    statusPageUrlPath: ${management.context-path:}/info
    healthCheckUrlPath: ${management.context-path:}/health
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

```

eureka-provider)controller

```
@RestController
@RequestMapping("/user")
public class UserController {
    @RequestMapping("/hello/{fallback}")
    @HystrixCommand(fallbackMethod="helloFallbackMethod")
    public String hello(@PathVariable("fallback") String fallback){
        LOGGER.info("execute method hello, fallback: {}", fallback);
        if("1".equals(fallback)){
            throw new RuntimeException("...");
        }
        return "hello";
    }

    public String helloFallbackMethod(String fallback){
        return "fallback :"+fallback;
    }
}
```

eureka-provider)application

```
@SpringBootApplication
@EnableEurekaClient
@EnableHystrix
public class ProviderApplication {

	public static void main(String[] args) {
		SpringApplication.run(ProviderApplication.class, args);
	}
}
```

 eureka-server)application.xml

```
 server:
  application:
    name: eureka-server
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
zuul:
  routes:
    eureka-provider:
      path: /usersystem/**
      serviceId: eureka-provider
ribbon:
  eureka:
    enabled: false
eureka-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
    UseIPAddrForServer: true
    DeploymentContextBasedVipAddresses: eureka-provider-vip
#    listOfServers: 127.0.0.1:8800, 127.0.0.1:8801

```

eureka-server)application
```
@SpringBootApplication
@EnableEurekaServer
@EnableZuulProxy
public class EurekaServerApplication {

	public static void main(String[] args) {
		SpringApplication.run(EurekaServerApplication.class, args);
	}
}
```

demo1)
use: `listOfServers: 127.0.0.1:8800, 127.0.0.1:8801` 
url:http://localhost:8761/usersystem/user/hello/2
return:success

demo2)
use:`NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList`
url:http://localhost:8761/usersystem/user/hello/2
return: Internal Server Error
server: Load balancer does not have available server for client: eureka-provider

 need help?

**Comment by ryanjbaxter** [comment] 2017-12-08 18:23
Please provide more information, including a description of the problem.  Also instead of pasting code in an issue it is better to provide the complete working apps to reproduce the issue.

**Comment by spencergibb** [comment] 2017-12-08 18:43
Why are you setting `NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList`? It should be the default if you use the eureka starter. What are you dependencies?

**Comment by xiezhaofeng** [comment] 2017-12-09 09:41
@ryanjbaxter git：git@github.com:xiezhaofeng/demo.git
run：provider、eureka-server

use eureka-server(spring.profiles.active=demo2)：
      http://localhost:8761/usersystem/user/hello/2           success

use eureka-server(spring.profiles.active=demo1)：
      http://localhost:8761/usersystem/user/hello/2           failed

I need to dynamically discover the list of service providers and access them via zuul on eureka-server。

**Comment by xiezhaofeng** [comment] 2017-12-09 09:44
Use listOfServers too rigid

**Comment by xiezhaofeng** [comment] 2017-12-09 09:45
Use listOfServers too rigid

**Comment by ryanjbaxter** [comment] 2017-12-15 19:32
I would not make your Eureka Server app use Zuul as well.  I would separate them into two separate apps.  The reason things are not working is because your Eureka Server is not a Eureka Client.  I suppose you can make a server be a client as well but I dont see why you would want to.

**Comment by silentFred** [comment] 2018-08-23 15:51
Are eureka servers not supposed to be clients as well? This is how they form a cluster

**Comment by ryanjbaxter** [comment] 2018-08-27 22:55
You are right a eureka server is also a client but in this case Zuul was also involved.  I don’t remember the exact reason this was causing a problem but I still don’t see a reason to combine a eureka server and zuul

**Comment by xiezhaofeng** [comment] 2018-08-28 03:42
What I want to do is dynamically discover the provider instead of configuring the provider's IP in the yml file.

**Comment by ryanjbaxter** [comment] 2018-08-28 13:54
What is the “provider”?

**Comment by xiezhaofeng** [comment] 2018-08-28 14:28
the Eureka Server.

**Comment by spencergibb** [comment] 2018-08-28 14:47
eureka server and zuul shouldn't be mixed.

**Comment by spring-issuemaster** [comment] 2019-02-28 14:52
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.

**Closed by spring-issuemaster** 2019-02-28 14:52 UTC
Labels: question
