### ISSUE TITLE
Feign Client could not search the service by name in eureka

### ISSUE THREAD

**Issue by pkumar53** [spring-cloud/spring-cloud-netflix#3753] opened 2020-02-26 23:58 UTC
**Describe the bug**
I was trying for openfeign application and found that openfeign is not able to find the service by name in eureka server but works fine when i use the url attribute and hardcode the hostname and port.

Created two spring boot microservices with below details
Demo1 > application.properties
![image](https://user-images.githubusercontent.com/8732087/75398695-66fe7880-5920-11ea-9723-133cfb281e31.png)
Demo2>application.properties
![image](https://user-images.githubusercontent.com/8732087/75398730-809fc000-5920-11ea-9f3b-0d1559d56187.png)

![image](https://user-images.githubusercontent.com/8732087/75398780-9f05bb80-5920-11ea-9e2e-b912029b1d67.png)
![image](https://user-images.githubusercontent.com/8732087/75398803-b2b12200-5920-11ea-8d8b-32751fd1a872.png)
![image](https://user-images.githubusercontent.com/8732087/75398845-cb213c80-5920-11ea-8ca9-75704ee46043.png)
![image](https://user-images.githubusercontent.com/8732087/75398890-e2f8c080-5920-11ea-8411-f5615c7cd797.png)
![image](https://user-images.githubusercontent.com/8732087/75398941-fc017180-5920-11ea-8da9-71fcf549b7ec.png)

Output:
![image](https://user-images.githubusercontent.com/8732087/75399224-b3968380-5921-11ea-8b1c-a5a23cee5d95.png)
![image](https://user-images.githubusercontent.com/8732087/75399257-c741ea00-5921-11ea-85f5-507857e0c9e1.png)
 The second output after few seconds.

Can you please help here?
NOTE: The same thing worked only once from office but when i tried again another day its failing not sure why

**Comment by spencergibb** [comment] 2020-03-02 15:49
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by pkumar53** [comment] 2020-03-03 12:22
I resolved the issue by deleting all the unnecessary host names present in the host file. The issue was happening due to multiple host names present in the laptop's host file and the microservices were not registering with localhost or laptop name rather were registering with some other host name present in the host file. As soon as I deleted the host name from the host file, the services started registering with the correct host name and then communication between microservice started working properly.

**Comment by pkumar53** [comment] 2020-03-03 12:26
Wondering what if I need to have some other host name in the host file. In that case, how do I register my microservice with eureka for a correct hostname out of the many hostnames present in the host file.

**Comment by spencergibb** [comment] 2020-03-03 12:47
The host shouldn't really matter. If spring cloud can't make an accurate guess, you should set it explicitly

**Comment by pkumar53** [comment] 2020-03-03 12:54
is there any property available as I remember setting eureka.instance.hostname for the microservice but still it did not work at that time. If there is any other property, please let know.

**Comment by spencergibb** [comment] 2020-03-03 12:55
That is the property

**Comment by spring-issuemaster** [comment] 2020-03-10 12:57
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-03-17 12:59
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-03-17 12:59 UTC
Labels: feedback-reminder, question, waiting for feedback
