### ISSUE TITLE
Eureka client leaving sockets open, too many CLOSE_WAIT

### ISSUE THREAD

**Issue by imrangthub** [spring-cloud/spring-cloud-netflix#4224] opened 2023-11-20 04:09 UTC
**Describe the bug**
Please provide details of the problem, including the version of Spring Cloud that you
are using. 

**Sample**
If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

**Comment by imrangthub** [comment] 2023-11-20 04:12
My projedct, Spring boot 2.5.14 and spring cloud 2020.0.5 with java 17.
Here Eureka server has 20 clients. 
on netstat -ant |grep CLOSE_WAIT | wc -l command why show too many CLOSE_WAIT status

**Comment by BenEfrati** [comment] 2023-11-24 08:04
Already reported https://github.com/spring-cloud/spring-cloud-netflix/issues/4103

**Comment by OlgaMaciaszek** [comment] 2023-12-18 12:15
Closing as duplicate of gh-4103.

**Closed by OlgaMaciaszek** 2023-12-18 12:15 UTC
Labels: duplicate
