### ISSUE TITLE
Veracode testing identifies SimpleHostRoutingFilter.java 195 has "Improper Validation of Certificate with Host Mismatch" flaw

### ISSUE THREAD

**Issue by rajaks257** [spring-cloud/spring-cloud-netflix#1990] opened 2017-05-26 11:07 UTC
Hi,

We are using spring-cloud-netflix-core-1.2.6.RELEASE.jar

We got the below issue when we ran Veracode testing for our code.

**Improper Validation of Certificate with Host Mismatch (CWE ID 297)**

Class : SimpleHostRoutingFilter.java 
line no: 195

As per the issue, the code in SimpleHostRoutingFilter at line number 195 communicates with a host that provides a certificate, but the software does not properly ensure that the certificate is actually associated with that host.

Please do let us know your thoughts and reasons on this issue. We can use the same to mitigate the issue accordingly.

Thank you,
Raja

**Comment by ryanjbaxter** [comment] 2017-05-30 17:50
I believe this is a duplicate of #1684.

**Closed by ryanjbaxter** 2017-05-30 17:50 UTC
Labels: duplicate
