### ISSUE TITLE
IllegalArgumentException for '=' in query param using Ribbon load balancer with https

### ISSUE THREAD

**Issue by mage-ante** [spring-cloud/spring-cloud-netflix#3682] opened 2019-10-25 07:10 UTC
Checked around and found that this is literally the same problem as issue [#1291](https://github.com/spring-cloud/spring-cloud-netflix/issues/1291), except that it happens for '=' instead of '+'. 

Is there a workaround for the meantime? Thanks!

**Comment by ryanjbaxter** [comment] 2019-10-28 14:40
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment] 2019-11-04 14:42
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-11-11 14:41
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-11-11 14:41 UTC
Labels: feedback-reminder, waiting for feedback
