### ISSUE TITLE
EurekaDiscoveryClient.getServices always return one 

### ISSUE THREAD

**Issue by pigxcloud** [spring-cloud/spring-cloud-netflix#3700] opened 2019-11-29 05:13 UTC
version: 2.2.0.RELEASE

---

console  all application  normal 

![](http://pigx.vip/20191129131056_vDKiEJ_Screenshot.jpeg)

EurekaDiscoveryClient.getServices  only return one
![](http://pigx.vip/20191129131159_dmIdoY_Screenshot.jpeg)

result `SBA` not work
https://github.com/codecentric/spring-boot-admin/issues/1315

**Comment by pigxcloud** [comment] 2019-11-29 05:17
Looks like it's not updated  `localRegionApps`

**Comment by OlgaMaciaszek** [comment] 2020-01-09 17:06
Hello, @pigxcloud 
Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-issuemaster** [comment] 2020-01-16 17:10
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-01-23 17:07
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-01-23 17:07 UTC
Labels: feedback-reminder, waiting for feedback
