### ISSUE TITLE
Zuul can't handle jsonp request

### ISSUE THREAD

**Issue by hhymarco** [spring-cloud/spring-cloud-netflix#998] opened 2016-04-29 06:00 UTC
If request's jsonp ,like:
`http://localhost:9995/rp-redpacket/redpackets.rp?data={%22userId%22:312565121,%22cmd%22:%22Redpacket000001%22,%22version%22:%221.0.0%22}&callback=jsonp2`
zuul's RibbonRoutingFilter will occur ZuulException:
`Caused by: javax.ws.rs.core.UriBuilderException: java.net.URISyntaxException: Illegal character in query at index 48: http://192.168.20.61:9006/redpackets.rp?data=%7B"userId":312565121,"cmd":"Redpacket000001","version":"1.0.0"%7D at com.sun.jersey.api.uri.UriBuilderImpl.createURI(UriBuilderImpl.java:723) at com.sun.jersey.api.uri.UriBuilderImpl._build(UriBuilderImpl.java:651) at com.sun.jersey.api.uri.UriBuilderImpl.build(UriBuilderImpl.java:641) at com.sun.jersey.api.client.WebResource.<init>(WebResource.java:88) at com.sun.jersey.api.client.WebResource.queryParam(WebResource.java:443) at com.netflix.niws.client.http.RestClient.execute(RestClient.java:598) at com.netflix.niws.client.http.RestClient.execute(RestClient.java:527) at 
`
springcloud version is Brixton.RC2

**Comment by spencergibb** [comment] 2016-05-02 17:04
Duplicate of #918

**Closed by spencergibb** 2016-05-02 17:04 UTC

**Comment by thecorvus** [comment] 2018-03-12 03:09
Seem this is not a duplicate. this issue is cause by character " in JSON, but not {.
In this request, { is encoded, but " is not.

**Comment by spencergibb** [comment] 2018-03-12 03:12
@thecorvus commenting on an old closed issue is not very helpful. Brixton is unsupported now
