### ISSUE TITLE
Load balancer does not have available server for client

### ISSUE THREAD

**Issue by juangallino** [spring-cloud/spring-cloud-netflix#4044] opened 2021-10-21 03:51 UTC
@cleversonledur I created two pull requests that fix your problems.

The gateway wasn't pointed at eureka properly. And microservice, you set the `eureka.instance.*` settings to the server, which is incorrect.

_Originally posted by @spencergibb in https://github.com/spring-cloud/spring-cloud-netflix/issues/2530#issuecomment-358764694_

Hi! i am having the exact same problem, while routing with url every things works fine, but when trying to load balance with service id, gets this error

DynamicServerListLoadBalancer for client ms-usuarios initialized: DynamicServerListLoadBalancer:{NFLoadBalancer:name=ms-usuarios,current list of Servers=[],Load balancer stats=Zone stats: {},Server stats: []}ServerList:com.netflix.loadbalancer.ConfigurationBasedServerList@3fbf6276

Caused by: com.netflix.client.ClientException: Load balancer does not have available server for client: ms-usuarios

But in eureka I can see both service client registered.  actuator info.

"discoveryComposite": {"status":"UP","components":{"discoveryClient":{"status":"UP","details":{"services":["dan-gateway","ms-usuarios"]}},"eureka":{"description":"Remote status from Eureka server","status":"UP","details":{"applications":{"DAN-GATEWAY":1,,"MS-USUARIOS":2,}}}}},

**Comment by spencergibb** [comment] 2021-10-21 03:53
If you'd like us to spend some time investigating, please take the time to provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) (something that we can unzip attached to this issue or git clone, build, and deploy) that reproduces the problem.

**Comment by spring-cloud-issues** [comment] 2021-11-04 03:55
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2021-11-04 03:55 UTC
Labels: waiting for feedback, feedback-reminder
