### ISSUE TITLE
Circular reference error

### ISSUE THREAD

**Issue by Subrhamanya** [spring-cloud/spring-cloud-netflix#4386] opened 2024-12-03 17:09 UTC
Recently we uplifted spring cloud from 2022.x to 2023.x version and suddenly our eureka server application started failing with the error.

`Description:

The dependencies of some of the beans in the application context form a cycle:
```
┌─────┐
|  org.springframework.cloud.netflix.eureka.server.EurekaServerAutoConfiguration (field private com.netflix.appinfo.ApplicationInfoManager org.springframework.cloud.netflix.eureka.server.EurekaServerAutoConfiguration.applicationInfoManager)
↑     ↓
|  org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration$EurekaClientConfiguration (field private com.netflix.discovery.AbstractDiscoveryClientOptionalArgs org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration$EurekaClientConfiguration.optionalArgs)
└─────┘
```

Action:

Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting `spring.main.allow-circular-references` to `true.`

Not sure if this is the right place to ask. Can anybody help?? 

Setting `spring.main.allow-circular-references` to `true` works for now.

**Comment by OlgaMaciaszek** [comment] 2024-12-09 15:43
Hello @Subrhamanya, thanks for reporting the issue. Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-cloud-issues** [comment] 2024-12-16 15:48
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2024-12-23 15:48
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2024-12-23 15:48 UTC
Labels: feedback-reminder
