### ISSUE TITLE
[Question]zuul url configuration is unable get 200 response

### ISSUE THREAD

**Issue by Switch-vov** [spring-cloud/spring-cloud-netflix#2737] opened 2018-02-22 11:11 UTC
application.yml
``` yaml
server:
  port: 6176
spring:
  application:
    name: xxx_app
  http:
    encoding:
      force: true
      enabled: true
      charset: utf-8
eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    healthcheck:
      enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

zuul:
  ignored-services: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  add-host-header: true
  add-proxy-headers: true
  ribbon:
    eager-load:
      enable: true
  routes:
    github:
      path: /github/**
      url: https://api.github.com
      sensitive-headers:
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.100:8888/eureka,http://192.168.1.101:8888/eureka
```

if i send request to `http://localhost:6176/github/users/switch`

the response is
``` html
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <title>Unicorn! &middot; GitHub</title>
        <style type="text/css" media="screen">

        <!-- delete something -->

    </style>
    </head>
    <body>
        <div class="container">
            <p>
                <img width="200" src="delete data">
            </p>
            <p>
                <strong>We didn't receive a proper request from your browser.</strong>
            </p>
            <p>Sorry about that. Please try refreshing and contact us if the problem persists.</p>
            <div id="suggestions">
                <a href="https://github.com/contact">Contact Support</a> &mdash;
                <a href="https://status.github.com">GitHub Status</a> &mdash;
                <a href="https://twitter.com/githubstatus">@githubstatus</a>
            </div>
            <a href="/" class="logo logo-img-1x">
                <img width="32" height="32" title="" alt="" src="delete data" />
            </a>
            <a href="/" class="logo logo-img-2x">
                <img width="32" height="32" title="" alt="" src="delete data" />
            </a>
        </div>
    </body>
</html>
```

but the success response is 
``` json
{
    "login": "switch",
    "id": 13577170,
    "avatar_url": "https://avatars2.githubusercontent.com/u/13577170?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/switch",
    "html_url": "https://github.com/switch",
    "followers_url": "https://api.github.com/users/switch/followers",
    "following_url": "https://api.github.com/users/switch/following{/other_user}",
    "gists_url": "https://api.github.com/users/switch/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/switch/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/switch/subscriptions",
    "organizations_url": "https://api.github.com/users/switch/orgs",
    "repos_url": "https://api.github.com/users/switch/repos",
    "events_url": "https://api.github.com/users/switch/events{/privacy}",
    "received_events_url": "https://api.github.com/users/switch/received_events",
    "type": "Organization",
    "site_admin": false,
    "name": "Switch",
    "company": null,
    "blog": "http://www.switch.co",
    "location": null,
    "email": null,
    "hireable": null,
    "bio": "Contributing our work back to the Backbone and Google App Engine communities",
    "public_repos": 1,
    "public_gists": 0,
    "followers": 0,
    "following": 0,
    "created_at": "2015-07-30T19:22:11Z",
    "updated_at": "2015-07-30T19:36:58Z"
}
```

**Comment by ryanjbaxter** [comment] 2018-02-23 14:13
Please provide a project that reproduces the issue and also provide a better description on what steps you need to take to reproduce the issue.

**Comment by Switch-vov** [comment] 2018-02-24 09:51
@ryanjbaxter edited

**Comment by ryanjbaxter** [comment] 2018-02-27 21:38
Its hard for me to say, I am not familiar with that github API.  Without information on what the API expects and what Zuul might not be sending I cant really tell you why it is not working.  If you want help please provide a project in the form of a git repo or zip file that reproduces that problem.  If you want to use this GitHub API to reproduce the problem please provide an example of what the API expects as far as a valid request and how you are sending that through Zuul.

**Comment by spencergibb** [comment] 2018-04-25 19:35
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2018-04-25 19:35 UTC
Labels: waiting for feedback
