### ISSUE TITLE
Zuul CustomSimpleHostRouteFilter is throwing java.net.SocketException: Connection reset for large payload response from microservice

### ISSUE THREAD

**Issue by jaiananth** [spring-cloud/spring-cloud-netflix#3045] opened 2018-06-30 12:17 UTC
Zuul CustomSimpleHostRouteFilter is throwing java.net.SocketException: Connection reset for large payload response from microservice

Spring boot: 1.5.13
Spring Cloud: Edgware.SR2

Error Message:

java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:220)
        at java.net.SocketInputStream.read(SocketInputStream.java:152)
        at com.ibm.jsse2.a.a(a.java:79)
        at com.ibm.jsse2.a.a(a.java:182)
        at com.ibm.jsse2.as.a(as.java:883)
        at com.ibm.jsse2.as.a(as.java:382)
        at com.ibm.jsse2.e.read(e.java:16)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
        at org.apache.http.impl.BHttpConnectionBase.fillInputBuffer(BHttpConnectionBase.java:344)
        at org.apache.http.impl.BHttpConnectionBase.awaitInput(BHttpConnectionBase.java:354)
        at org.apache.http.impl.DefaultBHttpClientConnection.isResponseAvailable(DefaultBHttpClientConnection.java:130)
        at org.apache.http.impl.conn.CPoolProxy.isResponseAvailable(CPoolProxy.java:150)
        at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:219)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:118)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)

**Comment by ryanjbaxter** [comment] 2018-07-02 23:41
Please provide a way to reproduce the problem.

Please learn how to [format code on GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

**Comment by spencergibb** [comment] 2018-10-01 23:01
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2018-10-01 23:01 UTC
Labels: waiting for feedback
