### ISSUE TITLE
Configure OAuth2FeignRequestInterceptor

### ISSUE THREAD

**Issue by bryantp** [spring-cloud/spring-cloud-netflix#1490] opened 2016-11-22 17:13 UTC
Hello All,

I am having an issue making a Feign request from an OAuth2 client to an OAuth2 resource. I was getting a 401 access denied error and saw that I needed to use the OAuth2FeignRequestInterceptor. My question is, is this auto configured or do I have to declare an bean to do so? Whenever I configure the bean to use an OAuth2FeignRequestInterceptor, I get this error: 

`No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? `

Here is my Feign Client definition:

```
@FeignClient(value = "STORE-SERVICE")
public interface StoreSearchClient {

    @RequestMapping(method = RequestMethod.POST, value = "/v1/search")
    SearchResponseMessage searchStore(SearchRequestMessage query);
}
```

My OAuth2FeignRequestInterceptor bean definition:

```
    @Bean
    public RequestInterceptor oauth2FeignRequestInterceptor(OAuth2ClientContext oAuth2ClientContext,
                                                            OAuth2ProtectedResourceDetails resource) {
        return new OAuth2FeignRequestInterceptor(oAuth2ClientContext, resource);
    }
```

Part of application yaml file:

```
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
```

and my gradle dependencies:

```
dependencies {
    compile('org.springframework.cloud:spring-cloud-starter-config')
    compile('org.springframework.cloud:spring-cloud-starter-eureka')
    compile group: 'org.springframework.cloud', name: 'spring-cloud-starter-oauth2', version: '1.1.3.RELEASE'
    compile('org.springframework.cloud:spring-cloud-starter-zuul')
    compile('org.springframework.security.oauth:spring-security-oauth2')
    compile('org.springframework.cloud:spring-cloud-starter-hystrix')
    compile('org.springframework.boot:spring-boot-starter-security')
	compile('org.springframework.boot:spring-boot-starter-web')
	compile("org.springframework.boot:spring-boot-starter-websocket")
    compile group: 'org.projectlombok', name: 'lombok', version: '1.16.10'
    compile('org.springframework.cloud:spring-cloud-starter-feign')
    compile group: 'org.springframework.cloud', name: 'spring-cloud-starter-security', version: '1.1.3.RELEASE'
    testCompile('org.springframework.boot:spring-boot-starter-test')
}
```

I also have the EnableOAuth2Sso annotation on one of my configuration classes. 

Thanks for any assistance

**Comment by ryanjbaxter** [comment] 2016-11-22 20:10
Can you try disabling hystrix entirely and seeing if that fixes the problem?
`feign.hystrix.enabled=false`

**Comment by bryantp** [comment] 2016-11-22 20:59
Doesn't seem to be making a difference. 

```
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          strategy: SEMAPHORE

feign:
  hystrix:
    enabled: false
```

**Comment by ryanjbaxter** [comment] 2016-11-30 16:03
Hmmm maybe it is not a problem with Feign.  Could you provide a sample app that reproduces the problem so we can look further into it?

**Comment by yy306525121** [comment] 2017-11-16 09:08
are you resolved this problem ?  i have same problem now

**Comment by spencergibb** [comment] 2018-01-18 00:46
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2018-01-18 00:46 UTC
Labels: waiting for feedback
