### ISSUE TITLE
eureka client send down status to server after access refresh endpoint

### ISSUE THREAD

**Issue by zhanglei-1987** [spring-cloud/spring-cloud-netflix#3507] opened 2019-04-17 11:19 UTC
after access refresh endpoint,  eureka client send 'DOWN' status to server , but health endpoint display status 'UP'.

**Comment by OlgaMaciaszek** [comment] 2019-04-17 12:14
Please provide more details. What is the config of your Eureka clients and server? What steps exactly were carried out? What do you see in Eureka dashboard?

Check that your Eureka server is not in self-preservation mode (https://github.com/Netflix/eureka/wiki/Server-Self-Preservation-Mode).

If this does not help, please come back with more details.

**Comment by zhanglei-1987** [comment] 2019-04-17 12:29
eureka.enableSelfPreservation=true

eureka dashboard:  "UP (1) - 172.21.22.119:8241 DOWN (1) - 172.21.22.120:8241"

eureka hearbeat:
http://172.21.20.32:8080/eureka/apps/FCS-SERVICE/172.21.22.120:8241?status=DOWN&lastDirtyTimestamp=1555494453422

**Comment by OlgaMaciaszek** [comment] 2019-04-17 16:54
Ok, so it's in self-preservation, 1 is up and 1 is down; I'm not sure I understand the issue. Please describe: 
1. what steps you carry out.
2. what happens vs. what you expect to happen.

Also, please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by zhanglei-1987** [comment] 2019-04-18 01:01
1. visit:  "http://172.21.22.120:8241/actuator/refresh"
2. eureka dashboard: "UP (1) - 172.21.22.119:8241 DOWN (1) - 172.21.22.120:8241"
3. in eureka access log: "http://172.21.20.32:8080/eureka/apps/FCS-SERVICE/172.21.22.120:8241?status=DOWN&lastDirtyTimestamp=1555494453422"

**Comment by ryanjbaxter** [comment] 2019-04-25 14:45
When we refresh the app it will mark the app as down in eureka while the refresh happens and then reregister the app, i think that is what you are seeing.

**Comment by spring-issuemaster** [comment] 2019-05-02 14:49
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-05-09 14:49
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-05-09 14:49 UTC
Labels: feedback-reminder, waiting for feedback
