### ISSUE TITLE
Ribbon and tests with context

### ISSUE THREAD

**Issue by mariuszluciow** [spring-cloud/spring-cloud-netflix#1957] opened 2017-05-17 12:30 UTC
Hi,

I noticed unexpected behaviour while testing Ribbon. I have two tests with separate, different contexts. During the tests Ribbon always uses properties from context that started first, even when test is run from the second context. 

I have example project with test showing this behaviour: https://github.com/mariuszluciow/ribbon-spring-issue

In more detail, first test:
```
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT, properties = "client.ribbon.listOfServers=http://localhost:123")
public class ADemoApplicationTests {
    @Test
    public void contextLoads() {
    }
}
```

and the second one:
```
@RunWith(SpringRunner.class)
@EnableFeignClients("com.example")
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT,
        properties = {"server.port=8083", "client.ribbon.listOfServers=http://localhost:${server.port}"})
public class DemoApplication2Tests {

    @Autowired
    Client client;
    @Test
    public void contextLoads() {
        client.test();
    }

    @FeignClient("client")
    public interface Client {
        @RequestMapping(value = "/test", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
        String test();
    }
}
```

When started, Ribbon logs 
```
DynamicServerListLoadBalancer for client client initialized: DynamicServerListLoadBalancer:{NFLoadBalancer:name=client,current list of Servers=[localhost:123],
...
```
while it should initialise list of servers with localhost:8083.

**Comment by spencergibb** [comment] 2017-05-17 12:41
Use `@DirtiesContext`

**Comment by mariuszluciow** [comment] 2017-05-17 13:04
Hi @spencergibb, thanks for the answer. `@DirtiesContext` helps, but the question is if this is the right solution, as the first test doesn't suggest any context *polluting* .

**Comment by spencergibb** [comment] 2017-05-17 21:15
We use it fairly regularly.

**Comment by spencergibb** [comment] 2017-05-17 21:16
Ribbon has some oddities

**Comment by machowski** [comment] 2017-08-23 14:34
@DirtiesContext is often considered to be bad practice 
- it makes your test suite run way slower
- and means that you somehow integrate inside your code under tests, instead of just testing it's behaviour

There are cases when it's useful, but shouldn't be considered as solution to problem reported by mariuszluciow

**Comment by spencergibb** [comment] 2017-08-23 21:01
Suggestions welcome. It's what we use in spring cloud.

**Comment by spring-issuemaster** [comment] 2018-10-02 17:01
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.

**Closed by spring-issuemaster** 2018-10-02 17:01 UTC
Labels: question

**Comment by k-tomaszewski** [comment] 2020-10-01 08:45
@spencergibb `@DirtiesContext` will not help in this case as the issue is caused by Ribbon which is getting configuration from Archaius which keeps configuration in a global variable (static field).

I've discovered a workaround for this and I've described it in a comment for a similar issue: https://github.com/spring-cloud/spring-cloud-netflix/issues/3219#issuecomment-701328327
