### ISSUE TITLE
Support for websockets (stomp) in Zuul proxy

### ISSUE THREAD

**Issue by hohwille** [spring-cloud/spring-cloud-netflix#256] opened 2015-03-13 08:49 UTC
compared to apache mod_proxy and mod_proxy_wstunnel the spring-cloud-netflix with zuul does not seem to support websockets. Do you plan to support websocket forwarding as well? Would be very helpful to use this cool solution widely.

**Comment by spencergibb** [comment] 2015-06-08 23:56
closed, duplicate of #163

**Closed by spencergibb** 2015-06-08 23:56 UTC
Labels: duplicate

**Comment by ExtremeYu** [comment] 2017-06-20 09:39
zuul starter 1.3.0 release stil not support websocke yet￣へ￣!!!

**Comment by spencergibb** [comment] 2017-06-20 18:36
zuul 1 will never support websockets.

**Comment by Boonearbear** [comment] 2020-04-24 06:32
> zuul 1将永远不支持websockets。

spring could zuul how to supper .mr.spencergibb

**Comment by spencergibb** [comment] 2020-04-24 13:51
No it will not
