### ISSUE TITLE
Exception while integrating SOAP service with Netflix Eureka Service Registry?

### ISSUE THREAD

**Issue by anubhabmohanty** [spring-cloud/spring-cloud-netflix#3506] opened 2019-04-17 10:27 UTC
I am trying to call SOAP service using WebserviceTemplate. The SOAP service & the client calling the service are registered with Eureka Service Registry. While trying to implement SOAP service call using WebserviceTemplate and use the qualified URL of the SOAP service getting exception.

Bean initialized as --

`
@Bean 
@LoadBalanced 
public WebServiceTemplate webServiceTemplate() {
         WebServiceTemplate webServiceTemplate = new WebServiceTemplate();
         webServiceTemplate.setDefaultUri("http://fil-bosscarrierstatus-service/fil/PostBossCarrierStatus");
         webServiceTemplate.setCheckConnectionForFault(true);
         return webServiceTemplate;
    }
`

SOAP Webservice called as --

`
StringResult responseResult = new StringResult();
webServiceTemplate.sendSourceAndReceiveToResult(new StringSource(request), responseResult); 
`

**fil-bosscarrierstatus-service -- This is the qualified URL or the application name.

Expected result is webservice call should happen successfully. It is working with full URL having IP (eg localhost:8089). But for qulaified URL giving the exception -- org.springframework.ws.client.WebServiceIOException: I/O error: fil-bosscarrierstatus-service; nested exception is java.net.UnknownHostException: fil-bosscarrierstatus-service

**Comment by OlgaMaciaszek** [comment] 2019-04-17 10:40
Hello, @anubhabmohanty do you see the service registered under this id in your Eureka server? What exactly do you see there in the registered services list?

**Comment by anubhabmohanty** [comment] 2019-04-18 18:31
@OlgaMaciaszek 
Hello,
Yes, I can see the service registered under this id in Eureka server. Both the SOAP service and the service which acts like client are registered in the Eureka server. Both service's status is UP and the actual URL is being shown at the right side of the service details.
![image](https://user-images.githubusercontent.com/30656803/56382884-1b763b00-6236-11e9-815e-6a37ca721758.png)

**Comment by OlgaMaciaszek** [comment] 2019-04-19 09:19
Ok. Looks like there's an issue. @anubhabmohanty . 
Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue, so that we can analyze it.

**Comment by anubhabmohanty** [comment] 2019-04-22 10:35
@OlgaMaciaszek
 
Please check the repo of github. This contains three services :- 

1. Eureka Server service (EUREKA_SERVER)
2. SOAP service (SOAP_PROJECTS)
3. REST service to call SOAP and acts as SOAP client (REST_PROJECTS)

Both 2 & 3 are registered with Eureka server.

https://github.com/anubhabmohanty/soap-service-registry

**Comment by OlgaMaciaszek** [comment] 2019-04-25 14:31
Ok, thanks @anubhabmohanty Will do

**Comment by OlgaMaciaszek** [comment] 2019-05-07 16:19
Hi @anubhabmohanty Have gone through your example; unfortunately, you can't use it in this way. Simply put, `@LoadBalanced` is not supported for `WebServiceTemplate` and I don't think we will ever introduce such support.

However, you could still use Service Discovery, such as Eureka to communicate with your soap service, but via `DiscoveryClient` and not `@LoadBalanced`.

If you modify your `WebServiceTemplate` bean definition like this, it works:

```
@Bean
	public WebServiceTemplate webServiceTemplate(DiscoveryClient discoveryClient) {
		 String uri = discoveryClient.getInstances("bangalore-details-service")
				 .get(0).getUri().toString();
		 WebServiceTemplate webServiceTemplate = new WebServiceTemplate();
		 webServiceTemplate.setDefaultUri(uri + "/find/getBangaloreLocationDetails.wsdl");
		 webServiceTemplate.setCheckConnectionForFault(true);
		 return webServiceTemplate;
	}
```
Of course, in this case, load-balancing would fall on you. In the example, I just pick the first available instance, but you should probably implement a more elaborate solution to select the right instance (i.e., load-balance), you could look for some inspiration in Ribbon implementation or [here](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/RoundRobinLoadBalancer.java) . Also, keep in mind that then you should probably retrieve the URI and pass it to template at each request and not use the default set at bean instantiation (cuase then you would end up sending requests to one instance either way).

Let me know if this is helpful.

**Comment by spring-issuemaster** [comment] 2019-05-14 16:23
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-05-21 16:21
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-05-21 16:21 UTC
Labels: feedback-reminder, waiting for feedback

**Comment by anubhabmohanty** [comment] 2019-06-14 10:44
@OlgaMaciaszek Thanks for the info. I tried with **LoadBalancerClient** object and fetched the **ServiceInstance** object to get URL on basis of Load balance. Now able to use Service Registry for SOAP service.
