### ISSUE TITLE
hystrix.threadpool.default.coreSize  under high concurrency  should be set up?

### ISSUE THREAD

**Issue by 347154468** [spring-cloud/spring-cloud-netflix#3484] opened 2019-03-27 03:36 UTC
Question

Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@72c03250 rejected from java.util.concurrent.ThreadPoolExecutor@2623d6ff[Running, pool size = 10, active threads = 10, queued tasks = 0, completed tasks = 61838]

**Comment by OlgaMaciaszek** [comment] 2019-03-27 14:23
@347154468 Please provide more details regarding this issue and please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-issuemaster** [comment] 2019-04-03 14:24
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-04-10 14:24
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-04-10 14:24 UTC
Labels: feedback-reminder, waiting for feedback
