### ISSUE TITLE
FormBodyWrapperFilter disabling

### ISSUE THREAD

**Issue by eichstaedtk** [spring-cloud/spring-cloud-netflix#2429] opened 2017-11-08 11:42 UTC
hi everybody, 

I needed your help in case of HTTP Post Ajax Request routing using Zuul. I'm using spring.clould version Finchley.M1 and Zuul as reverse proxy within my microservice project. The problem ist, that all ajax post request have distroyed UTF-8 encoding and multipart body params.

I needed to know how can I disable the relevant FormBodyWrapperFilter and replace this one against a simple one-to-one forwarding filter. 

Can someone please help? 

Many Thanks, best regards Konrad

**Comment by ryanjbaxter** [comment] 2017-11-08 15:45
My first suggestion would be to use the latest Finchley milestone M3 and try again.  If it is still failing please provide a sample that reproduces the problem.

**Comment by eichstaedtk** [comment] 2017-11-09 06:43
I only was able to go to Finchley.M2 because the build of Finchley.M3 failed caused by missing dependencies for zuul-starter and eureka-starter. 

But the problem still remains. 

Example: Within our frondent page exist javscript code which updates a primefaces datatable using a ajax http post command with an multipart form-data body. within this body exist a parameter like this: 

kodTableForm:kulturobjek_table:ko_signatur_column:filter=Gö

But the micorservice behind the zuul proxy got the form-data parameter like this: 

kodTableForm:kulturobjek_table:ko_signatur_column:filter=GÃ¶

In case we disable the routing using zuul than the whole thing is working. Could you please help?

**Comment by ryanjbaxter** [comment] 2017-11-09 11:25
Can you provide a sample that reproduces the problem?

**Comment by eichstaedtk** [comment] 2017-11-09 11:50
Send this to the spring cloud zuul server and check the request which will be send from zuul to the microservice

curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -d "kodTableForm%3Akulturobjek_table%3Ako_signatur_column%3Afilter=G%C3%B6" http://localhost:5555/microservicename/targetpage.jsf

**Comment by spencergibb** [comment] 2017-11-09 14:10
@eichstaedtk, we need a full sample (preferably a github project or a zip of a project) that reproduces the problem. Curl to a non-existant jsf page doesn't help.

**Comment by eichstaedtk** [comment] 2017-11-10 07:52
I uploaded our source code but it is a simple spring-cloud-zuul project using spring-boot

[servicegateway.zip](https://github.com/spring-cloud/spring-cloud-netflix/files/1460504/servicegateway.zip)

**Comment by ryanjbaxter** [comment] 2017-11-10 20:36
I dont see any route configuration in the sample.  Also if you could provide the backend service it would proxy too in the sample that would be great as well.

**Comment by eichstaedtk** [comment] 2017-12-11 11:51
Sorry but I can't upload the other projects. But we still have big problems for HTTP POST Requests. All Encodings are broken after routing using thr zuul. 

Have you any hint how we can fix this , maybe implementing out own FormBodyWrapperFilter or using another class?

**Comment by ryanjbaxter** [comment] 2017-12-12 17:47
Sorry we cant help further until we have something that reproduces the problem.

**Comment by spencergibb** [comment] 2018-01-18 00:53
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2018-01-18 00:53 UTC
Labels: waiting for feedback
