### ISSUE TITLE
Zuul trace shows lot of  404 errors

### ISSUE THREAD

**Issue by hellouserchn** [spring-cloud/spring-cloud-netflix#2294] opened 2017-09-22 18:35 UTC
In clustered Eureka Zuul environment, requests are forwarded properly too all the downstream services from zuul.

But, In the trace log we are seeing 404 exceptions every few seconds.

We are not sure of the reason we are seeing this error.

The trace response is as below,

`{
"timestamp": 1506102916365,
"info": {
          "method": "GET",
         "path": "/",
          "headers": {
              "request": {},"response": {"X-Application-Context": "zuul-service:dev,:4000","status": "404"}},"timeTaken": "1"}}, `

This is for **dev** profile in Zuul Service.

Also, in the metrics endpoint (**/metrics)** huge number of 404 failures  ,but service is not being used.

We are using Spring Cloud Netflix **Dalston.SR2** and Spring Boot **1.5.4.**

Also, we are using Spring cloud Config server.

Can you please help us on this.

**Comment by ryanjbaxter** [comment] 2017-09-22 20:13
It is hard to help debug the problem without a way to reproduce the problem.

**Comment by spencergibb** [comment] 2018-01-18 00:33
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2018-01-18 00:33 UTC
Labels: waiting for feedback
