### ISSUE TITLE
Potential bug with timeout warnings in Ribbon and Hystrix

### ISSUE THREAD

**Issue by davidgoate** [spring-cloud/spring-cloud-netflix#2987] opened 2018-06-01 17:34 UTC
# Environment

* Spring Boot 1.5.13.RELEASE
* Spring Cloud Edgware.SR3
* Compiled with Java version "1.8.0_172-ea",Java(TM) SE Runtime Environment (build 1.8.0_172-ea-b03) and source level 1.8
* Runtime JRE: in docker with `openjdk:10.0.1-jre-slim`

# Question
I have a ribbon client called `serviceA` and associated 

    serviceA.ribbon.ConnectTimeout=5000
    serviceA.ribbon.ReadTimeout=15000
    hystrix.command.serviceA.execution.isolation.thread.timeoutInMilliseconds = 20000

I have not (knowingly) got sprint-retry on the classpath. I execute `./mvnw dependency:list | grep -i retry` and get no results.

At runtime I get these warnings:

> The Hystrix timeout of 20000ms for the command serviceA is set lower than the combination of the Ribbon read and connect timeout, 40000ms.

I'm not sure where these numbers come from given that I thought I'd set them to 15 and 5 seconds respectively. Why is this figure double?

**Comment by spencergibb** [comment] 2018-06-01 17:46
hystrix wraps the ribbon invocation. The timeout for hystrix is lower than the potential time for ribbon which will cause the circuit breaker to timeout. This is a very common problem, hence the warning.

**Comment by davidgoate** [comment] 2018-06-01 20:21
@spencergibb thanks for explaining. 

The one thing that isn't clear is that when you say that Hystrix is wrapping ribbon - isn't that what I've tried to set using the property I configured for `hystrix.command.serviceA.execution.isolation.thread.timeoutInMilliseconds = 20000` I assume this is not the same Hystrix wrapper you are talking about?

**Comment by holy12345** [comment] 2018-06-04 01:50
Hi @davidgoate 

If you want know all detail about the ribbon and hystrix timeout logic, maybe you can see this PR(#2645) which I submit before.
I hope it can help you

thanks

**Comment by ryanjbaxter** [comment] 2018-08-30 14:26
Then you are not seeing the same error.

**Comment by davidgoate** [comment] 2018-08-30 14:30
@ryanjbaxter did you see [my last comment on this](https://github.com/spring-cloud/spring-cloud-netflix/issues/2987#issuecomment-393998527), do you know whether the warning I see is expected given I set the `hystrix.command.serviceA.execution.isolation.thread.timeoutInMilliseconds` property.

**Comment by ryanjbaxter** [comment] 2018-08-30 14:33
It seems that way.  The hystrix timeout should be longer than the combination of the connection or read timeout.

**Comment by davidgoate** [comment] 2018-08-30 16:40
@ryanjbaxter I know what you are saying, it does make sense and I know there must be something wrong with my config but i'm really not sure where the warning about 40,000 ms comes from as my settings are as described above. It seems like the ribbon connect and read timeout somehow gets doubled.

**Comment by ryanjbaxter** [comment] 2018-09-04 15:42
Can you provide a sample that reproduces the problem?

**Comment by ulmermark** [comment] 2018-10-10 21:06
Seeing the same here.  Versions are:

```
springBootVersion = '1.5.10.RELEASE'
springCloudVersion = 'Edgware.SR3'
```

```            
"ribbon.ReadTimeout" : "60000",
"hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds" : "60000",
"ribbon.ConnectTimeout" : "5000"
```


```
2018-10-10 18:00:39.720  WARN [dil-api-gateway-svc] 1 --- [http-nio-8086-exec-2] o.s.c.n.z.f.r.s.AbstractRibbonCommand    : The Hystrix timeout of 60000ms for the command dil-demo-svc-
v1 is set lower than the combination of the Ribbon read and connect timeout, 130000ms.
```

**Comment by davidgoate** [comment] 2018-10-10 21:52
`@ulmermark interesting that you also get the behaviour about the `2*hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds`.

In your case, though, it would seem that a warning is appropriate as you do have the properties set to `65,000ms` when combined (although personally I'd have expected the warning to be mentioning `60000ms` rather than `130000ms`.

In my original example, I see this warning even when the combination of ribbon read + connect timeout is `<=` the `hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds`.

**Comment by ulmermark** [comment] 2018-10-10 22:10
@davidgoate yes, I was expecting the WARNING log message, just commenting that the log message references a timeout that is double the sum of the 2 Ribbon timeouts.

**Comment by spring-issuemaster** [comment] 2018-10-17 23:41
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2018-10-24 23:41
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2018-10-24 23:41 UTC
Labels: feedback-reminder, question, waiting for feedback
