### ISSUE TITLE
Configuration for Zuul stripPrefix on Eureka discovered services

### ISSUE THREAD

**Issue by ukjbrown** [spring-cloud/spring-cloud-netflix#830] opened 2016-02-18 07:58 UTC
Correct me if I'm wrong, but there doesn't currently appear to be a way to configure a global value for stripPrefixes for services added by Eureka discovery. This means that you have to configure all the services manually via zuul.routes properties, losing the benefit of automatic route configuration.

It would be good if a default value could be specified for eureka discovered services (e.g. zuul.eureka.strip-prefixes), which would then be picked up by the ProxyRouteLocator when configuring the discovered services.

I don't want to go into too much detail as to why this is a requirement, but after days of trying to get redirections working from services proxied through Zuul, the only solution I could find is to run the proxied services on the same context-path as the Zuul route (i.e. server.context-path: /${spring.application.name}. Without doing this, the Location returned from the services was missing the path, and since Zuul doesn't rewrite returned URLs, the browser was getting redirected to the wrong location (e.g. /hello, rather than /service/hello).

**Comment by dsyer** [comment] 2016-02-18 11:09
Kind of a duplicate of #352. One comment there suggests a workaround using a custom `ZuulFilter` that sends the `X-Forwarded-Path` to the back end (Spring back ends respect this).

**Closed** 2016-02-18 11:09 UTC
Labels: duplicate
