### ISSUE TITLE
Zuul ignores DELETE request body when SimpleHostRoutingFilter is used

### ISSUE THREAD

**Issue by alenavorozhbieva** [spring-cloud/spring-cloud-netflix#1329] opened 2016-09-09 08:41 UTC
HttpEntityEnclosingRequestBase class is used only for PUT, PATCH and POST methods, not for DELETE. Please use it for DELETE method too

**Comment by spencergibb** [comment] 2016-09-09 17:11
Duplicate of #949

**Comment by spencergibb** [comment] 2016-09-09 17:12
I missed `SimpleHostRoutingFilter` which is different.

**Comment by spencergibb** [comment] 2016-09-09 17:14
Unfortunately `HttpDelete` does not extend `HttpEntityEnclosingRequestBase`. The only way to do this is similar to #949 which is to provide alternative clients for `SimpleHostRoutingFilter`.

**Comment by spencergibb** [comment] 2016-09-09 17:15
See #1219

**Comment by alenavorozhbieva** [comment] 2016-09-12 10:10
> Unfortunately HttpDelete does not extend HttpEntityEnclosingRequestBase. The only way to do this is similar to #949 which is to provide alternative clients for SimpleHostRoutingFilter.

Can you do something like this in forward method:

```
case "DELETE":
                BasicHttpEntityEnclosingRequest entityRequest = new BasicHttpEntityEnclosingRequest(verb, uri + this.helper.getQueryString(params));
                httpRequest = entityRequest;
                entityRequest.setEntity(entity);
                break;
``` 
?

PS: I don't undestand how alternative clients for SimpleHostRoutingFilter can solve my problem

**Comment by spencergibb** [comment] 2016-09-12 15:27
@alenavorozhbieva in the long run, providing an option other than apache is a goal since we provide it for the load balanced routes. The apache client should also not use deprecated APIs. How about a PR?

**Comment by spencergibb** [comment] 2016-09-12 15:27
whoops

**Comment by alenavorozhbieva** [comment] 2016-09-13 15:44
I have created PR: https://github.com/spring-cloud/spring-cloud-netflix/pull/1339

**Closed** 2016-10-13 15:34 UTC
Labels: enhancement
