### ISSUE TITLE
@FeignClient uses name attribute for service discovery

### ISSUE THREAD

**Issue by harthorst** [spring-cloud/spring-cloud-netflix#1139] opened 2016-06-27 08:37 UTC
I have the following situation: one service publishes 2 endoints which I want to consume in a client application. If I want to reuse the service interfaces using FeignClient I have the following problem:
Both @FeignClient annotated clients have to have the same name to get service discovery working. But the name attribute is the bean name and should be unique.

Code example:

Client A

```
@FeignClient(name = "http://MY-SERVICE", fallback = SomeFallbackA.class,
        configuration = SomeConfigurationA.class)
public interface ServiceClientA extends ServiceInterfaceA {
}
```

Client B
```
@FeignClient(name = "http://MY-SERVICE", fallback = SomeFallbackB.class,
        configuration = SomeConfigurationB.class)
public interface ServiceClientB extends ServiceInterfaceB {
}
```

I can't just set the URL to "MY-SERVICE" and use 2 different name attributes because no loadbalancing would be used then.

Adding trailing slashes for different bean names works but is ugly. Maybe an extra attribute for the service name would make sense.

Here is the code from FeignClientFactoryBean:

```
    public Object getObject() throws Exception {
        FeignContext context = (FeignContext) this.applicationContext.getBean(FeignContext.class);
        Feign.Builder builder = feign(context);
        if (!StringUtils.hasText(this.url)) {
            String url;
            if (!this.name.startsWith("http")) {
                url = "http://" + this.name;
            } else {
                url = this.name;
            }
            String url = url + cleanPath();
            return loadBalance(builder, context, new Target.HardCodedTarget(this.type, this.name, url));
        }
        if ((StringUtils.hasText(this.url)) && (!this.url.startsWith("http"))) {
            this.url = ("http://" + this.url);
        }
        String url = this.url + cleanPath();
        return targeter.target(this, builder, context, new Target.HardCodedTarget(this.type, this.name, url));
    }
```

**Comment by spencergibb** [comment] 2016-06-27 18:56
Feign uses the fully qualified class name as the bean name now. What version are you using? Also see #1073 for the ability to customize the bean name. `@FeignClient.name` is the serviceId. That's not going to change.

**Comment by harthorst** [comment] 2016-06-28 08:08
I use version 8.16.2. This problem seems to occur when I have 2 different configuration classes, in my case I use SpringMvcContract in Service A and JAXRSContract in Service B. If both clients have exact the same name I get the following error:

Method xxx not annotated with HTTP method type (ex. GET, POST)
	at feign.Util.checkState(Util.java:128)
	at feign.Contract$BaseContract.parseAndValidateMetadata(Contract.java:97)

In the debugger i see that contract is SpringMvcContract, not the configured JAXRSContract. If the names of both clients are different everything works like expected.

**Comment by spencergibb** [comment] 2016-06-29 18:46
@harthorst that's a different error than issue reported here.

**Comment by harthorst** [comment] 2016-06-30 07:55
@spencergibb Yes. But it seems to be related to the name. If the names differ I everything works like expected. When I find the time I'll send you an example project which demonstrates the problem. 

Many thanks, Thomas

**Comment by tjuchniewicz** [comment] 2016-08-08 12:04
We experience the same problem. When we use two different APIs (one is Spring MVC and one is JAX-RS) consumed from one service, we can't use the same name for both feign clients.

**Comment by spencergibb** [comment] 2016-08-08 14:34
@tjuchniewicz this is closed in favor of a solution or #1073

**Comment by tjuchniewicz** [comment] 2016-08-08 17:04
@spencergibb to be honest I don't get how #1073 solves this problem... I still get:

```
Method xxx not annotated with HTTP method type (ex. GET, POST)
at feign.Util.checkState(Util.java:128)
at feign.Contract$BaseContract.parseAndValidateMetadata(Contract.java:97)
```

but solution described by @harthorst helps:

```java
@FeignClient(name = "MY-SERVICE", fallback = SomeFallbackA.class,
        configuration = SomeConfigurationA.class)
public interface ServiceClientA extends ServiceInterfaceA {
}

@FeignClient(name = "http://MY-SERVICE", fallback = SomeFallbackB.class,
        configuration = JAXRSContract.class)
public interface ServiceClientB extends ServiceInterfaceB {
}
```

**Comment by spencergibb** [comment] 2016-08-09 02:42
So the problem is we have a context per named feign client. So the context name needs to be the same as the bean name so as to not conflict. That's why putting "http://" on the front fixes this.

**Comment by spencergibb** [comment] 2016-08-09 03:02
@ryanjbaxter @marcingrzejszczak and/or @adriancole I'm headed down the road of using the fully qualified class name as the name of the context (same as the bean name), so the configuration contexts are unique. Thoughts?

**Comment by adriancole** [comment] 2016-08-09 03:22
consistency is nice. It implies no duplicates (ex same interface different target).

**Comment by spencergibb** [comment] 2016-08-09 03:25
And in practice, no one references the context by name except the framework code. Also, when #1073 is implemented, it would work here for uniqueness as well.

**Comment by marcingrzejszczak** [comment] 2016-08-09 07:38
I agree with Adrian - looks good

**Comment by ryanjbaxter** [comment] 2016-08-09 14:43
@spencergibb sounds good.

**Comment by spencergibb** [comment] 2016-08-09 19:08
So in effect #1211 and this issue are the same. One of them should be closed. The approach I took above doesn't work because the class name becomes the key in archaius lookups like ribbon, which thankfully failed a test. Closing in favor of #1211

**Closed by spencergibb** 2016-08-09 19:08 UTC
