### ISSUE TITLE
not able to exceute

### ISSUE THREAD

**Issue by anjali090600** [spring-cloud/spring-cloud-netflix#4244] opened 2024-01-28 16:39 UTC
Hello 
@OlgaMaciaszek as you suggest i implement that but it is not working 
could you please help me out 
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    greatService:
      path: /api/greatingService/**
      url: https://localhost:8980/hs-laii-gateway/api/greating/

    goodService:
      path: /api/goodService/**
      url: http://localhost:8680/hs-laii-good/
      predicates:
        - Path=/api/goodService/**
      timeout:
        connect-timeout: 1000
        response-timeout: 5s
but it is not working

**Comment by OlgaMaciaszek** [comment] 2024-01-30 10:58
Hello @anjali090600, please do not duplicate issues. Please see the [response](https://github.com/spring-cloud/spring-cloud-netflix/issues/4241#issuecomment-1910127500).
Duplicate of gh-4241.

**Closed by OlgaMaciaszek** 2024-01-30 10:58 UTC
Labels: duplicate
