### ISSUE TITLE
ZuulHandlerMapping Not Happening On Startup So First Request Super Slow

### ISSUE THREAD

**Issue by bbk-pij-2012-22** [spring-cloud/spring-cloud-netflix#3097] opened 2018-07-22 09:38 UTC
I think this is just a question because most likely we've got some poor config choice that's causing this.

Just a note to say thanks first: Zuul is amazing! : ) We absolutely love it. It works really well and was super easy to integrate with our existing cloud services.

Anyway on to the question/problem:
We're using docker (and compose) to containerise and deploy multiple services including the cloud services with Eureka as our service registry and Zuul of course as our gateway. All the services can find each other and everything goes to the right place via the gateway as expected. However, the first request to the gateway is super slow. **We've seen similar threads complaining that this causes timeouts etc.** and we've tried various things we've seen in those threads including altering the timeout settings (haphazardly with a bit of trial and error and you can see we've done this badly both in the application.properties file and from the fact that the output warns us it's a weird setup) and we overcame the timeout problems but this obviously didn't address the actual issue that the first request is so slow. We also saw that we could set ribbon eager loading, which we've tried but doesn't seem to have helped. 

Here are the application.properties from the zuul spring boot project (we really haven't learned what we're doing with these properly yet): https://gist.github.com/bbk-pij-2012-22/d5bd22151b57c7258cfbccff786ad978

Here are the bootstrap.properties from the same project: https://gist.github.com/bbk-pij-2012-22/e159f7027f86541b27da131d0a5115bb

Here is the output from the gateway during the first request (not on app startup but once everything is running and we make the first request to the gateway): https://gist.github.com/bbk-pij-2012-22/06ed5c75cffc0bcde391c85d11e14288 

So we can see in the output that the gateway is busy getting the services during the first request and we guessed that this is the cause of the delay but the eager loading property did not help us. There are quite a few other lines of output that we don't really understand. 

Note: we are not using any defined routing to or ports for the services. All services are assigned a random port on registration with eureka and we expect Zuul to find the services by name when we hit the gateway with the extension (which it does).

So I guess the questions are: 
1. Is there some config that we're missing to force the gateway to load these services at startup (if that's even the cause of the delay? 
2. Are we hashing together settings in the application.properties that shouldn't go together/don't make sense?

Many thanks in advance and sorry for our lack of understanding.

**Comment by holy12345** [comment] 2018-07-22 13:39
Hi @bbk-pij-2012-22 

Maybe my answer not help you solution your issues, but I will talk about my understanding.

- First about your `application.properties`
   I see in this properties you have `hystrix` and `ribbon` properties, I think this properties about the time out, so my suggestion is hystrix timeout should include all ribbon timeout(include all ribbon retry)

- Second
   I see you have a config `ribbon.eager-load.enabled=true` which in `application.properties`, this represents whether the ribbon is loaded at startup instead of loading at the time of the call. but I think you miss other properties, so I think correct is like this and could you please have a try and see what happen : ) 

```
ribbon:
  eager-load:
    enabled: true
    clients: client1, client2, client3. --- YOU MISS THIS ONE 
```

I hope my answer can help you !

Thanks

**Comment by bbk-pij-2012-22** [comment] 2018-07-22 13:46
Thanks for your reply @holy12345 
Regarding point 1 - do you mean if I set the hystrix property it encompasses ribbon and so makes any ribbon properties I set redundant?

Regarding point 2 - I would prefer my gateway to know nothing about what services might be available to it via the registry until it starts up, specifically so that I don't have to specify any config that's specific to other services other than Eureka's location. Perhaps there is an option to load all at this point; I'll look into it and report back. 

Thanks again

**Comment by holy12345** [comment] 2018-07-22 14:52
@bbk-pij-2012-22 

- First
My thought is `Hystrix` timeout should include ALL `ribbon` timeout, if you see the spring-cloud reference you can see those sentence

> Hystrix Timeouts And Ribbon Clients
When using Hystrix commands that wrap Ribbon clients you want to make sure your Hystrix timeout is configured to be longer than the configured Ribbon timeout, including any potential retries that might be made. For example, if your Ribbon connection timeout is one second and the Ribbon client might retry the request three times, than your Hystrix timeout should be slightly more than three seconds.

- Second
IF you not set `ribbon.eager-load.clients` properties, this application context is lazily loaded on the first request to the named client

Hope this can help you : )

Thanks

**Comment by bbk-pij-2012-22** [comment] 2018-07-22 15:10
Comments understood; thanks. I am trying to find out now if I can eager load the clients without naming them.

**Comment by bbk-pij-2012-22** [comment] 2018-07-23 12:36
I can't find the answer from searching. I'd be surprised if this wasn't possible. Does anyone know?

**Comment by ryanjbaxter** [comment] 2018-07-23 12:46
I think this is the property you want
http://cloud.spring.io/spring-cloud-static/Edgware.SR4/single/spring-cloud.html#_zuul_eager_application_context_loading

**Comment by ryanjbaxter** [comment] 2018-07-23 13:47
yes it needs the `zuul` prefix

**Comment by bbk-pij-2012-22** [comment] 2018-07-23 15:30
Please see my pom dependencies; perhaps this will be useful.

https://gist.github.com/bbk-pij-2012-22/6f1217a38008379dd39969b7eb1d2c8a

**Comment by bbk-pij-2012-22** [comment] 2018-07-23 15:40
I've got a sneaking feeling it's because my other services haven't finished starting up and so haven't checked in with eureka by the time zuul starts up. I can depends_on my services in the docker compose file but it only depends on them starting up, not being in a ready state.

hmm

**Comment by bbk-pij-2012-22** [comment] 2018-07-23 15:54
I also only have the `@EnableZuulProxy,` `@EnableEurekaClient` and `@SpringBootApplication` annotations above my gateway application. Is `@EnableDiscoveryClient` needed? It seems to work without but maybe this would help me? I'm clutching at straws now..

**Comment by holy12345** [comment] 2018-07-27 02:41
HI @bbk-pij-2012-22 
Is this problem solved?

**Comment by bbk-pij-2012-22** [comment] 2018-07-27 05:50
Hi. I've not had a chance to try it again but I will do this weekend. Thanks for your patience

**Comment by bbk-pij-2012-22** [comment] 2018-07-27 14:11
Ok so I tried it without docker and with prefixes above as discussed and the delay was still there on the first request.

I decided to also try it by fully booting all the services first and waiting until they're all checked in with the eureka registry before booting up the zuul app. I still get the same result. Zuul is clearly mapping the routes at the time of the request and not before.

Perhaps I have no choice but to define the routes manually in Zuul for now?

**Comment by bbk-pij-2012-22** [comment] 2018-07-27 15:15
Thanks. I really appreciate the continued efforts to help.

Please could you tell me exactly what to provide so I don't just add lots of irrelevant spam for you.

**Comment by spencergibb** [comment] 2018-07-27 15:21
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by bbk-pij-2012-22** [comment] 2018-07-27 15:55
Several of our apps require a mysql and redis connection with specific credentials etc. I'd have to strip all of that out and hide some sensitive code. If that's really necessary and I can't just provide more specific logs/configuration then I can give it a go....

**Comment by spencergibb** [comment] 2019-01-31 19:39
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2019-01-31 19:39 UTC
Labels: feedback-provided
