### ISSUE TITLE
org.apache.http.NoHttpResponseException: <hostname>:<port> failed to respond

### ISSUE THREAD

**Issue by venkatvgit** [spring-cloud/spring-cloud-netflix#3564] opened 2019-06-13 17:23 UTC
Getting "org.apache.http.NoHttpResponseException: <hostname>:<port> failed to respond" Sporadically when Zuul Proxy try to forward the request to service. Please find below dependencies we are using.

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-zuul</artifactId>
			<version>1.4.3.RELEASE</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-ribbon</artifactId>
			<version>1.4.3.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-hystrix</artifactId>
			<version>1.4.3.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-hystrix-dashboard</artifactId>
			<version>1.4.3.RELEASE</version>
		</dependency>

Can anybody please help?

**Comment by spencergibb** [comment] 2019-06-13 17:27
No. That's not nearly enough information to go on. You've not provided a full stack trace or steps to reproduce the problem. In the end, we are likely going to need a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem.  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment] 2019-06-20 17:32
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-06-27 17:28
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-06-27 17:28 UTC
Labels: feedback-reminder, waiting for feedback
