### ISSUE TITLE
c.netflix.discovery.TimedSupervisorTask  : task supervisor timed out

### ISSUE THREAD

**Issue by abhisheksharma85** [spring-cloud/spring-cloud-netflix#2812] opened 2018-04-02 20:58 UTC
Getting error c.netflix.discovery.TimedSupervisorTask  : task supervisor timed out

In dev it is working fine, in prod I have registry in AWS instance and gateway is on anther instance. 

Bug report

2018-04-02 13:40:48.847  INFO 53346 --- [           main] com.pko.gateway.config.WebConfigurer     : Web application configuration, using profiles: swagger
2018-04-02 13:40:48.853  INFO 53346 --- [           main] com.pko.gateway.config.WebConfigurer     : Web application fully configured
2018-04-02 13:40:51.659  INFO 53346 --- [tbeatExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_GATEWAY/gateway:8bb33b1c01c244fe1a9c241eb9b57683 - Re-registering apps/GATEWAY
2018-04-02 13:40:51.660  INFO 53346 --- [tbeatExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_GATEWAY/gateway:8bb33b1c01c244fe1a9c241eb9b57683: registering service...
2018-04-02 13:40:51.738  INFO 53346 --- [tbeatExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_GATEWAY/gateway:8bb33b1c01c244fe1a9c241eb9b57683 - registration status: 204
2018-04-02 13:40:56.604  INFO 53346 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Disable delta property : false
2018-04-02 13:40:56.604  INFO 53346 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Single vip registry refresh property : null
2018-04-02 13:40:56.604  INFO 53346 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Force full registry fetch : false
2018-04-02 13:40:56.604  INFO 53346 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Application is null : false
2018-04-02 13:40:56.604  INFO 53346 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Registered Applications size is zero : true
2018-04-02 13:40:56.604  INFO 53346 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Application version is -1: false
2018-04-02 13:40:56.604  INFO 53346 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Getting all instance registry info from the eureka server
2018-04-02 13:40:56.654  INFO 53346 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : The response status is 200
2018-04-02 13:41:06.608 ERROR 53346 --- [scoveryClient-1] c.netflix.discovery.TimedSupervisorTask  : task supervisor timed out

java.util.concurrent.TimeoutException: null
        at java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at com.netflix.discovery.TimedSupervisorTask.run(TimedSupervisorTask.java:63)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by spencergibb** [comment] 2018-04-02 21:07
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

**Comment by ryanjbaxter** [comment] 2018-08-17 12:56
Please provide a complete working sample that reproduces the issue.

**Comment by xiaods** [comment] 2018-10-26 05:41
it should be tuning by eureka client lease time.
```
eureka.client.registry-fetch-interval-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=5
eureka.instance.lease-renewal-interval-in-seconds=30
```

**Comment by spring-issuemaster** [comment] 2018-11-02 15:28
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2018-11-09 15:29
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2018-11-09 15:29 UTC
Labels: feedback-reminder, waiting for feedback

**Comment by saint7007** [comment] 2020-12-17 21:44
hi,

m kind a facing same issue, here are the logs. 

[https://github.com/saint7007/java/blob/master/logfile]()

Application works for few hours or so and then the error continues forever until I restart.

Can anybody check the logs, if those are not enough I shall add configuration yml files.
M unable to reproduce it in hello world example. This thing is in production, for now have written a script to restarts the application based on logs.

Any help appreciated.
